### Dependencies

In [1]:
# Cell 0 — ONLY if the runtime has just started
!pip install -q huggingface_hub==0.23.0 transformers==4.39.3 diffusers==0.27.2 peft==0.10.0
!pip install -q insightface onnxruntime-gpu onnx onnx2torch
!pip install -q git+https://github.com/tencent-ailab/IP-Adapter.git

print("✓ Libraries installed")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.2/401.2 kB 37.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 122.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 106.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 23.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 125.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.0.0 requires huggingface-hub>=0.24.0, but you have huggingface-hub 0.23.0 which is incompatible.
sentence-transformers 5.4.1 requires transformers<6.0.0,>=4.41.0, but you have transformers 4.39.3 which is incompatible.
gradio 5.50.0 requires huggingface-hub<2.0,>=0.33.5, but you have huggingface-hub 0.23.0 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 27.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 277.0/277.0 MB 4.4 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 78.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.0/81.0 kB 6.0 MB/s eta 0:00:00
  Building wheel for insightface (pyproject.toml) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for ip-adapter (pyproject.toml) ... done
✓ Libraries installed

## Common setup

In [ ]:
# === Common project bootstrap ===
# Bootstrap Colab/Drive + src path
import os, sys

DRIVE = "/content/drive/MyDrive/Notebook4"
try:
    from google.colab import drive
    drive.mount("/content/drive")
except Exception:
    pass

for _path in [DRIVE, "/content", "/content/IP-Adapter"]:
    if _path not in sys.path:
        sys.path.insert(0, _path)


from src.config import DEFAULT_DRIVE
from src.inference_utils import (
    CHILD_NEGATIVE_PROMPT,
    DEFAULT_NEGATIVE_PROMPT,
    collect_bap2_alpha_stats,
    ensure_2d,
    generate_bap2_image,
    get_embedding,
    set_parent_scale_bap2,
)

from src.notebook_setup import setup_runtime, setup_data, setup_generation_models, setup_arcface
from src.model_utils import install_bap2, processor_counts
DRIVE = globals().get("DRIVE", DEFAULT_DRIVE)
ctx = setup_runtime(DRIVE, require_cuda=True)
ctx = setup_data(ctx)
ctx = setup_generation_models(ctx)
ctx = setup_arcface(ctx)

paths = ctx.paths
runtime = ctx.runtime
data = ctx.data
pipe = ctx.pipe
ip_model = ctx.ip_model
arcface_torch = ctx.arcface_torch

DEVICE = runtime.device
DTYPE = runtime.dtype
FIW_ROOT = str(paths.fiw_root)
EMBEDDINGS_PATH = str(paths.embeddings_path)
TRAIN_CSV = str(paths.train_csv)
VAL_CSV = str(paths.val_csv)
TEST_CSV = str(paths.test_csv)
AGES_CSV = str(paths.ages_csv)
GENDER_CACHE = str(paths.gender_cache_path)

embeddings = data.embeddings
gender_dict = data.gender_dict
train_ds = data.train_ds
val_ds = data.val_ds
test_ds = data.test_ds
train_loader = data.train_loader
val_loader = data.val_loader
test_loader = data.test_loader

bap2_modules = install_bap2(pipe, runtime, parent_scale=0.1, copy_ip_weights=True)
START_STEP = globals().get('START_STEP', 0)
CURRENT_STEP = globals().get('CURRENT_STEP', START_STEP)

print('Training context ready')
print('Processors:', processor_counts(pipe.unet))
print('BAP2 modules:', len(bap2_modules))


# Helpers finales comunes
import torch
from src.inference_utils import make_arcface_embedder

GUIDANCE = globals().get("GUIDANCE", 4.0)
STEPS = globals().get("STEPS", 30)
NEG_PROMPT = globals().get("NEG_PROMPT", DEFAULT_NEGATIVE_PROMPT)
arcface_embed_from_pil = make_arcface_embedder(arcface_torch, DEVICE)

@torch.inference_mode()
def generate_bap2_final(h_c, h_p, h_m, gender, age, parent_scale, seed):
    img, prompt, alpha_stats = generate_bap2_image(
        pipe=pipe,
        ip_model=ip_model,
        h_c=h_c,
        h_p=h_p,
        h_m=h_m,
        gender=gender,
        age=age,
        device=DEVICE,
        dtype=DTYPE,
        parent_scale=parent_scale,
        seed=seed,
        guidance_scale=GUIDANCE,
        num_inference_steps=STEPS,
        negative_prompt=NEG_PROMPT,
        child_prompt=False,
    )
    return img, alpha_stats, prompt

print('Helpers finales listos')

In [9]:
# ============================================================
# Cell 8 — Continue BAP2 training up to step500
# ============================================================

import os
import torch
import torch.nn.functional as F
import pandas as pd
from tqdm.auto import tqdm
from datetime import datetime

TARGET_STEP = 500

if START_STEP >= TARGET_STEP:
    CURRENT_STEP = START_STEP
    print(f"START_STEP={START_STEP}. TARGET_STEP={TARGET_STEP} already reached. Not training further.")

else:
    BATCH_SIZE = 1
    LR_BAP2 = 1e-4
    WEIGHT_DECAY = 0.0
    ADAM_EPS = 1e-6
    MAX_GRAD_NORM = 1.0
    LOG_EVERY = 10
    SAVE_EVERY = 100

    RUN_NAME = "bap2_linear_continue_step100_to_500_lr1e-4"
    BAP2_CONTINUE_DIR = f"{DRIVE}/results/child_anchor_bap_gate/{RUN_NAME}"
    os.makedirs(BAP2_CONTINUE_DIR, exist_ok=True)

    print("Results in:", BAP2_CONTINUE_DIR)
    print("Continuing from step", START_STEP, "to step", TARGET_STEP)

    pipe.unet.train()
    pipe.vae.eval()
    pipe.text_encoder.eval()
    ip_model.image_proj_model.eval()

    for p in pipe.unet.parameters():
        p.requires_grad = False

    for p in pipe.vae.parameters():
        p.requires_grad = False

    for p in pipe.text_encoder.parameters():
        p.requires_grad = False

    for p in ip_model.image_proj_model.parameters():
        p.requires_grad = False

    bap2_gate_params = []

    for name, proc in bap2_modules.items():
        proc.gate.float()
        for p in proc.gate.parameters():
            p.requires_grad = True
            bap2_gate_params.append(p)

    print("BAP2 gate params entrenables:", sum(p.numel() for p in bap2_gate_params))
    print("dtype example:", bap2_gate_params[0].dtype)

    optimizer = torch.optim.AdamW(
        bap2_gate_params,
        lr=LR_BAP2,
        eps=ADAM_EPS,
        weight_decay=WEIGHT_DECAY,
    )

    def ensure_2d(x):
        if x.ndim == 1:
            x = x.unsqueeze(0)
        return x

    def collect_bap2_alpha_stats():
        vals = []

        for name, proc in bap2_modules.items():
            if getattr(proc, "last_alpha", None) is not None:
                vals.append(proc.last_alpha.detach().float().cpu())

        if len(vals) == 0:
            return {
                "alpha_mean": None,
                "alpha_min": None,
                "alpha_max": None,
                "alpha_std": None,
                "alpha_has_nan": None,
            }

        x = torch.cat(vals, dim=0)

        return {
            "alpha_mean": x.mean().item(),
            "alpha_min": x.min().item(),
            "alpha_max": x.max().item(),
            "alpha_std": x.std().item(),
            "alpha_has_nan": torch.isnan(x).any().item(),
        }

    def bap2_param_stats():
        vals = []

        for name, proc in bap2_modules.items():
            for p in proc.gate.parameters():
                vals.append(p.detach().float().flatten().cpu())

        x = torch.cat(vals)

        return {
            "gate_param_mean": x.mean().item(),
            "gate_param_std": x.std().item(),
            "gate_param_max_abs": x.abs().max().item(),
            "gate_param_has_nan": torch.isnan(x).any().item(),
        }

    def build_prompts(batch):
        ages = batch["age"]
        genders = batch["gender"]

        if torch.is_tensor(ages):
            ages = ages.detach().cpu().tolist()

        if isinstance(genders, str):
            genders = [genders]

        prompts = []

        for gender, age in zip(genders, ages):
            if gender not in ["man", "woman", "person"]:
                gender = "person"

            prompts.append(
                f"portrait photo of a {gender}, age {int(age)}, realistic, neutral expression"
            )

        return prompts

    def train_step_bap2(batch):
        img = batch["img"].to(device=DEVICE, dtype=DTYPE)

        h_c = ensure_2d(batch["h_c"].to(device=DEVICE, dtype=DTYPE))
        h_p = ensure_2d(batch["h_p"].to(device=DEVICE, dtype=DTYPE))
        h_m = ensure_2d(batch["h_m"].to(device=DEVICE, dtype=DTYPE))

        prompts = build_prompts(batch)

        with torch.no_grad():
            latents = pipe.vae.encode(img).latent_dist.sample()
            latents = latents * pipe.vae.config.scaling_factor

            noise = torch.randn_like(latents)

            timesteps = torch.randint(
                low=0,
                high=pipe.scheduler.config.num_train_timesteps,
                size=(latents.shape[0],),
                device=DEVICE,
            ).long()

            noisy_latents = pipe.scheduler.add_noise(latents, noise, timesteps)

            child_tokens = ip_model.image_proj_model(h_c)
            father_tokens = ip_model.image_proj_model(h_p)
            mother_tokens = ip_model.image_proj_model(h_m)

            prompt_embeds, _ = pipe.encode_prompt(
                prompt=prompts,
                device=DEVICE,
                num_images_per_prompt=1,
                do_classifier_free_guidance=False,
            )

            encoder_hidden_states = torch.cat(
                [prompt_embeds, child_tokens, father_tokens, mother_tokens],
                dim=1,
            )

        noise_pred = pipe.unet(
            noisy_latents,
            timesteps,
            encoder_hidden_states=encoder_hidden_states,
        ).sample

        loss = F.mse_loss(noise_pred.float(), noise.float())

        return loss

    def save_bap2_checkpoint(global_step, logs):
        bap2_gate_state = {
            name: proc.gate.state_dict()
            for name, proc in bap2_modules.items()
        }

        ckpt_path = f"{BAP2_CONTINUE_DIR}/bap2_linear_step{global_step}.pt"

        torch.save(
            {
                "bap2_gate_state": bap2_gate_state,
                "step": global_step,
                "config": {
                    "run_name": RUN_NAME,
                    "loss": "L_diff",
                    "start_step": START_STEP,
                    "target_step": TARGET_STEP,
                    "batch_size": BATCH_SIZE,
                    "lr_bap2": LR_BAP2,
                    "adam_eps": ADAM_EPS,
                    "weight_decay": WEIGHT_DECAY,
                    "max_grad_norm": MAX_GRAD_NORM,
                    "parent_scale": 0.1,
                    "child_scale": 1.0,
                    "gate": "contextual_linear",
                    "gate_dtype": "float32",
                    "timestamp": datetime.now().isoformat(),
                },
                "logs": logs,
            },
            ckpt_path,
        )

        return ckpt_path

    logs_continue = []
    global_step = START_STEP
    loader_iter = iter(train_loader)

    pbar = tqdm(total=TARGET_STEP - START_STEP)

    while global_step < TARGET_STEP:

        try:
            batch = next(loader_iter)
        except StopIteration:
            loader_iter = iter(train_loader)
            batch = next(loader_iter)

        batch = {
            k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
            for k, v in batch.items()
        }

        optimizer.zero_grad(set_to_none=True)

        loss = train_step_bap2(batch)

        if not torch.isfinite(loss):
            print("⚠ Non-finite loss at global_step", global_step + 1, "loss:", loss.item())
            break

        loss.backward()

        grad_norm = torch.nn.utils.clip_grad_norm_(
            bap2_gate_params,
            max_norm=MAX_GRAD_NORM,
        )

        optimizer.step()

        global_step += 1

        alpha_stats = collect_bap2_alpha_stats()
        param_stats = bap2_param_stats()

        row = {
            "global_step": global_step,
            "loss": loss.item(),
            "grad_norm": float(grad_norm),
            **alpha_stats,
            **param_stats,
        }

        logs_continue.append(row)

        if global_step % LOG_EVERY == 0 or global_step == START_STEP + 1:
            print(
                f"step {global_step:04d} | "
                f"loss={loss.item():.6f} | "
                f"grad={float(grad_norm):.6e} | "
                f"alpha_mean={alpha_stats['alpha_mean']:.6f} | "
                f"alpha_std={alpha_stats['alpha_std']:.6f} | "
                f"alpha_min={alpha_stats['alpha_min']:.6f} | "
                f"alpha_max={alpha_stats['alpha_max']:.6f} | "
                f"param_max_abs={param_stats['gate_param_max_abs']:.6e}"
            )

        if alpha_stats["alpha_has_nan"] or param_stats["gate_param_has_nan"]:
            print("⚠ NaN detected in alpha or parameters. Stopping.")
            break

        if alpha_stats["alpha_min"] < 0.45 or alpha_stats["alpha_max"] > 0.55:
            print("⚠ Possible alpha collapse. Stopping.")
            print(alpha_stats)
            break

        if global_step % SAVE_EVERY == 0:
            ckpt_path = save_bap2_checkpoint(global_step, logs_continue)
            print(f"✓ Checkpoint saved: {ckpt_path}")

        pbar.update(1)

    pbar.close()

    df_bap2_continue = pd.DataFrame(logs_continue)
    display(df_bap2_continue.tail())

    logs_path = f"{BAP2_CONTINUE_DIR}/bap2_continue_logs_step{START_STEP}_to_{global_step}.csv"
    df_bap2_continue.to_csv(logs_path, index=False)

    final_ckpt_path = save_bap2_checkpoint(global_step, logs_continue)

    print("\n✓ Entrenamiento continuo terminado")
    print("Last global_step:", global_step)
    print("Logs:", logs_path)
    print("Checkpoint final:", final_ckpt_path)

    CURRENT_STEP = global_step
    START_STEP = global_step
    print("CURRENT_STEP:", CURRENT_STEP)

    if len(df_bap2_continue) > 0:
        print("\nAlpha summary:")
        print("alpha_mean inicial:", df_bap2_continue.iloc[0]["alpha_mean"])
        print("alpha_mean final:  ", df_bap2_continue.iloc[-1]["alpha_mean"])
        print("alpha_std inicial: ", df_bap2_continue.iloc[0]["alpha_std"])
        print("alpha_std final:   ", df_bap2_continue.iloc[-1]["alpha_std"])
        print("alpha_min final:   ", df_bap2_continue.iloc[-1]["alpha_min"])
        print("alpha_max final:   ", df_bap2_continue.iloc[-1]["alpha_max"])

        print("\nLoss summary:")
        print("loss inicial:", df_bap2_continue.iloc[0]["loss"])
        print("loss final:  ", df_bap2_continue.iloc[-1]["loss"])

Results in: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_continue_step100_to_500_lr1e-4
Continuing from step 100 a step 500
BAP2 gate params entrenables: 792832
dtype example: torch.float32

  0%|          | 0/400 [00:00<?, ?it/s]

step 0101 | loss=0.022591 | grad=7.249935e-05 | alpha_mean=0.499809 | alpha_std=0.002612 | alpha_min=0.486679 | alpha_max=0.508824 | param_max_abs=2.065763e-03
step 0110 | loss=0.006452 | grad=5.240910e-06 | alpha_mean=0.499694 | alpha_std=0.003097 | alpha_min=0.484620 | alpha_max=0.511557 | param_max_abs=2.037936e-03
step 0120 | loss=0.026962 | grad=5.547014e-05 | alpha_mean=0.499652 | alpha_std=0.003263 | alpha_min=0.484679 | alpha_max=0.511789 | param_max_abs=2.076948e-03
step 0130 | loss=0.070036 | grad=1.971656e-04 | alpha_mean=0.499823 | alpha_std=0.002977 | alpha_min=0.485831 | alpha_max=0.509898 | param_max_abs=2.216047e-03
step 0140 | loss=0.008234 | grad=3.326096e-06 | alpha_mean=0.499794 | alpha_std=0.003218 | alpha_min=0.483975 | alpha_max=0.514205 | param_max_abs=2.292941e-03
step 0150 | loss=0.003940 | grad=0.000000e+00 | alpha_mean=0.499646 | alpha_std=0.004290 | alpha_min=0.477117 | alpha_max=0.516196 | param_max_abs=2.112384e-03
step 0160 | loss=0.177620 | grad=1.948846e-04 | alpha_mean=0.499720 | alpha_std=0.003080 | alpha_min=0.485317 | alpha_max=0.509309 | param_max_abs=2.105326e-03
step 0170 | loss=0.040562 | grad=9.097445e-05 | alpha_mean=0.499712 | alpha_std=0.003314 | alpha_min=0.482871 | alpha_max=0.513663 | param_max_abs=2.031697e-03
step 0180 | loss=0.007505 | grad=3.121502e-05 | alpha_mean=0.499785 | alpha_std=0.003548 | alpha_min=0.483635 | alpha_max=0.513790 | param_max_abs=2.105986e-03
step 0190 | loss=0.064160 | grad=1.685017e-04 | alpha_mean=0.499789 | alpha_std=0.004101 | alpha_min=0.479841 | alpha_max=0.517847 | param_max_abs=2.082946e-03
step 0200 | loss=0.392795 | grad=1.634900e-04 | alpha_mean=0.499731 | alpha_std=0.003384 | alpha_min=0.488705 | alpha_max=0.510848 | param_max_abs=2.177705e-03
✓ Checkpoint saved: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_continue_step100_to_500_lr1e-4/bap2_linear_step200.pt
step 0210 | loss=0.171762 | grad=1.150287e-04 | alpha_mean=0.499870 | alpha_std=0.004254 | alpha_min=0.481330 | alpha_max=0.517897 | param_max_abs=2.349135e-03
step 0220 | loss=0.025161 | grad=4.309500e-05 | alpha_mean=0.499823 | alpha_std=0.003515 | alpha_min=0.486974 | alpha_max=0.512939 | param_max_abs=2.469857e-03
step 0230 | loss=0.109561 | grad=9.640763e-05 | alpha_mean=0.499858 | alpha_std=0.003956 | alpha_min=0.481844 | alpha_max=0.517653 | param_max_abs=2.429959e-03
step 0240 | loss=0.005979 | grad=8.160283e-07 | alpha_mean=0.499626 | alpha_std=0.004729 | alpha_min=0.479919 | alpha_max=0.516296 | param_max_abs=2.311472e-03
step 0250 | loss=0.187826 | grad=9.708390e-05 | alpha_mean=0.499831 | alpha_std=0.004239 | alpha_min=0.483482 | alpha_max=0.519873 | param_max_abs=2.339346e-03
step 0260 | loss=0.035842 | grad=1.143602e-04 | alpha_mean=0.499705 | alpha_std=0.004437 | alpha_min=0.485129 | alpha_max=0.513102 | param_max_abs=2.594296e-03
step 0270 | loss=0.338677 | grad=1.278356e-04 | alpha_mean=0.500100 | alpha_std=0.004123 | alpha_min=0.478068 | alpha_max=0.516590 | param_max_abs=2.800899e-03
step 0280 | loss=0.061388 | grad=1.053809e-04 | alpha_mean=0.499826 | alpha_std=0.004244 | alpha_min=0.478458 | alpha_max=0.511364 | param_max_abs=2.957866e-03
step 0290 | loss=0.011510 | grad=6.044439e-06 | alpha_mean=0.499774 | alpha_std=0.004940 | alpha_min=0.478333 | alpha_max=0.517769 | param_max_abs=3.067994e-03
step 0300 | loss=0.038823 | grad=1.037038e-04 | alpha_mean=0.499899 | alpha_std=0.004438 | alpha_min=0.481737 | alpha_max=0.513337 | param_max_abs=3.083973e-03
✓ Checkpoint saved: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_continue_step100_to_500_lr1e-4/bap2_linear_step300.pt
step 0310 | loss=0.120896 | grad=2.648510e-04 | alpha_mean=0.499901 | alpha_std=0.003690 | alpha_min=0.487173 | alpha_max=0.511116 | param_max_abs=2.984184e-03
step 0320 | loss=0.015567 | grad=3.293645e-05 | alpha_mean=0.499996 | alpha_std=0.004199 | alpha_min=0.484144 | alpha_max=0.518168 | param_max_abs=3.164570e-03
step 0330 | loss=0.079761 | grad=1.934875e-04 | alpha_mean=0.499777 | alpha_std=0.004414 | alpha_min=0.482612 | alpha_max=0.517310 | param_max_abs=3.508853e-03
step 0340 | loss=0.221938 | grad=2.580855e-04 | alpha_mean=0.499883 | alpha_std=0.004284 | alpha_min=0.482928 | alpha_max=0.512698 | param_max_abs=3.721486e-03
step 0350 | loss=0.007803 | grad=3.479217e-07 | alpha_mean=0.499736 | alpha_std=0.004968 | alpha_min=0.479294 | alpha_max=0.516261 | param_max_abs=3.723435e-03
step 0360 | loss=0.032621 | grad=7.427762e-05 | alpha_mean=0.499846 | alpha_std=0.004602 | alpha_min=0.481684 | alpha_max=0.515419 | param_max_abs=3.644713e-03
step 0370 | loss=0.076044 | grad=1.012757e-04 | alpha_mean=0.499665 | alpha_std=0.004680 | alpha_min=0.480920 | alpha_max=0.520330 | param_max_abs=3.548150e-03
step 0380 | loss=0.109346 | grad=1.905439e-04 | alpha_mean=0.499550 | alpha_std=0.004585 | alpha_min=0.479557 | alpha_max=0.513026 | param_max_abs=3.404994e-03
step 0390 | loss=0.175991 | grad=1.493874e-04 | alpha_mean=0.499616 | alpha_std=0.005317 | alpha_min=0.476650 | alpha_max=0.515411 | param_max_abs=3.255260e-03
step 0400 | loss=0.040950 | grad=1.180555e-04 | alpha_mean=0.499705 | alpha_std=0.005092 | alpha_min=0.480549 | alpha_max=0.528932 | param_max_abs=3.326301e-03
✓ Checkpoint saved: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_continue_step100_to_500_lr1e-4/bap2_linear_step400.pt
step 0410 | loss=0.543894 | grad=1.693358e-04 | alpha_mean=0.499812 | alpha_std=0.004643 | alpha_min=0.479275 | alpha_max=0.520592 | param_max_abs=3.365594e-03
step 0420 | loss=0.541168 | grad=1.123915e-04 | alpha_mean=0.499833 | alpha_std=0.004677 | alpha_min=0.478211 | alpha_max=0.516807 | param_max_abs=3.457794e-03
step 0430 | loss=0.011063 | grad=1.835382e-05 | alpha_mean=0.499860 | alpha_std=0.006245 | alpha_min=0.464692 | alpha_max=0.519906 | param_max_abs=3.626998e-03
step 0440 | loss=0.090278 | grad=2.168240e-04 | alpha_mean=0.499907 | alpha_std=0.006147 | alpha_min=0.472723 | alpha_max=0.525187 | param_max_abs=3.702810e-03
step 0450 | loss=0.277650 | grad=1.298376e-04 | alpha_mean=0.499782 | alpha_std=0.005212 | alpha_min=0.477698 | alpha_max=0.516490 | param_max_abs=3.560584e-03
step 0460 | loss=0.013460 | grad=1.406351e-05 | alpha_mean=0.499737 | alpha_std=0.005881 | alpha_min=0.477471 | alpha_max=0.519372 | param_max_abs=3.596613e-03
step 0470 | loss=0.200757 | grad=1.357118e-04 | alpha_mean=0.499801 | alpha_std=0.005116 | alpha_min=0.475988 | alpha_max=0.514617 | param_max_abs=3.823289e-03
step 0480 | loss=0.009846 | grad=1.411795e-05 | alpha_mean=0.499851 | alpha_std=0.006342 | alpha_min=0.471420 | alpha_max=0.522831 | param_max_abs=3.902994e-03
step 0490 | loss=0.005951 | grad=1.419092e-07 | alpha_mean=0.499763 | alpha_std=0.005586 | alpha_min=0.478862 | alpha_max=0.518920 | param_max_abs=3.884157e-03
step 0500 | loss=0.010698 | grad=2.308285e-05 | alpha_mean=0.499751 | alpha_std=0.006084 | alpha_min=0.469495 | alpha_max=0.518771 | param_max_abs=3.932926e-03
✓ Checkpoint saved: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_continue_step100_to_500_lr1e-4/bap2_linear_step500.pt

,global_step,loss,grad_norm,alpha_mean,alpha_min,alpha_max,alpha_std,alpha_has_nan,gate_param_mean,gate_param_std,gate_param_max_abs,gate_param_has_nan
395,496,0.006353,0.000002,0.499821,0.473938,0.518903,0.005757,False,-7.029519e-08,0.000262,0.003912,False
396,497,0.015702,0.000037,0.499779,0.466503,0.518239,0.005834,False,-7.243565e-08,0.000263,0.003919,False
397,498,0.008543,0.000003,0.499812,0.479900,0.517648,0.005480,False,-7.427204e-08,0.000263,0.003926,False
398,499,0.020480,0.000031,0.499935,0.471456,0.522486,0.006544,False,-7.633989e-08,0.000263,0.003930,False
399,500,0.010698,0.000023,0.499751,0.469495,0.518771,0.006084,False,-7.876925e-08,0.000263,0.003933,False

✓ Entrenamiento continuo terminado
Last global_step: 500
Logs: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_continue_step100_to_500_lr1e-4/bap2_continue_logs_step100_to_500.csv
Checkpoint final: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_continue_step100_to_500_lr1e-4/bap2_linear_step500.pt
CURRENT_STEP: 500

Alpha summary:
alpha_mean inicial: 0.49980852007865906
alpha_mean final:   0.4997512102127075
alpha_std inicial:  0.0026117393281310797
alpha_std final:    0.006084279622882605
alpha_min final:    0.46949541568756104
alpha_max final:    0.5187708139419556

Loss summary:
loss inicial: 0.022590555250644684
loss final:   0.01069796271622181

In [10]:
# ============================================================
# Cell 9 — BAP2 evaluation: λ=0.0 vs λ=0.1
# ============================================================

import os
import torch
import torch.nn.functional as F
import torchvision.transforms as T
import pandas as pd
from torch.utils.data._utils.collate import default_collate
from IPython.display import display

# ----------------------------
# Configuration
# ----------------------------
N_TRIADS = 10
AGES = [15, 25, 40, 60]
PARENT_SCALES = [0.0, 0.1]

SEED = 42
GUIDANCE = 4.0
STEPS = 30

negative_prompt = "monochrome, lowres, bad anatomy, worst quality, low quality, blurry"

# Fixed indices. Change them if you want.
EVAL_IDXS = [179, 12, 35, 48, 61, 74, 89, 103, 128, 150]
EVAL_IDXS = EVAL_IDXS[:N_TRIADS]

print("EVAL_IDXS:", EVAL_IDXS)

# ----------------------------
# ArcFace preprocessing
# ----------------------------
preprocess_arcface = T.Compose([
    T.Resize((112, 112)),
    T.ToTensor(),
    T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
])

@torch.inference_mode()
def arcface_embed_from_pil(img):
    x = preprocess_arcface(img.convert("RGB")).unsqueeze(0).to(DEVICE)
    x = x.float()
    emb = arcface_torch(x)
    emb = F.normalize(emb, p=2, dim=1)
    return emb

def ensure_2d(x):
    if x.ndim == 1:
        x = x.unsqueeze(0)
    return x

def set_parent_scale_bap2(unet, value):
    for proc in unet.attn_processors.values():
        if type(proc).__name__ == "BAP2":
            proc.parent_scale = value

def collect_bap2_alpha_stats(unet):
    vals = []

    for name, proc in unet.attn_processors.items():
        if type(proc).__name__ == "BAP2":
            if getattr(proc, "last_alpha", None) is not None:
                vals.append(proc.last_alpha.detach().float().cpu())

    if len(vals) == 0:
        return None

    x = torch.cat(vals, dim=0)

    return {
        "alpha_mean": x.mean().item(),
        "alpha_min": x.min().item(),
        "alpha_max": x.max().item(),
        "alpha_std": x.std().item(),
    }

@torch.inference_mode()
def generate_bap2_age(h_c, h_p, h_m, gender, age, parent_scale, seed=42):
    pipe.unet.eval()
    pipe.vae.eval()
    pipe.text_encoder.eval()
    ip_model.image_proj_model.eval()

    set_parent_scale_bap2(pipe.unet, parent_scale)

    h_c = ensure_2d(h_c).to(device=DEVICE, dtype=DTYPE)
    h_p = ensure_2d(h_p).to(device=DEVICE, dtype=DTYPE)
    h_m = ensure_2d(h_m).to(device=DEVICE, dtype=DTYPE)

    child_tokens = ip_model.image_proj_model(h_c)
    father_tokens = ip_model.image_proj_model(h_p)
    mother_tokens = ip_model.image_proj_model(h_m)

    zero_child_tokens = ip_model.image_proj_model(torch.zeros_like(h_c))
    zero_father_tokens = ip_model.image_proj_model(torch.zeros_like(h_p))
    zero_mother_tokens = ip_model.image_proj_model(torch.zeros_like(h_m))

    prompt = f"portrait photo of a {gender}, age {age}, realistic, neutral expression"

    prompt_embeds, negative_prompt_embeds = pipe.encode_prompt(
        prompt=[prompt],
        device=DEVICE,
        num_images_per_prompt=1,
        do_classifier_free_guidance=True,
        negative_prompt=[negative_prompt],
    )

    prompt_embeds = torch.cat(
        [prompt_embeds, child_tokens, father_tokens, mother_tokens],
        dim=1,
    )

    negative_prompt_embeds = torch.cat(
        [negative_prompt_embeds, zero_child_tokens, zero_father_tokens, zero_mother_tokens],
        dim=1,
    )

    generator = torch.Generator(device=DEVICE).manual_seed(seed)

    img = pipe(
        prompt_embeds=prompt_embeds,
        negative_prompt_embeds=negative_prompt_embeds,
        guidance_scale=GUIDANCE,
        num_inference_steps=STEPS,
        generator=generator,
    ).images[0]

    alpha_stats = collect_bap2_alpha_stats(pipe.unet)

    return img, alpha_stats

# ============================================================
# Evaluation loop
# ============================================================

rows = []

for triad_num, idx in enumerate(EVAL_IDXS, start=1):

    print(f"\n=== Triad {triad_num}/{len(EVAL_IDXS)} | idx={idx} ===")

    sample = val_ds[idx]

    batch = default_collate([sample])
    batch = {
        k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
        for k, v in batch.items()
    }

    h_c = ensure_2d(batch["h_c"])
    h_p = ensure_2d(batch["h_p"])
    h_m = ensure_2d(batch["h_m"])

    h_c_eval = F.normalize(h_c.float(), p=2, dim=1)
    h_p_eval = F.normalize(h_p.float(), p=2, dim=1)
    h_m_eval = F.normalize(h_m.float(), p=2, dim=1)

    gender = sample.get("gender", "person")
    if gender not in ["man", "woman", "person"]:
        gender = "person"

    print("Father:", sample.get("key_p", "N/A"))
    print("Mother:", sample.get("key_m", "N/A"))
    print("Child :", sample.get("key_c", "N/A"))
    print("Gender:", gender)

    for parent_scale in PARENT_SCALES:
        for age in AGES:

            img, alpha_stats = generate_bap2_age(
                h_c=h_c,
                h_p=h_p,
                h_m=h_m,
                gender=gender,
                age=age,
                parent_scale=parent_scale,
                seed=SEED,
            )

            h_gen = arcface_embed_from_pil(img)

            S_id = F.cosine_similarity(h_gen, h_c_eval).item()
            S_p = F.cosine_similarity(h_gen, h_p_eval).item()
            S_m = F.cosine_similarity(h_gen, h_m_eval).item()

            rows.append({
                "triad_idx": idx,
                "triad_num": triad_num,
                "variant": "BAP2_linear",
                "parent_scale": parent_scale,
                "age": age,
                "gender": gender,
                "S_id_child": S_id,
                "S_p_father": S_p,
                "S_m_mother": S_m,
                "S_family": 0.5 * (S_p + S_m),
                "balance_abs_gap": abs(S_p - S_m),
                "alpha_mean": alpha_stats["alpha_mean"] if alpha_stats else None,
                "alpha_std": alpha_stats["alpha_std"] if alpha_stats else None,
                "alpha_min": alpha_stats["alpha_min"] if alpha_stats else None,
                "alpha_max": alpha_stats["alpha_max"] if alpha_stats else None,
                "key_p": sample.get("key_p", ""),
                "key_m": sample.get("key_m", ""),
                "key_c": sample.get("key_c", ""),
            })

            print(
                f"λ={parent_scale} age={age} | "
                f"S_id={S_id:.4f} "
                f"S_p={S_p:.4f} "
                f"S_m={S_m:.4f} "
                f"S_family={0.5 * (S_p + S_m):.4f} "
                f"alpha_std={alpha_stats['alpha_std']:.5f}"
            )

df_bap2_eval_scales = pd.DataFrame(rows)

print("\n==============================")
print("Full results")
print("==============================")
display(df_bap2_eval_scales)

# ============================================================
# Global summary
# ============================================================

df_bap2_scale_summary = (
    df_bap2_eval_scales
    .groupby("parent_scale")
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
        "alpha_min",
        "alpha_max",
    ]]
    .mean()
    .reset_index()
)

print("\n==============================")
print("Global summary BAP2: λ=0.0 vs λ=0.1")
print("==============================")
display(df_bap2_scale_summary)

row_0 = df_bap2_scale_summary[df_bap2_scale_summary["parent_scale"] == 0.0].iloc[0]
row_1 = df_bap2_scale_summary[df_bap2_scale_summary["parent_scale"] == 0.1].iloc[0]

df_bap2_delta_scale_global = pd.DataFrame([{
    "delta_S_id_child_0.1_minus_0.0": row_1["S_id_child"] - row_0["S_id_child"],
    "delta_S_p_father_0.1_minus_0.0": row_1["S_p_father"] - row_0["S_p_father"],
    "delta_S_m_mother_0.1_minus_0.0": row_1["S_m_mother"] - row_0["S_m_mother"],
    "delta_S_family_0.1_minus_0.0": row_1["S_family"] - row_0["S_family"],
    "delta_balance_abs_gap_0.1_minus_0.0": row_1["balance_abs_gap"] - row_0["balance_abs_gap"],
}])

print("\n==============================")
print("Delta global BAP2: λ=0.1 menos λ=0.0")
print("==============================")
display(df_bap2_delta_scale_global)

# ============================================================
# Summary by age
# ============================================================

df_bap2_scale_age = (
    df_bap2_eval_scales
    .groupby(["age", "parent_scale"])
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
    ]]
    .mean()
    .reset_index()
)

print("\n==============================")
print("Summary by age BAP2: λ=0.0 vs λ=0.1")
print("==============================")
display(df_bap2_scale_age)

delta_rows = []

for age in AGES:
    sub = df_bap2_scale_age[df_bap2_scale_age["age"] == age]

    r0 = sub[sub["parent_scale"] == 0.0].iloc[0]
    r1 = sub[sub["parent_scale"] == 0.1].iloc[0]

    delta_rows.append({
        "age": age,
        "delta_S_id_child_0.1_minus_0.0": r1["S_id_child"] - r0["S_id_child"],
        "delta_S_p_father_0.1_minus_0.0": r1["S_p_father"] - r0["S_p_father"],
        "delta_S_m_mother_0.1_minus_0.0": r1["S_m_mother"] - r0["S_m_mother"],
        "delta_S_family_0.1_minus_0.0": r1["S_family"] - r0["S_family"],
        "delta_balance_abs_gap_0.1_minus_0.0": r1["balance_abs_gap"] - r0["balance_abs_gap"],
    })

df_bap2_delta_scale_age = pd.DataFrame(delta_rows)

print("\n==============================")
print("Delta by age BAP2: λ=0.1 minus λ=0.0")
print("==============================")
display(df_bap2_delta_scale_age)

# ============================================================
# Save results
# ============================================================

EVAL_STEP = CURRENT_STEP if "CURRENT_STEP" in globals() else START_STEP

OUT_DIR = f"{DRIVE}/results/child_anchor_bap_gate/bap2_linear_step{EVAL_STEP}_lambda_ablation"
os.makedirs(OUT_DIR, exist_ok=True)

df_bap2_eval_scales.to_csv(f"{OUT_DIR}/df_bap2_eval_scales.csv", index=False)
df_bap2_scale_summary.to_csv(f"{OUT_DIR}/df_bap2_scale_summary.csv", index=False)
df_bap2_delta_scale_global.to_csv(f"{OUT_DIR}/df_bap2_delta_scale_global.csv", index=False)
df_bap2_scale_age.to_csv(f"{OUT_DIR}/df_bap2_scale_age.csv", index=False)
df_bap2_delta_scale_age.to_csv(f"{OUT_DIR}/df_bap2_delta_scale_age.csv", index=False)

print("\n✓ Results saved to:")
print(OUT_DIR)

EVAL_IDXS: [179, 12, 35, 48, 61, 74, 89, 103, 128, 150]

=== Triad 1/10 | idx=179 ===
Padre: F0854/MID1/P09020_face1.jpg
Madre: F0854/MID3/P09026_face0.jpg
Hijo : F0854/MID2/P09020_face0.jpg
Gender: man

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.3175 S_p=0.0840 S_m=-0.0140 S_family=0.0350 alpha_std=0.00504

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.3612 S_p=0.0805 S_m=-0.0065 S_family=0.0370 alpha_std=0.00514

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.4681 S_p=0.1491 S_m=0.0491 S_family=0.0991 alpha_std=0.00515

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=0.3065 S_p=0.1032 S_m=0.0492 S_family=0.0762 alpha_std=0.00517

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.3076 S_p=0.0871 S_m=0.0285 S_family=0.0578 alpha_std=0.00500

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.3722 S_p=0.1008 S_m=0.0173 S_family=0.0591 alpha_std=0.00512

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.4729 S_p=0.1515 S_m=0.0520 S_family=0.1018 alpha_std=0.00515

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.3340 S_p=0.0608 S_m=0.0639 S_family=0.0624 alpha_std=0.00518

=== Triad 2/10 | idx=12 ===
Padre: F0061/MID1/P00609_face2.jpg
Madre: F0061/MID2/P00609_face1.jpg
Hijo : F0061/MID3/P00609_face3.jpg
Gender: woman

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=-0.0175 S_p=0.0940 S_m=0.0326 S_family=0.0633 alpha_std=0.00495

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.0521 S_p=0.0280 S_m=-0.0142 S_family=0.0069 alpha_std=0.00499

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.0819 S_p=0.0231 S_m=-0.0786 S_family=-0.0278 alpha_std=0.00497

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=-0.0211 S_p=-0.0839 S_m=-0.0149 S_family=-0.0494 alpha_std=0.00503

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=-0.0056 S_p=0.0912 S_m=0.0443 S_family=0.0678 alpha_std=0.00495

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.0505 S_p=0.0364 S_m=-0.0017 S_family=0.0174 alpha_std=0.00499

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.0781 S_p=0.0204 S_m=-0.0750 S_family=-0.0273 alpha_std=0.00496

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=-0.0135 S_p=-0.0709 S_m=-0.0102 S_family=-0.0405 alpha_std=0.00503

=== Triad 3/10 | idx=35 ===
Padre: F0144/MID1/P01524_face3.jpg
Madre: F0144/MID2/P01524_face4.jpg
Hijo : F0144/MID7/P01534_face2.jpg
Gender: woman

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.3035 S_p=0.0351 S_m=0.1239 S_family=0.0795 alpha_std=0.00493

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.1949 S_p=0.0031 S_m=0.0823 S_family=0.0427 alpha_std=0.00496

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.2549 S_p=0.0611 S_m=0.1114 S_family=0.0863 alpha_std=0.00499

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=0.2437 S_p=0.0724 S_m=0.1480 S_family=0.1102 alpha_std=0.00496

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.2907 S_p=0.0724 S_m=0.1325 S_family=0.1024 alpha_std=0.00493

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.2098 S_p=-0.0245 S_m=0.0645 S_family=0.0200 alpha_std=0.00495

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.2757 S_p=0.0881 S_m=0.1422 S_family=0.1151 alpha_std=0.00497

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.2951 S_p=0.0757 S_m=0.1545 S_family=0.1151 alpha_std=0.00496

=== Triad 4/10 | idx=48 ===
Padre: F0249/MID1/P02633_face4.jpg
Madre: F0249/MID7/P02637_face0.jpg
Hijo : F0249/MID4/P02640_face1.jpg
Gender: man

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.1025 S_p=-0.0639 S_m=0.0176 S_family=-0.0231 alpha_std=0.00511

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.2644 S_p=0.0205 S_m=0.0277 S_family=0.0241 alpha_std=0.00512

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.2326 S_p=0.0609 S_m=-0.0818 S_family=-0.0104 alpha_std=0.00513

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=0.1907 S_p=0.0085 S_m=-0.0850 S_family=-0.0383 alpha_std=0.00513

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.0900 S_p=-0.0648 S_m=0.0128 S_family=-0.0260 alpha_std=0.00511

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.2549 S_p=0.0139 S_m=0.0165 S_family=0.0152 alpha_std=0.00513

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.2320 S_p=0.0828 S_m=-0.0693 S_family=0.0067 alpha_std=0.00513

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.1851 S_p=0.0307 S_m=-0.0739 S_family=-0.0216 alpha_std=0.00512

=== Triad 5/10 | idx=61 ===
Padre: F0327/MID3/P03464_face1.jpg
Madre: F0327/MID2/P03464_face2.jpg
Hijo : F0327/MID4/P03465_face3.jpg
Gender: woman

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.0538 S_p=-0.0153 S_m=0.0639 S_family=0.0243 alpha_std=0.00509

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.0349 S_p=-0.0326 S_m=0.0563 S_family=0.0118 alpha_std=0.00510

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.1488 S_p=0.0075 S_m=0.1228 S_family=0.0652 alpha_std=0.00513

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=0.2158 S_p=0.0049 S_m=0.1194 S_family=0.0621 alpha_std=0.00514

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.0728 S_p=-0.0065 S_m=0.0776 S_family=0.0356 alpha_std=0.00507

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.0194 S_p=-0.0251 S_m=0.0469 S_family=0.0109 alpha_std=0.00509

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.1403 S_p=-0.0032 S_m=0.1433 S_family=0.0700 alpha_std=0.00513

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.2497 S_p=0.0098 S_m=0.1001 S_family=0.0550 alpha_std=0.00515

=== Triad 6/10 | idx=74 ===
Padre: F0380/MID5/P04034_face0.jpg
Madre: F0380/MID7/P04034_face2.jpg
Hijo : F0380/MID6/P04034_face3.jpg
Gender: man

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.0752 S_p=0.0752 S_m=-0.0063 S_family=0.0344 alpha_std=0.00529

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.1204 S_p=0.0853 S_m=0.0286 S_family=0.0569 alpha_std=0.00530

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.3025 S_p=0.0683 S_m=0.0766 S_family=0.0724 alpha_std=0.00537

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=-0.0131 S_p=-0.0389 S_m=-0.0432 S_family=-0.0411 alpha_std=0.00534

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.0827 S_p=0.0775 S_m=0.0010 S_family=0.0392 alpha_std=0.00529

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.1233 S_p=0.0749 S_m=0.0257 S_family=0.0503 alpha_std=0.00531

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.2890 S_p=0.0736 S_m=0.0760 S_family=0.0748 alpha_std=0.00535

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.0342 S_p=-0.0600 S_m=-0.0079 S_family=-0.0340 alpha_std=0.00536

=== Triad 7/10 | idx=89 ===
Padre: F0434/MID3/P04573_face0.jpg
Madre: F0434/MID1/P04572_face1.jpg
Hijo : F0434/MID2/P04572_face0.jpg
Gender: man

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.2182 S_p=-0.0806 S_m=0.1222 S_family=0.0208 alpha_std=0.00555

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.2132 S_p=-0.0138 S_m=0.0827 S_family=0.0345 alpha_std=0.00556

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.2156 S_p=0.0558 S_m=0.0451 S_family=0.0504 alpha_std=0.00557

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=0.2038 S_p=-0.0214 S_m=0.0215 S_family=0.0000 alpha_std=0.00557

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.2132 S_p=-0.0686 S_m=0.1343 S_family=0.0328 alpha_std=0.00555

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.2250 S_p=0.0090 S_m=0.0840 S_family=0.0465 alpha_std=0.00555

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.2127 S_p=0.0642 S_m=0.0592 S_family=0.0617 alpha_std=0.00557

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.2277 S_p=-0.0301 S_m=0.0543 S_family=0.0121 alpha_std=0.00558

=== Triad 8/10 | idx=103 ===
Padre: F0490/MID4/P05159_face1.jpg
Madre: F0490/MID5/P05161_face0.jpg
Hijo : F0490/MID7/P05166_face0.jpg
Gender: woman

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.1603 S_p=0.0470 S_m=-0.0139 S_family=0.0165 alpha_std=0.00516

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.2499 S_p=0.0630 S_m=-0.0084 S_family=0.0273 alpha_std=0.00517

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.2618 S_p=0.0656 S_m=-0.0000 S_family=0.0328 alpha_std=0.00519

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=0.2802 S_p=0.0904 S_m=-0.0028 S_family=0.0438 alpha_std=0.00521

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.2013 S_p=0.0596 S_m=-0.0038 S_family=0.0279 alpha_std=0.00514

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.2543 S_p=0.0677 S_m=0.0006 S_family=0.0341 alpha_std=0.00518

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.2569 S_p=0.0626 S_m=-0.0030 S_family=0.0298 alpha_std=0.00518

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.2508 S_p=0.0906 S_m=-0.0255 S_family=0.0326 alpha_std=0.00520

=== Triad 9/10 | idx=128 ===
Padre: F0599/MID6/P10738_face6.jpg
Madre: F0599/MID4/P10736_face1.jpg
Hijo : F0599/MID1/P10729_face1.jpg
Gender: man

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.1445 S_p=-0.1012 S_m=0.0259 S_family=-0.0377 alpha_std=0.00535

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.0649 S_p=-0.1279 S_m=-0.0121 S_family=-0.0700 alpha_std=0.00538

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.3071 S_p=0.0184 S_m=0.0171 S_family=0.0177 alpha_std=0.00544

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=0.2135 S_p=-0.0467 S_m=0.0267 S_family=-0.0100 alpha_std=0.00545

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.1196 S_p=-0.0965 S_m=0.0380 S_family=-0.0292 alpha_std=0.00535

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.0727 S_p=-0.0859 S_m=-0.0147 S_family=-0.0503 alpha_std=0.00538

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.3036 S_p=0.0197 S_m=0.0292 S_family=0.0245 alpha_std=0.00543

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.1924 S_p=-0.0451 S_m=0.0439 S_family=-0.0006 alpha_std=0.00545

=== Triad 10/10 | idx=150 ===
Padre: F0683/MID2/P07121_face1.jpg
Madre: F0683/MID4/P07132_face2.jpg
Hijo : F0683/MID6/P07135_face1.jpg
Gender: woman

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=15 | S_id=0.0791 S_p=0.0269 S_m=0.0122 S_family=0.0196 alpha_std=0.00549

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=25 | S_id=0.2098 S_p=0.0362 S_m=0.0570 S_family=0.0466 alpha_std=0.00551

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=40 | S_id=0.3462 S_p=0.0206 S_m=0.0269 S_family=0.0238 alpha_std=0.00558

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.0 age=60 | S_id=0.1092 S_p=-0.0018 S_m=0.0017 S_family=-0.0000 alpha_std=0.00549

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=15 | S_id=0.1335 S_p=0.0295 S_m=0.0649 S_family=0.0472 alpha_std=0.00549

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=25 | S_id=0.2618 S_p=0.0434 S_m=0.0884 S_family=0.0659 alpha_std=0.00551

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=40 | S_id=0.4319 S_p=0.0186 S_m=0.0348 S_family=0.0267 alpha_std=0.00558

  0%|          | 0/30 [00:00<?, ?it/s]

λ=0.1 age=60 | S_id=0.1134 S_p=0.0110 S_m=0.0081 S_family=0.0095 alpha_std=0.00549

==============================
Resultados completos
==============================

,triad_idx,triad_num,variant,parent_scale,age,gender,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap,alpha_mean,alpha_std,alpha_min,alpha_max,key_p,key_m,key_c
0,179,1,BAP2_linear,0.0,15,man,0.317474,0.084024,-0.014007,0.035009,0.098030,0.499912,0.005044,0.478898,0.518562,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg
1,179,1,BAP2_linear,0.0,25,man,0.361151,0.080538,-0.006492,0.037023,0.087029,0.499911,0.005139,0.478252,0.518632,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg
2,179,1,BAP2_linear,0.0,40,man,0.468141,0.149085,0.049127,0.099106,0.099959,0.499908,0.005151,0.478342,0.518663,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg
3,179,1,BAP2_linear,0.0,60,man,0.306503,0.103163,0.049210,0.076186,0.053954,0.499907,0.005167,0.478877,0.518683,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg
4,179,1,BAP2_linear,0.1,15,man,0.307587,0.087117,0.028492,0.057804,0.058625,0.499912,0.004997,0.479759,0.518543,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,150,10,BAP2_linear,0.0,60,woman,0.109204,-0.001779,0.001720,-0.000030,0.003500,0.499877,0.005491,0.474175,0.518829,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg
76,150,10,BAP2_linear,0.1,15,woman,0.133462,0.029524,0.064891,0.047208,0.035366,0.499867,0.005490,0.474600,0.518844,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg
77,150,10,BAP2_linear,0.1,25,woman,0.261832,0.043388,0.088356,0.065872,0.044968,0.499868,0.005513,0.474058,0.518841,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg
78,150,10,BAP2_linear,0.1,40,woman,0.431889,0.018622,0.034781,0.026702,0.016159,0.499872,0.005581,0.473364,0.518929,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg
79,150,10,BAP2_linear,0.1,60,woman,0.113351,0.011040,0.008055,0.009547,0.002985,0.499880,0.005490,0.474049,0.518828,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg

==============================
Global summary BAP2: λ=0.0 vs λ=0.1
==============================

,parent_scale,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap,alpha_mean,alpha_std,alpha_min,alpha_max
0,0.0,0.188783,0.021517,0.029169,0.025343,0.069691,0.499909,0.005229,0.477376,0.518784
1,0.1,0.197791,0.026065,0.038852,0.032458,0.069015,0.499909,0.005227,0.477392,0.518785

==============================
Delta global BAP2: λ=0.1 menos λ=0.0
==============================

,delta_S_id_child_0.1_minus_0.0,delta_S_p_father_0.1_minus_0.0,delta_S_m_mother_0.1_minus_0.0,delta_S_family_0.1_minus_0.0,delta_balance_abs_gap_0.1_minus_0.0
0,0.009009,0.004548,0.009682,0.007115,-0.000676

==============================
Summary by age BAP2: λ=0.0 vs λ=0.1
==============================

,age,parent_scale,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap
0,15,0.0,0.143712,0.010130,0.036404,0.023267,0.089591
1,15,0.1,0.150570,0.018103,0.053007,0.035555,0.083967
2,25,0.0,0.176557,0.014231,0.029358,0.021794,0.066584
3,25,0.1,0.184387,0.021055,0.032742,0.026899,0.059249
4,40,0.0,0.261945,0.053046,0.028864,0.040955,0.060202
5,40,0.1,0.269313,0.057840,0.038925,0.048382,0.064634
6,60,0.0,0.172917,0.008662,0.022051,0.015356,0.062385
7,60,0.1,0.186896,0.007261,0.030732,0.018996,0.068210

==============================
Delta by age BAP2: λ=0.1 minus λ=0.0
==============================

,age,delta_S_id_child_0.1_minus_0.0,delta_S_p_father_0.1_minus_0.0,delta_S_m_mother_0.1_minus_0.0,delta_S_family_0.1_minus_0.0,delta_balance_abs_gap_0.1_minus_0.0
0,15,0.006858,0.007973,0.016603,0.012288,-0.005624
1,25,0.007829,0.006825,0.003384,0.005105,-0.007335
2,40,0.007368,0.004795,0.010061,0.007428,0.004431
3,60,0.013979,-0.001401,0.008681,0.003640,0.005825

✓ Results saved to:
/content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_step500_lambda_ablation

In [12]:
# ============================================================
# Cell — BAP2 visual audit (FIXED)
# Does not use cross_attention_kwargs.
# Builds prompt_embeds + child/father/mother tokens as in evaluation.
# ============================================================

import os
import math
import numpy as np
import torch
import matplotlib.pyplot as plt
from PIL import Image
from torch.utils.data._utils.collate import default_collate

# -------------------------------
# Configuration
# -------------------------------
TRIAD_IDX       = 0
AGES_TO_SHOW    = [5, 10, 15, 20, 25, 30, 40, 50, 60]
PARENT_SCALE    = 0.1
GUIDANCE_SCALE  = 4.0
NUM_STEPS       = 30
SEED            = 42

NEG_PROMPT = "monochrome, lowres, bad anatomy, worst quality, low quality, blurry"

print("CURRENT_STEP:", CURRENT_STEP if "CURRENT_STEP" in globals() else "N/A")
print("TRIAD_IDX:", TRIAD_IDX)
print("AGES:", AGES_TO_SHOW)
print("PARENT_SCALE:", PARENT_SCALE)

# -------------------------------
# Helpers
# -------------------------------
def ensure_2d(x):
    if x.ndim == 1:
        x = x.unsqueeze(0)
    return x

def set_parent_scale_bap2(unet, value):
    for proc in unet.attn_processors.values():
        if type(proc).__name__ == "BAP2":
            proc.parent_scale = value

def load_fiw_image(key):
    path = os.path.join(FIW_ROOT, key)
    if not os.path.exists(path):
        print("Not found:", path)
        return None
    return Image.open(path).convert("RGB")

def tensor_img_to_pil(x):
    x = x.detach().cpu().float()
    x = (x + 1.0) / 2.0
    x = x.clamp(0, 1)
    x = x.permute(1, 2, 0).numpy()
    x = (x * 255).astype(np.uint8)
    return Image.fromarray(x)

def show_or_placeholder(ax, pil_img, title):
    ax.axis("off")
    ax.set_title(title, fontsize=10)
    if pil_img is None:
        ax.text(0.5, 0.5, "Not found", ha="center", va="center")
    else:
        ax.imshow(pil_img)

@torch.inference_mode()
def generate_bap2_age_correct(h_c, h_p, h_m, gender, age, parent_scale, seed=42):
    pipe.unet.eval()
    pipe.vae.eval()
    pipe.text_encoder.eval()
    ip_model.image_proj_model.eval()

    set_parent_scale_bap2(pipe.unet, parent_scale)

    h_c = ensure_2d(h_c).to(device=DEVICE, dtype=DTYPE)
    h_p = ensure_2d(h_p).to(device=DEVICE, dtype=DTYPE)
    h_m = ensure_2d(h_m).to(device=DEVICE, dtype=DTYPE)

    child_tokens  = ip_model.image_proj_model(h_c)
    father_tokens = ip_model.image_proj_model(h_p)
    mother_tokens = ip_model.image_proj_model(h_m)

    zero_child_tokens  = ip_model.image_proj_model(torch.zeros_like(h_c))
    zero_father_tokens = ip_model.image_proj_model(torch.zeros_like(h_p))
    zero_mother_tokens = ip_model.image_proj_model(torch.zeros_like(h_m))

    prompt = f"portrait photo of a {gender}, age {age}, realistic, neutral expression"

    prompt_embeds, negative_prompt_embeds = pipe.encode_prompt(
        prompt=[prompt],
        device=DEVICE,
        num_images_per_prompt=1,
        do_classifier_free_guidance=True,
        negative_prompt=[NEG_PROMPT],
    )

    prompt_embeds = torch.cat(
        [prompt_embeds, child_tokens, father_tokens, mother_tokens],
        dim=1,
    )

    negative_prompt_embeds = torch.cat(
        [negative_prompt_embeds, zero_child_tokens, zero_father_tokens, zero_mother_tokens],
        dim=1,
    )

    generator = torch.Generator(device=DEVICE).manual_seed(seed)

    img = pipe(
        prompt_embeds=prompt_embeds,
        negative_prompt_embeds=negative_prompt_embeds,
        guidance_scale=GUIDANCE_SCALE,
        num_inference_steps=NUM_STEPS,
        generator=generator,
    ).images[0]

    return img, prompt

# -------------------------------
# Load sample
# -------------------------------
sample = val_ds[TRIAD_IDX]

batch = default_collate([sample])
batch = {
    k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
    for k, v in batch.items()
}

h_c = ensure_2d(batch["h_c"])
h_p = ensure_2d(batch["h_p"])
h_m = ensure_2d(batch["h_m"])

gender = sample.get("gender", "person")
if gender not in ["man", "woman", "person"]:
    gender = "person"

img_p = load_fiw_image(sample["key_p"])
img_m = load_fiw_image(sample["key_m"])
img_c = load_fiw_image(sample["key_c"])

if img_c is None and "img" in sample:
    img_c = tensor_img_to_pil(sample["img"])

print("Father:", sample["key_p"])
print("Mother:", sample["key_m"])
print("Child :", sample["key_c"])
print("Gender:", gender)
print("Age real estimada:", sample["age"])

# -------------------------------
# Generate ages
# -------------------------------
gen_images = []

for age in AGES_TO_SHOW:
    img_gen, prompt = generate_bap2_age_correct(
        h_c=h_c,
        h_p=h_p,
        h_m=h_m,
        gender=gender,
        age=age,
        parent_scale=PARENT_SCALE,
        seed=SEED,
    )
    gen_images.append((age, img_gen))
    print(f"✓ age={age} generado")

# -------------------------------
# Visualization
# -------------------------------
total_panels = 3 + len(gen_images)
ncols = 4
nrows = math.ceil(total_panels / ncols)

fig, axes = plt.subplots(nrows, ncols, figsize=(4 * ncols, 4.4 * nrows))
axes = np.array(axes).reshape(-1)

show_or_placeholder(axes[0], img_p, "Real father")
show_or_placeholder(axes[1], img_m, "Real mother")
show_or_placeholder(axes[2], img_c, f"Real child | age≈{sample['age']}")

for i, (age, img_gen) in enumerate(gen_images, start=3):
    show_or_placeholder(axes[i], img_gen, f"BAP2 age {age}")

for j in range(3 + len(gen_images), len(axes)):
    axes[j].axis("off")

plt.suptitle(
    f"BAP2 visual audit | idx={TRIAD_IDX} | gender={gender} | parent_scale={PARENT_SCALE}",
    fontsize=15
)
plt.tight_layout()
plt.show()

CURRENT_STEP: 500
TRIAD_IDX: 0
AGES: [5, 10, 15, 20, 25, 30, 40, 50, 60]
PARENT_SCALE: 0.1
Padre: F0011/MID1/P00114_face3.jpg
Madre: F0011/MID3/P00114_face1.jpg
Hijo : F0011/MID2/P00113_face1.jpg
Gender: man
Age real estimada: 5

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=5 generado

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=10 generado

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=15 generado

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=20 generado

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=25 generado

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=30 generado

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=40 generado

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=50 generado

  0%|          | 0/30 [00:00<?, ?it/s]

✓ age=60 generado

In [ ]:
# ============================================================
# Cell — parent_scale sweep BAP2 step500
# Clean triads: [1, 5, 8]
# Scales: [0.0, 0.05, 0.1, 0.2]
# Ages: [15, 25, 40, 60]
#
# No training. Only generates, evaluates and saves figures/tables.
# ============================================================

import os
import math
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import torchvision.transforms as T
from PIL import Image
from torch.utils.data._utils.collate import default_collate
from IPython.display import display

# -------------------------------
# Configuration
# -------------------------------
SWEEP_IDXS = [1, 5, 8]
PARENT_SCALES = [0.0, 0.05, 0.1, 0.2]
AGES = [15, 25, 40, 60]

GUIDANCE_SCALE = 4.0
NUM_STEPS = 30
SEED = 42

NEG_PROMPT = "monochrome, lowres, bad anatomy, worst quality, low quality, blurry"

EVAL_STEP = CURRENT_STEP if "CURRENT_STEP" in globals() else 500

OUT_SWEEP_DIR = (
    f"{DRIVE}/results/child_anchor_bap_gate/"
    f"bap2_step{EVAL_STEP}_parent_scale_sweep_clean"
)
os.makedirs(OUT_SWEEP_DIR, exist_ok=True)

print("EVAL_STEP:", EVAL_STEP)
print("SWEEP_IDXS:", SWEEP_IDXS)
print("PARENT_SCALES:", PARENT_SCALES)
print("AGES:", AGES)
print("Total generaciones:", len(SWEEP_IDXS) * len(PARENT_SCALES) * len(AGES))
print("Salida:", OUT_SWEEP_DIR)

# -------------------------------
# Helpers
# -------------------------------
def ensure_2d(x):
    if x.ndim == 1:
        x = x.unsqueeze(0)
    return x

def set_parent_scale_bap2(unet, value):
    for proc in unet.attn_processors.values():
        if type(proc).__name__ == "BAP2":
            proc.parent_scale = value

def load_fiw_image_safe(key):
    path = os.path.join(FIW_ROOT, key)
    if not os.path.exists(path):
        return None
    return Image.open(path).convert("RGB")

def show_img(ax, img, title):
    ax.axis("off")
    ax.set_title(title, fontsize=9)
    if img is None:
        ax.text(0.5, 0.5, "Not found", ha="center", va="center")
    else:
        ax.imshow(img)

def collect_bap2_alpha_stats(unet):
    vals = []

    for name, proc in unet.attn_processors.items():
        if type(proc).__name__ == "BAP2":
            if getattr(proc, "last_alpha", None) is not None:
                vals.append(proc.last_alpha.detach().float().cpu())

    if len(vals) == 0:
        return {
            "alpha_mean": None,
            "alpha_std": None,
            "alpha_min": None,
            "alpha_max": None,
        }

    x = torch.cat(vals, dim=0)

    return {
        "alpha_mean": x.mean().item(),
        "alpha_std": x.std().item(),
        "alpha_min": x.min().item(),
        "alpha_max": x.max().item(),
    }

# ArcFace preprocessing, same as in the previous evaluation
preprocess_arcface = T.Compose([
    T.Resize((112, 112)),
    T.ToTensor(),
    T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
])

@torch.inference_mode()
def arcface_embed_from_pil(img):
    x = preprocess_arcface(img.convert("RGB")).unsqueeze(0).to(DEVICE)
    x = x.float()
    emb = arcface_torch(x)
    emb = F.normalize(emb, p=2, dim=1)
    return emb

@torch.inference_mode()
def generate_bap2_age_sweep(h_c, h_p, h_m, gender, age, parent_scale, seed=42):
    """
    Correct for our BAP2:
    encoder_hidden_states = [prompt | child_tokens | father_tokens | mother_tokens]
    """
    pipe.unet.eval()
    pipe.vae.eval()
    pipe.text_encoder.eval()
    ip_model.image_proj_model.eval()

    set_parent_scale_bap2(pipe.unet, parent_scale)

    h_c = ensure_2d(h_c).to(device=DEVICE, dtype=DTYPE)
    h_p = ensure_2d(h_p).to(device=DEVICE, dtype=DTYPE)
    h_m = ensure_2d(h_m).to(device=DEVICE, dtype=DTYPE)

    child_tokens  = ip_model.image_proj_model(h_c)
    father_tokens = ip_model.image_proj_model(h_p)
    mother_tokens = ip_model.image_proj_model(h_m)

    zero_child_tokens  = ip_model.image_proj_model(torch.zeros_like(h_c))
    zero_father_tokens = ip_model.image_proj_model(torch.zeros_like(h_p))
    zero_mother_tokens = ip_model.image_proj_model(torch.zeros_like(h_m))

    prompt = f"portrait photo of a {gender}, age {age}, realistic, neutral expression"

    prompt_embeds, negative_prompt_embeds = pipe.encode_prompt(
        prompt=[prompt],
        device=DEVICE,
        num_images_per_prompt=1,
        do_classifier_free_guidance=True,
        negative_prompt=[NEG_PROMPT],
    )

    prompt_embeds = torch.cat(
        [prompt_embeds, child_tokens, father_tokens, mother_tokens],
        dim=1,
    )

    negative_prompt_embeds = torch.cat(
        [negative_prompt_embeds, zero_child_tokens, zero_father_tokens, zero_mother_tokens],
        dim=1,
    )

    generator = torch.Generator(device=DEVICE).manual_seed(seed)

    img = pipe(
        prompt_embeds=prompt_embeds,
        negative_prompt_embeds=negative_prompt_embeds,
        guidance_scale=GUIDANCE_SCALE,
        num_inference_steps=NUM_STEPS,
        generator=generator,
    ).images[0]

    alpha_stats = collect_bap2_alpha_stats(pipe.unet)

    return img, prompt, alpha_stats

# ============================================================
# Sweep
# ============================================================

all_rows = []

for triad_idx in SWEEP_IDXS:

    print("\n" + "=" * 100)
    print("TRIAD_IDX:", triad_idx)
    print("=" * 100)

    sample = val_ds[triad_idx]

    batch = default_collate([sample])
    batch = {
        k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
        for k, v in batch.items()
    }

    h_c = ensure_2d(batch["h_c"])
    h_p = ensure_2d(batch["h_p"])
    h_m = ensure_2d(batch["h_m"])

    h_c_eval = F.normalize(h_c.float(), p=2, dim=1)
    h_p_eval = F.normalize(h_p.float(), p=2, dim=1)
    h_m_eval = F.normalize(h_m.float(), p=2, dim=1)

    gender = sample.get("gender", "person")
    if gender not in ["man", "woman", "person"]:
        gender = "person"

    img_p = load_fiw_image_safe(sample["key_p"])
    img_m = load_fiw_image_safe(sample["key_m"])
    img_c = load_fiw_image_safe(sample["key_c"])

    print("Father:", sample["key_p"])
    print("Mother:", sample["key_m"])
    print("Child :", sample["key_c"])
    print("Gender:", gender)
    print("Age real estimada:", sample["age"])

    generated = {}

    for parent_scale in PARENT_SCALES:
        for age in AGES:

            img_gen, prompt, alpha_stats = generate_bap2_age_sweep(
                h_c=h_c,
                h_p=h_p,
                h_m=h_m,
                gender=gender,
                age=age,
                parent_scale=parent_scale,
                seed=SEED,
            )

            generated[(parent_scale, age)] = img_gen

            h_gen = arcface_embed_from_pil(img_gen)

            S_id = F.cosine_similarity(h_gen, h_c_eval).item()
            S_p = F.cosine_similarity(h_gen, h_p_eval).item()
            S_m = F.cosine_similarity(h_gen, h_m_eval).item()

            all_rows.append({
                "triad_idx": triad_idx,
                "gender": gender,
                "age": age,
                "parent_scale": parent_scale,
                "S_id_child": S_id,
                "S_p_father": S_p,
                "S_m_mother": S_m,
                "S_family": 0.5 * (S_p + S_m),
                "balance_abs_gap": abs(S_p - S_m),
                "alpha_mean": alpha_stats["alpha_mean"],
                "alpha_std": alpha_stats["alpha_std"],
                "alpha_min": alpha_stats["alpha_min"],
                "alpha_max": alpha_stats["alpha_max"],
                "key_p": sample["key_p"],
                "key_m": sample["key_m"],
                "key_c": sample["key_c"],
            })

            print(
                f"idx={triad_idx} | λ={parent_scale} | age={age} | "
                f"S_id={S_id:.4f} | S_family={0.5 * (S_p + S_m):.4f}"
            )

    # -------------------------------
    # Figure per triad
    # Fila 0: reales
    # Following rows: each parent_scale
    # Columns: real/ages
    # -------------------------------
    nrows = 1 + len(PARENT_SCALES)
    ncols = max(3, len(AGES))

    fig, axes = plt.subplots(nrows, ncols, figsize=(4 * ncols, 4.2 * nrows))

    if nrows == 1:
        axes = axes.reshape(1, -1)

    # Fila reales
    show_img(axes[0, 0], img_p, "Real father")
    show_img(axes[0, 1], img_m, "Real mother")
    show_img(axes[0, 2], img_c, f"Real child | age≈{sample['age']}")

    for c in range(3, ncols):
        axes[0, c].axis("off")

    # Scale rows
    for r, parent_scale in enumerate(PARENT_SCALES, start=1):
        for c, age in enumerate(AGES):
            img_gen = generated[(parent_scale, age)]
            show_img(
                axes[r, c],
                img_gen,
                f"λ={parent_scale} | age {age}"
            )

    plt.suptitle(
        f"Sweep parent_scale BAP2 | idx={triad_idx} | gender={gender} | step={EVAL_STEP}",
        fontsize=15
    )
    plt.tight_layout()

    fig_path = f"{OUT_SWEEP_DIR}/sweep_idx{triad_idx}_step{EVAL_STEP}.png"
    plt.savefig(fig_path, dpi=160, bbox_inches="tight")
    plt.show()

    print("✓ Figura guardada:", fig_path)

# ============================================================
# Tablas resumen
# ============================================================

df_sweep = pd.DataFrame(all_rows)

csv_path = f"{OUT_SWEEP_DIR}/df_parent_scale_sweep_clean.csv"
df_sweep.to_csv(csv_path, index=False)

print("\n✓ Full CSV saved:")
print(csv_path)

print("\n==============================")
print("Full results")
print("==============================")
display(df_sweep)

summary_global = (
    df_sweep
    .groupby("parent_scale")
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
    ]]
    .mean()
    .reset_index()
)

print("\n==============================")
print("Global summary by parent_scale")
print("==============================")
display(summary_global)

summary_age = (
    df_sweep
    .groupby(["age", "parent_scale"])
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
    ]]
    .mean()
    .reset_index()
)

print("\n==============================")
print("Summary by age and parent_scale")
print("==============================")
display(summary_age)

# Delta contra λ=0.0
base = summary_global[summary_global["parent_scale"] == 0.0].iloc[0]

delta_rows = []
for _, row in summary_global.iterrows():
    delta_rows.append({
        "parent_scale": row["parent_scale"],
        "delta_S_id_child_vs_0.0": row["S_id_child"] - base["S_id_child"],
        "delta_S_family_vs_0.0": row["S_family"] - base["S_family"],
        "delta_S_p_father_vs_0.0": row["S_p_father"] - base["S_p_father"],
        "delta_S_m_mother_vs_0.0": row["S_m_mother"] - base["S_m_mother"],
        "delta_balance_abs_gap_vs_0.0": row["balance_abs_gap"] - base["balance_abs_gap"],
    })

df_delta = pd.DataFrame(delta_rows)

print("\n==============================")
print("Delta global contra parent_scale=0.0")
print("==============================")
display(df_delta)

summary_global.to_csv(f"{OUT_SWEEP_DIR}/summary_global_parent_scale.csv", index=False)
summary_age.to_csv(f"{OUT_SWEEP_DIR}/summary_age_parent_scale.csv", index=False)
df_delta.to_csv(f"{OUT_SWEEP_DIR}/delta_vs_scale0.csv", index=False)

print("\n✓ Summaries saved to:")
print(OUT_SWEEP_DIR)

EVAL_STEP: 500
SWEEP_IDXS: [1, 5, 8]
PARENT_SCALES: [0.0, 0.05, 0.1, 0.2]
AGES: [15, 25, 40, 60]
Total generaciones: 48
Salida: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_step500_parent_scale_sweep_clean

====================================================================================================
TRIAD_IDX: 1
====================================================================================================
Padre: F0037/MID1/P00382_face3.jpg
Madre: F0037/MID5/P00384_face1.jpg
Hijo : F0037/MID6/P00385_face6.jpg
Gender: man
Age real estimada: 8

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.0 | age=15 | S_id=0.2669 | S_family=0.0139

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.0 | age=25 | S_id=0.3444 | S_family=-0.0096

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.0 | age=40 | S_id=0.2918 | S_family=0.0453

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.0 | age=60 | S_id=0.2062 | S_family=0.0710

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.05 | age=15 | S_id=0.2791 | S_family=0.0397

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.05 | age=25 | S_id=0.3461 | S_family=-0.0053

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.05 | age=40 | S_id=0.2913 | S_family=0.0493

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.05 | age=60 | S_id=0.1928 | S_family=0.0651

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.1 | age=15 | S_id=0.2885 | S_family=0.0340

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.1 | age=25 | S_id=0.3462 | S_family=-0.0040

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.1 | age=40 | S_id=0.2885 | S_family=0.0524

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.1 | age=60 | S_id=0.1904 | S_family=0.0728

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.2 | age=15 | S_id=0.2889 | S_family=0.0342

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.2 | age=25 | S_id=0.3425 | S_family=0.0037

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.2 | age=40 | S_id=0.2811 | S_family=0.0594

  0%|          | 0/30 [00:00<?, ?it/s]

idx=1 | λ=0.2 | age=60 | S_id=0.1800 | S_family=0.0709

✓ Figura guardada: /content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_step500_parent_scale_sweep_clean/sweep_idx1_step500.png

====================================================================================================
TRIAD_IDX: 5
====================================================================================================
Padre: F0037/MID1/P00382_face3.jpg
Madre: F0037/MID8/P00390_face1.jpg
Hijo : F0037/MID4/P00382_face2.jpg
Gender: woman
Age real estimada: 6

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.0 | age=15 | S_id=0.2069 | S_family=0.0122

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.0 | age=25 | S_id=0.1824 | S_family=-0.0079

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.0 | age=40 | S_id=0.1737 | S_family=0.0080

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.0 | age=60 | S_id=0.1756 | S_family=0.0427

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.05 | age=15 | S_id=0.2175 | S_family=0.0259

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.05 | age=25 | S_id=0.1872 | S_family=-0.0024

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.05 | age=40 | S_id=0.1718 | S_family=0.0237

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.05 | age=60 | S_id=0.1765 | S_family=0.0494

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.1 | age=15 | S_id=0.2570 | S_family=0.0315

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.1 | age=25 | S_id=0.1929 | S_family=-0.0025

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.1 | age=40 | S_id=0.1856 | S_family=0.0149

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.1 | age=60 | S_id=0.1764 | S_family=0.0554

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.2 | age=15 | S_id=0.2283 | S_family=0.0337

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.2 | age=25 | S_id=0.0911 | S_family=-0.0079

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.2 | age=40 | S_id=0.1343 | S_family=0.0210

  0%|          | 0/30 [00:00<?, ?it/s]

idx=5 | λ=0.2 | age=60 | S_id=0.1759 | S_family=0.0625

In [8]:
from collections import Counter
import os
import pandas as pd

print("test_ds exists:", "test_ds" in globals())
print("bap2_modules exists:", "bap2_modules" in globals())
print("generate_bap2_final exists:", "generate_bap2_final" in globals())
print("arcface_embed_from_pil exists:", "arcface_embed_from_pil" in globals())
print("ensure_2d exists:", "ensure_2d" in globals())

if "bap2_modules" in globals():
    print("len bap2_modules:", len(bap2_modules))

types = Counter(type(p).__name__ for p in pipe.unet.attn_processors.values())
print("Processors:", types)

OUT_CSV = f"{DRIVE}/results/eval/nogate/nogate.csv"
print("Partial CSV exists:", os.path.exists(OUT_CSV))

if os.path.exists(OUT_CSV):
    df = pd.read_csv(OUT_CSV)
    print("Filas actuales:", len(df))
    print("Unique triads:", df["triad_idx"].nunique())
    print("Last rows:")
    display(df.tail())

test_ds exists: True
bap2_modules exists: True
generate_bap2_final exists: False
arcface_embed_from_pil exists: False
ensure_2d exists: False
len bap2_modules: 16
Processors: Counter({'LoRAAttnProcessor2_0': 16, 'BAP2': 16})
Partial CSV exists: True
Filas actuales: 450
Unique triads: 90
Last rows:

,variant,checkpoint_step,triad_idx,age,parent_scale,gender,S_id_child,S_p_father,S_m_mother,S_family,...,alpha_mean,alpha_std,alpha_min,alpha_max,key_p,key_m,key_c,seed,prompt,image_path
445,NoGate_fixed_alpha05,fixed_alpha_0.5,89,5,0.1,woman,0.328934,0.086942,-0.005537,0.040703,...,0.5,0.0,0.5,0.5,F0542/MID4/P05684_face5.jpg,F0542/MID5/P05684_face2.jpg,F0542/MID2/P05684_face1.jpg,89047,"portrait photo of a woman, age 5, realistic, n...",/content/drive/MyDrive/Notebook4/results/final...
446,NoGate_fixed_alpha05,fixed_alpha_0.5,89,15,0.1,woman,0.357122,0.074940,-0.046193,0.014374,...,0.5,0.0,0.5,0.5,F0542/MID4/P05684_face5.jpg,F0542/MID5/P05684_face2.jpg,F0542/MID2/P05684_face1.jpg,89057,"portrait photo of a woman, age 15, realistic, ...",/content/drive/MyDrive/Notebook4/results/final...
447,NoGate_fixed_alpha05,fixed_alpha_0.5,89,25,0.1,woman,0.432372,0.133125,-0.077023,0.028051,...,0.5,0.0,0.5,0.5,F0542/MID4/P05684_face5.jpg,F0542/MID5/P05684_face2.jpg,F0542/MID2/P05684_face1.jpg,89067,"portrait photo of a woman, age 25, realistic, ...",/content/drive/MyDrive/Notebook4/results/final...
448,NoGate_fixed_alpha05,fixed_alpha_0.5,89,40,0.1,woman,0.351275,0.065148,0.012005,0.038576,...,0.5,0.0,0.5,0.5,F0542/MID4/P05684_face5.jpg,F0542/MID5/P05684_face2.jpg,F0542/MID2/P05684_face1.jpg,89082,"portrait photo of a woman, age 40, realistic, ...",/content/drive/MyDrive/Notebook4/results/final...
449,NoGate_fixed_alpha05,fixed_alpha_0.5,89,60,0.1,woman,-0.061819,-0.047405,0.026627,-0.010389,...,0.5,0.0,0.5,0.5,F0542/MID4/P05684_face5.jpg,F0542/MID5/P05684_face2.jpg,F0542/MID2/P05684_face1.jpg,89102,"portrait photo of a woman, age 60, realistic, ...",/content/drive/MyDrive/Notebook4/results/final...

In [10]:
# ============================================================
# TEST FINAL — NoGate / FixedGate α=0.5
# 208 triads × 5 ages × λ=0.1 = 1040 images
#
# Baseline:
#   child anchor + father + mother
#   but WITHOUT a learned gate
#   alpha = 0.5 fijo
# ============================================================

import os
import torch
import torch.nn.functional as F
import pandas as pd
from torch.utils.data._utils.collate import default_collate
from IPython.display import display

# ------------------------------------------------------------
# Verificaciones
# ------------------------------------------------------------

required = [
    "test_ds",
    "bap2_modules",
    "generate_bap2_final",
    "arcface_embed_from_pil",
    "ensure_2d",
]

missing = [x for x in required if x not in globals()]
assert len(missing) == 0, f"Missing objects in memory: {missing}"

assert len(bap2_modules) == 16, "bap2_modules must have 16 modules."

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

AGES = [5, 15, 25, 40, 60]
PARENT_SCALE = 0.1

BASE_SEED = 42

OUT_DIR = f"{DRIVE}/results/eval/nogate"
IMG_DIR = f"{OUT_DIR}/images"
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(IMG_DIR, exist_ok=True)

OUT_CSV = f"{OUT_DIR}/nogate.csv"

print("Test triads:", len(test_ds))
print("Ages:", AGES)
print("Parent scale:", PARENT_SCALE)
print("Total images:", len(test_ds) * len(AGES))
print("OUT_DIR:", OUT_DIR)

# ------------------------------------------------------------
# Forzar NoGate: alpha = sigmoid(0) = 0.5
# ------------------------------------------------------------

for name, proc in bap2_modules.items():
    proc.gate.float()
    with torch.no_grad():
        proc.gate.weight.zero_()
        proc.gate.bias.zero_()
    proc.gate.to(DEVICE)

print("✓ Gates reseteados a cero: alpha fijo = 0.5")

# Sanity check alpha
with torch.no_grad():
    first_name, first_proc = next(iter(bap2_modules.items()))
    dummy = torch.randn(
        1,
        first_proc.gate.in_features,
        device=DEVICE,
        dtype=torch.float32,
    )
    alpha = torch.sigmoid(first_proc.gate(dummy))

print("Alpha sanity:")
print("mean:", alpha.mean().item())
print("std :", alpha.std().item())
print("min :", alpha.min().item())
print("max :", alpha.max().item())

assert abs(alpha.mean().item() - 0.5) < 1e-6
assert alpha.std().item() < 1e-6

# ------------------------------------------------------------
# Saving NoGate images
# ------------------------------------------------------------

def save_nogate_image(img, triad_idx, age):
    subdir = f"{IMG_DIR}/age_{age}"
    os.makedirs(subdir, exist_ok=True)

    path = f"{subdir}/t{triad_idx:04d}_a{int(age):02d}.jpg"
    img.save(path, quality=95)
    return path

# ------------------------------------------------------------
# Automatic resume
# ------------------------------------------------------------

rows = []
done = set()

if os.path.exists(OUT_CSV):
    old = pd.read_csv(OUT_CSV)
    rows = old.to_dict("records")
    done = set(zip(old["triad_idx"], old["age"]))
    print(f"✓ Resume detected: {len(old)} existing rows")

# ------------------------------------------------------------
# Loop principal
# ------------------------------------------------------------

for triad_idx in range(len(test_ds)):

    sample = test_ds[triad_idx]

    batch = default_collate([sample])
    batch = {
        k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
        for k, v in batch.items()
    }

    h_c = ensure_2d(batch["h_c"])
    h_p = ensure_2d(batch["h_p"])
    h_m = ensure_2d(batch["h_m"])

    h_c_eval = F.normalize(h_c.float(), p=2, dim=1)
    h_p_eval = F.normalize(h_p.float(), p=2, dim=1)
    h_m_eval = F.normalize(h_m.float(), p=2, dim=1)

    gender = sample.get("gender", "person")
    if gender not in ["man", "woman", "person"]:
        gender = "person"

    print(f"\nNoGate | Triada {triad_idx + 1}/{len(test_ds)} | gender={gender}")

    for age in AGES:

        if (triad_idx, age) in done:
            print(f"skip triad={triad_idx} age={age}")
            continue

        paired_seed = BASE_SEED + triad_idx * 1000 + age

        img, alpha_stats, prompt = generate_bap2_final(
            h_c=h_c,
            h_p=h_p,
            h_m=h_m,
            gender=gender,
            age=age,
            parent_scale=PARENT_SCALE,
            seed=paired_seed,
        )

        img_path = save_nogate_image(
            img=img,
            triad_idx=triad_idx,
            age=age,
        )

        h_gen = arcface_embed_from_pil(img)

        S_id = F.cosine_similarity(h_gen, h_c_eval).item()
        S_p  = F.cosine_similarity(h_gen, h_p_eval).item()
        S_m  = F.cosine_similarity(h_gen, h_m_eval).item()

        row = {
            "variant": "NoGate_fixed_alpha05",
            "checkpoint_step": "fixed_alpha_0.5",
            "triad_idx": triad_idx,
            "age": age,
            "parent_scale": PARENT_SCALE,
            "gender": gender,
            "S_id_child": S_id,
            "S_p_father": S_p,
            "S_m_mother": S_m,
            "S_family": 0.5 * (S_p + S_m),
            "balance_abs_gap": abs(S_p - S_m),
            "alpha_mean": alpha_stats["alpha_mean"],
            "alpha_std": alpha_stats["alpha_std"],
            "alpha_min": alpha_stats["alpha_min"],
            "alpha_max": alpha_stats["alpha_max"],
            "key_p": sample.get("key_p", ""),
            "key_m": sample.get("key_m", ""),
            "key_c": sample.get("key_c", ""),
            "seed": paired_seed,
            "prompt": prompt,
            "image_path": img_path,
        }

        rows.append(row)

        # Incremental saving
        pd.DataFrame(rows).to_csv(OUT_CSV, index=False)

        print(
            f"age={age} | "
            f"S_id={S_id:.4f} | "
            f"S_p={S_p:.4f} | "
            f"S_m={S_m:.4f} | "
            f"S_family={row['S_family']:.4f} | "
            f"gap={row['balance_abs_gap']:.4f} | "
            f"alpha_mean={alpha_stats['alpha_mean']:.4f}"
        )

# ------------------------------------------------------------
# Final summary NoGate
# ------------------------------------------------------------

df_final_nogate = pd.DataFrame(rows)

print("\n==============================")
print("Filas finales NoGate")
print("==============================")
print(len(df_final_nogate))

expected_rows = len(test_ds) * len(AGES)
print("Esperadas:", expected_rows)

if len(df_final_nogate) != expected_rows:
    print("⚠ Warning: unexpected number of rows. Check whether there was an interruption.")
else:
    print("✓ Row count is correct.")

summary_nogate_global = (
    df_final_nogate
    .groupby("variant")
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
        "alpha_min",
        "alpha_max",
    ]]
    .mean()
    .reset_index()
)

summary_nogate_age = (
    df_final_nogate
    .groupby(["age"])
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
        "alpha_min",
        "alpha_max",
    ]]
    .mean()
    .reset_index()
)

print("\n==============================")
print("Global summary NoGate")
print("==============================")
display(summary_nogate_global)

print("\n==============================")
print("Summary by age NoGate")
print("==============================")
display(summary_nogate_age)

summary_nogate_global.to_csv(f"{OUT_DIR}/summary_global_nogate.csv", index=False)
summary_nogate_age.to_csv(f"{OUT_DIR}/summary_age_nogate.csv", index=False)

print("\n✓ TEST FINAL NoGate terminado")
print("CSV:", OUT_CSV)
print("Images:", IMG_DIR)
print("Summary:", OUT_DIR)

Test triads: 208
Edades: [5, 15, 25, 40, 60]
Parent scale: 0.1
Total images: 1040
OUT_DIR: /content/drive/MyDrive/Notebook4/results/eval/nogate
✓ Gates reseteados a cero: alpha fijo = 0.5
Alpha sanity:
mean: 0.5
std : 0.0
min : 0.5
max : 0.5
✓ Resume detected: 450 existing rows

NoGate | Triada 1/208 | gender=woman
skip triad=0 age=5
skip triad=0 age=15
skip triad=0 age=25
skip triad=0 age=40
skip triad=0 age=60

NoGate | Triada 2/208 | gender=woman
skip triad=1 age=5
skip triad=1 age=15
skip triad=1 age=25
skip triad=1 age=40
skip triad=1 age=60

NoGate | Triada 3/208 | gender=woman
skip triad=2 age=5
skip triad=2 age=15
skip triad=2 age=25
skip triad=2 age=40
skip triad=2 age=60

NoGate | Triada 4/208 | gender=woman
skip triad=3 age=5
skip triad=3 age=15
skip triad=3 age=25
skip triad=3 age=40
skip triad=3 age=60

NoGate | Triada 5/208 | gender=man
skip triad=4 age=5
skip triad=4 age=15
skip triad=4 age=25
skip triad=4 age=40
skip triad=4 age=60

NoGate | Triada 6/208 | gender=man
skip triad=5 age=5
skip triad=5 age=15
skip triad=5 age=25
skip triad=5 age=40
skip triad=5 age=60

NoGate | Triada 7/208 | gender=woman
skip triad=6 age=5
skip triad=6 age=15
skip triad=6 age=25
skip triad=6 age=40
skip triad=6 age=60

NoGate | Triada 8/208 | gender=man
skip triad=7 age=5
skip triad=7 age=15
skip triad=7 age=25
skip triad=7 age=40
skip triad=7 age=60

NoGate | Triada 9/208 | gender=woman
skip triad=8 age=5
skip triad=8 age=15
skip triad=8 age=25
skip triad=8 age=40
skip triad=8 age=60

NoGate | Triada 10/208 | gender=woman
skip triad=9 age=5
skip triad=9 age=15
skip triad=9 age=25
skip triad=9 age=40
skip triad=9 age=60

NoGate | Triada 11/208 | gender=woman
skip triad=10 age=5
skip triad=10 age=15
skip triad=10 age=25
skip triad=10 age=40
skip triad=10 age=60

NoGate | Triada 12/208 | gender=man
skip triad=11 age=5
skip triad=11 age=15
skip triad=11 age=25
skip triad=11 age=40
skip triad=11 age=60

NoGate | Triada 13/208 | gender=man
skip triad=12 age=5
skip triad=12 age=15
skip triad=12 age=25
skip triad=12 age=40
skip triad=12 age=60

NoGate | Triada 14/208 | gender=woman
skip triad=13 age=5
skip triad=13 age=15
skip triad=13 age=25
skip triad=13 age=40
skip triad=13 age=60

NoGate | Triada 15/208 | gender=man
skip triad=14 age=5
skip triad=14 age=15
skip triad=14 age=25
skip triad=14 age=40
skip triad=14 age=60

NoGate | Triada 16/208 | gender=woman
skip triad=15 age=5
skip triad=15 age=15
skip triad=15 age=25
skip triad=15 age=40
skip triad=15 age=60

NoGate | Triada 17/208 | gender=man
skip triad=16 age=5
skip triad=16 age=15
skip triad=16 age=25
skip triad=16 age=40
skip triad=16 age=60

NoGate | Triada 18/208 | gender=woman
skip triad=17 age=5
skip triad=17 age=15
skip triad=17 age=25
skip triad=17 age=40
skip triad=17 age=60

NoGate | Triada 19/208 | gender=woman
skip triad=18 age=5
skip triad=18 age=15
skip triad=18 age=25
skip triad=18 age=40
skip triad=18 age=60

NoGate | Triada 20/208 | gender=man
skip triad=19 age=5
skip triad=19 age=15
skip triad=19 age=25
skip triad=19 age=40
skip triad=19 age=60

NoGate | Triada 21/208 | gender=woman
skip triad=20 age=5
skip triad=20 age=15
skip triad=20 age=25
skip triad=20 age=40
skip triad=20 age=60

NoGate | Triada 22/208 | gender=man
skip triad=21 age=5
skip triad=21 age=15
skip triad=21 age=25
skip triad=21 age=40
skip triad=21 age=60

NoGate | Triada 23/208 | gender=man
skip triad=22 age=5
skip triad=22 age=15
skip triad=22 age=25
skip triad=22 age=40
skip triad=22 age=60

NoGate | Triada 24/208 | gender=man
skip triad=23 age=5
skip triad=23 age=15
skip triad=23 age=25
skip triad=23 age=40
skip triad=23 age=60

NoGate | Triada 25/208 | gender=woman
skip triad=24 age=5
skip triad=24 age=15
skip triad=24 age=25
skip triad=24 age=40
skip triad=24 age=60

NoGate | Triada 26/208 | gender=man
skip triad=25 age=5
skip triad=25 age=15
skip triad=25 age=25
skip triad=25 age=40
skip triad=25 age=60

NoGate | Triada 27/208 | gender=man
skip triad=26 age=5
skip triad=26 age=15
skip triad=26 age=25
skip triad=26 age=40
skip triad=26 age=60

NoGate | Triada 28/208 | gender=woman
skip triad=27 age=5
skip triad=27 age=15
skip triad=27 age=25
skip triad=27 age=40
skip triad=27 age=60

NoGate | Triada 29/208 | gender=man
skip triad=28 age=5
skip triad=28 age=15
skip triad=28 age=25
skip triad=28 age=40
skip triad=28 age=60

NoGate | Triada 30/208 | gender=woman
skip triad=29 age=5
skip triad=29 age=15
skip triad=29 age=25
skip triad=29 age=40
skip triad=29 age=60

NoGate | Triada 31/208 | gender=man
skip triad=30 age=5
skip triad=30 age=15
skip triad=30 age=25
skip triad=30 age=40
skip triad=30 age=60

NoGate | Triada 32/208 | gender=man
skip triad=31 age=5
skip triad=31 age=15
skip triad=31 age=25
skip triad=31 age=40
skip triad=31 age=60

NoGate | Triada 33/208 | gender=man
skip triad=32 age=5
skip triad=32 age=15
skip triad=32 age=25
skip triad=32 age=40
skip triad=32 age=60

NoGate | Triada 34/208 | gender=woman
skip triad=33 age=5
skip triad=33 age=15
skip triad=33 age=25
skip triad=33 age=40
skip triad=33 age=60

NoGate | Triada 35/208 | gender=woman
skip triad=34 age=5
skip triad=34 age=15
skip triad=34 age=25
skip triad=34 age=40
skip triad=34 age=60

NoGate | Triada 36/208 | gender=woman
skip triad=35 age=5
skip triad=35 age=15
skip triad=35 age=25
skip triad=35 age=40
skip triad=35 age=60

NoGate | Triada 37/208 | gender=man
skip triad=36 age=5
skip triad=36 age=15
skip triad=36 age=25
skip triad=36 age=40
skip triad=36 age=60

NoGate | Triada 38/208 | gender=man
skip triad=37 age=5
skip triad=37 age=15
skip triad=37 age=25
skip triad=37 age=40
skip triad=37 age=60

NoGate | Triada 39/208 | gender=man
skip triad=38 age=5
skip triad=38 age=15
skip triad=38 age=25
skip triad=38 age=40
skip triad=38 age=60

NoGate | Triada 40/208 | gender=man
skip triad=39 age=5
skip triad=39 age=15
skip triad=39 age=25
skip triad=39 age=40
skip triad=39 age=60

NoGate | Triada 41/208 | gender=man
skip triad=40 age=5
skip triad=40 age=15
skip triad=40 age=25
skip triad=40 age=40
skip triad=40 age=60

NoGate | Triada 42/208 | gender=man
skip triad=41 age=5
skip triad=41 age=15
skip triad=41 age=25
skip triad=41 age=40
skip triad=41 age=60

NoGate | Triada 43/208 | gender=woman
skip triad=42 age=5
skip triad=42 age=15
skip triad=42 age=25
skip triad=42 age=40
skip triad=42 age=60

NoGate | Triada 44/208 | gender=woman
skip triad=43 age=5
skip triad=43 age=15
skip triad=43 age=25
skip triad=43 age=40
skip triad=43 age=60

NoGate | Triada 45/208 | gender=woman
skip triad=44 age=5
skip triad=44 age=15
skip triad=44 age=25
skip triad=44 age=40
skip triad=44 age=60

NoGate | Triada 46/208 | gender=man
skip triad=45 age=5
skip triad=45 age=15
skip triad=45 age=25
skip triad=45 age=40
skip triad=45 age=60

NoGate | Triada 47/208 | gender=woman
skip triad=46 age=5
skip triad=46 age=15
skip triad=46 age=25
skip triad=46 age=40
skip triad=46 age=60

NoGate | Triada 48/208 | gender=woman
skip triad=47 age=5
skip triad=47 age=15
skip triad=47 age=25
skip triad=47 age=40
skip triad=47 age=60

NoGate | Triada 49/208 | gender=man
skip triad=48 age=5
skip triad=48 age=15
skip triad=48 age=25
skip triad=48 age=40
skip triad=48 age=60

NoGate | Triada 50/208 | gender=woman
skip triad=49 age=5
skip triad=49 age=15
skip triad=49 age=25
skip triad=49 age=40
skip triad=49 age=60

NoGate | Triada 51/208 | gender=man
skip triad=50 age=5
skip triad=50 age=15
skip triad=50 age=25
skip triad=50 age=40
skip triad=50 age=60

NoGate | Triada 52/208 | gender=man
skip triad=51 age=5
skip triad=51 age=15
skip triad=51 age=25
skip triad=51 age=40
skip triad=51 age=60

NoGate | Triada 53/208 | gender=woman
skip triad=52 age=5
skip triad=52 age=15
skip triad=52 age=25
skip triad=52 age=40
skip triad=52 age=60

NoGate | Triada 54/208 | gender=woman
skip triad=53 age=5
skip triad=53 age=15
skip triad=53 age=25
skip triad=53 age=40
skip triad=53 age=60

NoGate | Triada 55/208 | gender=man
skip triad=54 age=5
skip triad=54 age=15
skip triad=54 age=25
skip triad=54 age=40
skip triad=54 age=60

NoGate | Triada 56/208 | gender=woman
skip triad=55 age=5
skip triad=55 age=15
skip triad=55 age=25
skip triad=55 age=40
skip triad=55 age=60

NoGate | Triada 57/208 | gender=man
skip triad=56 age=5
skip triad=56 age=15
skip triad=56 age=25
skip triad=56 age=40
skip triad=56 age=60

NoGate | Triada 58/208 | gender=woman
skip triad=57 age=5
skip triad=57 age=15
skip triad=57 age=25
skip triad=57 age=40
skip triad=57 age=60

NoGate | Triada 59/208 | gender=woman
skip triad=58 age=5
skip triad=58 age=15
skip triad=58 age=25
skip triad=58 age=40
skip triad=58 age=60

NoGate | Triada 60/208 | gender=man
skip triad=59 age=5
skip triad=59 age=15
skip triad=59 age=25
skip triad=59 age=40
skip triad=59 age=60

NoGate | Triada 61/208 | gender=woman
skip triad=60 age=5
skip triad=60 age=15
skip triad=60 age=25
skip triad=60 age=40
skip triad=60 age=60

NoGate | Triada 62/208 | gender=man
skip triad=61 age=5
skip triad=61 age=15
skip triad=61 age=25
skip triad=61 age=40
skip triad=61 age=60

NoGate | Triada 63/208 | gender=man
skip triad=62 age=5
skip triad=62 age=15
skip triad=62 age=25
skip triad=62 age=40
skip triad=62 age=60

NoGate | Triada 64/208 | gender=man
skip triad=63 age=5
skip triad=63 age=15
skip triad=63 age=25
skip triad=63 age=40
skip triad=63 age=60

NoGate | Triada 65/208 | gender=woman
skip triad=64 age=5
skip triad=64 age=15
skip triad=64 age=25
skip triad=64 age=40
skip triad=64 age=60

NoGate | Triada 66/208 | gender=man
skip triad=65 age=5
skip triad=65 age=15
skip triad=65 age=25
skip triad=65 age=40
skip triad=65 age=60

NoGate | Triada 67/208 | gender=man
skip triad=66 age=5
skip triad=66 age=15
skip triad=66 age=25
skip triad=66 age=40
skip triad=66 age=60

NoGate | Triada 68/208 | gender=man
skip triad=67 age=5
skip triad=67 age=15
skip triad=67 age=25
skip triad=67 age=40
skip triad=67 age=60

NoGate | Triada 69/208 | gender=man
skip triad=68 age=5
skip triad=68 age=15
skip triad=68 age=25
skip triad=68 age=40
skip triad=68 age=60

NoGate | Triada 70/208 | gender=woman
skip triad=69 age=5
skip triad=69 age=15
skip triad=69 age=25
skip triad=69 age=40
skip triad=69 age=60

NoGate | Triada 71/208 | gender=woman
skip triad=70 age=5
skip triad=70 age=15
skip triad=70 age=25
skip triad=70 age=40
skip triad=70 age=60

NoGate | Triada 72/208 | gender=woman
skip triad=71 age=5
skip triad=71 age=15
skip triad=71 age=25
skip triad=71 age=40
skip triad=71 age=60

NoGate | Triada 73/208 | gender=woman
skip triad=72 age=5
skip triad=72 age=15
skip triad=72 age=25
skip triad=72 age=40
skip triad=72 age=60

NoGate | Triada 74/208 | gender=man
skip triad=73 age=5
skip triad=73 age=15
skip triad=73 age=25
skip triad=73 age=40
skip triad=73 age=60

NoGate | Triada 75/208 | gender=man
skip triad=74 age=5
skip triad=74 age=15
skip triad=74 age=25
skip triad=74 age=40
skip triad=74 age=60

NoGate | Triada 76/208 | gender=woman
skip triad=75 age=5
skip triad=75 age=15
skip triad=75 age=25
skip triad=75 age=40
skip triad=75 age=60

NoGate | Triada 77/208 | gender=man
skip triad=76 age=5
skip triad=76 age=15
skip triad=76 age=25
skip triad=76 age=40
skip triad=76 age=60

NoGate | Triada 78/208 | gender=man
skip triad=77 age=5
skip triad=77 age=15
skip triad=77 age=25
skip triad=77 age=40
skip triad=77 age=60

NoGate | Triada 79/208 | gender=woman
skip triad=78 age=5
skip triad=78 age=15
skip triad=78 age=25
skip triad=78 age=40
skip triad=78 age=60

NoGate | Triada 80/208 | gender=woman
skip triad=79 age=5
skip triad=79 age=15
skip triad=79 age=25
skip triad=79 age=40
skip triad=79 age=60

NoGate | Triada 81/208 | gender=man
skip triad=80 age=5
skip triad=80 age=15
skip triad=80 age=25
skip triad=80 age=40
skip triad=80 age=60

NoGate | Triada 82/208 | gender=woman
skip triad=81 age=5
skip triad=81 age=15
skip triad=81 age=25
skip triad=81 age=40
skip triad=81 age=60

NoGate | Triada 83/208 | gender=woman
skip triad=82 age=5
skip triad=82 age=15
skip triad=82 age=25
skip triad=82 age=40
skip triad=82 age=60

NoGate | Triada 84/208 | gender=man
skip triad=83 age=5
skip triad=83 age=15
skip triad=83 age=25
skip triad=83 age=40
skip triad=83 age=60

NoGate | Triada 85/208 | gender=man
skip triad=84 age=5
skip triad=84 age=15
skip triad=84 age=25
skip triad=84 age=40
skip triad=84 age=60

NoGate | Triada 86/208 | gender=man
skip triad=85 age=5
skip triad=85 age=15
skip triad=85 age=25
skip triad=85 age=40
skip triad=85 age=60

NoGate | Triada 87/208 | gender=woman
skip triad=86 age=5
skip triad=86 age=15
skip triad=86 age=25
skip triad=86 age=40
skip triad=86 age=60

NoGate | Triada 88/208 | gender=woman
skip triad=87 age=5
skip triad=87 age=15
skip triad=87 age=25
skip triad=87 age=40
skip triad=87 age=60

NoGate | Triada 89/208 | gender=woman
skip triad=88 age=5
skip triad=88 age=15
skip triad=88 age=25
skip triad=88 age=40
skip triad=88 age=60

NoGate | Triada 90/208 | gender=woman
skip triad=89 age=5
skip triad=89 age=15
skip triad=89 age=25
skip triad=89 age=40
skip triad=89 age=60

NoGate | Triada 91/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4076 | S_p=0.0797 | S_m=0.0045 | S_family=0.0421 | gap=0.0752 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4859 | S_p=0.0347 | S_m=0.0221 | S_family=0.0284 | gap=0.0126 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0478 | S_p=-0.0072 | S_m=-0.0371 | S_family=-0.0221 | gap=0.0299 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.4285 | S_p=0.0843 | S_m=0.0355 | S_family=0.0599 | gap=0.0488 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3657 | S_p=0.0496 | S_m=0.0996 | S_family=0.0746 | gap=0.0500 | alpha_mean=0.5000

NoGate | Triada 92/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3815 | S_p=0.0792 | S_m=-0.0360 | S_family=0.0216 | gap=0.1152 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0790 | S_p=0.0256 | S_m=-0.0490 | S_family=-0.0117 | gap=0.0746 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2227 | S_p=0.1331 | S_m=-0.0603 | S_family=0.0364 | gap=0.1934 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1513 | S_p=0.0966 | S_m=-0.0137 | S_family=0.0414 | gap=0.1103 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0351 | S_p=-0.0453 | S_m=-0.0439 | S_family=-0.0446 | gap=0.0014 | alpha_mean=0.5000

NoGate | Triada 93/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2954 | S_p=0.0503 | S_m=-0.0599 | S_family=-0.0048 | gap=0.1101 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1953 | S_p=0.0067 | S_m=0.0368 | S_family=0.0218 | gap=0.0300 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3916 | S_p=-0.0142 | S_m=-0.0726 | S_family=-0.0434 | gap=0.0585 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2393 | S_p=0.0463 | S_m=-0.1213 | S_family=-0.0375 | gap=0.1676 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3216 | S_p=0.0901 | S_m=0.0498 | S_family=0.0700 | gap=0.0403 | alpha_mean=0.5000

NoGate | Triada 94/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2633 | S_p=-0.0148 | S_m=-0.0064 | S_family=-0.0106 | gap=0.0084 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1266 | S_p=0.0349 | S_m=0.0475 | S_family=0.0412 | gap=0.0126 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1028 | S_p=0.0747 | S_m=-0.0232 | S_family=0.0258 | gap=0.0980 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1913 | S_p=0.1343 | S_m=0.0198 | S_family=0.0770 | gap=0.1144 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0613 | S_p=0.0667 | S_m=0.0534 | S_family=0.0600 | gap=0.0133 | alpha_mean=0.5000

NoGate | Triada 95/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2193 | S_p=0.1118 | S_m=0.0203 | S_family=0.0661 | gap=0.0915 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3219 | S_p=0.0934 | S_m=0.0071 | S_family=0.0502 | gap=0.0863 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0671 | S_p=-0.0258 | S_m=0.0145 | S_family=-0.0057 | gap=0.0403 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1000 | S_p=0.0111 | S_m=-0.0379 | S_family=-0.0134 | gap=0.0490 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3078 | S_p=0.0569 | S_m=-0.0510 | S_family=0.0029 | gap=0.1079 | alpha_mean=0.5000

NoGate | Triada 96/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1686 | S_p=0.0937 | S_m=0.1190 | S_family=0.1064 | gap=0.0253 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2062 | S_p=0.0429 | S_m=0.0105 | S_family=0.0267 | gap=0.0324 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1280 | S_p=0.0113 | S_m=0.0374 | S_family=0.0243 | gap=0.0261 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0844 | S_p=-0.0391 | S_m=0.0720 | S_family=0.0165 | gap=0.1111 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1449 | S_p=-0.0368 | S_m=0.0744 | S_family=0.0188 | gap=0.1112 | alpha_mean=0.5000

NoGate | Triada 97/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0384 | S_p=-0.0336 | S_m=-0.0554 | S_family=-0.0445 | gap=0.0218 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0781 | S_p=0.0072 | S_m=-0.1144 | S_family=-0.0536 | gap=0.1216 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2583 | S_p=0.0543 | S_m=0.0419 | S_family=0.0481 | gap=0.0124 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2609 | S_p=0.0864 | S_m=0.0606 | S_family=0.0735 | gap=0.0257 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1852 | S_p=0.0810 | S_m=0.1011 | S_family=0.0910 | gap=0.0200 | alpha_mean=0.5000

NoGate | Triada 98/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0372 | S_p=0.0131 | S_m=0.0220 | S_family=0.0176 | gap=0.0088 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1199 | S_p=0.0966 | S_m=0.0155 | S_family=0.0561 | gap=0.0811 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0372 | S_p=0.0072 | S_m=-0.0327 | S_family=-0.0127 | gap=0.0399 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0321 | S_p=0.0077 | S_m=0.0002 | S_family=0.0039 | gap=0.0075 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0337 | S_p=-0.0087 | S_m=0.0352 | S_family=0.0132 | gap=0.0439 | alpha_mean=0.5000

NoGate | Triada 99/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1660 | S_p=-0.0427 | S_m=0.1182 | S_family=0.0378 | gap=0.1608 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1067 | S_p=-0.0514 | S_m=0.0306 | S_family=-0.0104 | gap=0.0820 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1164 | S_p=-0.0171 | S_m=-0.0113 | S_family=-0.0142 | gap=0.0059 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2290 | S_p=-0.0118 | S_m=0.0615 | S_family=0.0248 | gap=0.0733 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=-0.0342 | S_p=0.0181 | S_m=-0.0434 | S_family=-0.0126 | gap=0.0615 | alpha_mean=0.5000

NoGate | Triada 100/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2644 | S_p=-0.0218 | S_m=-0.0447 | S_family=-0.0333 | gap=0.0230 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1592 | S_p=-0.0017 | S_m=-0.0941 | S_family=-0.0479 | gap=0.0924 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2186 | S_p=-0.0426 | S_m=-0.0059 | S_family=-0.0243 | gap=0.0367 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1794 | S_p=-0.0347 | S_m=0.0540 | S_family=0.0097 | gap=0.0887 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1662 | S_p=-0.0284 | S_m=0.1005 | S_family=0.0361 | gap=0.1289 | alpha_mean=0.5000

NoGate | Triada 101/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2001 | S_p=0.0029 | S_m=-0.0583 | S_family=-0.0277 | gap=0.0613 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0397 | S_p=-0.0046 | S_m=-0.0292 | S_family=-0.0169 | gap=0.0246 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1590 | S_p=-0.0506 | S_m=0.0144 | S_family=-0.0181 | gap=0.0650 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1758 | S_p=-0.0263 | S_m=0.0004 | S_family=-0.0130 | gap=0.0267 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2346 | S_p=-0.0097 | S_m=0.0672 | S_family=0.0288 | gap=0.0769 | alpha_mean=0.5000

NoGate | Triada 102/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1623 | S_p=-0.0167 | S_m=0.1726 | S_family=0.0780 | gap=0.1892 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2638 | S_p=0.1848 | S_m=0.1357 | S_family=0.1603 | gap=0.0491 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1563 | S_p=-0.0065 | S_m=0.0244 | S_family=0.0090 | gap=0.0309 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1546 | S_p=0.1092 | S_m=0.1786 | S_family=0.1439 | gap=0.0694 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1971 | S_p=0.0111 | S_m=0.1176 | S_family=0.0644 | gap=0.1065 | alpha_mean=0.5000

NoGate | Triada 103/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2625 | S_p=0.0801 | S_m=0.0794 | S_family=0.0798 | gap=0.0006 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2770 | S_p=0.0944 | S_m=0.0899 | S_family=0.0922 | gap=0.0045 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0104 | S_p=0.0188 | S_m=0.0353 | S_family=0.0270 | gap=0.0165 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1290 | S_p=0.1131 | S_m=0.1361 | S_family=0.1246 | gap=0.0230 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2539 | S_p=0.1213 | S_m=0.1053 | S_family=0.1133 | gap=0.0160 | alpha_mean=0.5000

NoGate | Triada 104/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3163 | S_p=-0.0668 | S_m=0.0749 | S_family=0.0040 | gap=0.1417 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1301 | S_p=0.0521 | S_m=-0.0648 | S_family=-0.0064 | gap=0.1169 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1998 | S_p=-0.0325 | S_m=0.1096 | S_family=0.0386 | gap=0.1421 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2084 | S_p=0.0571 | S_m=-0.0060 | S_family=0.0256 | gap=0.0631 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1833 | S_p=-0.0088 | S_m=-0.0085 | S_family=-0.0086 | gap=0.0003 | alpha_mean=0.5000

NoGate | Triada 105/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3542 | S_p=0.0693 | S_m=0.0803 | S_family=0.0748 | gap=0.0110 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2361 | S_p=-0.0009 | S_m=0.0858 | S_family=0.0424 | gap=0.0867 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3488 | S_p=0.1192 | S_m=0.0871 | S_family=0.1032 | gap=0.0320 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3010 | S_p=0.0287 | S_m=0.1081 | S_family=0.0684 | gap=0.0794 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2558 | S_p=0.0301 | S_m=0.1064 | S_family=0.0683 | gap=0.0763 | alpha_mean=0.5000

NoGate | Triada 106/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2465 | S_p=0.0408 | S_m=-0.1546 | S_family=-0.0569 | gap=0.1955 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0793 | S_p=0.0301 | S_m=-0.0678 | S_family=-0.0189 | gap=0.0978 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3835 | S_p=0.1606 | S_m=-0.0052 | S_family=0.0777 | gap=0.1659 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2003 | S_p=0.1499 | S_m=0.0027 | S_family=0.0763 | gap=0.1472 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1057 | S_p=0.1258 | S_m=-0.0231 | S_family=0.0514 | gap=0.1488 | alpha_mean=0.5000

NoGate | Triada 107/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4343 | S_p=0.0257 | S_m=0.0126 | S_family=0.0192 | gap=0.0131 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0574 | S_p=-0.0131 | S_m=0.0339 | S_family=0.0104 | gap=0.0471 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1871 | S_p=-0.0192 | S_m=0.0041 | S_family=-0.0075 | gap=0.0232 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3533 | S_p=-0.0552 | S_m=0.0515 | S_family=-0.0018 | gap=0.1067 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3649 | S_p=0.0186 | S_m=0.1119 | S_family=0.0652 | gap=0.0933 | alpha_mean=0.5000

NoGate | Triada 108/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3742 | S_p=-0.0034 | S_m=-0.0693 | S_family=-0.0363 | gap=0.0659 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2836 | S_p=0.1065 | S_m=-0.0191 | S_family=0.0437 | gap=0.1256 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0412 | S_p=-0.0395 | S_m=-0.0197 | S_family=-0.0296 | gap=0.0198 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1374 | S_p=0.0377 | S_m=0.0060 | S_family=0.0218 | gap=0.0317 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2283 | S_p=0.1408 | S_m=0.0173 | S_family=0.0791 | gap=0.1234 | alpha_mean=0.5000

NoGate | Triada 109/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3978 | S_p=-0.0369 | S_m=-0.0399 | S_family=-0.0384 | gap=0.0030 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1077 | S_p=0.0050 | S_m=-0.0285 | S_family=-0.0118 | gap=0.0335 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3097 | S_p=0.0955 | S_m=-0.0243 | S_family=0.0356 | gap=0.1198 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1225 | S_p=0.0424 | S_m=0.0136 | S_family=0.0280 | gap=0.0288 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0656 | S_p=0.0178 | S_m=0.0091 | S_family=0.0135 | gap=0.0087 | alpha_mean=0.5000

NoGate | Triada 110/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4320 | S_p=-0.0115 | S_m=0.1035 | S_family=0.0460 | gap=0.1150 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1392 | S_p=0.0270 | S_m=0.0127 | S_family=0.0198 | gap=0.0144 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2631 | S_p=-0.0411 | S_m=0.0647 | S_family=0.0118 | gap=0.1057 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0881 | S_p=-0.0908 | S_m=0.0073 | S_family=-0.0417 | gap=0.0981 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1391 | S_p=-0.0237 | S_m=0.0524 | S_family=0.0144 | gap=0.0760 | alpha_mean=0.5000

NoGate | Triada 111/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2898 | S_p=-0.0834 | S_m=-0.0451 | S_family=-0.0643 | gap=0.0383 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2459 | S_p=-0.0194 | S_m=-0.0577 | S_family=-0.0385 | gap=0.0383 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2525 | S_p=0.0453 | S_m=-0.0103 | S_family=0.0175 | gap=0.0556 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0658 | S_p=0.0270 | S_m=-0.0534 | S_family=-0.0132 | gap=0.0804 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2120 | S_p=0.0233 | S_m=0.0497 | S_family=0.0365 | gap=0.0264 | alpha_mean=0.5000

NoGate | Triada 112/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1746 | S_p=0.0350 | S_m=-0.0855 | S_family=-0.0253 | gap=0.1205 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4497 | S_p=-0.0272 | S_m=0.0046 | S_family=-0.0113 | gap=0.0318 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2695 | S_p=-0.0065 | S_m=0.0525 | S_family=0.0230 | gap=0.0590 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1040 | S_p=0.0133 | S_m=0.0691 | S_family=0.0412 | gap=0.0558 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2747 | S_p=-0.0093 | S_m=0.0940 | S_family=0.0423 | gap=0.1033 | alpha_mean=0.5000

NoGate | Triada 113/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4339 | S_p=0.1378 | S_m=0.0503 | S_family=0.0940 | gap=0.0875 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0897 | S_p=0.0294 | S_m=0.0034 | S_family=0.0164 | gap=0.0260 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0836 | S_p=0.0173 | S_m=0.0601 | S_family=0.0387 | gap=0.0428 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1649 | S_p=0.0269 | S_m=0.1156 | S_family=0.0713 | gap=0.0887 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1971 | S_p=0.1041 | S_m=0.0125 | S_family=0.0583 | gap=0.0916 | alpha_mean=0.5000

NoGate | Triada 114/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0939 | S_p=0.0126 | S_m=0.0642 | S_family=0.0384 | gap=0.0516 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1291 | S_p=0.0018 | S_m=0.0338 | S_family=0.0178 | gap=0.0320 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1071 | S_p=-0.0009 | S_m=0.0419 | S_family=0.0205 | gap=0.0428 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2577 | S_p=0.0673 | S_m=0.0242 | S_family=0.0458 | gap=0.0431 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0428 | S_p=0.1080 | S_m=-0.0271 | S_family=0.0404 | gap=0.1351 | alpha_mean=0.5000

NoGate | Triada 115/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0325 | S_p=0.0116 | S_m=-0.0182 | S_family=-0.0033 | gap=0.0298 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0691 | S_p=-0.0361 | S_m=-0.0369 | S_family=-0.0365 | gap=0.0008 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0519 | S_p=-0.0059 | S_m=-0.0008 | S_family=-0.0034 | gap=0.0051 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0564 | S_p=-0.0356 | S_m=-0.0865 | S_family=-0.0611 | gap=0.0509 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=-0.0585 | S_p=0.0163 | S_m=-0.0600 | S_family=-0.0218 | gap=0.0763 | alpha_mean=0.5000

NoGate | Triada 116/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3211 | S_p=0.1250 | S_m=-0.0590 | S_family=0.0330 | gap=0.1840 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0364 | S_p=-0.0353 | S_m=-0.0351 | S_family=-0.0352 | gap=0.0002 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0611 | S_p=0.0090 | S_m=0.0400 | S_family=0.0245 | gap=0.0311 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1903 | S_p=-0.0384 | S_m=0.0490 | S_family=0.0053 | gap=0.0874 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0627 | S_p=0.0434 | S_m=0.0837 | S_family=0.0636 | gap=0.0403 | alpha_mean=0.5000

NoGate | Triada 117/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2798 | S_p=0.0224 | S_m=0.1575 | S_family=0.0899 | gap=0.1351 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0300 | S_p=-0.0164 | S_m=0.0299 | S_family=0.0068 | gap=0.0463 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4188 | S_p=0.0963 | S_m=0.0636 | S_family=0.0800 | gap=0.0327 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2401 | S_p=0.0583 | S_m=0.0458 | S_family=0.0520 | gap=0.0125 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0326 | S_p=-0.0355 | S_m=0.1127 | S_family=0.0386 | gap=0.1483 | alpha_mean=0.5000

NoGate | Triada 118/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3577 | S_p=0.0788 | S_m=0.0031 | S_family=0.0410 | gap=0.0757 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0214 | S_p=0.0446 | S_m=-0.0131 | S_family=0.0158 | gap=0.0577 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2654 | S_p=0.0523 | S_m=-0.0758 | S_family=-0.0118 | gap=0.1281 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.4051 | S_p=0.0007 | S_m=-0.0699 | S_family=-0.0346 | gap=0.0706 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1872 | S_p=0.0876 | S_m=-0.0108 | S_family=0.0384 | gap=0.0985 | alpha_mean=0.5000

NoGate | Triada 119/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2207 | S_p=0.0047 | S_m=-0.0046 | S_family=0.0001 | gap=0.0093 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1720 | S_p=0.0592 | S_m=0.0268 | S_family=0.0430 | gap=0.0324 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2049 | S_p=0.0243 | S_m=0.0073 | S_family=0.0158 | gap=0.0169 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2398 | S_p=0.0407 | S_m=-0.0158 | S_family=0.0124 | gap=0.0565 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1550 | S_p=0.0109 | S_m=0.0247 | S_family=0.0178 | gap=0.0138 | alpha_mean=0.5000

NoGate | Triada 120/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2717 | S_p=0.0751 | S_m=0.0619 | S_family=0.0685 | gap=0.0132 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0351 | S_p=0.0392 | S_m=0.0225 | S_family=0.0308 | gap=0.0167 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3706 | S_p=0.0818 | S_m=0.0330 | S_family=0.0574 | gap=0.0488 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.4353 | S_p=0.0018 | S_m=0.0897 | S_family=0.0457 | gap=0.0879 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1667 | S_p=0.0662 | S_m=-0.0362 | S_family=0.0150 | gap=0.1024 | alpha_mean=0.5000

NoGate | Triada 121/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0615 | S_p=0.0044 | S_m=-0.0005 | S_family=0.0019 | gap=0.0050 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2001 | S_p=0.0552 | S_m=0.0997 | S_family=0.0774 | gap=0.0445 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3658 | S_p=-0.0129 | S_m=0.0131 | S_family=0.0001 | gap=0.0260 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3862 | S_p=-0.0373 | S_m=0.2077 | S_family=0.0852 | gap=0.2450 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2275 | S_p=0.0613 | S_m=0.0917 | S_family=0.0765 | gap=0.0304 | alpha_mean=0.5000

NoGate | Triada 122/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2894 | S_p=0.0840 | S_m=0.0706 | S_family=0.0773 | gap=0.0134 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2614 | S_p=0.0470 | S_m=0.1100 | S_family=0.0785 | gap=0.0630 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0381 | S_p=-0.0336 | S_m=0.0211 | S_family=-0.0062 | gap=0.0547 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3026 | S_p=0.0176 | S_m=0.0353 | S_family=0.0265 | gap=0.0177 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2084 | S_p=0.0181 | S_m=0.1076 | S_family=0.0628 | gap=0.0895 | alpha_mean=0.5000

NoGate | Triada 123/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1370 | S_p=0.0022 | S_m=0.1180 | S_family=0.0601 | gap=0.1158 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1972 | S_p=0.0853 | S_m=0.0038 | S_family=0.0445 | gap=0.0814 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1455 | S_p=0.0722 | S_m=0.1354 | S_family=0.1038 | gap=0.0632 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0110 | S_p=0.0180 | S_m=-0.0640 | S_family=-0.0230 | gap=0.0820 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1032 | S_p=-0.0301 | S_m=0.0351 | S_family=0.0025 | gap=0.0652 | alpha_mean=0.5000

NoGate | Triada 124/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3804 | S_p=-0.0168 | S_m=0.0824 | S_family=0.0328 | gap=0.0992 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3735 | S_p=0.0495 | S_m=0.0437 | S_family=0.0466 | gap=0.0058 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3516 | S_p=0.0309 | S_m=0.0148 | S_family=0.0228 | gap=0.0161 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2384 | S_p=-0.0139 | S_m=0.1402 | S_family=0.0631 | gap=0.1541 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1452 | S_p=0.1418 | S_m=0.0083 | S_family=0.0750 | gap=0.1335 | alpha_mean=0.5000

NoGate | Triada 125/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3650 | S_p=-0.0512 | S_m=-0.0878 | S_family=-0.0695 | gap=0.0366 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0120 | S_p=-0.0354 | S_m=0.0305 | S_family=-0.0025 | gap=0.0659 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1266 | S_p=0.0199 | S_m=-0.0058 | S_family=0.0071 | gap=0.0257 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3245 | S_p=-0.0491 | S_m=-0.0091 | S_family=-0.0291 | gap=0.0400 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1314 | S_p=-0.0298 | S_m=-0.0171 | S_family=-0.0235 | gap=0.0127 | alpha_mean=0.5000

NoGate | Triada 126/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1946 | S_p=0.0226 | S_m=0.1418 | S_family=0.0822 | gap=0.1192 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2399 | S_p=0.0532 | S_m=0.1375 | S_family=0.0954 | gap=0.0843 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1928 | S_p=0.0651 | S_m=0.0920 | S_family=0.0786 | gap=0.0269 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0808 | S_p=0.0808 | S_m=0.1262 | S_family=0.1035 | gap=0.0454 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2024 | S_p=0.0713 | S_m=0.0328 | S_family=0.0521 | gap=0.0385 | alpha_mean=0.5000

NoGate | Triada 127/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3538 | S_p=0.0106 | S_m=0.1507 | S_family=0.0807 | gap=0.1401 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4570 | S_p=-0.0192 | S_m=0.1100 | S_family=0.0454 | gap=0.1292 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3778 | S_p=-0.0511 | S_m=0.0880 | S_family=0.0184 | gap=0.1391 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1015 | S_p=-0.0138 | S_m=0.0704 | S_family=0.0283 | gap=0.0842 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3063 | S_p=-0.0185 | S_m=0.0763 | S_family=0.0289 | gap=0.0948 | alpha_mean=0.5000

NoGate | Triada 128/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3953 | S_p=-0.0127 | S_m=0.0940 | S_family=0.0407 | gap=0.1067 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1053 | S_p=-0.0190 | S_m=0.1045 | S_family=0.0428 | gap=0.1235 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2215 | S_p=0.0213 | S_m=-0.0310 | S_family=-0.0048 | gap=0.0523 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1919 | S_p=0.1711 | S_m=-0.0064 | S_family=0.0824 | gap=0.1775 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2480 | S_p=0.1852 | S_m=-0.0288 | S_family=0.0782 | gap=0.2140 | alpha_mean=0.5000

NoGate | Triada 129/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4537 | S_p=-0.0328 | S_m=0.0930 | S_family=0.0301 | gap=0.1258 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1348 | S_p=-0.0116 | S_m=0.0680 | S_family=0.0282 | gap=0.0797 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3289 | S_p=-0.0134 | S_m=0.1500 | S_family=0.0683 | gap=0.1634 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0726 | S_p=-0.0023 | S_m=-0.0198 | S_family=-0.0111 | gap=0.0175 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2351 | S_p=-0.0108 | S_m=0.1921 | S_family=0.0907 | gap=0.2029 | alpha_mean=0.5000

NoGate | Triada 130/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1838 | S_p=0.0345 | S_m=-0.0372 | S_family=-0.0014 | gap=0.0717 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2186 | S_p=-0.0293 | S_m=-0.0018 | S_family=-0.0156 | gap=0.0275 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3789 | S_p=0.0313 | S_m=-0.0455 | S_family=-0.0071 | gap=0.0768 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2358 | S_p=0.0474 | S_m=0.0519 | S_family=0.0497 | gap=0.0045 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3436 | S_p=0.0518 | S_m=0.0233 | S_family=0.0375 | gap=0.0284 | alpha_mean=0.5000

NoGate | Triada 131/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3683 | S_p=0.0029 | S_m=-0.0159 | S_family=-0.0065 | gap=0.0188 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3556 | S_p=0.0431 | S_m=0.0619 | S_family=0.0525 | gap=0.0189 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1661 | S_p=-0.0258 | S_m=-0.0238 | S_family=-0.0248 | gap=0.0020 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2768 | S_p=0.0917 | S_m=0.0452 | S_family=0.0684 | gap=0.0465 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2691 | S_p=0.1040 | S_m=0.0135 | S_family=0.0588 | gap=0.0905 | alpha_mean=0.5000

NoGate | Triada 132/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1007 | S_p=0.0070 | S_m=0.0435 | S_family=0.0252 | gap=0.0365 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1062 | S_p=-0.0340 | S_m=-0.0224 | S_family=-0.0282 | gap=0.0117 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1112 | S_p=0.0072 | S_m=0.0936 | S_family=0.0504 | gap=0.0864 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0382 | S_p=-0.0453 | S_m=0.1259 | S_family=0.0403 | gap=0.1711 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1881 | S_p=0.0099 | S_m=0.0625 | S_family=0.0362 | gap=0.0526 | alpha_mean=0.5000

NoGate | Triada 133/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1418 | S_p=-0.0813 | S_m=0.0218 | S_family=-0.0297 | gap=0.1031 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0993 | S_p=-0.0419 | S_m=0.0092 | S_family=-0.0163 | gap=0.0511 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1853 | S_p=-0.0065 | S_m=-0.0245 | S_family=-0.0155 | gap=0.0181 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2064 | S_p=-0.0318 | S_m=0.0994 | S_family=0.0338 | gap=0.1312 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0567 | S_p=-0.0423 | S_m=0.1134 | S_family=0.0356 | gap=0.1557 | alpha_mean=0.5000

NoGate | Triada 134/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2851 | S_p=-0.1022 | S_m=0.0615 | S_family=-0.0204 | gap=0.1637 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2456 | S_p=-0.0681 | S_m=0.1182 | S_family=0.0250 | gap=0.1863 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1729 | S_p=-0.0542 | S_m=0.0072 | S_family=-0.0235 | gap=0.0614 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0642 | S_p=-0.0948 | S_m=0.1076 | S_family=0.0064 | gap=0.2024 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2269 | S_p=-0.1005 | S_m=0.1963 | S_family=0.0479 | gap=0.2967 | alpha_mean=0.5000

NoGate | Triada 135/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3312 | S_p=-0.0231 | S_m=-0.0495 | S_family=-0.0363 | gap=0.0264 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2848 | S_p=-0.0019 | S_m=-0.0439 | S_family=-0.0229 | gap=0.0420 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2584 | S_p=-0.0239 | S_m=-0.0375 | S_family=-0.0307 | gap=0.0136 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3640 | S_p=-0.0168 | S_m=-0.0920 | S_family=-0.0544 | gap=0.0752 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1913 | S_p=0.0132 | S_m=0.0272 | S_family=0.0202 | gap=0.0140 | alpha_mean=0.5000

NoGate | Triada 136/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3299 | S_p=0.0150 | S_m=0.0772 | S_family=0.0461 | gap=0.0621 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3586 | S_p=0.0488 | S_m=0.0607 | S_family=0.0548 | gap=0.0119 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4030 | S_p=0.0339 | S_m=0.1258 | S_family=0.0799 | gap=0.0919 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1827 | S_p=0.0035 | S_m=0.0037 | S_family=0.0036 | gap=0.0002 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2082 | S_p=0.0011 | S_m=0.0587 | S_family=0.0299 | gap=0.0577 | alpha_mean=0.5000

NoGate | Triada 137/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0859 | S_p=-0.0317 | S_m=0.0337 | S_family=0.0010 | gap=0.0653 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4608 | S_p=0.0483 | S_m=0.0129 | S_family=0.0306 | gap=0.0354 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0824 | S_p=0.0315 | S_m=0.0672 | S_family=0.0493 | gap=0.0356 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0786 | S_p=0.0330 | S_m=0.0256 | S_family=0.0293 | gap=0.0074 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0361 | S_p=-0.0010 | S_m=0.0019 | S_family=0.0005 | gap=0.0029 | alpha_mean=0.5000

NoGate | Triada 138/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3666 | S_p=0.0221 | S_m=0.0264 | S_family=0.0242 | gap=0.0043 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2607 | S_p=0.0035 | S_m=0.0229 | S_family=0.0132 | gap=0.0194 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0116 | S_p=-0.0176 | S_m=0.0219 | S_family=0.0021 | gap=0.0395 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3348 | S_p=-0.0070 | S_m=0.1436 | S_family=0.0683 | gap=0.1506 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3673 | S_p=0.0893 | S_m=0.1703 | S_family=0.1298 | gap=0.0810 | alpha_mean=0.5000

NoGate | Triada 139/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1607 | S_p=0.0875 | S_m=0.0298 | S_family=0.0586 | gap=0.0577 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2570 | S_p=0.0026 | S_m=-0.0217 | S_family=-0.0095 | gap=0.0244 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0314 | S_p=0.0573 | S_m=0.0677 | S_family=0.0625 | gap=0.0104 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.4837 | S_p=-0.0299 | S_m=-0.0457 | S_family=-0.0378 | gap=0.0157 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3918 | S_p=0.0143 | S_m=-0.0163 | S_family=-0.0010 | gap=0.0306 | alpha_mean=0.5000

NoGate | Triada 140/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1752 | S_p=0.0637 | S_m=0.0645 | S_family=0.0641 | gap=0.0009 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1161 | S_p=-0.0106 | S_m=0.0531 | S_family=0.0213 | gap=0.0637 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4512 | S_p=0.0401 | S_m=-0.0359 | S_family=0.0021 | gap=0.0761 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1315 | S_p=0.0873 | S_m=0.0204 | S_family=0.0538 | gap=0.0669 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1709 | S_p=0.1467 | S_m=0.0304 | S_family=0.0885 | gap=0.1163 | alpha_mean=0.5000

NoGate | Triada 141/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2141 | S_p=-0.0102 | S_m=-0.0172 | S_family=-0.0137 | gap=0.0069 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2497 | S_p=0.0089 | S_m=0.0550 | S_family=0.0319 | gap=0.0462 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0846 | S_p=-0.0383 | S_m=0.0226 | S_family=-0.0079 | gap=0.0609 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2216 | S_p=0.0759 | S_m=0.0507 | S_family=0.0633 | gap=0.0251 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0363 | S_p=-0.0835 | S_m=0.0245 | S_family=-0.0295 | gap=0.1080 | alpha_mean=0.5000

NoGate | Triada 142/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0924 | S_p=0.0688 | S_m=-0.0456 | S_family=0.0116 | gap=0.1144 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0879 | S_p=-0.0136 | S_m=0.0204 | S_family=0.0034 | gap=0.0339 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2921 | S_p=0.1166 | S_m=0.0566 | S_family=0.0866 | gap=0.0600 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1443 | S_p=0.0107 | S_m=-0.0054 | S_family=0.0026 | gap=0.0161 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2307 | S_p=-0.0252 | S_m=0.0247 | S_family=-0.0002 | gap=0.0499 | alpha_mean=0.5000

NoGate | Triada 143/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1421 | S_p=0.0012 | S_m=-0.0105 | S_family=-0.0046 | gap=0.0117 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1487 | S_p=-0.0710 | S_m=-0.0312 | S_family=-0.0511 | gap=0.0399 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1958 | S_p=-0.0334 | S_m=-0.0202 | S_family=-0.0268 | gap=0.0132 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0551 | S_p=0.0034 | S_m=0.0375 | S_family=0.0205 | gap=0.0341 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3498 | S_p=-0.0057 | S_m=-0.0607 | S_family=-0.0332 | gap=0.0550 | alpha_mean=0.5000

NoGate | Triada 144/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0093 | S_p=0.0119 | S_m=-0.0429 | S_family=-0.0155 | gap=0.0549 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0632 | S_p=-0.0379 | S_m=-0.0204 | S_family=-0.0291 | gap=0.0176 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0457 | S_p=-0.0397 | S_m=-0.0514 | S_family=-0.0456 | gap=0.0117 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0158 | S_p=-0.0493 | S_m=-0.0356 | S_family=-0.0424 | gap=0.0137 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1633 | S_p=-0.0179 | S_m=0.0725 | S_family=0.0273 | gap=0.0904 | alpha_mean=0.5000

NoGate | Triada 145/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1607 | S_p=-0.0375 | S_m=-0.0152 | S_family=-0.0264 | gap=0.0223 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1567 | S_p=-0.0092 | S_m=-0.0178 | S_family=-0.0135 | gap=0.0086 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3408 | S_p=-0.0310 | S_m=-0.0538 | S_family=-0.0424 | gap=0.0228 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3592 | S_p=0.0373 | S_m=-0.0969 | S_family=-0.0298 | gap=0.1341 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0113 | S_p=-0.0303 | S_m=-0.0223 | S_family=-0.0263 | gap=0.0080 | alpha_mean=0.5000

NoGate | Triada 146/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1263 | S_p=0.0568 | S_m=0.0471 | S_family=0.0520 | gap=0.0097 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1502 | S_p=0.0041 | S_m=0.1139 | S_family=0.0590 | gap=0.1097 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1943 | S_p=0.0515 | S_m=0.0606 | S_family=0.0561 | gap=0.0092 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1420 | S_p=0.0243 | S_m=0.1278 | S_family=0.0761 | gap=0.1035 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3412 | S_p=-0.0342 | S_m=0.1242 | S_family=0.0450 | gap=0.1584 | alpha_mean=0.5000

NoGate | Triada 147/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1914 | S_p=0.0933 | S_m=0.1008 | S_family=0.0971 | gap=0.0075 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0695 | S_p=0.0300 | S_m=0.0603 | S_family=0.0452 | gap=0.0303 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1393 | S_p=0.0458 | S_m=-0.0406 | S_family=0.0026 | gap=0.0864 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0311 | S_p=-0.0332 | S_m=0.0265 | S_family=-0.0033 | gap=0.0598 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1177 | S_p=-0.0515 | S_m=0.0055 | S_family=-0.0230 | gap=0.0570 | alpha_mean=0.5000

NoGate | Triada 148/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3284 | S_p=0.0023 | S_m=0.0980 | S_family=0.0502 | gap=0.0957 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2098 | S_p=0.0516 | S_m=-0.0053 | S_family=0.0231 | gap=0.0570 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3184 | S_p=-0.0378 | S_m=0.1036 | S_family=0.0329 | gap=0.1414 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3149 | S_p=-0.0389 | S_m=0.1118 | S_family=0.0364 | gap=0.1507 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2554 | S_p=-0.0691 | S_m=0.0629 | S_family=-0.0031 | gap=0.1319 | alpha_mean=0.5000

NoGate | Triada 149/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1145 | S_p=0.1308 | S_m=0.0400 | S_family=0.0854 | gap=0.0908 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2071 | S_p=0.1383 | S_m=0.1213 | S_family=0.1298 | gap=0.0169 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2725 | S_p=0.1044 | S_m=0.1097 | S_family=0.1070 | gap=0.0053 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0524 | S_p=0.0948 | S_m=-0.0161 | S_family=0.0394 | gap=0.1109 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1863 | S_p=-0.0050 | S_m=0.0961 | S_family=0.0456 | gap=0.1011 | alpha_mean=0.5000

NoGate | Triada 150/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3152 | S_p=0.0577 | S_m=0.0765 | S_family=0.0671 | gap=0.0189 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0283 | S_p=-0.0339 | S_m=0.0411 | S_family=0.0036 | gap=0.0750 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2792 | S_p=0.0779 | S_m=0.0584 | S_family=0.0682 | gap=0.0195 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2549 | S_p=0.0301 | S_m=0.0411 | S_family=0.0356 | gap=0.0110 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3270 | S_p=-0.0039 | S_m=-0.0053 | S_family=-0.0046 | gap=0.0015 | alpha_mean=0.5000

NoGate | Triada 151/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4424 | S_p=0.0471 | S_m=0.0319 | S_family=0.0395 | gap=0.0152 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1013 | S_p=-0.0304 | S_m=-0.0122 | S_family=-0.0213 | gap=0.0182 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2175 | S_p=0.0466 | S_m=0.0603 | S_family=0.0535 | gap=0.0138 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0499 | S_p=0.0244 | S_m=0.0269 | S_family=0.0257 | gap=0.0025 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0139 | S_p=0.0802 | S_m=-0.0376 | S_family=0.0213 | gap=0.1178 | alpha_mean=0.5000

NoGate | Triada 152/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1506 | S_p=0.0819 | S_m=-0.0089 | S_family=0.0365 | gap=0.0908 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0678 | S_p=0.0532 | S_m=0.1292 | S_family=0.0912 | gap=0.0760 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0656 | S_p=0.0147 | S_m=0.0537 | S_family=0.0342 | gap=0.0390 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0801 | S_p=0.0289 | S_m=0.0651 | S_family=0.0470 | gap=0.0363 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2216 | S_p=-0.0102 | S_m=0.0544 | S_family=0.0221 | gap=0.0646 | alpha_mean=0.5000

NoGate | Triada 153/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1925 | S_p=0.0280 | S_m=0.0199 | S_family=0.0240 | gap=0.0081 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0508 | S_p=0.0262 | S_m=-0.0155 | S_family=0.0053 | gap=0.0417 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3814 | S_p=0.0898 | S_m=0.0483 | S_family=0.0691 | gap=0.0415 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0512 | S_p=0.0136 | S_m=-0.0037 | S_family=0.0049 | gap=0.0174 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0476 | S_p=0.0129 | S_m=0.0474 | S_family=0.0301 | gap=0.0344 | alpha_mean=0.5000

NoGate | Triada 154/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1387 | S_p=0.0396 | S_m=0.1109 | S_family=0.0752 | gap=0.0712 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0189 | S_p=0.0594 | S_m=0.0679 | S_family=0.0636 | gap=0.0085 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1066 | S_p=0.0903 | S_m=0.0529 | S_family=0.0716 | gap=0.0374 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0996 | S_p=0.0409 | S_m=0.0774 | S_family=0.0591 | gap=0.0365 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0624 | S_p=0.0454 | S_m=0.0030 | S_family=0.0242 | gap=0.0424 | alpha_mean=0.5000

NoGate | Triada 155/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1374 | S_p=-0.0217 | S_m=0.0254 | S_family=0.0018 | gap=0.0471 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4361 | S_p=0.0032 | S_m=-0.0115 | S_family=-0.0041 | gap=0.0147 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3570 | S_p=-0.0804 | S_m=-0.1162 | S_family=-0.0983 | gap=0.0357 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2432 | S_p=-0.0483 | S_m=-0.0410 | S_family=-0.0447 | gap=0.0073 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2724 | S_p=0.0775 | S_m=-0.0216 | S_family=0.0280 | gap=0.0991 | alpha_mean=0.5000

NoGate | Triada 156/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0626 | S_p=-0.0028 | S_m=-0.0289 | S_family=-0.0158 | gap=0.0260 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3797 | S_p=-0.0269 | S_m=-0.0138 | S_family=-0.0204 | gap=0.0131 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0068 | S_p=0.0024 | S_m=-0.0239 | S_family=-0.0108 | gap=0.0264 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1568 | S_p=0.0007 | S_m=0.1045 | S_family=0.0526 | gap=0.1039 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1875 | S_p=0.0379 | S_m=0.1080 | S_family=0.0729 | gap=0.0701 | alpha_mean=0.5000

NoGate | Triada 157/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1610 | S_p=-0.0114 | S_m=-0.0539 | S_family=-0.0326 | gap=0.0425 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0772 | S_p=0.0167 | S_m=0.0287 | S_family=0.0227 | gap=0.0119 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0293 | S_p=0.0265 | S_m=-0.0302 | S_family=-0.0019 | gap=0.0567 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2145 | S_p=-0.0680 | S_m=-0.0345 | S_family=-0.0513 | gap=0.0335 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=-0.0137 | S_p=0.0840 | S_m=-0.0198 | S_family=0.0321 | gap=0.1038 | alpha_mean=0.5000

NoGate | Triada 158/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3854 | S_p=-0.0610 | S_m=-0.0526 | S_family=-0.0568 | gap=0.0085 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2466 | S_p=0.0342 | S_m=-0.0189 | S_family=0.0077 | gap=0.0531 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0741 | S_p=0.0379 | S_m=-0.0601 | S_family=-0.0111 | gap=0.0981 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1911 | S_p=0.0050 | S_m=-0.0194 | S_family=-0.0072 | gap=0.0244 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1592 | S_p=0.0139 | S_m=0.0791 | S_family=0.0465 | gap=0.0652 | alpha_mean=0.5000

NoGate | Triada 159/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0887 | S_p=0.0388 | S_m=0.0328 | S_family=0.0358 | gap=0.0061 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0376 | S_p=-0.0742 | S_m=-0.0644 | S_family=-0.0693 | gap=0.0099 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2181 | S_p=0.0084 | S_m=0.0040 | S_family=0.0062 | gap=0.0043 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1793 | S_p=-0.0301 | S_m=0.0621 | S_family=0.0160 | gap=0.0922 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0345 | S_p=0.0266 | S_m=-0.0499 | S_family=-0.0117 | gap=0.0765 | alpha_mean=0.5000

NoGate | Triada 160/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0029 | S_p=0.0553 | S_m=-0.0685 | S_family=-0.0066 | gap=0.1238 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0274 | S_p=-0.0033 | S_m=-0.0084 | S_family=-0.0058 | gap=0.0051 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0528 | S_p=-0.0651 | S_m=-0.0399 | S_family=-0.0525 | gap=0.0251 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1612 | S_p=-0.0020 | S_m=0.0002 | S_family=-0.0009 | gap=0.0022 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3176 | S_p=0.0304 | S_m=-0.0060 | S_family=0.0122 | gap=0.0364 | alpha_mean=0.5000

NoGate | Triada 161/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2919 | S_p=0.0948 | S_m=0.0176 | S_family=0.0562 | gap=0.0772 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1096 | S_p=-0.0340 | S_m=0.1448 | S_family=0.0554 | gap=0.1788 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0557 | S_p=-0.0137 | S_m=0.0396 | S_family=0.0130 | gap=0.0533 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0440 | S_p=-0.0059 | S_m=0.1221 | S_family=0.0581 | gap=0.1280 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1623 | S_p=-0.0935 | S_m=0.1109 | S_family=0.0087 | gap=0.2044 | alpha_mean=0.5000

NoGate | Triada 162/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3617 | S_p=-0.0182 | S_m=0.0510 | S_family=0.0164 | gap=0.0691 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3543 | S_p=-0.0302 | S_m=-0.0203 | S_family=-0.0253 | gap=0.0099 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.5057 | S_p=-0.0135 | S_m=0.0719 | S_family=0.0292 | gap=0.0854 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0295 | S_p=0.0330 | S_m=-0.0139 | S_family=0.0095 | gap=0.0469 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1751 | S_p=0.0453 | S_m=-0.0272 | S_family=0.0091 | gap=0.0725 | alpha_mean=0.5000

NoGate | Triada 163/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0158 | S_p=0.0754 | S_m=-0.0250 | S_family=0.0252 | gap=0.1004 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2626 | S_p=0.0047 | S_m=0.1544 | S_family=0.0795 | gap=0.1497 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0160 | S_p=0.0007 | S_m=-0.0305 | S_family=-0.0149 | gap=0.0312 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0037 | S_p=0.0155 | S_m=-0.1154 | S_family=-0.0499 | gap=0.1309 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0538 | S_p=0.0305 | S_m=-0.0377 | S_family=-0.0036 | gap=0.0682 | alpha_mean=0.5000

NoGate | Triada 164/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2302 | S_p=0.0493 | S_m=0.0713 | S_family=0.0603 | gap=0.0220 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0661 | S_p=0.0035 | S_m=-0.0473 | S_family=-0.0219 | gap=0.0508 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0967 | S_p=-0.0146 | S_m=-0.0751 | S_family=-0.0448 | gap=0.0605 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1694 | S_p=0.0577 | S_m=0.0360 | S_family=0.0468 | gap=0.0217 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0622 | S_p=0.0106 | S_m=0.0156 | S_family=0.0131 | gap=0.0050 | alpha_mean=0.5000

NoGate | Triada 165/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4862 | S_p=-0.0094 | S_m=0.0115 | S_family=0.0011 | gap=0.0209 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0592 | S_p=0.0052 | S_m=0.0160 | S_family=0.0106 | gap=0.0107 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2554 | S_p=0.0165 | S_m=-0.0065 | S_family=0.0050 | gap=0.0230 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2239 | S_p=0.0644 | S_m=0.0519 | S_family=0.0582 | gap=0.0125 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2411 | S_p=0.0853 | S_m=0.0144 | S_family=0.0499 | gap=0.0709 | alpha_mean=0.5000

NoGate | Triada 166/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2726 | S_p=0.1236 | S_m=0.1273 | S_family=0.1254 | gap=0.0037 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1054 | S_p=0.0209 | S_m=-0.0263 | S_family=-0.0027 | gap=0.0473 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0516 | S_p=0.0214 | S_m=0.0060 | S_family=0.0137 | gap=0.0154 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1451 | S_p=-0.0234 | S_m=0.0506 | S_family=0.0136 | gap=0.0740 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0918 | S_p=0.0379 | S_m=0.0357 | S_family=0.0368 | gap=0.0022 | alpha_mean=0.5000

NoGate | Triada 167/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4415 | S_p=0.0265 | S_m=0.0553 | S_family=0.0409 | gap=0.0287 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1243 | S_p=0.0107 | S_m=0.0214 | S_family=0.0161 | gap=0.0107 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1266 | S_p=0.0267 | S_m=-0.0003 | S_family=0.0132 | gap=0.0270 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0941 | S_p=-0.0328 | S_m=-0.0020 | S_family=-0.0174 | gap=0.0309 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0869 | S_p=0.0001 | S_m=-0.0555 | S_family=-0.0277 | gap=0.0556 | alpha_mean=0.5000

NoGate | Triada 168/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4512 | S_p=0.1080 | S_m=-0.0250 | S_family=0.0415 | gap=0.1329 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0402 | S_p=-0.0045 | S_m=-0.0014 | S_family=-0.0029 | gap=0.0031 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0948 | S_p=0.0096 | S_m=-0.0402 | S_family=-0.0153 | gap=0.0498 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0513 | S_p=-0.0154 | S_m=-0.0037 | S_family=-0.0095 | gap=0.0117 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=-0.0328 | S_p=-0.1131 | S_m=-0.0321 | S_family=-0.0726 | gap=0.0810 | alpha_mean=0.5000

NoGate | Triada 169/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2350 | S_p=0.1081 | S_m=0.0255 | S_family=0.0668 | gap=0.0825 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2923 | S_p=0.1088 | S_m=0.0093 | S_family=0.0591 | gap=0.0995 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3568 | S_p=0.1677 | S_m=0.0708 | S_family=0.1193 | gap=0.0970 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1900 | S_p=0.0902 | S_m=0.0022 | S_family=0.0462 | gap=0.0879 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2084 | S_p=0.1719 | S_m=0.1337 | S_family=0.1528 | gap=0.0382 | alpha_mean=0.5000

NoGate | Triada 170/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1491 | S_p=0.0006 | S_m=0.0382 | S_family=0.0194 | gap=0.0376 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1983 | S_p=-0.1128 | S_m=0.0339 | S_family=-0.0395 | gap=0.1467 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2100 | S_p=-0.0259 | S_m=-0.0099 | S_family=-0.0179 | gap=0.0160 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2128 | S_p=-0.1225 | S_m=0.0637 | S_family=-0.0294 | gap=0.1863 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2270 | S_p=-0.0080 | S_m=0.0927 | S_family=0.0424 | gap=0.1007 | alpha_mean=0.5000

NoGate | Triada 171/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2216 | S_p=0.0392 | S_m=0.1035 | S_family=0.0714 | gap=0.0643 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0810 | S_p=0.1266 | S_m=0.1213 | S_family=0.1240 | gap=0.0053 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1205 | S_p=0.1050 | S_m=0.0791 | S_family=0.0920 | gap=0.0259 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3536 | S_p=0.1159 | S_m=0.1200 | S_family=0.1180 | gap=0.0041 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1767 | S_p=0.0992 | S_m=0.0734 | S_family=0.0863 | gap=0.0257 | alpha_mean=0.5000

NoGate | Triada 172/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0421 | S_p=0.0013 | S_m=0.0254 | S_family=0.0133 | gap=0.0241 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0139 | S_p=-0.0197 | S_m=0.0323 | S_family=0.0063 | gap=0.0519 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0478 | S_p=-0.0391 | S_m=0.0184 | S_family=-0.0103 | gap=0.0576 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0542 | S_p=-0.0135 | S_m=-0.0669 | S_family=-0.0402 | gap=0.0535 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2655 | S_p=0.0253 | S_m=0.0219 | S_family=0.0236 | gap=0.0034 | alpha_mean=0.5000

NoGate | Triada 173/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3047 | S_p=0.0567 | S_m=0.0951 | S_family=0.0759 | gap=0.0384 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0407 | S_p=-0.0244 | S_m=0.0563 | S_family=0.0160 | gap=0.0807 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0145 | S_p=-0.0320 | S_m=-0.0111 | S_family=-0.0216 | gap=0.0209 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3430 | S_p=0.0715 | S_m=-0.0317 | S_family=0.0199 | gap=0.1032 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.4261 | S_p=0.1353 | S_m=0.1015 | S_family=0.1184 | gap=0.0338 | alpha_mean=0.5000

NoGate | Triada 174/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3058 | S_p=-0.1104 | S_m=0.0647 | S_family=-0.0229 | gap=0.1750 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0239 | S_p=-0.0520 | S_m=-0.0373 | S_family=-0.0446 | gap=0.0147 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0330 | S_p=-0.0577 | S_m=0.0037 | S_family=-0.0270 | gap=0.0614 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0323 | S_p=-0.0082 | S_m=-0.0410 | S_family=-0.0246 | gap=0.0328 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0124 | S_p=-0.0456 | S_m=-0.0206 | S_family=-0.0331 | gap=0.0250 | alpha_mean=0.5000

NoGate | Triada 175/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2103 | S_p=0.0342 | S_m=0.0531 | S_family=0.0436 | gap=0.0190 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2323 | S_p=-0.0253 | S_m=0.0606 | S_family=0.0177 | gap=0.0859 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1099 | S_p=0.0976 | S_m=0.0232 | S_family=0.0604 | gap=0.0744 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1735 | S_p=-0.0005 | S_m=0.0121 | S_family=0.0058 | gap=0.0126 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1377 | S_p=0.0230 | S_m=0.0431 | S_family=0.0331 | gap=0.0201 | alpha_mean=0.5000

NoGate | Triada 176/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0209 | S_p=-0.0111 | S_m=-0.0001 | S_family=-0.0056 | gap=0.0109 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0085 | S_p=0.0229 | S_m=0.0048 | S_family=0.0138 | gap=0.0181 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0815 | S_p=-0.0107 | S_m=-0.0024 | S_family=-0.0065 | gap=0.0083 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3379 | S_p=-0.0440 | S_m=-0.0160 | S_family=-0.0300 | gap=0.0280 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3007 | S_p=0.0981 | S_m=0.0146 | S_family=0.0563 | gap=0.0836 | alpha_mean=0.5000

NoGate | Triada 177/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2072 | S_p=-0.0561 | S_m=-0.0610 | S_family=-0.0585 | gap=0.0049 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1993 | S_p=-0.0113 | S_m=0.0295 | S_family=0.0091 | gap=0.0408 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2499 | S_p=-0.0417 | S_m=-0.0115 | S_family=-0.0266 | gap=0.0302 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3888 | S_p=0.0135 | S_m=-0.0235 | S_family=-0.0050 | gap=0.0370 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.4396 | S_p=-0.0411 | S_m=-0.0158 | S_family=-0.0284 | gap=0.0253 | alpha_mean=0.5000

NoGate | Triada 178/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4069 | S_p=0.0256 | S_m=0.0418 | S_family=0.0337 | gap=0.0163 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0719 | S_p=-0.0080 | S_m=-0.0540 | S_family=-0.0310 | gap=0.0460 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0092 | S_p=0.0578 | S_m=0.0225 | S_family=0.0402 | gap=0.0353 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2958 | S_p=0.0021 | S_m=0.0716 | S_family=0.0368 | gap=0.0694 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2826 | S_p=-0.0309 | S_m=0.0187 | S_family=-0.0061 | gap=0.0497 | alpha_mean=0.5000

NoGate | Triada 179/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2087 | S_p=-0.0137 | S_m=0.1212 | S_family=0.0538 | gap=0.1349 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2022 | S_p=0.0426 | S_m=0.1061 | S_family=0.0743 | gap=0.0635 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2546 | S_p=-0.0132 | S_m=0.0522 | S_family=0.0195 | gap=0.0655 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2878 | S_p=0.1090 | S_m=0.0405 | S_family=0.0748 | gap=0.0685 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1611 | S_p=0.0030 | S_m=0.0535 | S_family=0.0282 | gap=0.0505 | alpha_mean=0.5000

NoGate | Triada 180/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1758 | S_p=0.0054 | S_m=0.0430 | S_family=0.0242 | gap=0.0377 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0372 | S_p=-0.1226 | S_m=0.0290 | S_family=-0.0468 | gap=0.1515 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1311 | S_p=-0.0145 | S_m=0.0609 | S_family=0.0232 | gap=0.0754 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1971 | S_p=-0.0210 | S_m=0.0698 | S_family=0.0244 | gap=0.0908 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1315 | S_p=0.0536 | S_m=0.0069 | S_family=0.0303 | gap=0.0467 | alpha_mean=0.5000

NoGate | Triada 181/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0416 | S_p=0.0604 | S_m=0.0169 | S_family=0.0387 | gap=0.0435 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3403 | S_p=-0.0087 | S_m=0.0550 | S_family=0.0232 | gap=0.0637 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0390 | S_p=0.0602 | S_m=0.0031 | S_family=0.0316 | gap=0.0571 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0225 | S_p=0.0399 | S_m=0.0375 | S_family=0.0387 | gap=0.0024 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0447 | S_p=0.0247 | S_m=0.0733 | S_family=0.0490 | gap=0.0486 | alpha_mean=0.5000

NoGate | Triada 182/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1844 | S_p=0.0589 | S_m=0.1062 | S_family=0.0825 | gap=0.0474 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2813 | S_p=-0.0447 | S_m=0.0463 | S_family=0.0008 | gap=0.0910 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2976 | S_p=-0.0452 | S_m=0.0967 | S_family=0.0257 | gap=0.1419 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2654 | S_p=0.0020 | S_m=0.0117 | S_family=0.0069 | gap=0.0097 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2640 | S_p=-0.0109 | S_m=0.0689 | S_family=0.0290 | gap=0.0798 | alpha_mean=0.5000

NoGate | Triada 183/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4758 | S_p=-0.0037 | S_m=-0.0502 | S_family=-0.0270 | gap=0.0465 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1418 | S_p=-0.0121 | S_m=-0.0262 | S_family=-0.0192 | gap=0.0142 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4455 | S_p=-0.0242 | S_m=0.0112 | S_family=-0.0065 | gap=0.0354 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2387 | S_p=0.0337 | S_m=-0.1448 | S_family=-0.0555 | gap=0.1785 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3429 | S_p=0.0145 | S_m=-0.0087 | S_family=0.0029 | gap=0.0231 | alpha_mean=0.5000

NoGate | Triada 184/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1010 | S_p=0.0717 | S_m=-0.0554 | S_family=0.0081 | gap=0.1271 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1624 | S_p=-0.0208 | S_m=0.0681 | S_family=0.0237 | gap=0.0889 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0115 | S_p=-0.0129 | S_m=0.0267 | S_family=0.0069 | gap=0.0397 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2154 | S_p=-0.0582 | S_m=0.0898 | S_family=0.0158 | gap=0.1480 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2684 | S_p=-0.0606 | S_m=-0.0320 | S_family=-0.0463 | gap=0.0286 | alpha_mean=0.5000

NoGate | Triada 185/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4627 | S_p=0.0530 | S_m=0.0280 | S_family=0.0405 | gap=0.0250 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3835 | S_p=0.0596 | S_m=0.0121 | S_family=0.0358 | gap=0.0474 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4856 | S_p=-0.0184 | S_m=-0.0227 | S_family=-0.0206 | gap=0.0043 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.4010 | S_p=0.0394 | S_m=0.0365 | S_family=0.0379 | gap=0.0029 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2692 | S_p=0.0168 | S_m=0.0858 | S_family=0.0513 | gap=0.0690 | alpha_mean=0.5000

NoGate | Triada 186/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3473 | S_p=0.0488 | S_m=0.0435 | S_family=0.0462 | gap=0.0053 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3532 | S_p=-0.0384 | S_m=0.0853 | S_family=0.0235 | gap=0.1237 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1519 | S_p=-0.0683 | S_m=0.0792 | S_family=0.0055 | gap=0.1476 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1133 | S_p=0.0323 | S_m=-0.0207 | S_family=0.0058 | gap=0.0531 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1953 | S_p=0.0038 | S_m=0.0522 | S_family=0.0280 | gap=0.0485 | alpha_mean=0.5000

NoGate | Triada 187/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2918 | S_p=0.0593 | S_m=0.0322 | S_family=0.0458 | gap=0.0272 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3275 | S_p=0.0478 | S_m=0.1087 | S_family=0.0782 | gap=0.0609 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2910 | S_p=0.0812 | S_m=-0.0161 | S_family=0.0326 | gap=0.0973 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3172 | S_p=0.0101 | S_m=0.0984 | S_family=0.0542 | gap=0.0883 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3496 | S_p=0.0229 | S_m=0.0743 | S_family=0.0486 | gap=0.0513 | alpha_mean=0.5000

NoGate | Triada 188/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0663 | S_p=-0.0516 | S_m=-0.0209 | S_family=-0.0363 | gap=0.0307 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2523 | S_p=-0.0921 | S_m=0.0685 | S_family=-0.0118 | gap=0.1607 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0012 | S_p=-0.0565 | S_m=-0.0410 | S_family=-0.0487 | gap=0.0156 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1117 | S_p=-0.0180 | S_m=0.0735 | S_family=0.0278 | gap=0.0915 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2708 | S_p=-0.0992 | S_m=0.0304 | S_family=-0.0344 | gap=0.1297 | alpha_mean=0.5000

NoGate | Triada 189/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2672 | S_p=-0.0843 | S_m=0.0595 | S_family=-0.0124 | gap=0.1438 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0155 | S_p=-0.0408 | S_m=-0.0570 | S_family=-0.0489 | gap=0.0162 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1174 | S_p=0.0632 | S_m=0.0674 | S_family=0.0653 | gap=0.0043 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2392 | S_p=-0.0403 | S_m=0.0113 | S_family=-0.0145 | gap=0.0516 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2898 | S_p=-0.0314 | S_m=-0.0163 | S_family=-0.0239 | gap=0.0151 | alpha_mean=0.5000

NoGate | Triada 190/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1551 | S_p=0.0012 | S_m=-0.0792 | S_family=-0.0390 | gap=0.0805 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3123 | S_p=0.0173 | S_m=0.0036 | S_family=0.0104 | gap=0.0137 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0203 | S_p=-0.0555 | S_m=0.0282 | S_family=-0.0136 | gap=0.0837 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3119 | S_p=-0.0703 | S_m=0.0181 | S_family=-0.0261 | gap=0.0883 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2615 | S_p=-0.0452 | S_m=0.0261 | S_family=-0.0095 | gap=0.0713 | alpha_mean=0.5000

NoGate | Triada 191/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1782 | S_p=0.0406 | S_m=0.0402 | S_family=0.0404 | gap=0.0004 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2675 | S_p=0.0244 | S_m=0.0854 | S_family=0.0549 | gap=0.0610 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2642 | S_p=0.0400 | S_m=0.0731 | S_family=0.0566 | gap=0.0331 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0129 | S_p=-0.0315 | S_m=0.0299 | S_family=-0.0008 | gap=0.0614 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2660 | S_p=0.0472 | S_m=-0.0009 | S_family=0.0231 | gap=0.0481 | alpha_mean=0.5000

NoGate | Triada 192/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1995 | S_p=-0.0312 | S_m=0.0771 | S_family=0.0229 | gap=0.1083 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0128 | S_p=-0.0252 | S_m=0.0107 | S_family=-0.0073 | gap=0.0359 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0130 | S_p=-0.0335 | S_m=-0.0530 | S_family=-0.0433 | gap=0.0195 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2948 | S_p=0.0799 | S_m=0.0751 | S_family=0.0775 | gap=0.0048 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2038 | S_p=0.0267 | S_m=0.0945 | S_family=0.0606 | gap=0.0678 | alpha_mean=0.5000

NoGate | Triada 193/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0518 | S_p=0.0798 | S_m=-0.0056 | S_family=0.0371 | gap=0.0854 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0600 | S_p=-0.0412 | S_m=-0.0889 | S_family=-0.0651 | gap=0.0477 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0926 | S_p=0.0885 | S_m=0.0888 | S_family=0.0887 | gap=0.0003 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0135 | S_p=-0.0058 | S_m=-0.0497 | S_family=-0.0278 | gap=0.0438 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1101 | S_p=0.0628 | S_m=0.0465 | S_family=0.0547 | gap=0.0164 | alpha_mean=0.5000

NoGate | Triada 194/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1410 | S_p=0.0291 | S_m=0.0660 | S_family=0.0476 | gap=0.0369 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0237 | S_p=-0.0012 | S_m=0.0039 | S_family=0.0013 | gap=0.0052 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2620 | S_p=0.0598 | S_m=0.1032 | S_family=0.0815 | gap=0.0434 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0990 | S_p=0.0694 | S_m=0.0680 | S_family=0.0687 | gap=0.0013 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2294 | S_p=0.0608 | S_m=0.0389 | S_family=0.0498 | gap=0.0219 | alpha_mean=0.5000

NoGate | Triada 195/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1639 | S_p=0.0450 | S_m=0.0498 | S_family=0.0474 | gap=0.0048 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0043 | S_p=0.0732 | S_m=-0.0054 | S_family=0.0339 | gap=0.0785 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0009 | S_p=0.0574 | S_m=0.0263 | S_family=0.0418 | gap=0.0311 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2179 | S_p=0.0267 | S_m=0.0332 | S_family=0.0299 | gap=0.0064 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2268 | S_p=0.0218 | S_m=0.0212 | S_family=0.0215 | gap=0.0005 | alpha_mean=0.5000

NoGate | Triada 196/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0158 | S_p=0.0226 | S_m=-0.0052 | S_family=0.0087 | gap=0.0278 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3679 | S_p=0.0726 | S_m=0.0585 | S_family=0.0655 | gap=0.0141 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2567 | S_p=0.0768 | S_m=0.1015 | S_family=0.0891 | gap=0.0247 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0445 | S_p=0.0855 | S_m=-0.0249 | S_family=0.0303 | gap=0.1105 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1242 | S_p=0.1331 | S_m=0.0164 | S_family=0.0747 | gap=0.1167 | alpha_mean=0.5000

NoGate | Triada 197/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4776 | S_p=0.0634 | S_m=-0.0068 | S_family=0.0283 | gap=0.0702 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3058 | S_p=0.0224 | S_m=0.0305 | S_family=0.0264 | gap=0.0082 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0983 | S_p=0.1186 | S_m=0.0153 | S_family=0.0669 | gap=0.1033 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0126 | S_p=-0.0488 | S_m=-0.0176 | S_family=-0.0332 | gap=0.0313 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1912 | S_p=0.0178 | S_m=-0.0402 | S_family=-0.0112 | gap=0.0579 | alpha_mean=0.5000

NoGate | Triada 198/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2175 | S_p=-0.0143 | S_m=0.0052 | S_family=-0.0045 | gap=0.0195 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0977 | S_p=-0.0170 | S_m=0.0612 | S_family=0.0221 | gap=0.0782 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0223 | S_p=-0.0269 | S_m=0.0410 | S_family=0.0071 | gap=0.0679 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2252 | S_p=-0.0057 | S_m=0.0166 | S_family=0.0055 | gap=0.0223 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2298 | S_p=-0.0652 | S_m=-0.0058 | S_family=-0.0355 | gap=0.0594 | alpha_mean=0.5000

NoGate | Triada 199/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4542 | S_p=0.0098 | S_m=-0.0400 | S_family=-0.0151 | gap=0.0498 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3867 | S_p=0.0313 | S_m=-0.0457 | S_family=-0.0072 | gap=0.0770 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1432 | S_p=-0.1102 | S_m=-0.0731 | S_family=-0.0916 | gap=0.0371 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0260 | S_p=-0.0311 | S_m=0.0580 | S_family=0.0135 | gap=0.0891 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1644 | S_p=0.0135 | S_m=-0.0499 | S_family=-0.0182 | gap=0.0633 | alpha_mean=0.5000

NoGate | Triada 200/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0303 | S_p=0.0202 | S_m=-0.0563 | S_family=-0.0180 | gap=0.0765 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0385 | S_p=-0.1024 | S_m=0.0002 | S_family=-0.0511 | gap=0.1026 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2854 | S_p=0.0539 | S_m=-0.0296 | S_family=0.0122 | gap=0.0835 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0771 | S_p=0.0280 | S_m=-0.0432 | S_family=-0.0076 | gap=0.0712 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1182 | S_p=-0.0073 | S_m=-0.0496 | S_family=-0.0285 | gap=0.0422 | alpha_mean=0.5000

NoGate | Triada 201/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0894 | S_p=-0.0482 | S_m=-0.0531 | S_family=-0.0506 | gap=0.0048 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1743 | S_p=0.0143 | S_m=0.0309 | S_family=0.0226 | gap=0.0166 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0536 | S_p=-0.0182 | S_m=-0.1257 | S_family=-0.0719 | gap=0.1075 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1672 | S_p=-0.0148 | S_m=0.0408 | S_family=0.0130 | gap=0.0556 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0809 | S_p=-0.1344 | S_m=-0.0625 | S_family=-0.0984 | gap=0.0719 | alpha_mean=0.5000

NoGate | Triada 202/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0332 | S_p=-0.1062 | S_m=0.0754 | S_family=-0.0154 | gap=0.1816 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0366 | S_p=-0.0284 | S_m=-0.0159 | S_family=-0.0221 | gap=0.0125 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0392 | S_p=-0.0876 | S_m=0.0989 | S_family=0.0057 | gap=0.1865 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0365 | S_p=-0.0390 | S_m=0.0031 | S_family=-0.0180 | gap=0.0421 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2839 | S_p=0.0677 | S_m=0.0182 | S_family=0.0429 | gap=0.0495 | alpha_mean=0.5000

NoGate | Triada 203/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2602 | S_p=0.0791 | S_m=0.0287 | S_family=0.0539 | gap=0.0504 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2444 | S_p=0.0565 | S_m=-0.0414 | S_family=0.0075 | gap=0.0980 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2696 | S_p=0.0814 | S_m=-0.0302 | S_family=0.0256 | gap=0.1116 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2048 | S_p=0.0207 | S_m=-0.0549 | S_family=-0.0171 | gap=0.0756 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2605 | S_p=0.1032 | S_m=-0.0392 | S_family=0.0320 | gap=0.1424 | alpha_mean=0.5000

NoGate | Triada 204/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3715 | S_p=0.0992 | S_m=-0.0590 | S_family=0.0201 | gap=0.1582 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0595 | S_p=0.0253 | S_m=0.0135 | S_family=0.0194 | gap=0.0118 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3330 | S_p=0.0421 | S_m=0.0418 | S_family=0.0419 | gap=0.0003 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2435 | S_p=0.1242 | S_m=0.0919 | S_family=0.1081 | gap=0.0323 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1578 | S_p=0.0441 | S_m=0.0181 | S_family=0.0311 | gap=0.0260 | alpha_mean=0.5000

NoGate | Triada 205/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2432 | S_p=0.0835 | S_m=0.0274 | S_family=0.0554 | gap=0.0561 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1829 | S_p=0.0279 | S_m=-0.0213 | S_family=0.0033 | gap=0.0492 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2549 | S_p=0.1027 | S_m=0.0457 | S_family=0.0742 | gap=0.0570 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2203 | S_p=-0.0544 | S_m=0.1650 | S_family=0.0553 | gap=0.2195 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0558 | S_p=-0.0092 | S_m=0.0319 | S_family=0.0113 | gap=0.0412 | alpha_mean=0.5000

NoGate | Triada 206/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1964 | S_p=-0.0837 | S_m=-0.0243 | S_family=-0.0540 | gap=0.0594 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2416 | S_p=0.0260 | S_m=0.0414 | S_family=0.0337 | gap=0.0154 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0247 | S_p=-0.0758 | S_m=0.0630 | S_family=-0.0064 | gap=0.1387 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1476 | S_p=0.0614 | S_m=0.0775 | S_family=0.0694 | gap=0.0162 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1374 | S_p=0.0076 | S_m=-0.0149 | S_family=-0.0037 | gap=0.0224 | alpha_mean=0.5000

NoGate | Triada 207/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2174 | S_p=-0.0060 | S_m=0.0893 | S_family=0.0417 | gap=0.0952 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3504 | S_p=0.0473 | S_m=0.0425 | S_family=0.0449 | gap=0.0048 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0378 | S_p=-0.0363 | S_m=-0.0069 | S_family=-0.0216 | gap=0.0293 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0040 | S_p=-0.0668 | S_m=0.0677 | S_family=0.0004 | gap=0.1345 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0782 | S_p=-0.0611 | S_m=0.0350 | S_family=-0.0131 | gap=0.0961 | alpha_mean=0.5000

NoGate | Triada 208/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.5077 | S_p=0.0180 | S_m=0.0843 | S_family=0.0512 | gap=0.0663 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0707 | S_p=0.0220 | S_m=0.0117 | S_family=0.0168 | gap=0.0104 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1261 | S_p=0.0261 | S_m=0.1012 | S_family=0.0636 | gap=0.0751 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0708 | S_p=-0.0662 | S_m=0.0250 | S_family=-0.0206 | gap=0.0912 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2367 | S_p=0.0057 | S_m=0.0589 | S_family=0.0323 | gap=0.0532 | alpha_mean=0.5000

==============================
Filas finales NoGate
==============================
1040
Esperadas: 1040
✓ Row count is correct.

==============================
Global summary NoGate
==============================

,variant,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap,alpha_mean,alpha_std,alpha_min,alpha_max
0,NoGate_fixed_alpha05,0.186611,0.016898,0.022914,0.019906,0.059253,0.5,0.0,0.5,0.5

==============================
Summary by age NoGate
==============================

,age,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap,alpha_mean,alpha_std,alpha_min,alpha_max
0,5,0.228732,0.021340,0.021394,0.021367,0.058969,0.5,0.0,0.5,0.5
1,15,0.174104,0.014445,0.021142,0.017793,0.051344,0.5,0.0,0.5,0.5
2,25,0.174422,0.011256,0.016773,0.014014,0.056325,0.5,0.0,0.5,0.5
3,40,0.175843,0.015316,0.024331,0.019823,0.061478,0.5,0.0,0.5,0.5
4,60,0.179955,0.022136,0.030933,0.026535,0.068150,0.5,0.0,0.5,0.5

✓ TEST FINAL NoGate terminado
CSV: /content/drive/MyDrive/Notebook4/results/eval/nogate/nogate.csv
Images: /content/drive/MyDrive/Notebook4/results/eval/nogate/img
Summary: /content/drive/MyDrive/Notebook4/results/eval/nogate

In [2]:
# ============================================================
# Final comparison:
# BAP2 step4689 λ=0.1 vs NoGate fixed α=0.5 λ=0.1
# CPU only
# ============================================================

import os
import numpy as np
import pandas as pd
from IPython.display import display

try:
    from scipy.stats import wilcoxon
    HAS_SCIPY = True
except Exception as e:
    HAS_SCIPY = False
    print("⚠ scipy not available:", e)

BAP2_CSV = f"{DRIVE}/results/eval/bap2/bap2.csv"
NOGATE_CSV = f"{DRIVE}/results/eval/nogate/nogate.csv"

assert os.path.exists(BAP2_CSV), BAP2_CSV
assert os.path.exists(NOGATE_CSV), NOGATE_CSV

df_bap2 = pd.read_csv(BAP2_CSV)
df_nogate = pd.read_csv(NOGATE_CSV)

# Only BAP2 with active parents
df_bap2_01 = df_bap2[df_bap2["parent_scale"] == 0.1].copy()

print("BAP2 λ=0.1 rows:", len(df_bap2_01))
print("NoGate rows:", len(df_nogate))

metrics = [
    "S_id_child",
    "S_p_father",
    "S_m_mother",
    "S_family",
    "balance_abs_gap",
]

key_cols = ["triad_idx", "age"]

merged = df_bap2_01[key_cols + metrics].merge(
    df_nogate[key_cols + metrics],
    on=key_cols,
    suffixes=("_bap2", "_nogate")
)

print("Pares comparados:", len(merged))
print("Triads:", merged["triad_idx"].nunique())
print("Ages:", sorted(merged["age"].unique()))

assert len(merged) == 1040, "Expected 208 triads × 5 ages = 1040 pairs"

rng = np.random.default_rng(123)
B = 5000

rows = []

for m in metrics:
    d = merged[f"{m}_bap2"] - merged[f"{m}_nogate"]
    arr = d.values

    boot = []
    for _ in range(B):
        sample = rng.choice(arr, size=len(arr), replace=True)
        boot.append(sample.mean())

    boot = np.array(boot)

    row = {
        "metric": m,
        "mean_bap2": merged[f"{m}_bap2"].mean(),
        "mean_nogate": merged[f"{m}_nogate"].mean(),
        "mean_delta_bap2_minus_nogate": d.mean(),
        "median_delta": d.median(),
        "ci95_low": np.percentile(boot, 2.5),
        "ci95_high": np.percentile(boot, 97.5),
        "win_rate_bap2_gt_nogate": (d > 0).mean(),
        "n_pairs": len(d),
    }

    if HAS_SCIPY:
        try:
            stat, p = wilcoxon(d)
            row["wilcoxon_stat"] = stat
            row["wilcoxon_p"] = p
        except Exception as e:
            row["wilcoxon_stat"] = None
            row["wilcoxon_p"] = None
            row["wilcoxon_error"] = str(e)

    rows.append(row)

df_gate_stats = pd.DataFrame(rows)

print("\n==============================")
print("BAP2 λ=0.1 vs NoGate α=0.5")
print("==============================")
display(df_gate_stats)

# By age
age_rows = []

for age in sorted(merged["age"].unique()):
    sub = merged[merged["age"] == age]

    for m in metrics:
        d = sub[f"{m}_bap2"] - sub[f"{m}_nogate"]

        age_rows.append({
            "age": age,
            "metric": m,
            "mean_delta_bap2_minus_nogate": d.mean(),
            "median_delta": d.median(),
            "win_rate_bap2_gt_nogate": (d > 0).mean(),
            "n_pairs": len(d),
        })

df_gate_stats_age = pd.DataFrame(age_rows)

print("\n==============================")
print("BAP2 vs NoGate by age")
print("==============================")
display(df_gate_stats_age)

OUT_DIR = f"{DRIVE}/results/eval/cmp"
os.makedirs(OUT_DIR, exist_ok=True)

df_gate_stats.to_csv(f"{OUT_DIR}/stats_bap2_vs_nogate.csv", index=False)
df_gate_stats_age.to_csv(f"{OUT_DIR}/stats_bap2_vs_nogate_by_age.csv", index=False)

print("\n✓ Saved to:", OUT_DIR)

BAP2 λ=0.1 rows: 1040
NoGate rows: 1040
Pares comparados: 1040
Triads: 208
Edades: [np.int64(5), np.int64(15), np.int64(25), np.int64(40), np.int64(60)]

==============================
BAP2 λ=0.1 vs NoGate α=0.5
==============================

,metric,mean_bap2,mean_nogate,mean_delta_bap2_minus_nogate,median_delta,ci95_low,ci95_high,win_rate_bap2_gt_nogate,n_pairs,wilcoxon_stat,wilcoxon_p
0,S_id_child,0.186964,0.186611,0.000353,0.000132,-0.000110,0.000870,0.531731,1040,253717.0,0.080341
1,S_p_father,0.017099,0.016898,0.000200,0.000092,-0.000114,0.000507,0.513462,1040,253317.0,0.073455
2,S_m_mother,0.023106,0.022914,0.000192,0.000082,-0.000107,0.000492,0.524038,1040,252571.0,0.061903
3,S_family,0.020102,0.019906,0.000196,0.000087,-0.000056,0.000423,0.529808,1040,244683.0,0.007338
4,balance_abs_gap,0.058842,0.059253,-0.000411,-0.000073,-0.000781,-0.000055,0.484615,1040,255640.0,0.121085

==============================
BAP2 vs NoGate by age
==============================

,age,metric,mean_delta_bap2_minus_nogate,median_delta,win_rate_bap2_gt_nogate,n_pairs
0,5,S_id_child,0.000470,0.000232,0.581731,208
1,5,S_p_father,0.000091,0.000123,0.528846,208
2,5,S_m_mother,0.000379,0.000193,0.552885,208
3,5,S_family,0.000235,0.000125,0.548077,208
4,5,balance_abs_gap,-0.001093,-0.000048,0.490385,208
5,15,S_id_child,0.000341,0.000112,0.528846,208
6,15,S_p_father,0.000028,-0.000022,0.495192,208
7,15,S_m_mother,0.000582,0.000215,0.567308,208
8,15,S_family,0.000305,0.000065,0.514423,208
9,15,balance_abs_gap,0.000253,0.000111,0.514423,208
10,25,S_id_child,0.000728,0.000232,0.567308,208
11,25,S_p_father,-0.000015,-0.000197,0.447115,208
12,25,S_m_mother,-0.000037,-0.000071,0.475962,208
13,25,S_family,-0.000026,-0.000040,0.475962,208
14,25,balance_abs_gap,-0.000330,0.000047,0.500000,208
15,40,S_id_child,0.000255,-0.000043,0.490385,208
16,40,S_p_father,0.000031,0.000231,0.548077,208
17,40,S_m_mother,-0.000138,0.000178,0.533654,208
18,40,S_family,-0.000053,0.000228,0.600962,208
19,40,balance_abs_gap,-0.000088,-0.000140,0.451923,208
20,60,S_id_child,-0.000031,-0.000044,0.490385,208
21,60,S_p_father,0.000865,0.000230,0.548077,208
22,60,S_m_mother,0.000172,-0.000034,0.490385,208
23,60,S_family,0.000519,0.000034,0.509615,208
24,60,balance_abs_gap,-0.000797,-0.000124,0.466346,208

✓ Saved to: /content/drive/MyDrive/Notebook4/results/eval/cmp

In [ ]:
# ============================================================
# FIGURE A — Qualitative comparison by method
#
# Columnas:
# Father | Mother | Real Child | BAP2 λ=0.0 | NoGate α=0.5 | BAP2 λ=0.1
#
# Fixed age: 25
# Selection: 8 representative triads
# Output: PNG + PDF + CSV of selected triads
# ============================================================

import os
import textwrap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image, ImageOps, ImageDraw

# ------------------------------------------------------------
# Rutas
# ------------------------------------------------------------

BAP2_CSV = f"{DRIVE}/results/eval/bap2/bap2.csv"
NOGATE_CSV = f"{DRIVE}/results/eval/nogate/nogate.csv"

OUT_DIR = f"{DRIVE}/results/figs"
os.makedirs(OUT_DIR, exist_ok=True)

FIG_PNG = f"{OUT_DIR}/method/a25.png"
SEL_CSV = f"{OUT_DIR}/meta/method_sel.csv"

assert os.path.exists(BAP2_CSV), BAP2_CSV
assert os.path.exists(NOGATE_CSV), NOGATE_CSV
assert "FIW_ROOT" in globals(), "Falta FIW_ROOT"

df_bap2 = pd.read_csv(BAP2_CSV)
df_nogate = pd.read_csv(NOGATE_CSV)

AGE_FIG = 25
N_ROWS = 8

# ------------------------------------------------------------
# Preparar datos
# ------------------------------------------------------------

b0 = df_bap2[(df_bap2["age"] == AGE_FIG) & (df_bap2["parent_scale"] == 0.0)].copy()
b1 = df_bap2[(df_bap2["age"] == AGE_FIG) & (df_bap2["parent_scale"] == 0.1)].copy()
ng = df_nogate[df_nogate["age"] == AGE_FIG].copy()

metrics = [
    "S_id_child",
    "S_p_father",
    "S_m_mother",
    "S_family",
    "balance_abs_gap",
    "image_path",
    "key_p",
    "key_m",
    "key_c",
    "gender",
]

merged = (
    b0[["triad_idx"] + metrics]
    .merge(
        b1[["triad_idx"] + metrics],
        on="triad_idx",
        suffixes=("_lambda0", "_bap2")
    )
    .merge(
        ng[["triad_idx"] + metrics],
        on="triad_idx",
        suffixes=("", "_nogate")
    )
)

# Rename NoGate columns left without suffix after the second merge
rename_ng = {
    "S_id_child": "S_id_child_nogate",
    "S_p_father": "S_p_father_nogate",
    "S_m_mother": "S_m_mother_nogate",
    "S_family": "S_family_nogate",
    "balance_abs_gap": "balance_abs_gap_nogate",
    "image_path": "image_path_nogate",
    "key_p": "key_p_nogate",
    "key_m": "key_m_nogate",
    "key_c": "key_c_nogate",
    "gender": "gender_nogate",
}
merged = merged.rename(columns=rename_ng)

# Delta parental BAP2 vs lambda0
merged["delta_family_bap2_vs_lambda0"] = (
    merged["S_family_bap2"] - merged["S_family_lambda0"]
)

merged["delta_id_bap2_vs_lambda0"] = (
    merged["S_id_child_bap2"] - merged["S_id_child_lambda0"]
)

merged["delta_family_bap2_vs_nogate"] = (
    merged["S_family_bap2"] - merged["S_family_nogate"]
)

# ------------------------------------------------------------
# Representative selection
# ------------------------------------------------------------
# Condiciones:
# 1) BAP2 mejora S_family frente a λ=0.0
# 2) S_id_child_bap2 is not too low
# 3) avoid overly extreme examples: use a combined ranking

pool = merged[
    (merged["delta_family_bap2_vs_lambda0"] > 0)
    & (merged["S_id_child_bap2"] > merged["S_id_child_bap2"].quantile(0.40))
].copy()

if len(pool) < N_ROWS:
    print("⚠ Small pool, relaxing the S_id criterion.")
    pool = merged[merged["delta_family_bap2_vs_lambda0"] > 0].copy()

if len(pool) < N_ROWS:
    print("⚠ Pool still small, using all.")
    pool = merged.copy()

# score moderado:
# high S_id + high family gain, without taking only extremes
pool["rank_id"] = pool["S_id_child_bap2"].rank(pct=True)
pool["rank_delta_family"] = pool["delta_family_bap2_vs_lambda0"].rank(pct=True)
pool["score"] = 0.55 * pool["rank_id"] + 0.45 * pool["rank_delta_family"]

# Select from high but spread percentiles, not just the top 8
pool_sorted = pool.sort_values("score", ascending=True).reset_index(drop=True)

target_qs = np.linspace(0.60, 0.95, N_ROWS)
selected_idxs = []
for q in target_qs:
    pos = int(q * (len(pool_sorted) - 1))
    selected_idxs.append(pos)

selected = pool_sorted.iloc[selected_idxs].drop_duplicates("triad_idx")

# If rows are missing due to duplicates, fill with the best remaining
if len(selected) < N_ROWS:
    extra = pool_sorted[~pool_sorted["triad_idx"].isin(selected["triad_idx"])]
    selected = pd.concat([selected, extra.tail(N_ROWS - len(selected))], axis=0)

selected = selected.head(N_ROWS).copy()
selected = selected.sort_values("triad_idx").reset_index(drop=True)

print("Selected triads:")
display(selected[[
    "triad_idx",
    "S_id_child_lambda0",
    "S_id_child_nogate",
    "S_id_child_bap2",
    "S_family_lambda0",
    "S_family_nogate",
    "S_family_bap2",
    "delta_family_bap2_vs_lambda0",
    "delta_family_bap2_vs_nogate",
]])

selected.to_csv(SEL_CSV, index=False)

# ------------------------------------------------------------
# Image helpers
# ------------------------------------------------------------

def read_img(path):
    try:
        img = Image.open(path).convert("RGB")
        return img
    except Exception as e:
        print("⚠ Could not open:", path, "|", e)
        return Image.new("RGB", (256, 256), color=(230, 230, 230))

def square_center_crop(img):
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    img = img.crop((left, top, left + side, top + side))
    return img

def prep_img(path, size=180):
    img = read_img(path)
    img = square_center_crop(img)
    img = ImageOps.fit(img, (size, size), method=Image.Resampling.LANCZOS)
    return img

def add_border(img, width=2):
    return ImageOps.expand(img, border=width, fill=(255, 255, 255))

def key_to_path(key):
    return os.path.join(FIW_ROOT, key)

# ------------------------------------------------------------
# Crear figura
# ------------------------------------------------------------

columns = [
    "Father",
    "Mother",
    "Real Child",
    "λ=0.0",
    "NoGate\nα=0.5",
    "BAP2\nλ=0.1",
]

n_rows = len(selected)
n_cols = len(columns)

fig_w = n_cols * 2.0
fig_h = n_rows * 2.0 + 0.7

fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(fig_w, fig_h),
    dpi=300
)

if n_rows == 1:
    axes = np.expand_dims(axes, axis=0)

for r, row in selected.iterrows():

    father_path = key_to_path(row["key_p_lambda0"])
    mother_path = key_to_path(row["key_m_lambda0"])
    child_path  = key_to_path(row["key_c_lambda0"])

    paths = [
        father_path,
        mother_path,
        child_path,
        row["image_path_lambda0"],
        row["image_path_nogate"],
        row["image_path_bap2"],
    ]

    for c, path in enumerate(paths):
        ax = axes[r, c]
        img = prep_img(path, size=220)
        ax.imshow(img)
        ax.axis("off")

        if r == 0:
            ax.set_title(columns[c], fontsize=10, pad=6)

    # side label with the triad index
    axes[r, 0].text(
        -0.18, 0.5,
        f"T{int(row['triad_idx'])}",
        transform=axes[r, 0].transAxes,
        rotation=90,
        va="center",
        ha="center",
        fontsize=8
    )

plt.subplots_adjust(
    left=0.04,
    right=0.995,
    top=0.93,
    bottom=0.03,
    wspace=0.03,
    hspace=0.06
)

fig.suptitle(
    f"Qualitative comparison of generated descendants at age {AGE_FIG}",
    fontsize=12,
    y=0.985
)

plt.savefig(FIG_PNG, dpi=300, bbox_inches="tight")
plt.show()

print("✓ Figura guardada:")
print(FIG_PNG)
print("✓ Selection CSV:")
print(SEL_CSV)