### Dependencies

In [1]:
# Cell 0 — ONLY if the runtime has just started
!pip install -q huggingface_hub==0.23.0 transformers==4.39.3 diffusers==0.27.2 peft==0.10.0
!pip install -q insightface onnxruntime-gpu onnx onnx2torch
!pip install -q git+https://github.com/tencent-ailab/IP-Adapter.git

print("✓ Libraries installed")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.2/401.2 kB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 82.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 41.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 71.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.0.0 requires huggingface-hub>=0.24.0, but you have huggingface-hub 0.23.0 which is incompatible.
sentence-transformers 5.4.1 requires transformers<6.0.0,>=4.41.0, but you have transformers 4.39.3 which is incompatible.
gradio 5.50.0 requires huggingface-hub<2.0,>=0.33.5, but you have huggingface-hub 0.23.0 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 9.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 277.0/277.0 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 101.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.0/81.0 kB 8.4 MB/s eta 0:00:00
  Building wheel for insightface (pyproject.toml) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for ip-adapter (pyproject.toml) ... done
✓ Libraries installed

### Drive

In [2]:
# ============================================================
# Cell 1 — Drive, paths and src
# ============================================================

from google.colab import drive
drive.mount("/content/drive")

import os, sys, shutil, importlib, torch
from collections import Counter

DRIVE = "/content/drive/MyDrive/Notebook4"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE = torch.float16

print("DEVICE:", DEVICE)
print("DTYPE:", DTYPE)
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NO GPU")
print("DRIVE:", DRIVE)

# Recargar src desde Drive
if os.path.exists("/content/src"):
    shutil.rmtree("/content/src")

shutil.copytree(f"{DRIVE}/src", "/content/src")

if "/content" not in sys.path:
    sys.path.insert(0, "/content")

for m in list(sys.modules.keys()):
    if m.startswith("src"):
        del sys.modules[m]

importlib.invalidate_caches()

from src.bap2 import BAP2
from src.att2 import attach_bap2

print("✓ src recargado")
print("BAP2:", BAP2)
print("attach_bap2:", attach_bap2)

Mounted at /content/drive
DEVICE: cuda
DTYPE: torch.float16
GPU: Tesla T4
DRIVE: /content/drive/MyDrive/Notebook4
✓ src recargado
BAP2: <class 'src.bap2.BAP2'>
attach_bap2: <function attach_bap2 at 0x7c12310814e0>

## Models

### Stable Diffusion

In [3]:
# Cell 3 - StableDiffusionPipeline

from diffusers import StableDiffusionPipeline, DDIMScheduler, AutoencoderKL
from huggingface_hub import hf_hub_download
from ip_adapter.ip_adapter_faceid import IPAdapterFaceID

DEVICE = "cuda"
DTYPE = torch.float16

vae = AutoencoderKL.from_pretrained(
    "stabilityai/sd-vae-ft-mse",
    torch_dtype=DTYPE
).to(DEVICE)

pipe = StableDiffusionPipeline.from_pretrained(
    "SG161222/Realistic_Vision_V4.0_noVAE",
    vae=vae,
    torch_dtype=DTYPE,
    safety_checker=None
).to(DEVICE)

pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)

ip_ckpt = hf_hub_download(
    repo_id="h94/IP-Adapter-FaceID",
    filename="ip-adapter-faceid_sd15.bin"
)

print("✓ pipeline limpio")
print(type(pipe.unet))

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/547 [00:00<?, ?B/s]

diffusion_pytorch_model.safetensors:   0%|          | 0.00/335M [00:00<?, ?B/s]

model_index.json:   0%|          | 0.00/609 [00:00<?, ?B/s]

Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]

vocab.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/472 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/737 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/492M [00:00<?, ?B/s]

scheduler_config.json:   0%|          | 0.00/548 [00:00<?, ?B/s]

diffusion_pytorch_model.safetensors:   0%|          | 0.00/3.44G [00:00<?, ?B/s]

Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]

ip-adapter-faceid_sd15.bin:   0%|          | 0.00/96.7M [00:00<?, ?B/s]

✓ pipeline limpio
<class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'>

### ArcFace

In [4]:
# Cell 4 — ArcFace PyTorch
import onnx, onnx2torch
from insightface.app import FaceAnalysis

# Initialize insightface so it downloads buffalo_l
app = FaceAnalysis(name="buffalo_l", providers=["CUDAExecutionProvider"])
app.prepare(ctx_id=0, det_size=(320, 320))

# Convertir ONNX → PyTorch (gotcha 13.14: .float() obligatorio)
ONNX_PATH = "/root/.insightface/models/buffalo_l/w600k_r50.onnx"
onnx_model = onnx.load(ONNX_PATH)
arcface_torch = onnx2torch.convert(onnx_model).to(DEVICE).eval()
arcface_torch = arcface_torch.float()  # buffers + params a fp32

for p in arcface_torch.parameters():
    p.requires_grad = False

print("✓ ArcFace loaded and converted to PyTorch")
print(f"  Parameters: {sum(p.numel() for p in arcface_torch.parameters()):,}")
print(f"  requires_grad on any param: {any(p.requires_grad for p in arcface_torch.parameters())}")
print(f"  VRAM usada: {torch.cuda.memory_allocated()/1e9:.2f} GB")

download_path: /root/.insightface/models/buffalo_l
Downloading /root/.insightface/models/buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...

100%|██████████| 281857/281857 [00:03<00:00, 71115.42KB/s]

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'sdpa_kernel': '0', 'use_tf32': '1', 'fuse_conv_bias': '0', 'prefer_nhwc': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_enable': '0', 'use_ep_level_unified_stream': '0', 'device_id': '0', 'has_user_compute_stream': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'user_compute_stream': '0', 'cudnn_conv_use_max_workspace': '1'}}
find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'sdpa_kernel': '0', 'use_tf32': '1', 'fuse_conv_bias': '0', 'prefer_nhwc': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_enable': '0', 'use_ep_level_unified_stream': '0', 'device_id': '0', 'has_user_compute_stream': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'user_compute_stream': '0', 'cudnn_conv_use_max_workspace': '1'}}
find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'sdpa_kernel': '0', 'use_tf32': '1', 'fuse_conv_bias': '0', 'prefer_nhwc': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_enable': '0', 'use_ep_level_unified_stream': '0', 'device_id': '0', 'has_user_compute_stream': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'user_compute_stream': '0', 'cudnn_conv_use_max_workspace': '1'}}
find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'sdpa_kernel': '0', 'use_tf32': '1', 'fuse_conv_bias': '0', 'prefer_nhwc': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_enable': '0', 'use_ep_level_unified_stream': '0', 'device_id': '0', 'has_user_compute_stream': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'user_compute_stream': '0', 'cudnn_conv_use_max_workspace': '1'}}
find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'sdpa_kernel': '0', 'use_tf32': '1', 'fuse_conv_bias': '0', 'prefer_nhwc': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_enable': '0', 'use_ep_level_unified_stream': '0', 'device_id': '0', 'has_user_compute_stream': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'user_compute_stream': '0', 'cudnn_conv_use_max_workspace': '1'}}
find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (320, 320)
✓ ArcFace loaded and converted to PyTorch
  Parameters: 43,572,288
  requires_grad on any param: False
  VRAM usada: 2.35 GB

### IP-Adapter

In [5]:
# Cell 5 - IPAdapterFaceID

ip_model = IPAdapterFaceID(
    pipe,
    ip_ckpt,
    device=DEVICE,
    num_tokens=4
)

ip_model.image_proj_model = ip_model.image_proj_model.to(dtype=DTYPE)

print("✓ Official IP-Adapter loaded")
print("processors:", len(pipe.unet.attn_processors))
print(type(pipe.unet))

from collections import Counter

types = Counter(type(proc).__name__ for proc in pipe.unet.attn_processors.values())

print("\nProcessors after IP-Adapter:")
for k, v in types.items():
    print(k, ":", v)

n_ip = 0
for name, proc in pipe.unet.attn_processors.items():
    if hasattr(proc, "to_k_ip") and hasattr(proc, "to_v_ip"):
        n_ip += 1

print("\nProcessors with to_k_ip/to_v_ip:", n_ip)
assert n_ip == 16, "IP-Adapter was not installed correctly: expected 16 processors with to_k_ip/to_v_ip"

/usr/local/lib/python3.12/dist-packages/diffusers/models/lora.py:208: FutureWarning: `LoRALinearLayer` is deprecated and will be removed in version 1.0.0. Use of `LoRALinearLayer` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRALinearLayer", "1.0.0", deprecation_message)

✓ Official IP-Adapter loaded
processors: 32
<class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'>

Processors after IP-Adapter:
LoRAAttnProcessor2_0 : 16
LoRAIPAttnProcessor2_0 : 16

Processors with to_k_ip/to_v_ip: 16

### Dataset

In [6]:
# ============================================================
# Cell — Dataset + DataLoaders
# ============================================================

import os
import pickle
import pandas as pd
from torch.utils.data import DataLoader
from src.dataset import FIWTriadsDataset

EMBEDDINGS_PATH = f"{DRIVE}/data/embeddings/arcface_insightface.pkl"
FIW_ROOT        = f"{DRIVE}/data/raw/FIDs"
TRAIN_CSV       = f"{DRIVE}/data/splits/train_identity.csv"
VAL_CSV         = f"{DRIVE}/data/splits/val_identity.csv"
AGES_CSV        = f"{DRIVE}/data/ages/mivolo_ages.csv"
GENDER_CACHE    = f"{DRIVE}/data/gender_dict.pkl"
TEST_CSV = f"{DRIVE}/data/splits/test_identity.csv"

with open(EMBEDDINGS_PATH, "rb") as f:
    embeddings = pickle.load(f)

with open(GENDER_CACHE, "rb") as f:
    gender_dict = pickle.load(f)

ages_path = AGES_CSV if os.path.exists(AGES_CSV) else None

train_ds = FIWTriadsDataset(
    csv_path=TRAIN_CSV,
    embeddings=embeddings,
    fiw_root=FIW_ROOT,
    gender_dict=gender_dict,
    ages_csv_path=ages_path,
)

val_ds = FIWTriadsDataset(
    csv_path=VAL_CSV,
    embeddings=embeddings,
    fiw_root=FIW_ROOT,
    gender_dict=gender_dict,
    ages_csv_path=ages_path,
)

test_ds = FIWTriadsDataset(
    csv_path=TEST_CSV,
    embeddings=embeddings,
    fiw_root=FIW_ROOT,
    gender_dict=gender_dict,
    ages_csv_path=ages_path,
)

test_loader = DataLoader(
    test_ds,
    batch_size=1,
    shuffle=False,
    num_workers=0,
    pin_memory=False,
)

train_loader = DataLoader(
    train_ds,
    batch_size=1,
    shuffle=True,
    num_workers=0,
    pin_memory=False,
)

val_loader = DataLoader(
    val_ds,
    batch_size=1,
    shuffle=False,
    num_workers=0,
    pin_memory=False,
)

print(f"✓ Train: {len(train_ds):,} triads")
print(f"✓ Val:   {len(val_ds):,} triads")
print(f"✓ Test:  {len(test_ds):,} triads")

sample = test_ds[0]
print("Keys sample:", sample.keys())
print("img:", sample["img"].shape)
print("h_c:", sample["h_c"].shape)
print("age:", sample["age"])
print("gender:", sample["gender"])
print("key_p:", sample.get("key_p", "N/A"))
print("key_m:", sample.get("key_m", "N/A"))
print("key_c:", sample.get("key_c", "N/A"))

✓ Train: 1,563 triads
✓ Val:   196 triads
✓ Test:  208 triads
Keys sample: dict_keys(['h_p', 'h_m', 'h_c', 'img', 'age', 'gender', 'key_p', 'key_m', 'key_c'])
img: torch.Size([3, 512, 512])
h_c: torch.Size([512])
age: 43
gender: woman
key_p: F0003/MID2/P00019_face2.jpg
key_m: F0003/MID3/P00022_face1.jpg
key_c: F0003/MID1/P00019_face1.jpg

### Reload

In [ ]:
import os, sys, shutil, importlib

if os.path.exists("/content/src"):
    shutil.rmtree("/content/src")

shutil.copytree(f"{DRIVE}/src", "/content/src")

if "/content" not in sys.path:
    sys.path.insert(0, "/content")

for m in list(sys.modules.keys()):
    if m.startswith("src"):
        del sys.modules[m]

importlib.invalidate_caches()

from src.bap2 import BAP2
from src.att2 import attach_bap2

print("✓ BAP2 and att2 imported correctly")
print(BAP2)
print(attach_bap2)

### Attach

In [7]:
# ============================================================
# Re-attach BAP2 lineal + sanity check
# ============================================================


from src.bap2 import BAP2
from src.att2 import attach_bap2

print("✓ src recargado")
print("BAP2:", BAP2)
print("attach_bap2:", attach_bap2)

# Instalar BAP2 lineal
bap2_modules = attach_bap2(
    pipe.unet,
    num_tokens=4,
    scale=1.0,
    child_scale=1.0,
    parent_scale=0.1,
    gate_groups=16,
    gate_hidden=256,   # ignored by the linear BAP2 gate
    temperature=1.0,
    device=DEVICE,
    dtype=DTYPE,
    copy_ip_weights=True,
)

print("\n✓ attach BAP2 lineal terminado")
print("BAP2 modules:", len(bap2_modules))

# Contar processors
types = Counter(type(proc).__name__ for proc in pipe.unet.attn_processors.values())

print("\nProcessors actuales:")
for k, v in types.items():
    print(k, ":", v)

# Check dtype, parameters and alpha
gate_dtypes = Counter()
total_gate_params = 0
max_abs_w = 0.0
max_abs_b = 0.0

for name, proc in bap2_modules.items():
    gate_dtypes[str(proc.gate.weight.dtype)] += 1
    total_gate_params += sum(p.numel() for p in proc.gate.parameters())

    max_abs_w = max(
        max_abs_w,
        proc.gate.weight.detach().abs().max().float().item()
    )
    max_abs_b = max(
        max_abs_b,
        proc.gate.bias.detach().abs().max().float().item()
    )

print("\nDtypes gate.weight:")
for k, v in gate_dtypes.items():
    print(k, ":", v)

print("\nGate params totales:", total_gate_params)

print("\nGate initialization:")
print("max |W|:", max_abs_w)
print("max |b|:", max_abs_b)

# Dummy alpha of the first module
with torch.no_grad():
    first_name, first_proc = next(iter(bap2_modules.items()))

    in_features = first_proc.gate.in_features

    dummy = torch.randn(
        1,
        in_features,
        device=DEVICE,
        dtype=torch.float32,
    )

    alpha = torch.sigmoid(first_proc.gate(dummy))

print("\nDummy alpha, first module:")
print("module:", first_name)
print("gate input dim:", in_features)
print("alpha shape:", alpha.shape)
print("alpha mean:", alpha.mean().item())
print("alpha min :", alpha.min().item())
print("alpha max :", alpha.max().item())

print("\nVRAM usada:", torch.cuda.memory_allocated() / 1e9, "GB")

if (
    len(bap2_modules) == 16
    and str(first_proc.gate.weight.dtype) == "torch.float32"
    and max_abs_w == 0.0
    and max_abs_b == 0.0
):
    print("\n✓ Sanity check BAP2 lineal OK")
else:
    print("\n⚠ Check the linear BAP2 before continuing")

✓ src recargado
BAP2: <class 'src.bap2.BAP2'>
attach_bap2: <function attach_bap2 at 0x7c12310814e0>
✓ BAP2 instalado
  attn2 reemplazados:      16
  attn1/intactos:          16
  pesos copiados desde IP: 16/16
  pesos copiados desde BAP:0/16
  child_scale:             1.0
  parent_scale:            0.1
  gate_groups:             16
  gate_hidden:             256
  temperature:             1.0
  alpha inicial esperado:  0.5
  gate dtype esperado:     float32

✓ attach BAP2 lineal terminado
BAP2 modules: 16

Processors actuales:
LoRAAttnProcessor2_0 : 16
BAP2 : 16

Dtypes gate.weight:
torch.float32 : 16

Gate params totales: 792832

Gate initialization:
max |W|: 0.0
max |b|: 0.0

Dummy alpha, first module:
module: down_blocks_0_attentions_0_transformer_blocks_0_attn2
gate input dim: 2176
alpha shape: torch.Size([1, 16])
alpha mean: 0.5
alpha min : 0.5
alpha max : 0.5

VRAM usada: 2.50650624 GB

✓ Sanity check BAP2 lineal OK

### Load checkpoint

In [ ]:
# ============================================================
# Cell 7 — Load the latest BAP2 checkpoint + checks
# Requiere:
# bap2_modules, DEVICE, DRIVE
# ============================================================

import os, glob, torch
import pandas as pd

# ============================================================
# Use step600 DIRECTLY
# ============================================================

BAP2_CKPT_PATH = (
    f"{DRIVE}/results/child_anchor_bap_gate/"
    "bap2_linear_continue_step500_to_1000_lr1e-4/"
    "bap2_s600.pt"
)

print("Checkpoint seleccionado:")
print(BAP2_CKPT_PATH)
print("Existe:", os.path.exists(BAP2_CKPT_PATH))

assert os.path.exists(BAP2_CKPT_PATH), "BAP2 checkpoint does not exist."

# ------------------------------------------------------------
# 2. Load checkpoint
# ------------------------------------------------------------

ckpt = torch.load(BAP2_CKPT_PATH, map_location=DEVICE)

print("\nClaves checkpoint:", ckpt.keys())
print("Step checkpoint:", ckpt.get("step", "N/A"))

assert "bap2_gate_state" in ckpt, "The checkpoint has no bap2_gate_state."

gate_state = ckpt["bap2_gate_state"]

loaded = 0
missing_names = []

for name, proc in bap2_modules.items():
    if name in gate_state:
        proc.gate.load_state_dict(gate_state[name])
        proc.gate.to(device=DEVICE)
        proc.gate.float()
        loaded += 1
    else:
        missing_names.append(name)

print("\nGates loaded:", loaded, "/", len(bap2_modules))

if missing_names:
    print("Modules without state in checkpoint:")
    for n in missing_names:
        print(" -", n)

assert loaded == len(bap2_modules), "Not all BAP2 gates were loaded."

START_STEP = int(ckpt["step"])
TARGET_STEP = 1000

print("\nSTART_STEP:", START_STEP)
print("TARGET_STEP:", TARGET_STEP)

# ------------------------------------------------------------
# 3. Check parameters
# ------------------------------------------------------------

dtype_set = set()
nan_count = 0
max_abs = 0.0
param_std_vals = []

for name, proc in bap2_modules.items():
    dtype_set.add(str(proc.gate.weight.dtype))

    for p in proc.gate.parameters():
        nan_count += torch.isnan(p).sum().item()
        max_abs = max(max_abs, p.detach().abs().max().float().item())
        param_std_vals.append(p.detach().float().std().item())

print("\nParameter check:")
print("Dtypes gate:", dtype_set)
print("NaNs in gate:", nan_count)
print("max_abs gate params:", max_abs)
print("std promedio params:", sum(param_std_vals) / len(param_std_vals))

assert dtype_set == {"torch.float32"}, "The gate is not float32."
assert nan_count == 0, "There are NaNs in the gate parameters."
assert max_abs > 0.0, "The gate looks reset; the checkpoint did not load correctly."

# ------------------------------------------------------------
# 4. Verificar alpha dummy
# ------------------------------------------------------------

with torch.no_grad():
    first_name, first_proc = next(iter(bap2_modules.items()))

    dummy = torch.randn(
        1,
        first_proc.gate.in_features,
        device=DEVICE,
        dtype=torch.float32,
    )

    alpha = torch.sigmoid(first_proc.gate(dummy))

print("\nAlpha dummy checkpoint:")
print("module:", first_name)
print("alpha mean:", alpha.mean().item())
print("alpha min :", alpha.min().item())
print("alpha max :", alpha.max().item())
print("alpha std :", alpha.std().item())
print("alpha has NaN:", torch.isnan(alpha).any().item())

assert not torch.isnan(alpha).any().item(), "Alpha dummy tiene NaN."

# ------------------------------------------------------------
# 5. Load previous BAP2 λ=0.1 evaluation if it exists
# ------------------------------------------------------------

# ============================================================
# Use step600 DIRECTLY
# ============================================================

BAP2_CKPT_PATH = (
    f"{DRIVE}/results/child_anchor_bap_gate/"
    "bap2_linear_continue_step500_to_1000_lr1e-4/"
    "bap2_s600.pt"
)

# ------------------------------------------------------------
# 6. Verificar dataset
# ------------------------------------------------------------

required = ["train_ds", "val_ds"]
missing = [x for x in required if x not in globals()]
if missing:
    raise RuntimeError(f"Faltan datasets: {missing}")

sample = train_ds[0]

print("\nSample train_ds[0] keys:", sample.keys())
print("h_c:", sample["h_c"].shape)
print("h_p:", sample["h_p"].shape)
print("h_m:", sample["h_m"].shape)
print("img:", sample["img"].shape)
print("gender:", sample.get("gender", "N/A"))
print("age:", sample.get("age", "N/A"))

print("\n ALL OK: BAP2 checkpoint loaded and ready for training/evaluation.")

Checkpoint seleccionado:
/content/drive/MyDrive/Notebook4/results/child_anchor_bap_gate/bap2_linear_continue_step500_to_1000_lr1e-4/bap2_s600.pt
Existe: True

Claves checkpoint: dict_keys(['bap2_gate_state', 'step', 'config', 'logs'])
Step checkpoint: 600

Gates loaded: 16 / 16

START_STEP: 600
TARGET_STEP: 800

Parameter check:
Dtypes gate: {'torch.float32'}
NaNs in gate: 0
max_abs gate params: 0.00423230417072773
std promedio params: 0.0004358860115871721

Alpha dummy checkpoint:
module: down_blocks_0_attentions_0_transformer_blocks_0_attn2
alpha mean: 0.5001251101493835
alpha min : 0.49978432059288025
alpha max : 0.5015527606010437
alpha std : 0.0004014701407868415
alpha has NaN: False

Sample train_ds[0] keys: dict_keys(['h_p', 'h_m', 'h_c', 'img', 'age', 'gender', 'key_p', 'key_m', 'key_c'])
h_c: torch.Size([512])
h_p: torch.Size([512])
h_m: torch.Size([512])
img: torch.Size([3, 512, 512])
gender: man
age: 35

 ALL OK: BAP2 checkpoint loaded and ready for training/evaluation.

### Training

In [8]:
# ============================================================
# ENTRENAMIENTO FINAL BAP2 — step1000 → step4689
# 3 effective epochs over train_ds
#
# train_ds = 1563 triads
# batch_size = 1
# 1 epoch efectiva = 1563 steps
# 3 epochs efectivas = 4689 steps
#
# Trainable: ONLY the Heredity Gate
# Loss: L_diff
# ============================================================

import os
import torch
import torch.nn.functional as F
import pandas as pd
from tqdm.auto import tqdm
from datetime import datetime

# ------------------------------------------------------------
# Main configuration
# ------------------------------------------------------------

CKPT_START = f"{DRIVE}/results/ckpt/bap2_s1000.pt"

RUN_NAME = "bap2_4689"
OUT_DIR = f"{DRIVE}/results/ckpt/{RUN_NAME}"
os.makedirs(OUT_DIR, exist_ok=True)

LOGS_PATH = f"{OUT_DIR}/logs.csv"

START_STEP_EXPECTED = 1000
TARGET_STEP = 4689

SAVE_STEPS = {1563, 3126, 4689}
LOG_EVERY = 10

LR_BAP2 = 1e-4
WEIGHT_DECAY = 0.0
ADAM_EPS = 1e-6
MAX_GRAD_NORM = 1.0

PARENT_SCALE_TRAIN = 0.1

print("CKPT_START:", CKPT_START)
print("Existe:", os.path.exists(CKPT_START))
print("OUT_DIR:", OUT_DIR)
print("TARGET_STEP:", TARGET_STEP)
print("SAVE_STEPS:", SAVE_STEPS)

assert os.path.exists(CKPT_START), "The step1000 checkpoint does not exist."
assert "train_loader" in globals(), "Falta train_loader."
assert "bap2_modules" in globals(), "Falta bap2_modules."
assert len(bap2_modules) == 16, "bap2_modules must have 16 modules."

# ------------------------------------------------------------
# Load the step1000 checkpoint
# ------------------------------------------------------------

ckpt = torch.load(CKPT_START, map_location=DEVICE)

assert "bap2_gate_state" in ckpt, "Checkpoint without bap2_gate_state."
assert int(ckpt["step"]) == START_STEP_EXPECTED, f"Expected step1000, got {ckpt['step']}."

gate_state = ckpt["bap2_gate_state"]

loaded = 0
for name, proc in bap2_modules.items():
    assert name in gate_state, f"Missing gate_state for {name}"
    proc.gate.load_state_dict(gate_state[name])
    proc.gate.to(DEVICE)
    proc.gate.float()
    loaded += 1

print(f"✓ Cargado step{ckpt['step']} | gates {loaded}/{len(bap2_modules)}")

START_STEP = int(ckpt["step"])
CURRENT_STEP = START_STEP

# ------------------------------------------------------------
# Congelar todo excepto gate
# ------------------------------------------------------------

pipe.unet.train()
pipe.vae.eval()
pipe.text_encoder.eval()
ip_model.image_proj_model.eval()

for p in pipe.unet.parameters():
    p.requires_grad = False

for p in pipe.vae.parameters():
    p.requires_grad = False

for p in pipe.text_encoder.parameters():
    p.requires_grad = False

for p in ip_model.image_proj_model.parameters():
    p.requires_grad = False

bap2_gate_params = []

for name, proc in bap2_modules.items():
    proc.gate.float()
    for p in proc.gate.parameters():
        p.requires_grad = True
        bap2_gate_params.append(p)

print("Gate params entrenables:", sum(p.numel() for p in bap2_gate_params))
print("dtype gate example:", bap2_gate_params[0].dtype)

optimizer = torch.optim.AdamW(
    bap2_gate_params,
    lr=LR_BAP2,
    eps=ADAM_EPS,
    weight_decay=WEIGHT_DECAY,
)

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

def ensure_2d(x):
    if x.ndim == 1:
        x = x.unsqueeze(0)
    return x

def set_parent_scale_bap2(unet, value):
    for proc in unet.attn_processors.values():
        if type(proc).__name__ == "BAP2":
            proc.parent_scale = value

def collect_bap2_alpha_stats():
    vals = []

    for name, proc in bap2_modules.items():
        if getattr(proc, "last_alpha", None) is not None:
            vals.append(proc.last_alpha.detach().float().cpu())

    if len(vals) == 0:
        return {
            "alpha_mean": None,
            "alpha_min": None,
            "alpha_max": None,
            "alpha_std": None,
            "alpha_has_nan": None,
        }

    x = torch.cat(vals, dim=0)

    return {
        "alpha_mean": x.mean().item(),
        "alpha_min": x.min().item(),
        "alpha_max": x.max().item(),
        "alpha_std": x.std().item(),
        "alpha_has_nan": torch.isnan(x).any().item(),
    }

def bap2_param_stats():
    vals = []

    for name, proc in bap2_modules.items():
        for p in proc.gate.parameters():
            vals.append(p.detach().float().flatten().cpu())

    x = torch.cat(vals)

    return {
        "gate_param_mean": x.mean().item(),
        "gate_param_std": x.std().item(),
        "gate_param_max_abs": x.abs().max().item(),
        "gate_param_has_nan": torch.isnan(x).any().item(),
    }

def build_prompts(batch):
    ages = batch["age"]
    genders = batch["gender"]

    if torch.is_tensor(ages):
        ages = ages.detach().cpu().tolist()

    if isinstance(genders, str):
        genders = [genders]

    prompts = []

    for gender, age in zip(genders, ages):
        if gender not in ["man", "woman", "person"]:
            gender = "person"

        prompts.append(
            f"portrait photo of a {gender}, age {int(age)}, realistic, neutral expression"
        )

    return prompts

def train_step_bap2(batch):
    img = batch["img"].to(device=DEVICE, dtype=DTYPE)

    h_c = ensure_2d(batch["h_c"].to(device=DEVICE, dtype=DTYPE))
    h_p = ensure_2d(batch["h_p"].to(device=DEVICE, dtype=DTYPE))
    h_m = ensure_2d(batch["h_m"].to(device=DEVICE, dtype=DTYPE))

    prompts = build_prompts(batch)

    set_parent_scale_bap2(pipe.unet, PARENT_SCALE_TRAIN)

    with torch.no_grad():
        latents = pipe.vae.encode(img).latent_dist.sample()
        latents = latents * pipe.vae.config.scaling_factor

        noise = torch.randn_like(latents)

        timesteps = torch.randint(
            low=0,
            high=pipe.scheduler.config.num_train_timesteps,
            size=(latents.shape[0],),
            device=DEVICE,
        ).long()

        noisy_latents = pipe.scheduler.add_noise(latents, noise, timesteps)

        child_tokens = ip_model.image_proj_model(h_c)
        father_tokens = ip_model.image_proj_model(h_p)
        mother_tokens = ip_model.image_proj_model(h_m)

        prompt_embeds, _ = pipe.encode_prompt(
            prompt=prompts,
            device=DEVICE,
            num_images_per_prompt=1,
            do_classifier_free_guidance=False,
        )

        encoder_hidden_states = torch.cat(
            [prompt_embeds, child_tokens, father_tokens, mother_tokens],
            dim=1,
        )

    noise_pred = pipe.unet(
        noisy_latents,
        timesteps,
        encoder_hidden_states=encoder_hidden_states,
    ).sample

    loss = F.mse_loss(noise_pred.float(), noise.float())

    return loss

def save_bap2_checkpoint(global_step, logs):
    bap2_gate_state = {
        name: proc.gate.state_dict()
        for name, proc in bap2_modules.items()
    }

    ckpt_path = f"{OUT_DIR}/bap2_linear_step{global_step}.pt"

    torch.save(
        {
            "bap2_gate_state": bap2_gate_state,
            "step": int(global_step),
            "config": {
                "run_name": RUN_NAME,
                "loss": "L_diff",
                "start_step": START_STEP,
                "target_step": TARGET_STEP,
                "effective_epochs_target": TARGET_STEP / len(train_ds),
                "train_size": len(train_ds),
                "batch_size": 1,
                "lr_bap2": LR_BAP2,
                "adam_eps": ADAM_EPS,
                "weight_decay": WEIGHT_DECAY,
                "max_grad_norm": MAX_GRAD_NORM,
                "parent_scale": PARENT_SCALE_TRAIN,
                "child_scale": 1.0,
                "gate": "contextual_linear",
                "gate_dtype": "float32",
                "trainable": "gate_only",
                "timestamp": datetime.now().isoformat(),
            },
            "logs": logs,
        },
        ckpt_path,
    )

    return ckpt_path

# ------------------------------------------------------------
# Resume logs if they exist
# Note: this does NOT resume the optimizer, it only avoids losing logs.
# To resume from another checkpoint, load it manually.
# ------------------------------------------------------------

logs_continue = []
global_step = START_STEP

print("\nEntrenamiento:")
print("START_STEP:", START_STEP)
print("TARGET_STEP:", TARGET_STEP)
print("epochs efectivas objetivo:", TARGET_STEP / len(train_ds))

loader_iter = iter(train_loader)

pbar = tqdm(total=TARGET_STEP - START_STEP)

# ------------------------------------------------------------
# Loop principal
# ------------------------------------------------------------

while global_step < TARGET_STEP:

    try:
        batch = next(loader_iter)
    except StopIteration:
        loader_iter = iter(train_loader)
        batch = next(loader_iter)

    batch = {
        k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
        for k, v in batch.items()
    }

    optimizer.zero_grad(set_to_none=True)

    loss = train_step_bap2(batch)

    if not torch.isfinite(loss):
        print("⚠ Non-finite loss at step", global_step + 1, "loss:", loss.item())
        break

    loss.backward()

    grad_norm = torch.nn.utils.clip_grad_norm_(
        bap2_gate_params,
        max_norm=MAX_GRAD_NORM,
    )

    optimizer.step()

    global_step += 1

    alpha_stats = collect_bap2_alpha_stats()
    param_stats = bap2_param_stats()

    row = {
        "global_step": global_step,
        "effective_epoch": global_step / len(train_ds),
        "loss": loss.item(),
        "grad_norm": float(grad_norm),
        **alpha_stats,
        **param_stats,
    }

    logs_continue.append(row)

    if global_step % LOG_EVERY == 0 or global_step in SAVE_STEPS or global_step == START_STEP + 1:
        print(
            f"step {global_step:04d} | "
            f"epoch={global_step / len(train_ds):.3f} | "
            f"loss={loss.item():.6f} | "
            f"grad={float(grad_norm):.6e} | "
            f"alpha_mean={alpha_stats['alpha_mean']:.6f} | "
            f"alpha_std={alpha_stats['alpha_std']:.6f} | "
            f"alpha_min={alpha_stats['alpha_min']:.6f} | "
            f"alpha_max={alpha_stats['alpha_max']:.6f} | "
            f"param_max_abs={param_stats['gate_param_max_abs']:.6e}"
        )

    # ----------------------------
    # Seguridad
    # ----------------------------
    if alpha_stats["alpha_has_nan"] or param_stats["gate_param_has_nan"]:
        print("⚠ NaN detected in alpha or parameters. Stopping.")
        break

    # Allow the gate to open while avoiding extreme collapse.
    if alpha_stats["alpha_min"] < 0.20 or alpha_stats["alpha_max"] > 0.80:
        print("⚠ Gate demasiado extremo. Deteniendo.")
        print(alpha_stats)
        break

    # Evitar sesgo global fuerte hacia un progenitor.
    if alpha_stats["alpha_mean"] < 0.42 or alpha_stats["alpha_mean"] > 0.58:
        print("⚠ Global father/mother bias detected. Stopping.")
        print(alpha_stats)
        break

    # ----------------------------
    # Save at key checkpoints
    # ----------------------------
    if global_step in SAVE_STEPS:
        ckpt_path = save_bap2_checkpoint(global_step, logs_continue)
        print(f"✓ Checkpoint saved: {ckpt_path}")

    # Save logs incrementally every 50 steps
    if global_step % 50 == 0:
        pd.DataFrame(logs_continue).to_csv(LOGS_PATH, index=False)

    pbar.update(1)

pbar.close()

# ------------------------------------------------------------
# Final save
# ------------------------------------------------------------

df_logs_final_train = pd.DataFrame(logs_continue)
df_logs_final_train.to_csv(LOGS_PATH, index=False)

final_ckpt_path = save_bap2_checkpoint(global_step, logs_continue)

CURRENT_STEP = global_step
START_STEP = global_step

print("\n✓ Entrenamiento final terminado")
print("Last global_step:", global_step)
print("Epoch efectiva:", global_step / len(train_ds))
print("Logs:", LOGS_PATH)
print("Checkpoint final:", final_ckpt_path)
print("CURRENT_STEP:", CURRENT_STEP)

if len(df_logs_final_train) > 0:
    print("\nAlpha summary:")
    print("alpha_mean inicial:", df_logs_final_train.iloc[0]["alpha_mean"])
    print("alpha_mean final:  ", df_logs_final_train.iloc[-1]["alpha_mean"])
    print("alpha_std inicial: ", df_logs_final_train.iloc[0]["alpha_std"])
    print("alpha_std final:   ", df_logs_final_train.iloc[-1]["alpha_std"])
    print("alpha_min final:   ", df_logs_final_train.iloc[-1]["alpha_min"])
    print("alpha_max final:   ", df_logs_final_train.iloc[-1]["alpha_max"])

    print("\nLoss summary:")
    print("loss inicial:", df_logs_final_train.iloc[0]["loss"])
    print("loss final:  ", df_logs_final_train.iloc[-1]["loss"])

display(df_logs_final_train.tail())

CKPT_START: /content/drive/MyDrive/Notebook4/results/ckpt/bap2_s1000.pt
Existe: True
OUT_DIR: /content/drive/MyDrive/Notebook4/results/ckpt/bap2_4689
TARGET_STEP: 4689
SAVE_STEPS: {4689, 1563, 3126}
✓ Cargado step1000 | gates 16/16
Gate params entrenables: 792832
dtype gate example: torch.float32

Entrenamiento:
START_STEP: 1000
TARGET_STEP: 4689
epochs efectivas objetivo: 3.0

  0%|          | 0/3689 [00:00<?, ?it/s]

step 1001 | epoch=0.640 | loss=0.074456 | grad=1.549425e-04 | alpha_mean=0.499737 | alpha_std=0.009128 | alpha_min=0.453669 | alpha_max=0.533014 | param_max_abs=7.395222e-03
step 1010 | epoch=0.646 | loss=0.660909 | grad=9.415825e-05 | alpha_mean=0.499533 | alpha_std=0.007303 | alpha_min=0.458652 | alpha_max=0.526375 | param_max_abs=7.202412e-03
step 1020 | epoch=0.653 | loss=0.483562 | grad=1.072951e-04 | alpha_mean=0.499483 | alpha_std=0.007600 | alpha_min=0.462143 | alpha_max=0.530738 | param_max_abs=7.179497e-03
step 1030 | epoch=0.659 | loss=0.047552 | grad=3.902100e-05 | alpha_mean=0.499436 | alpha_std=0.007725 | alpha_min=0.453226 | alpha_max=0.524300 | param_max_abs=7.362105e-03
step 1040 | epoch=0.665 | loss=0.005667 | grad=5.857036e-07 | alpha_mean=0.500407 | alpha_std=0.012379 | alpha_min=0.427096 | alpha_max=0.562601 | param_max_abs=7.398665e-03
step 1050 | epoch=0.672 | loss=0.083753 | grad=1.332768e-04 | alpha_mean=0.499614 | alpha_std=0.008214 | alpha_min=0.457727 | alpha_max=0.526561 | param_max_abs=7.422734e-03
step 1060 | epoch=0.678 | loss=0.022244 | grad=3.628513e-05 | alpha_mean=0.499907 | alpha_std=0.008789 | alpha_min=0.446186 | alpha_max=0.534382 | param_max_abs=7.650595e-03
step 1070 | epoch=0.685 | loss=0.012633 | grad=2.564809e-05 | alpha_mean=0.499908 | alpha_std=0.009804 | alpha_min=0.451940 | alpha_max=0.542943 | param_max_abs=7.795538e-03
step 1080 | epoch=0.691 | loss=0.088222 | grad=1.439250e-04 | alpha_mean=0.499827 | alpha_std=0.011114 | alpha_min=0.429812 | alpha_max=0.539290 | param_max_abs=7.842555e-03
step 1090 | epoch=0.697 | loss=0.004597 | grad=0.000000e+00 | alpha_mean=0.499702 | alpha_std=0.009251 | alpha_min=0.451721 | alpha_max=0.524258 | param_max_abs=7.866920e-03
step 1100 | epoch=0.704 | loss=0.225155 | grad=8.998907e-05 | alpha_mean=0.499705 | alpha_std=0.008587 | alpha_min=0.459720 | alpha_max=0.538374 | param_max_abs=7.838490e-03
step 1110 | epoch=0.710 | loss=0.388996 | grad=1.075908e-04 | alpha_mean=0.500460 | alpha_std=0.010218 | alpha_min=0.448868 | alpha_max=0.539170 | param_max_abs=7.887616e-03
step 1120 | epoch=0.717 | loss=0.008675 | grad=1.197605e-05 | alpha_mean=0.499730 | alpha_std=0.009580 | alpha_min=0.453637 | alpha_max=0.531445 | param_max_abs=7.923551e-03
step 1130 | epoch=0.723 | loss=0.230557 | grad=1.267997e-04 | alpha_mean=0.499887 | alpha_std=0.009761 | alpha_min=0.456218 | alpha_max=0.534731 | param_max_abs=7.839693e-03
step 1140 | epoch=0.729 | loss=0.102565 | grad=1.749058e-04 | alpha_mean=0.499635 | alpha_std=0.011502 | alpha_min=0.451134 | alpha_max=0.562203 | param_max_abs=7.749204e-03
step 1150 | epoch=0.736 | loss=0.077342 | grad=9.882181e-05 | alpha_mean=0.499124 | alpha_std=0.010840 | alpha_min=0.433630 | alpha_max=0.529140 | param_max_abs=7.707417e-03
step 1160 | epoch=0.742 | loss=0.016323 | grad=4.054663e-05 | alpha_mean=0.499342 | alpha_std=0.009895 | alpha_min=0.436425 | alpha_max=0.534097 | param_max_abs=7.708340e-03
step 1170 | epoch=0.749 | loss=0.107018 | grad=1.587181e-04 | alpha_mean=0.499412 | alpha_std=0.010555 | alpha_min=0.435834 | alpha_max=0.538908 | param_max_abs=7.766060e-03
step 1180 | epoch=0.755 | loss=0.007887 | grad=2.469402e-06 | alpha_mean=0.499625 | alpha_std=0.010339 | alpha_min=0.443761 | alpha_max=0.537363 | param_max_abs=8.186323e-03
step 1190 | epoch=0.761 | loss=0.111442 | grad=1.307775e-04 | alpha_mean=0.499279 | alpha_std=0.008516 | alpha_min=0.447061 | alpha_max=0.522643 | param_max_abs=8.304914e-03
step 1200 | epoch=0.768 | loss=0.005136 | grad=1.383001e-06 | alpha_mean=0.499345 | alpha_std=0.009899 | alpha_min=0.448559 | alpha_max=0.538514 | param_max_abs=8.300235e-03
step 1210 | epoch=0.774 | loss=0.096496 | grad=6.561571e-05 | alpha_mean=0.499361 | alpha_std=0.009583 | alpha_min=0.447198 | alpha_max=0.533859 | param_max_abs=8.269311e-03
step 1220 | epoch=0.781 | loss=0.023085 | grad=3.650368e-05 | alpha_mean=0.499202 | alpha_std=0.010554 | alpha_min=0.451644 | alpha_max=0.539046 | param_max_abs=8.347748e-03
step 1230 | epoch=0.787 | loss=0.006978 | grad=1.039438e-05 | alpha_mean=0.499573 | alpha_std=0.010974 | alpha_min=0.445638 | alpha_max=0.540585 | param_max_abs=8.336514e-03
step 1240 | epoch=0.793 | loss=0.051823 | grad=1.385734e-04 | alpha_mean=0.499436 | alpha_std=0.009531 | alpha_min=0.448962 | alpha_max=0.533978 | param_max_abs=8.204055e-03
step 1250 | epoch=0.800 | loss=0.360783 | grad=1.634965e-04 | alpha_mean=0.499541 | alpha_std=0.009177 | alpha_min=0.450691 | alpha_max=0.536213 | param_max_abs=7.961738e-03
step 1260 | epoch=0.806 | loss=0.517458 | grad=1.082935e-04 | alpha_mean=0.499568 | alpha_std=0.008671 | alpha_min=0.443097 | alpha_max=0.525762 | param_max_abs=8.048365e-03
step 1270 | epoch=0.813 | loss=0.262697 | grad=1.685906e-04 | alpha_mean=0.499594 | alpha_std=0.010718 | alpha_min=0.439189 | alpha_max=0.538765 | param_max_abs=8.166810e-03
step 1280 | epoch=0.819 | loss=0.102427 | grad=1.471252e-04 | alpha_mean=0.499448 | alpha_std=0.010978 | alpha_min=0.447290 | alpha_max=0.549436 | param_max_abs=8.460253e-03
step 1290 | epoch=0.825 | loss=0.017101 | grad=5.635505e-05 | alpha_mean=0.499544 | alpha_std=0.010881 | alpha_min=0.444597 | alpha_max=0.537467 | param_max_abs=8.613976e-03
step 1300 | epoch=0.832 | loss=0.008023 | grad=8.836198e-06 | alpha_mean=0.499811 | alpha_std=0.013194 | alpha_min=0.426388 | alpha_max=0.549708 | param_max_abs=8.713786e-03
step 1310 | epoch=0.838 | loss=0.099369 | grad=6.253735e-05 | alpha_mean=0.499903 | alpha_std=0.011375 | alpha_min=0.420336 | alpha_max=0.534327 | param_max_abs=8.833951e-03
step 1320 | epoch=0.845 | loss=0.028690 | grad=5.623626e-05 | alpha_mean=0.499673 | alpha_std=0.011195 | alpha_min=0.437348 | alpha_max=0.541961 | param_max_abs=8.928796e-03
step 1330 | epoch=0.851 | loss=0.067045 | grad=9.131795e-05 | alpha_mean=0.499582 | alpha_std=0.010217 | alpha_min=0.438908 | alpha_max=0.532799 | param_max_abs=8.981801e-03
step 1340 | epoch=0.857 | loss=0.054971 | grad=1.392711e-04 | alpha_mean=0.499812 | alpha_std=0.011424 | alpha_min=0.442930 | alpha_max=0.542475 | param_max_abs=9.074922e-03
step 1350 | epoch=0.864 | loss=0.117667 | grad=1.933258e-04 | alpha_mean=0.499680 | alpha_std=0.018926 | alpha_min=0.359086 | alpha_max=0.584762 | param_max_abs=9.117328e-03
step 1360 | epoch=0.870 | loss=0.411660 | grad=1.141075e-04 | alpha_mean=0.499832 | alpha_std=0.009257 | alpha_min=0.456271 | alpha_max=0.533268 | param_max_abs=9.318054e-03
step 1370 | epoch=0.877 | loss=0.087981 | grad=1.181937e-04 | alpha_mean=0.499524 | alpha_std=0.013028 | alpha_min=0.446388 | alpha_max=0.550179 | param_max_abs=9.454433e-03
step 1380 | epoch=0.883 | loss=0.047771 | grad=7.494965e-05 | alpha_mean=0.499630 | alpha_std=0.009213 | alpha_min=0.455319 | alpha_max=0.535751 | param_max_abs=9.561305e-03
step 1390 | epoch=0.889 | loss=0.075386 | grad=1.131464e-04 | alpha_mean=0.499663 | alpha_std=0.012213 | alpha_min=0.426435 | alpha_max=0.547588 | param_max_abs=9.507285e-03
step 1400 | epoch=0.896 | loss=0.121163 | grad=1.435458e-04 | alpha_mean=0.499795 | alpha_std=0.011014 | alpha_min=0.441290 | alpha_max=0.538088 | param_max_abs=9.609094e-03
step 1410 | epoch=0.902 | loss=0.009536 | grad=1.920713e-05 | alpha_mean=0.499818 | alpha_std=0.012745 | alpha_min=0.422228 | alpha_max=0.544154 | param_max_abs=9.763588e-03
step 1420 | epoch=0.909 | loss=0.052975 | grad=4.831709e-05 | alpha_mean=0.499761 | alpha_std=0.011559 | alpha_min=0.432376 | alpha_max=0.549523 | param_max_abs=9.850144e-03
step 1430 | epoch=
... [50,605 output characters omitted] ...
m_max_abs=2.125361e-02
step 4310 | epoch=2.758 | loss=0.010104 | grad=4.383169e-05 | alpha_mean=0.497653 | alpha_std=0.028230 | alpha_min=0.345003 | alpha_max=0.613923 | param_max_abs=2.121086e-02
step 4320 | epoch=2.764 | loss=0.011208 | grad=1.792114e-06 | alpha_mean=0.499317 | alpha_std=0.027881 | alpha_min=0.385974 | alpha_max=0.655464 | param_max_abs=2.099384e-02
step 4330 | epoch=2.770 | loss=0.057523 | grad=7.564853e-05 | alpha_mean=0.499097 | alpha_std=0.026915 | alpha_min=0.357035 | alpha_max=0.627926 | param_max_abs=2.078346e-02
step 4340 | epoch=2.777 | loss=0.007628 | grad=7.965384e-07 | alpha_mean=0.497210 | alpha_std=0.031431 | alpha_min=0.351875 | alpha_max=0.696088 | param_max_abs=2.091150e-02
step 4350 | epoch=2.783 | loss=0.285465 | grad=2.000801e-04 | alpha_mean=0.499459 | alpha_std=0.023567 | alpha_min=0.408971 | alpha_max=0.616224 | param_max_abs=2.093117e-02
step 4360 | epoch=2.790 | loss=0.006533 | grad=4.517121e-07 | alpha_mean=0.497449 | alpha_std=0.031933 | alpha_min=0.336371 | alpha_max=0.617625 | param_max_abs=2.085755e-02
step 4370 | epoch=2.796 | loss=0.127318 | grad=1.319800e-04 | alpha_mean=0.498929 | alpha_std=0.024017 | alpha_min=0.387636 | alpha_max=0.626733 | param_max_abs=2.092905e-02
step 4380 | epoch=2.802 | loss=0.249118 | grad=1.074911e-04 | alpha_mean=0.498876 | alpha_std=0.023077 | alpha_min=0.401935 | alpha_max=0.593513 | param_max_abs=2.121917e-02
step 4390 | epoch=2.809 | loss=0.003809 | grad=6.257397e-07 | alpha_mean=0.498183 | alpha_std=0.028614 | alpha_min=0.385812 | alpha_max=0.643751 | param_max_abs=2.128877e-02
step 4400 | epoch=2.815 | loss=0.231338 | grad=3.933199e-04 | alpha_mean=0.497421 | alpha_std=0.025168 | alpha_min=0.373787 | alpha_max=0.618459 | param_max_abs=2.102837e-02
step 4410 | epoch=2.821 | loss=0.107229 | grad=1.319959e-04 | alpha_mean=0.497841 | alpha_std=0.022605 | alpha_min=0.385039 | alpha_max=0.584940 | param_max_abs=2.101247e-02
step 4420 | epoch=2.828 | loss=0.013369 | grad=8.377147e-06 | alpha_mean=0.495579 | alpha_std=0.032206 | alpha_min=0.339047 | alpha_max=0.619866 | param_max_abs=2.104546e-02
step 4430 | epoch=2.834 | loss=0.124033 | grad=2.020868e-04 | alpha_mean=0.498119 | alpha_std=0.030278 | alpha_min=0.337955 | alpha_max=0.665591 | param_max_abs=2.139308e-02
step 4440 | epoch=2.841 | loss=0.135739 | grad=8.842378e-05 | alpha_mean=0.500807 | alpha_std=0.032152 | alpha_min=0.322140 | alpha_max=0.698906 | param_max_abs=2.173300e-02
step 4450 | epoch=2.847 | loss=0.002936 | grad=0.000000e+00 | alpha_mean=0.499364 | alpha_std=0.027604 | alpha_min=0.376995 | alpha_max=0.610274 | param_max_abs=2.166522e-02
step 4460 | epoch=2.853 | loss=0.131716 | grad=5.313575e-05 | alpha_mean=0.498438 | alpha_std=0.024397 | alpha_min=0.360473 | alpha_max=0.604507 | param_max_abs=2.144966e-02
step 4470 | epoch=2.860 | loss=0.624861 | grad=9.513009e-05 | alpha_mean=0.499037 | alpha_std=0.025306 | alpha_min=0.397709 | alpha_max=0.661222 | param_max_abs=2.131944e-02
step 4480 | epoch=2.866 | loss=0.003867 | grad=2.405284e-07 | alpha_mean=0.498282 | alpha_std=0.028950 | alpha_min=0.361818 | alpha_max=0.612137 | param_max_abs=2.128590e-02
step 4490 | epoch=2.873 | loss=0.376652 | grad=6.903571e-05 | alpha_mean=0.497071 | alpha_std=0.024381 | alpha_min=0.399675 | alpha_max=0.595675 | param_max_abs=2.119348e-02
step 4500 | epoch=2.879 | loss=0.052990 | grad=8.260678e-05 | alpha_mean=0.498106 | alpha_std=0.028112 | alpha_min=0.372562 | alpha_max=0.613388 | param_max_abs=2.122513e-02
step 4510 | epoch=2.885 | loss=0.029045 | grad=1.045175e-04 | alpha_mean=0.498918 | alpha_std=0.033043 | alpha_min=0.359018 | alpha_max=0.675815 | param_max_abs=2.125790e-02
step 4520 | epoch=2.892 | loss=0.033080 | grad=6.180237e-05 | alpha_mean=0.498649 | alpha_std=0.030731 | alpha_min=0.362086 | alpha_max=0.657741 | param_max_abs=2.131011e-02
step 4530 | epoch=2.898 | loss=0.388606 | grad=7.363319e-05 | alpha_mean=0.498036 | alpha_std=0.023963 | alpha_min=0.396441 | alpha_max=0.637786 | param_max_abs=2.133618e-02
step 4540 | epoch=2.905 | loss=0.025389 | grad=9.271333e-05 | alpha_mean=0.499128 | alpha_std=0.027313 | alpha_min=0.359652 | alpha_max=0.653200 | param_max_abs=2.139164e-02
step 4550 | epoch=2.911 | loss=0.014839 | grad=4.763870e-05 | alpha_mean=0.499072 | alpha_std=0.031239 | alpha_min=0.356672 | alpha_max=0.661818 | param_max_abs=2.149028e-02
step 4560 | epoch=2.917 | loss=0.259086 | grad=1.003091e-04 | alpha_mean=0.498811 | alpha_std=0.024016 | alpha_min=0.383527 | alpha_max=0.649353 | param_max_abs=2.168461e-02
step 4570 | epoch=2.924 | loss=0.330411 | grad=1.916418e-04 | alpha_mean=0.498850 | alpha_std=0.025539 | alpha_min=0.364273 | alpha_max=0.618171 | param_max_abs=2.194475e-02
step 4580 | epoch=2.930 | loss=0.842905 | grad=9.018179e-05 | alpha_mean=0.498003 | alpha_std=0.025358 | alpha_min=0.377399 | alpha_max=0.620314 | param_max_abs=2.200832e-02
step 4590 | epoch=2.937 | loss=0.019943 | grad=4.213489e-05 | alpha_mean=0.496571 | alpha_std=0.030090 | alpha_min=0.348827 | alpha_max=0.621266 | param_max_abs=2.203882e-02
step 4600 | epoch=2.943 | loss=0.011201 | grad=2.227794e-05 | alpha_mean=0.498267 | alpha_std=0.028968 | alpha_min=0.360661 | alpha_max=0.635606 | param_max_abs=2.208424e-02
step 4610 | epoch=2.949 | loss=0.014130 | grad=3.820960e-05 | alpha_mean=0.498133 | alpha_std=0.028996 | alpha_min=0.352534 | alpha_max=0.658449 | param_max_abs=2.201835e-02
step 4620 | epoch=2.956 | loss=0.208536 | grad=1.352013e-04 | alpha_mean=0.497888 | alpha_std=0.028242 | alpha_min=0.354982 | alpha_max=0.631044 | param_max_abs=2.196178e-02
step 4630 | epoch=2.962 | loss=0.018242 | grad=4.993973e-05 | alpha_mean=0.498585 | alpha_std=0.030881 | alpha_min=0.370075 | alpha_max=0.649521 | param_max_abs=2.186790e-02
step 4640 | epoch=2.969 | loss=0.063420 | grad=6.949683e-05 | alpha_mean=0.498168 | alpha_std=0.033839 | alpha_min=0.275591 | alpha_max=0.639934 | param_max_abs=2.171154e-02
step 4650 | epoch=2.975 | loss=0.019995 | grad=2.386069e-05 | alpha_mean=0.498245 | alpha_std=0.030750 | alpha_min=0.345871 | alpha_max=0.626078 | param_max_abs=2.172559e-02
step 4660 | epoch=2.981 | loss=0.017551 | grad=3.881157e-05 | alpha_mean=0.497222 | alpha_std=0.032981 | alpha_min=0.322024 | alpha_max=0.666641 | param_max_abs=2.189552e-02
step 4670 | epoch=2.988 | loss=0.524611 | grad=1.621512e-04 | alpha_mean=0.498942 | alpha_std=0.031237 | alpha_min=0.279868 | alpha_max=0.622264 | param_max_abs=2.214619e-02
step 4680 | epoch=2.994 | loss=0.016935 | grad=3.639383e-05 | alpha_mean=0.499126 | alpha_std=0.032313 | alpha_min=0.360651 | alpha_max=0.691282 | param_max_abs=2.237883e-02
step 4689 | epoch=3.000 | loss=0.013843 | grad=4.963456e-05 | alpha_mean=0.497532 | alpha_std=0.030428 | alpha_min=0.343440 | alpha_max=0.627004 | param_max_abs=2.245843e-02
✓ Checkpoint saved: /content/drive/MyDrive/Notebook4/results/ckpt/bap2_4689/bap2_s4689.pt

✓ Entrenamiento final terminado
Last global_step: 4689
Epoch efectiva: 3.0
Logs: /content/drive/MyDrive/Notebook4/results/ckpt/bap2_4689/logs.csv
Checkpoint final: /content/drive/MyDrive/Notebook4/results/ckpt/bap2_4689/bap2_s4689.pt
CURRENT_STEP: 4689

Alpha summary:
alpha_mean inicial: 0.49973738193511963
alpha_mean final:   0.4975322484970093
alpha_std inicial:  0.009127944707870483
alpha_std final:    0.03042794018983841
alpha_min final:    0.34344008564949036
alpha_max final:    0.6270043253898621

Loss summary:
loss inicial: 0.07445602118968964
loss final:   0.013842955231666565

,global_step,effective_epoch,loss,grad_norm,alpha_mean,alpha_min,alpha_max,alpha_std,alpha_has_nan,gate_param_mean,gate_param_std,gate_param_max_abs,gate_param_has_nan
3684,4685,2.997441,0.018683,2.121083e-05,0.497536,0.368891,0.650033,0.031738,False,0.000004,0.001250,0.022381,False
3685,4686,2.998081,0.274145,2.532855e-04,0.498717,0.359291,0.731647,0.033033,False,0.000004,0.001251,0.022384,False
3686,4687,2.998720,0.004652,1.739100e-07,0.498514,0.364390,0.626687,0.030655,False,0.000004,0.001251,0.022388,False
3687,4688,2.999360,0.338190,1.961141e-04,0.497441,0.368342,0.605738,0.027600,False,0.000004,0.001251,0.022425,False
3688,4689,3.000000,0.013843,4.963456e-05,0.497532,0.343440,0.627004,0.030428,False,0.000004,0.001252,0.022458,False

### Evaluation

In [9]:
# ============================================================
# FINAL CHECKPOINT SELECTION
# Evaluates step1000, step1563, step3126, step4689
# 10 VAL triads × age 25 × λ=0.1
# ============================================================

import os
import torch
import torch.nn.functional as F
import torchvision.transforms as T
import pandas as pd
from torch.utils.data._utils.collate import default_collate
from IPython.display import display

# ------------------------------------------------------------
# Checkpoints candidatos
# ------------------------------------------------------------

CKPT_CANDIDATES = {
    "step1000": f"{DRIVE}/results/ckpt/bap2_s1000.pt",

    "step1563": (
        f"{DRIVE}/results/ckpt/"
        "bap2_4689/"
        "bap2_s1563.pt"
    ),

    "step3126": (
        f"{DRIVE}/results/ckpt/"
        "bap2_4689/"
        "bap2_s3126.pt"
    ),

    "step4689": (
        f"{DRIVE}/results/ckpt/"
        "bap2_4689/"
        "bap2_s4689.pt"
    ),
}

available_ckpts = {}

for name, path in CKPT_CANDIDATES.items():
    exists = os.path.exists(path)
    print(f"{name}: {exists} | {path}")
    if exists:
        available_ckpts[name] = path

assert len(available_ckpts) >= 2, "At least 2 checkpoints are needed for comparison."

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

N_TRIADS = 10
EVAL_IDXS = [179, 12, 35, 48, 61, 74, 89, 103, 128, 150]
EVAL_IDXS = EVAL_IDXS[:N_TRIADS]

AGE = 25
PARENT_SCALE = 0.1

GUIDANCE = 4.0
STEPS = 30
BASE_SEED = 42

NEG_PROMPT = "monochrome, lowres, bad anatomy, worst quality, low quality, blurry"

OUT_DIR = f"{DRIVE}/results/checkpoint_selection_final"
os.makedirs(OUT_DIR, exist_ok=True)

print("\nEVAL_IDXS:", EVAL_IDXS)
print("AGE:", AGE)
print("PARENT_SCALE:", PARENT_SCALE)
print("OUT_DIR:", OUT_DIR)

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

preprocess_arcface = T.Compose([
    T.Resize((112, 112)),
    T.ToTensor(),
    T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
])

@torch.inference_mode()
def arcface_embed_from_pil(img):
    x = preprocess_arcface(img.convert("RGB")).unsqueeze(0).to(DEVICE).float()
    emb = arcface_torch(x)
    emb = F.normalize(emb, p=2, dim=1)
    return emb

def ensure_2d(x):
    if x.ndim == 1:
        x = x.unsqueeze(0)
    return x

def set_parent_scale_bap2(value):
    for proc in pipe.unet.attn_processors.values():
        if type(proc).__name__ == "BAP2":
            proc.parent_scale = value

def collect_bap2_alpha_stats():
    vals = []

    for proc in pipe.unet.attn_processors.values():
        if type(proc).__name__ == "BAP2":
            if getattr(proc, "last_alpha", None) is not None:
                vals.append(proc.last_alpha.detach().float().cpu())

    if len(vals) == 0:
        return {
            "alpha_mean": None,
            "alpha_std": None,
            "alpha_min": None,
            "alpha_max": None,
        }

    x = torch.cat(vals, dim=0)

    return {
        "alpha_mean": x.mean().item(),
        "alpha_std": x.std().item(),
        "alpha_min": x.min().item(),
        "alpha_max": x.max().item(),
    }

def load_bap2_checkpoint(ckpt_path):
    ckpt = torch.load(ckpt_path, map_location=DEVICE)

    assert "bap2_gate_state" in ckpt, "Checkpoint without bap2_gate_state."

    gate_state = ckpt["bap2_gate_state"]

    loaded = 0

    for name, proc in bap2_modules.items():
        assert name in gate_state, f"Missing gate for {name}"
        proc.gate.load_state_dict(gate_state[name])
        proc.gate.to(DEVICE)
        proc.gate.float()
        loaded += 1

    print(f"✓ Cargado checkpoint step={ckpt.get('step')} | gates={loaded}/{len(bap2_modules)}")
    return int(ckpt.get("step", -1))

@torch.inference_mode()
def generate_bap2_eval(h_c, h_p, h_m, gender, age, parent_scale, seed):
    pipe.unet.eval()
    pipe.vae.eval()
    pipe.text_encoder.eval()
    ip_model.image_proj_model.eval()

    set_parent_scale_bap2(parent_scale)

    h_c = ensure_2d(h_c).to(DEVICE, dtype=DTYPE)
    h_p = ensure_2d(h_p).to(DEVICE, dtype=DTYPE)
    h_m = ensure_2d(h_m).to(DEVICE, dtype=DTYPE)

    child_tokens  = ip_model.image_proj_model(h_c)
    father_tokens = ip_model.image_proj_model(h_p)
    mother_tokens = ip_model.image_proj_model(h_m)

    zero_child_tokens  = ip_model.image_proj_model(torch.zeros_like(h_c))
    zero_father_tokens = ip_model.image_proj_model(torch.zeros_like(h_p))
    zero_mother_tokens = ip_model.image_proj_model(torch.zeros_like(h_m))

    prompt = f"portrait photo of a {gender}, age {age}, realistic, neutral expression"

    prompt_embeds, negative_prompt_embeds = pipe.encode_prompt(
        prompt=[prompt],
        device=DEVICE,
        num_images_per_prompt=1,
        do_classifier_free_guidance=True,
        negative_prompt=[NEG_PROMPT],
    )

    prompt_embeds = torch.cat(
        [prompt_embeds, child_tokens, father_tokens, mother_tokens],
        dim=1,
    )

    negative_prompt_embeds = torch.cat(
        [negative_prompt_embeds, zero_child_tokens, zero_father_tokens, zero_mother_tokens],
        dim=1,
    )

    generator = torch.Generator(device=DEVICE).manual_seed(seed)

    img = pipe(
        prompt_embeds=prompt_embeds,
        negative_prompt_embeds=negative_prompt_embeds,
        guidance_scale=GUIDANCE,
        num_inference_steps=STEPS,
        generator=generator,
    ).images[0]

    alpha_stats = collect_bap2_alpha_stats()

    return img, alpha_stats

# ============================================================
# Evaluation loop
# ============================================================

rows = []

for ckpt_name, ckpt_path in available_ckpts.items():

    print("\n" + "=" * 80)
    print("CHECKPOINT:", ckpt_name)
    print("=" * 80)

    loaded_step = load_bap2_checkpoint(ckpt_path)

    for triad_num, idx in enumerate(EVAL_IDXS, start=1):

        sample = val_ds[idx]

        batch = default_collate([sample])
        batch = {
            k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
            for k, v in batch.items()
        }

        h_c = ensure_2d(batch["h_c"])
        h_p = ensure_2d(batch["h_p"])
        h_m = ensure_2d(batch["h_m"])

        h_c_eval = F.normalize(h_c.float(), p=2, dim=1)
        h_p_eval = F.normalize(h_p.float(), p=2, dim=1)
        h_m_eval = F.normalize(h_m.float(), p=2, dim=1)

        gender = sample.get("gender", "person")
        if gender not in ["man", "woman", "person"]:
            gender = "person"

        seed = BASE_SEED + idx * 1000 + AGE

        img, alpha_stats = generate_bap2_eval(
            h_c=h_c,
            h_p=h_p,
            h_m=h_m,
            gender=gender,
            age=AGE,
            parent_scale=PARENT_SCALE,
            seed=seed,
        )

        h_gen = arcface_embed_from_pil(img)

        S_id = F.cosine_similarity(h_gen, h_c_eval).item()
        S_p  = F.cosine_similarity(h_gen, h_p_eval).item()
        S_m  = F.cosine_similarity(h_gen, h_m_eval).item()

        rows.append({
            "checkpoint": ckpt_name,
            "step": loaded_step,
            "triad_idx": idx,
            "triad_num": triad_num,
            "age": AGE,
            "parent_scale": PARENT_SCALE,
            "gender": gender,
            "S_id_child": S_id,
            "S_p_father": S_p,
            "S_m_mother": S_m,
            "S_family": 0.5 * (S_p + S_m),
            "balance_abs_gap": abs(S_p - S_m),
            "alpha_mean": alpha_stats["alpha_mean"],
            "alpha_std": alpha_stats["alpha_std"],
            "alpha_min": alpha_stats["alpha_min"],
            "alpha_max": alpha_stats["alpha_max"],
            "key_p": sample.get("key_p", ""),
            "key_m": sample.get("key_m", ""),
            "key_c": sample.get("key_c", ""),
            "seed": seed,
        })

        print(
            f"{ckpt_name} | idx={idx} | "
            f"S_id={S_id:.4f} | "
            f"S_family={0.5 * (S_p + S_m):.4f} | "
            f"gap={abs(S_p - S_m):.4f} | "
            f"alpha_std={alpha_stats['alpha_std']:.5f}"
        )

df_ckpt_selection = pd.DataFrame(rows)

print("\n==============================")
print("Full results")
print("==============================")
display(df_ckpt_selection)

# ============================================================
# Summary by checkpoint
# ============================================================

summary_ckpt = (
    df_ckpt_selection
    .groupby("checkpoint")
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
        "alpha_min",
        "alpha_max",
    ]]
    .mean()
    .reset_index()
)

print("\n==============================")
print("Summary by checkpoint")
print("==============================")
display(summary_ckpt)

# ============================================================
# Delta vs step1000 if it exists
# ============================================================

metrics = ["S_id_child", "S_p_father", "S_m_mother", "S_family", "balance_abs_gap"]

delta_rows = []

if "step1000" in df_ckpt_selection["checkpoint"].unique():

    base = df_ckpt_selection[df_ckpt_selection["checkpoint"] == "step1000"]

    for ckpt_name in sorted(df_ckpt_selection["checkpoint"].unique()):
        if ckpt_name == "step1000":
            continue

        comp = df_ckpt_selection[df_ckpt_selection["checkpoint"] == ckpt_name]

        merged = base[["triad_idx", "age"] + metrics].merge(
            comp[["triad_idx", "age"] + metrics],
            on=["triad_idx", "age"],
            suffixes=("_1000", f"_{ckpt_name}")
        )

        for m in metrics:
            d = merged[f"{m}_{ckpt_name}"] - merged[f"{m}_1000"]

            delta_rows.append({
                "checkpoint_vs_step1000": ckpt_name,
                "metric": m,
                "mean_delta": d.mean(),
                "median_delta": d.median(),
                "win_rate_gt_step1000": (d > 0).mean(),
                "n": len(d),
            })

df_delta_vs_1000 = pd.DataFrame(delta_rows)

print("\n==============================")
print("Delta contra step1000")
print("==============================")
display(df_delta_vs_1000)

# ============================================================
# Save
# ============================================================

df_ckpt_selection.to_csv(f"{OUT_DIR}/df_ckpt_selection_val10.csv", index=False)
summary_ckpt.to_csv(f"{OUT_DIR}/summary_ckpt_selection_val10.csv", index=False)
df_delta_vs_1000.to_csv(f"{OUT_DIR}/delta_vs_step1000_val10.csv", index=False)

print("\n✓ Saved to:")
print(OUT_DIR)

step1000: True | /content/drive/MyDrive/Notebook4/results/ckpt/bap2_s1000.pt
step1563: True | /content/drive/MyDrive/Notebook4/results/ckpt/bap2_4689/bap2_s1563.pt
step3126: True | /content/drive/MyDrive/Notebook4/results/ckpt/bap2_4689/bap2_s3126.pt
step4689: True | /content/drive/MyDrive/Notebook4/results/ckpt/bap2_4689/bap2_s4689.pt

EVAL_IDXS: [179, 12, 35, 48, 61, 74, 89, 103, 128, 150]
AGE: 25
PARENT_SCALE: 0.1
OUT_DIR: /content/drive/MyDrive/Notebook4/results/checkpoint_selection_final

================================================================================
CHECKPOINT: step1000
================================================================================
✓ Cargado checkpoint step=1000 | gates=16/16

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=179 | S_id=-0.0285 | S_family=0.0037 | gap=0.0002 | alpha_std=0.00761

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=12 | S_id=0.0737 | S_family=-0.0374 | gap=0.0135 | alpha_std=0.00773

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=35 | S_id=0.0406 | S_family=0.0431 | gap=0.1265 | alpha_std=0.00731

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=48 | S_id=0.2229 | S_family=-0.0331 | gap=0.0519 | alpha_std=0.00755

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=61 | S_id=0.0968 | S_family=-0.0278 | gap=0.0459 | alpha_std=0.00785

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=74 | S_id=-0.0078 | S_family=0.0212 | gap=0.0438 | alpha_std=0.00770

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=89 | S_id=0.1850 | S_family=0.0644 | gap=0.0814 | alpha_std=0.00809

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=103 | S_id=0.2728 | S_family=0.0195 | gap=0.0102 | alpha_std=0.00815

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=128 | S_id=0.1601 | S_family=-0.0391 | gap=0.1087 | alpha_std=0.00818

  0%|          | 0/30 [00:00<?, ?it/s]

step1000 | idx=150 | S_id=0.1353 | S_family=-0.0190 | gap=0.0323 | alpha_std=0.00822

================================================================================
CHECKPOINT: step1563
================================================================================
✓ Cargado checkpoint step=1563 | gates=16/16

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=179 | S_id=-0.0278 | S_family=0.0032 | gap=0.0010 | alpha_std=0.01135

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=12 | S_id=0.0730 | S_family=-0.0378 | gap=0.0129 | alpha_std=0.01129

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=35 | S_id=0.0396 | S_family=0.0430 | gap=0.1268 | alpha_std=0.01080

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=48 | S_id=0.2228 | S_family=-0.0328 | gap=0.0511 | alpha_std=0.01115

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=61 | S_id=0.0957 | S_family=-0.0279 | gap=0.0458 | alpha_std=0.01151

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=74 | S_id=-0.0081 | S_family=0.0205 | gap=0.0448 | alpha_std=0.01136

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=89 | S_id=0.1862 | S_family=0.0644 | gap=0.0818 | alpha_std=0.01200

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=103 | S_id=0.2754 | S_family=0.0194 | gap=0.0082 | alpha_std=0.01174

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=128 | S_id=0.1590 | S_family=-0.0410 | gap=0.1113 | alpha_std=0.01207

  0%|          | 0/30 [00:00<?, ?it/s]

step1563 | idx=150 | S_id=0.1360 | S_family=-0.0191 | gap=0.0327 | alpha_std=0.01198

================================================================================
CHECKPOINT: step3126
================================================================================
✓ Cargado checkpoint step=3126 | gates=16/16

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=179 | S_id=-0.0276 | S_family=0.0035 | gap=0.0001 | alpha_std=0.01835

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=12 | S_id=0.0733 | S_family=-0.0372 | gap=0.0144 | alpha_std=0.01844

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=35 | S_id=0.0406 | S_family=0.0431 | gap=0.1257 | alpha_std=0.01747

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=48 | S_id=0.2226 | S_family=-0.0333 | gap=0.0515 | alpha_std=0.01799

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=61 | S_id=0.0963 | S_family=-0.0278 | gap=0.0456 | alpha_std=0.01878

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=74 | S_id=-0.0080 | S_family=0.0192 | gap=0.0450 | alpha_std=0.01845

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=89 | S_id=0.1856 | S_family=0.0639 | gap=0.0808 | alpha_std=0.01918

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=103 | S_id=0.2756 | S_family=0.0199 | gap=0.0090 | alpha_std=0.01892

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=128 | S_id=0.1589 | S_family=-0.0401 | gap=0.1082 | alpha_std=0.01968

  0%|          | 0/30 [00:00<?, ?it/s]

step3126 | idx=150 | S_id=0.1381 | S_family=-0.0189 | gap=0.0345 | alpha_std=0.01949

================================================================================
CHECKPOINT: step4689
================================================================================
✓ Cargado checkpoint step=4689 | gates=16/16

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=179 | S_id=-0.0248 | S_family=0.0031 | gap=0.0019 | alpha_std=0.02611

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=12 | S_id=0.0733 | S_family=-0.0372 | gap=0.0130 | alpha_std=0.02613

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=35 | S_id=0.0431 | S_family=0.0439 | gap=0.1227 | alpha_std=0.02457

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=48 | S_id=0.2242 | S_family=-0.0330 | gap=0.0512 | alpha_std=0.02567

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=61 | S_id=0.0965 | S_family=-0.0292 | gap=0.0452 | alpha_std=0.02642

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=74 | S_id=-0.0078 | S_family=0.0203 | gap=0.0447 | alpha_std=0.02620

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=89 | S_id=0.1863 | S_family=0.0645 | gap=0.0790 | alpha_std=0.02750

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=103 | S_id=0.2757 | S_family=0.0206 | gap=0.0082 | alpha_std=0.02662

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=128 | S_id=0.1597 | S_family=-0.0395 | gap=0.1095 | alpha_std=0.02748

  0%|          | 0/30 [00:00<?, ?it/s]

step4689 | idx=150 | S_id=0.1357 | S_family=-0.0208 | gap=0.0354 | alpha_std=0.02736

==============================
Resultados completos
==============================

,checkpoint,step,triad_idx,triad_num,age,parent_scale,gender,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap,alpha_mean,alpha_std,alpha_min,alpha_max,key_p,key_m,key_c,seed
0,step1000,1000,179,1,25,0.1,man,-0.028505,0.003831,0.003635,0.003733,0.000196,0.499768,0.007612,0.459507,0.530295,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg,179067
1,step1000,1000,12,2,25,0.1,woman,0.073722,-0.030661,-0.044130,-0.037395,0.013469,0.499739,0.007730,0.458551,0.531314,F0061/MID1/P00609_face2.jpg,F0061/MID2/P00609_face1.jpg,F0061/MID3/P00609_face3.jpg,12067
2,step1000,1000,35,3,25,0.1,woman,0.040562,0.106391,-0.020130,0.043131,0.126521,0.499743,0.007312,0.459499,0.525737,F0144/MID1/P01524_face3.jpg,F0144/MID2/P01524_face4.jpg,F0144/MID7/P01534_face2.jpg,35067
3,step1000,1000,48,4,25,0.1,man,0.222921,-0.007196,-0.059055,-0.033126,0.051860,0.499699,0.007549,0.459501,0.526245,F0249/MID1/P02633_face4.jpg,F0249/MID7/P02637_face0.jpg,F0249/MID4/P02640_face1.jpg,48067
4,step1000,1000,61,5,25,0.1,woman,0.096759,-0.050706,-0.004813,-0.027760,0.045893,0.499708,0.007849,0.457985,0.532858,F0327/MID3/P03464_face1.jpg,F0327/MID2/P03464_face2.jpg,F0327/MID4/P03465_face3.jpg,61067
5,step1000,1000,74,6,25,0.1,man,-0.007753,-0.000713,0.043082,0.021184,0.043795,0.499792,0.007705,0.460472,0.530537,F0380/MID5/P04034_face0.jpg,F0380/MID7/P04034_face2.jpg,F0380/MID6/P04034_face3.jpg,74067
6,step1000,1000,89,7,25,0.1,man,0.185041,0.105149,0.023751,0.064450,0.081398,0.499762,0.008090,0.456579,0.527395,F0434/MID3/P04573_face0.jpg,F0434/MID1/P04572_face1.jpg,F0434/MID2/P04572_face0.jpg,89067
7,step1000,1000,103,8,25,0.1,woman,0.272758,0.024532,0.014373,0.019453,0.010159,0.499670,0.008153,0.456358,0.532432,F0490/MID4/P05159_face1.jpg,F0490/MID5/P05161_face0.jpg,F0490/MID7/P05166_face0.jpg,103067
8,step1000,1000,128,9,25,0.1,man,0.160104,0.015270,-0.093465,-0.039098,0.108735,0.499766,0.008182,0.456704,0.531120,F0599/MID6/P10738_face6.jpg,F0599/MID4/P10736_face1.jpg,F0599/MID1/P10729_face1.jpg,128067
9,step1000,1000,150,10,25,0.1,woman,0.135271,-0.002841,-0.035183,-0.019012,0.032342,0.499685,0.008218,0.453940,0.536128,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg,150067
10,step1563,1563,179,1,25,0.1,man,-0.027837,0.003701,0.002688,0.003194,0.001013,0.499682,0.011346,0.438227,0.540895,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg,179067
11,step1563,1563,12,2,25,0.1,woman,0.072999,-0.031355,-0.044217,-0.037786,0.012862,0.499694,0.011293,0.431708,0.544202,F0061/MID1/P00609_face2.jpg,F0061/MID2/P00609_face1.jpg,F0061/MID3/P00609_face3.jpg,12067
12,step1563,1563,35,3,25,0.1,woman,0.039551,0.106399,-0.020417,0.042991,0.126816,0.499678,0.010802,0.438022,0.540161,F0144/MID1/P01524_face3.jpg,F0144/MID2/P01524_face4.jpg,F0144/MID7/P01534_face2.jpg,35067
13,step1563,1563,48,4,25,0.1,man,0.222787,-0.007207,-0.058308,-0.032757,0.051100,0.499614,0.011150,0.440340,0.540793,F0249/MID1/P02633_face4.jpg,F0249/MID7/P02637_face0.jpg,F0249/MID4/P02640_face1.jpg,48067
14,step1563,1563,61,5,25,0.1,woman,0.095652,-0.050858,-0.005019,-0.027938,0.045839,0.499593,0.011507,0.439558,0.541434,F0327/MID3/P03464_face1.jpg,F0327/MID2/P03464_face2.jpg,F0327/MID4/P03465_face3.jpg,61067
15,step1563,1563,74,6,25,0.1,man,-0.008061,-0.001899,0.042946,0.020523,0.044844,0.499787,0.011360,0.432987,0.544726,F0380/MID5/P04034_face0.jpg,F0380/MID7/P04034_face2.jpg,F0380/MID6/P04034_face3.jpg,74067
16,step1563,1563,89,7,25,0.1,man,0.186176,0.105366,0.023520,0.064443,0.081846,0.499681,0.012001,0.439379,0.561896,F0434/MID3/P04573_face0.jpg,F0434/MID1/P04572_face1.jpg,F0434/MID2/P04572_face0.jpg,89067
17,step1563,1563,103,8,25,0.1,woman,0.275378,0.023452,0.015291,0.019371,0.008161,0.499583,0.011742,0.421647,0.547058,F0490/MID4/P05159_face1.jpg,F0490/MID5/P05161_face0.jpg,F0490/MID7/P05166_face0.jpg,103067
18,step1563,1563,128,9,25,0.1,man,0.159025,0.014677,-0.096671,-0.040997,0.111348,0.499763,0.012070,0.420415,0.547689,F0599/MID6/P10738_face6.jpg,F0599/MID4/P10736_face1.jpg,F0599/MID1/P10729_face1.jpg,128067
19,step1563,1563,150,10,25,0.1,woman,0.136017,-0.002754,-0.035476,-0.019115,0.032722,0.499592,0.011984,0.427684,0.546279,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg,150067
20,step3126,3126,179,1,25,0.1,man,-0.027566,0.003482,0.003576,0.003529,0.000094,0.499703,0.018346,0.399772,0.590774,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg,179067
21,step3126,3126,12,2,25,0.1,woman,0.073274,-0.030058,-0.044426,-0.037242,0.014368,0.499633,0.018440,0.400308,0.593702,F0061/MID1/P00609_face2.jpg,F0061/MID2/P00609_face1.jpg,F0061/MID3/P00609_face3.jpg,12067
22,step3126,3126,35,3,25,0.1,woman,0.040644,0.105950,-0.019795,0.043077,0.125746,0.499614,0.017466,0.398669,0.588894,F0144/MID1/P01524_face3.jpg,F0144/MID2/P01524_face4.jpg,F0144/MID7/P01534_face2.jpg,35067
23,step3126,3126,48,4,25,0.1,man,0.222609,-0.007523,-0.059055,-0.033289,0.051532,0.499615,0.017987,0.399597,0.590467,F0249/MID1/P02633_face4.jpg,F0249/MID7/P02637_face0.jpg,F0249/MID4/P02640_face1.jpg,48067
24,step3126,3126,61,5,25,0.1,woman,0.096348,-0.050600,-0.005035,-0.027817,0.045565,0.499484,0.018780,0.396907,0.592309,F0327/MID3/P03464_face1.jpg,F0327/MID2/P03464_face2.jpg,F0327/MID4/P03465_face3.jpg,61067
25,step3126,3126,74,6,25,0.1,man,-0.008012,-0.003307,0.041723,0.019208,0.045030,0.499848,0.018449,0.401704,0.588588,F0380/MID5/P04034_face0.jpg,F0380/MID7/P04034_face2.jpg,F0380/MID6/P04034_face3.jpg,74067
26,step3126,3126,89,7,25,0.1,man,0.185573,0.104291,0.023456,0.063874,0.080835,0.499674,0.019184,0.395541,0.604858,F0434/MID3/P04573_face0.jpg,F0434/MID1/P04572_face1.jpg,F0434/MID2/P04572_face0.jpg,89067
27,step3126,3126,103,8,25,0.1,woman,0.275567,0.024371,0.015394,0.019883,0.008977,0.499545,0.018924,0.397521,0.591707,F0490/MID4/P05159_face1.jpg,F0490/MID5/P05161_face0.jpg,F0490/MID7/P05166_face0.jpg,103067
28,step3126,3126,128,9,25,0.1,man,0.158895,0.014004,-0.094241,-0.040119,0.108245,0.499728,0.019682,0.392643,0.593095,F0599/MID6/P10738_face6.jpg,F0599/MID4/P10736_face1.jpg,F0599/MID1/P10729_face1.jpg,128067
29,step3126,3126,150,10,25,0.1,woman,0.138146,-0.001665,-0.036152,-0.018909,0.034487,0.499514,0.019487,0.391473,0.590922,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg,150067
30,step4689,4689,179,1,25,0.1,man,-0.024814,0.004093,0.002172,0.003132,0.001921,0.498271,0.026106,0.376162,0.630180,F0854/MID1/P09020_face1.jpg,F0854/MID3/P09026_face0.jpg,F0854/MID2/P09020_face0.jpg,179067
31,step4689,4689,12,2,25,0.1,woman,0.073297,-0.030656,-0.043696,-0.037176,0.013040,0.498244,0.026130,0.377076,0.648101,F0061/MID1/P00609_face2.jpg,F0061/MID2/P00609_face1.jpg,F0061/MID3/P00609_face3.jpg,12067
32,step4689,4689,35,3,25,0.1,woman,0.043067,0.105187,-0.017479,0.043854,0.122666,0.498271,0.024570,0.374095,0.599873,F0144/MID1/P01524_face3.jpg,F0144/MID2/P01524_face4.jpg,F0144/MID7/P01534_face2.jpg,35067
33,step4689,4689,48,4,25,0.1,man,0.224214,-0.007429,-0.058650,-0.033040,0.051221,0.498213,0.025665,0.376029,0.638574,F0249/MID1/P02633_face4.jpg,F0249/MID7/P02637_face0.jpg,F0249/MID4/P02640_face1.jpg,48067
34,step4689,4689,61,5,25,0.1,woman,0.096496,-0.051773,-0.006578,-0.029176,0.045195,0.497956,0.026425,0.372265,0.627705,F0327/MID3/P03464_face1.jpg,F0327/MID2/P03464_face2.jpg,F0327/MID4/P03465_face3.jpg,61067
35,step4689,4689,74,6,25,0.1,man,-0.007793,-0.002070,0.042618,0.020274,0.044688,0.498453,0.026200,0.378803,0.637480,F0380/MID5/P04034_face0.jpg,F0380/MID7/P04034_face2.jpg,F0380/MID6/P04034_face3.jpg,74067
36,step4689,4689,89,7,25,0.1,man,0.186251,0.103952,0.024985,0.064469,0.078967,0.498145,0.027501,0.370095,0.676736,F0434/MID3/P04573_face0.jpg,F0434/MID1/P04572_face1.jpg,F0434/MID2/P04572_face0.jpg,89067
37,step4689,4689,103,8,25,0.1,woman,0.275746,0.024688,0.016472,0.020580,0.008216,0.498152,0.026615,0.373618,0.629850,F0490/MID4/P05159_face1.jpg,F0490/MID5/P05161_face0.jpg,F0490/MID7/P05166_face0.jpg,103067
38,step4689,4689,128,9,25,0.1,man,0.159699,0.015203,-0.094299,-0.039548,0.109501,0.498358,0.027478,0.372403,0.641390,F0599/MID6/P10738_face6.jpg,F0599/MID4/P10736_face1.jpg,F0599/MID1/P10729_face1.jpg,128067
39,step4689,4689,150,10,25,0.1,woman,0.135653,-0.003126,-0.038494,-0.020810,0.035368,0.498005,0.027361,0.369534,0.612476,F0683/MID2/P07121_face1.jpg,F0683/MID4/P07132_face2.jpg,F0683/MID6/P07135_face1.jpg,150067

==============================
Summary by checkpoint
==============================

,checkpoint,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap,alpha_mean,alpha_std,alpha_min,alpha_max
0,step1000,0.115088,0.016306,-0.017194,-0.000444,0.051437,0.499733,0.007840,0.457910,0.530406
1,step1563,0.115169,0.015952,-0.017566,-0.000807,0.051655,0.499667,0.011526,0.432997,0.545513
2,step3126,0.115548,0.015895,-0.017455,-0.000780,0.051488,0.499636,0.018675,0.397413,0.592532
3,step4689,0.116182,0.015807,-0.017295,-0.000744,0.051078,0.498207,0.026405,0.374008,0.634236

==============================
Delta contra step1000
==============================

,checkpoint_vs_step1000,metric,mean_delta,median_delta,win_rate_gt_step1000,n
0,step1563,S_id_child,0.000081,-0.000221,0.4,10
1,step1563,S_p_father,-0.000354,-0.000141,0.3,10
2,step1563,S_m_mother,-0.000373,-0.000218,0.2,10
3,step1563,S_family,-0.000363,-0.000159,0.1,10
4,step1563,balance_abs_gap,0.000218,0.000337,0.6,10
5,step3126,S_id_child,0.000460,-0.000089,0.5,10
6,step3126,S_p_father,-0.000411,-0.000338,0.3,10
7,step3126,S_m_mother,-0.000262,-0.000258,0.3,10
8,step3126,S_family,-0.000336,-0.000110,0.3,10
9,step3126,balance_abs_gap,0.000051,-0.000328,0.3,10
10,step4689,S_id_child,0.001094,0.000796,0.6,10
11,step4689,S_p_father,-0.000499,-0.000259,0.3,10
12,step4689,S_m_mother,-0.000101,-0.000030,0.5,10
13,step4689,S_family,-0.000300,-0.000216,0.5,10
14,step4689,balance_abs_gap,-0.000359,-0.000534,0.4,10

✓ Saved to:
/content/drive/MyDrive/Notebook4/results/checkpoint_selection_final

In [10]:
# ============================================================
# TEST FINAL — BAP2 step4689
# 208 triads × 5 ages × 2 lambdas = 2080 images
#
# Methods:
#   BAP2 λ=0.0
#   BAP2 λ=0.1
#
# Guarda:
#   - CSV incremental
#   - generated images
#   - summary final
# Automatic resume if interrupted
# ============================================================

import os
import torch
import torch.nn.functional as F
import torchvision.transforms as T
import pandas as pd
from torch.utils.data._utils.collate import default_collate
from IPython.display import display

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

CKPT_FINAL = (
    f"{DRIVE}/results/ckpt/"
    "bap2_4689/"
    "bap2_s4689.pt"
)

assert os.path.exists(CKPT_FINAL), f"Final checkpoint does not exist: {CKPT_FINAL}"

AGES = [5, 15, 25, 40, 60]
PARENT_SCALES = [0.0, 0.1]

GUIDANCE = 4.0
STEPS = 30
BASE_SEED = 42

NEG_PROMPT = "monochrome, lowres, bad anatomy, worst quality, low quality, blurry"

OUT_DIR = f"{DRIVE}/results/eval/bap2"
IMG_DIR = f"{OUT_DIR}/images"
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(IMG_DIR, exist_ok=True)

OUT_CSV = f"{OUT_DIR}/bap2.csv"

print("Checkpoint:", CKPT_FINAL)
print("Test triads:", len(test_ds))
print("Ages:", AGES)
print("Parent scales:", PARENT_SCALES)
print("Total images:", len(test_ds) * len(AGES) * len(PARENT_SCALES))
print("OUT_DIR:", OUT_DIR)

# ------------------------------------------------------------
# Load BAP2 checkpoint step4689
# ------------------------------------------------------------

ckpt = torch.load(CKPT_FINAL, map_location=DEVICE)

assert "bap2_gate_state" in ckpt, "Checkpoint without bap2_gate_state."
assert int(ckpt["step"]) == 4689, f"Expected step4689, got {ckpt['step']}."
assert "bap2_modules" in globals(), "Falta bap2_modules."
assert len(bap2_modules) == 16, "bap2_modules must have 16 modules."

gate_state = ckpt["bap2_gate_state"]

loaded = 0
for name, proc in bap2_modules.items():
    assert name in gate_state, f"Missing gate for {name}"
    proc.gate.load_state_dict(gate_state[name])
    proc.gate.to(DEVICE)
    proc.gate.float()
    loaded += 1

CURRENT_STEP = int(ckpt["step"])

print(f"✓ Checkpoint loaded: step={CURRENT_STEP}, gates={loaded}/{len(bap2_modules)}")

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

preprocess_arcface = T.Compose([
    T.Resize((112, 112)),
    T.ToTensor(),
    T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
])

@torch.inference_mode()
def arcface_embed_from_pil(img):
    x = preprocess_arcface(img.convert("RGB")).unsqueeze(0).to(DEVICE).float()
    emb = arcface_torch(x)
    emb = F.normalize(emb, p=2, dim=1)
    return emb

def ensure_2d(x):
    if x.ndim == 1:
        x = x.unsqueeze(0)
    return x

def set_parent_scale_bap2(value):
    for proc in pipe.unet.attn_processors.values():
        if type(proc).__name__ == "BAP2":
            proc.parent_scale = value

def collect_bap2_alpha_stats():
    vals = []

    for proc in pipe.unet.attn_processors.values():
        if type(proc).__name__ == "BAP2":
            if getattr(proc, "last_alpha", None) is not None:
                vals.append(proc.last_alpha.detach().float().cpu())

    if len(vals) == 0:
        return {
            "alpha_mean": None,
            "alpha_std": None,
            "alpha_min": None,
            "alpha_max": None,
        }

    x = torch.cat(vals, dim=0)

    return {
        "alpha_mean": x.mean().item(),
        "alpha_std": x.std().item(),
        "alpha_min": x.min().item(),
        "alpha_max": x.max().item(),
    }

@torch.inference_mode()
def generate_bap2_final(h_c, h_p, h_m, gender, age, parent_scale, seed):
    pipe.unet.eval()
    pipe.vae.eval()
    pipe.text_encoder.eval()
    ip_model.image_proj_model.eval()

    set_parent_scale_bap2(parent_scale)

    h_c = ensure_2d(h_c).to(DEVICE, dtype=DTYPE)
    h_p = ensure_2d(h_p).to(DEVICE, dtype=DTYPE)
    h_m = ensure_2d(h_m).to(DEVICE, dtype=DTYPE)

    child_tokens  = ip_model.image_proj_model(h_c)
    father_tokens = ip_model.image_proj_model(h_p)
    mother_tokens = ip_model.image_proj_model(h_m)

    zero_child_tokens  = ip_model.image_proj_model(torch.zeros_like(h_c))
    zero_father_tokens = ip_model.image_proj_model(torch.zeros_like(h_p))
    zero_mother_tokens = ip_model.image_proj_model(torch.zeros_like(h_m))

    prompt = f"portrait photo of a {gender}, age {age}, realistic, neutral expression"

    prompt_embeds, negative_prompt_embeds = pipe.encode_prompt(
        prompt=[prompt],
        device=DEVICE,
        num_images_per_prompt=1,
        do_classifier_free_guidance=True,
        negative_prompt=[NEG_PROMPT],
    )

    prompt_embeds = torch.cat(
        [prompt_embeds, child_tokens, father_tokens, mother_tokens],
        dim=1,
    )

    negative_prompt_embeds = torch.cat(
        [negative_prompt_embeds, zero_child_tokens, zero_father_tokens, zero_mother_tokens],
        dim=1,
    )

    generator = torch.Generator(device=DEVICE).manual_seed(seed)

    img = pipe(
        prompt_embeds=prompt_embeds,
        negative_prompt_embeds=negative_prompt_embeds,
        guidance_scale=GUIDANCE,
        num_inference_steps=STEPS,
        generator=generator,
    ).images[0]

    alpha_stats = collect_bap2_alpha_stats()

    return img, alpha_stats, prompt

def save_generated_image(img, triad_idx, age, parent_scale):
    scale_tag = str(parent_scale).replace(".", "p")
    subdir = f"{IMG_DIR}/lambda_{scale_tag}/age_{age}"
    os.makedirs(subdir, exist_ok=True)

    path = f"{subdir}/triad_{triad_idx:04d}_age_{age}_lambda_{scale_tag}.jpg"
    img.save(path, quality=95)
    return path

# ------------------------------------------------------------
# Automatic resume
# ------------------------------------------------------------

rows = []
done = set()

if os.path.exists(OUT_CSV):
    old = pd.read_csv(OUT_CSV)
    rows = old.to_dict("records")
    done = set(zip(old["triad_idx"], old["age"], old["parent_scale"]))
    print(f"✓ Resume detected: {len(old)} existing rows")

# ------------------------------------------------------------
# Loop principal TEST
# ------------------------------------------------------------

for triad_idx in range(len(test_ds)):

    sample = test_ds[triad_idx]

    batch = default_collate([sample])
    batch = {
        k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
        for k, v in batch.items()
    }

    h_c = ensure_2d(batch["h_c"])
    h_p = ensure_2d(batch["h_p"])
    h_m = ensure_2d(batch["h_m"])

    h_c_eval = F.normalize(h_c.float(), p=2, dim=1)
    h_p_eval = F.normalize(h_p.float(), p=2, dim=1)
    h_m_eval = F.normalize(h_m.float(), p=2, dim=1)

    gender = sample.get("gender", "person")
    if gender not in ["man", "woman", "person"]:
        gender = "person"

    print(f"\nTriada {triad_idx + 1}/{len(test_ds)} | gender={gender}")

    for age in AGES:

        # Same seed for λ=0.0 and λ=0.1 on the same triad/age.
        paired_seed = BASE_SEED + triad_idx * 1000 + age

        for parent_scale in PARENT_SCALES:

            if (triad_idx, age, parent_scale) in done:
                print(f"skip triad={triad_idx} age={age} λ={parent_scale}")
                continue

            img, alpha_stats, prompt = generate_bap2_final(
                h_c=h_c,
                h_p=h_p,
                h_m=h_m,
                gender=gender,
                age=age,
                parent_scale=parent_scale,
                seed=paired_seed,
            )

            img_path = save_generated_image(
                img=img,
                triad_idx=triad_idx,
                age=age,
                parent_scale=parent_scale,
            )

            h_gen = arcface_embed_from_pil(img)

            S_id = F.cosine_similarity(h_gen, h_c_eval).item()
            S_p  = F.cosine_similarity(h_gen, h_p_eval).item()
            S_m  = F.cosine_similarity(h_gen, h_m_eval).item()

            row = {
                "variant": "BAP2_step4689",
                "checkpoint_step": CURRENT_STEP,
                "triad_idx": triad_idx,
                "age": age,
                "parent_scale": parent_scale,
                "gender": gender,
                "S_id_child": S_id,
                "S_p_father": S_p,
                "S_m_mother": S_m,
                "S_family": 0.5 * (S_p + S_m),
                "balance_abs_gap": abs(S_p - S_m),
                "alpha_mean": alpha_stats["alpha_mean"],
                "alpha_std": alpha_stats["alpha_std"],
                "alpha_min": alpha_stats["alpha_min"],
                "alpha_max": alpha_stats["alpha_max"],
                "key_p": sample.get("key_p", ""),
                "key_m": sample.get("key_m", ""),
                "key_c": sample.get("key_c", ""),
                "seed": paired_seed,
                "prompt": prompt,
                "image_path": img_path,
            }

            rows.append(row)

            # Incremental saving so progress is not lost
            pd.DataFrame(rows).to_csv(OUT_CSV, index=False)

            print(
                f"age={age} | λ={parent_scale} | "
                f"S_id={S_id:.4f} | "
                f"S_p={S_p:.4f} | "
                f"S_m={S_m:.4f} | "
                f"S_family={row['S_family']:.4f} | "
                f"gap={row['balance_abs_gap']:.4f} | "
                f"alpha_std={alpha_stats['alpha_std']:.5f}"
            )

# ------------------------------------------------------------
# Final summary BAP2
# ------------------------------------------------------------

df_final_bap2 = pd.DataFrame(rows)

print("\n==============================")
print("Filas finales BAP2")
print("==============================")
print(len(df_final_bap2))

expected_rows = len(test_ds) * len(AGES) * len(PARENT_SCALES)
print("Esperadas:", expected_rows)

if len(df_final_bap2) != expected_rows:
    print("⚠ Warning: unexpected number of rows. Check whether there was an interruption.")
else:
    print("✓ Row count is correct.")

summary_bap2_global = (
    df_final_bap2
    .groupby("parent_scale")
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
        "alpha_min",
        "alpha_max",
    ]]
    .mean()
    .reset_index()
)

summary_bap2_age = (
    df_final_bap2
    .groupby(["age", "parent_scale"])
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
        "alpha_min",
        "alpha_max",
    ]]
    .mean()
    .reset_index()
)

print("\n==============================")
print("Global summary BAP2 step4689")
print("==============================")
display(summary_bap2_global)

print("\n==============================")
print("Summary by age BAP2 step4689")
print("==============================")
display(summary_bap2_age)

summary_bap2_global.to_csv(f"{OUT_DIR}/summary_global_bap2.csv", index=False)
summary_bap2_age.to_csv(f"{OUT_DIR}/summary_age_bap2.csv", index=False)

print("\n✓ TEST FINAL BAP2 terminado")
print("CSV:", OUT_CSV)
print("Images:", IMG_DIR)
print("Summary:", OUT_DIR)

Checkpoint: /content/drive/MyDrive/Notebook4/results/ckpt/bap2_4689/bap2_s4689.pt
Test triads: 208
Edades: [5, 15, 25, 40, 60]
Parent scales: [0.0, 0.1]
Total images: 2080
OUT_DIR: /content/drive/MyDrive/Notebook4/results/eval/bap2
✓ Checkpoint loaded: step=4689, gates=16/16

Triada 1/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0340 | S_p=-0.0140 | S_m=0.0370 | S_family=0.0115 | gap=0.0510 | alpha_std=0.02621

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0646 | S_p=-0.0089 | S_m=0.0155 | S_family=0.0033 | gap=0.0245 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0948 | S_p=0.0032 | S_m=-0.0409 | S_family=-0.0188 | gap=0.0440 | alpha_std=0.02664

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0561 | S_p=-0.0164 | S_m=-0.0293 | S_family=-0.0228 | gap=0.0128 | alpha_std=0.02640

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0426 | S_p=-0.0132 | S_m=-0.0222 | S_family=-0.0177 | gap=0.0090 | alpha_std=0.02681

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0246 | S_p=-0.0050 | S_m=-0.0175 | S_family=-0.0113 | gap=0.0125 | alpha_std=0.02679

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2617 | S_p=0.0135 | S_m=-0.0108 | S_family=0.0014 | gap=0.0243 | alpha_std=0.02779

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2662 | S_p=0.0196 | S_m=0.0051 | S_family=0.0123 | gap=0.0146 | alpha_std=0.02777

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1821 | S_p=-0.1064 | S_m=-0.0275 | S_family=-0.0669 | gap=0.0789 | alpha_std=0.02764

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1805 | S_p=-0.1011 | S_m=-0.0278 | S_family=-0.0644 | gap=0.0733 | alpha_std=0.02766

Triada 2/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1355 | S_p=0.0210 | S_m=-0.0281 | S_family=-0.0035 | gap=0.0491 | alpha_std=0.02794

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1440 | S_p=0.0395 | S_m=-0.0139 | S_family=0.0128 | gap=0.0534 | alpha_std=0.02800

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1007 | S_p=0.0184 | S_m=-0.0754 | S_family=-0.0285 | gap=0.0938 | alpha_std=0.02732

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0985 | S_p=0.0137 | S_m=-0.0720 | S_family=-0.0292 | gap=0.0857 | alpha_std=0.02731

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0154 | S_p=-0.0508 | S_m=-0.0392 | S_family=-0.0450 | gap=0.0116 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0096 | S_p=-0.0513 | S_m=-0.0274 | S_family=-0.0394 | gap=0.0239 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3533 | S_p=0.0075 | S_m=0.0703 | S_family=0.0389 | gap=0.0627 | alpha_std=0.02701

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3474 | S_p=0.0133 | S_m=0.0783 | S_family=0.0458 | gap=0.0650 | alpha_std=0.02701

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1779 | S_p=-0.0073 | S_m=0.0982 | S_family=0.0455 | gap=0.1055 | alpha_std=0.02711

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1788 | S_p=-0.0028 | S_m=0.1016 | S_family=0.0494 | gap=0.1045 | alpha_std=0.02709

Triada 3/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3923 | S_p=0.0784 | S_m=0.0877 | S_family=0.0830 | gap=0.0093 | alpha_std=0.02818

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3437 | S_p=0.0675 | S_m=0.1326 | S_family=0.1000 | gap=0.0651 | alpha_std=0.02828

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2985 | S_p=0.0838 | S_m=-0.0220 | S_family=0.0309 | gap=0.1058 | alpha_std=0.02788

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4288 | S_p=0.0443 | S_m=0.0834 | S_family=0.0638 | gap=0.0390 | alpha_std=0.02802

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4365 | S_p=0.0502 | S_m=0.0645 | S_family=0.0573 | gap=0.0143 | alpha_std=0.02872

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4501 | S_p=0.0548 | S_m=0.0742 | S_family=0.0645 | gap=0.0193 | alpha_std=0.02874

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3515 | S_p=0.0892 | S_m=0.0653 | S_family=0.0773 | gap=0.0239 | alpha_std=0.02946

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3718 | S_p=0.0276 | S_m=0.1047 | S_family=0.0662 | gap=0.0771 | alpha_std=0.02939

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2699 | S_p=0.0754 | S_m=-0.0270 | S_family=0.0242 | gap=0.1024 | alpha_std=0.02920

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2668 | S_p=0.0651 | S_m=-0.0087 | S_family=0.0282 | gap=0.0737 | alpha_std=0.02923

Triada 4/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3846 | S_p=0.0110 | S_m=0.0692 | S_family=0.0401 | gap=0.0582 | alpha_std=0.02768

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3857 | S_p=0.0151 | S_m=0.0800 | S_family=0.0475 | gap=0.0649 | alpha_std=0.02767

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1228 | S_p=0.0678 | S_m=-0.0088 | S_family=0.0295 | gap=0.0766 | alpha_std=0.02747

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1408 | S_p=0.0452 | S_m=-0.0060 | S_family=0.0196 | gap=0.0512 | alpha_std=0.02745

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0016 | S_p=0.0117 | S_m=-0.0422 | S_family=-0.0153 | gap=0.0540 | alpha_std=0.02704

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0056 | S_p=-0.0034 | S_m=-0.0437 | S_family=-0.0236 | gap=0.0403 | alpha_std=0.02689

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2034 | S_p=0.0637 | S_m=0.0768 | S_family=0.0702 | gap=0.0132 | alpha_std=0.02848

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1995 | S_p=0.0848 | S_m=0.0724 | S_family=0.0786 | gap=0.0124 | alpha_std=0.02850

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2508 | S_p=0.0370 | S_m=0.0932 | S_family=0.0651 | gap=0.0561 | alpha_std=0.02863

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2413 | S_p=0.0823 | S_m=0.0865 | S_family=0.0844 | gap=0.0042 | alpha_std=0.02868

Triada 5/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3477 | S_p=0.0255 | S_m=-0.0255 | S_family=0.0000 | gap=0.0509 | alpha_std=0.02774

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3402 | S_p=0.0314 | S_m=-0.0194 | S_family=0.0060 | gap=0.0507 | alpha_std=0.02775

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3334 | S_p=0.0392 | S_m=-0.0058 | S_family=0.0167 | gap=0.0450 | alpha_std=0.02819

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3268 | S_p=0.0456 | S_m=0.0009 | S_family=0.0232 | gap=0.0447 | alpha_std=0.02817

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2678 | S_p=0.0370 | S_m=0.0924 | S_family=0.0647 | gap=0.0554 | alpha_std=0.02912

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2606 | S_p=0.0458 | S_m=0.1184 | S_family=0.0821 | gap=0.0726 | alpha_std=0.02915

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1888 | S_p=0.0048 | S_m=0.0095 | S_family=0.0071 | gap=0.0047 | alpha_std=0.02966

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1901 | S_p=0.0113 | S_m=0.0347 | S_family=0.0230 | gap=0.0234 | alpha_std=0.02966

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1432 | S_p=-0.0583 | S_m=0.0571 | S_family=-0.0006 | gap=0.1154 | alpha_std=0.02920

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1512 | S_p=-0.0351 | S_m=0.0722 | S_family=0.0185 | gap=0.1073 | alpha_std=0.02918

Triada 6/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3983 | S_p=-0.0168 | S_m=-0.0422 | S_family=-0.0295 | gap=0.0254 | alpha_std=0.02844

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3795 | S_p=-0.0103 | S_m=-0.0282 | S_family=-0.0193 | gap=0.0179 | alpha_std=0.02841

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0447 | S_p=-0.0175 | S_m=0.0158 | S_family=-0.0008 | gap=0.0334 | alpha_std=0.02689

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0559 | S_p=-0.0277 | S_m=0.0224 | S_family=-0.0026 | gap=0.0501 | alpha_std=0.02688

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2501 | S_p=0.0275 | S_m=-0.0427 | S_family=-0.0076 | gap=0.0702 | alpha_std=0.02849

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2343 | S_p=0.0575 | S_m=-0.0164 | S_family=0.0206 | gap=0.0739 | alpha_std=0.02847

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1887 | S_p=0.0290 | S_m=0.0045 | S_family=0.0168 | gap=0.0244 | alpha_std=0.02820

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1982 | S_p=0.0475 | S_m=0.0252 | S_family=0.0363 | gap=0.0223 | alpha_std=0.02821

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1948 | S_p=0.0248 | S_m=0.0345 | S_family=0.0296 | gap=0.0098 | alpha_std=0.02916

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1968 | S_p=0.0287 | S_m=0.0330 | S_family=0.0308 | gap=0.0042 | alpha_std=0.02915

Triada 7/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1097 | S_p=0.0493 | S_m=0.0212 | S_family=0.0352 | gap=0.0281 | alpha_std=0.02546

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1426 | S_p=0.0610 | S_m=0.0275 | S_family=0.0443 | gap=0.0335 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1267 | S_p=0.0550 | S_m=-0.0481 | S_family=0.0034 | gap=0.1031 | alpha_std=0.02486

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1229 | S_p=0.0659 | S_m=-0.0508 | S_family=0.0075 | gap=0.1167 | alpha_std=0.02494

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1391 | S_p=-0.0350 | S_m=0.0178 | S_family=-0.0086 | gap=0.0528 | alpha_std=0.02592

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1526 | S_p=-0.0074 | S_m=0.0382 | S_family=0.0154 | gap=0.0456 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2414 | S_p=0.0037 | S_m=0.0360 | S_family=0.0198 | gap=0.0323 | alpha_std=0.02645

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2641 | S_p=0.0084 | S_m=0.0555 | S_family=0.0319 | gap=0.0471 | alpha_std=0.02643

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2286 | S_p=0.0148 | S_m=0.0641 | S_family=0.0395 | gap=0.0493 | alpha_std=0.02554

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2298 | S_p=0.0172 | S_m=0.0668 | S_family=0.0420 | gap=0.0496 | alpha_std=0.02550

Triada 8/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1548 | S_p=0.1118 | S_m=0.0625 | S_family=0.0872 | gap=0.0493 | alpha_std=0.02554

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1414 | S_p=0.1148 | S_m=0.0772 | S_family=0.0960 | gap=0.0377 | alpha_std=0.02557

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1063 | S_p=0.1311 | S_m=-0.0046 | S_family=0.0632 | gap=0.1358 | alpha_std=0.02539

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1065 | S_p=0.1367 | S_m=0.0063 | S_family=0.0715 | gap=0.1304 | alpha_std=0.02537

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1655 | S_p=0.0916 | S_m=-0.0058 | S_family=0.0429 | gap=0.0974 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1685 | S_p=0.1036 | S_m=0.0151 | S_family=0.0594 | gap=0.0885 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1669 | S_p=0.0424 | S_m=0.0171 | S_family=0.0297 | gap=0.0252 | alpha_std=0.02558

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2009 | S_p=0.0207 | S_m=-0.0114 | S_family=0.0046 | gap=0.0321 | alpha_std=0.02552

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1801 | S_p=0.0943 | S_m=-0.0081 | S_family=0.0431 | gap=0.1024 | alpha_std=0.02640

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1909 | S_p=0.1378 | S_m=0.0060 | S_family=0.0719 | gap=0.1317 | alpha_std=0.02637

Triada 9/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1743 | S_p=0.1676 | S_m=-0.0249 | S_family=0.0713 | gap=0.1925 | alpha_std=0.02640

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2115 | S_p=0.1460 | S_m=0.0132 | S_family=0.0796 | gap=0.1328 | alpha_std=0.02536

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0948 | S_p=0.0257 | S_m=0.0170 | S_family=0.0214 | gap=0.0087 | alpha_std=0.02524

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1150 | S_p=0.0748 | S_m=-0.0341 | S_family=0.0204 | gap=0.1089 | alpha_std=0.02510

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1044 | S_p=0.0490 | S_m=-0.0266 | S_family=0.0112 | gap=0.0756 | alpha_std=0.02540

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1012 | S_p=0.0346 | S_m=-0.0387 | S_family=-0.0020 | gap=0.0733 | alpha_std=0.02535

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1584 | S_p=-0.0315 | S_m=-0.0149 | S_family=-0.0232 | gap=0.0166 | alpha_std=0.02534

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1593 | S_p=-0.0322 | S_m=-0.0137 | S_family=-0.0229 | gap=0.0185 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2283 | S_p=0.0371 | S_m=-0.0725 | S_family=-0.0177 | gap=0.1096 | alpha_std=0.02582

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2418 | S_p=0.0496 | S_m=-0.0724 | S_family=-0.0114 | gap=0.1220 | alpha_std=0.02581

Triada 10/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0333 | S_p=0.0405 | S_m=0.0302 | S_family=0.0354 | gap=0.0103 | alpha_std=0.02516

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0337 | S_p=0.0230 | S_m=0.0377 | S_family=0.0303 | gap=0.0147 | alpha_std=0.02517

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1059 | S_p=0.0638 | S_m=0.0540 | S_family=0.0589 | gap=0.0097 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1096 | S_p=0.0686 | S_m=0.0482 | S_family=0.0584 | gap=0.0204 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1033 | S_p=0.0671 | S_m=0.0506 | S_family=0.0588 | gap=0.0165 | alpha_std=0.02555

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1019 | S_p=0.0718 | S_m=0.0607 | S_family=0.0663 | gap=0.0111 | alpha_std=0.02554

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1136 | S_p=0.0815 | S_m=-0.0110 | S_family=0.0352 | gap=0.0925 | alpha_std=0.02600

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1454 | S_p=0.1151 | S_m=0.0041 | S_family=0.0596 | gap=0.1110 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1631 | S_p=0.0249 | S_m=0.0395 | S_family=0.0322 | gap=0.0146 | alpha_std=0.02578

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1546 | S_p=0.0322 | S_m=0.0602 | S_family=0.0462 | gap=0.0280 | alpha_std=0.02571

Triada 11/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2501 | S_p=0.1158 | S_m=0.0929 | S_family=0.1043 | gap=0.0229 | alpha_std=0.02561

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2441 | S_p=0.1224 | S_m=0.0965 | S_family=0.1095 | gap=0.0259 | alpha_std=0.02558

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1919 | S_p=0.0567 | S_m=0.1026 | S_family=0.0797 | gap=0.0460 | alpha_std=0.02529

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1846 | S_p=0.0765 | S_m=0.1200 | S_family=0.0982 | gap=0.0436 | alpha_std=0.02523

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0704 | S_p=0.0347 | S_m=-0.0207 | S_family=0.0070 | gap=0.0554 | alpha_std=0.02512

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0749 | S_p=0.0516 | S_m=-0.0200 | S_family=0.0158 | gap=0.0716 | alpha_std=0.02515

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0297 | S_p=0.0626 | S_m=-0.0003 | S_family=0.0312 | gap=0.0629 | alpha_std=0.02592

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2065 | S_p=0.0863 | S_m=0.0217 | S_family=0.0540 | gap=0.0646 | alpha_std=0.02637

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0552 | S_p=0.0293 | S_m=-0.0162 | S_family=0.0065 | gap=0.0455 | alpha_std=0.02527

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0734 | S_p=0.0258 | S_m=-0.0134 | S_family=0.0062 | gap=0.0391 | alpha_std=0.02530

Triada 12/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0195 | S_p=-0.0009 | S_m=0.0901 | S_family=0.0446 | gap=0.0910 | alpha_std=0.02549

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0061 | S_p=0.0089 | S_m=0.0819 | S_family=0.0454 | gap=0.0731 | alpha_std=0.02549

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0033 | S_p=-0.0431 | S_m=0.0431 | S_family=-0.0000 | gap=0.0862 | alpha_std=0.02556

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0281 | S_p=-0.0687 | S_m=0.0702 | S_family=0.0008 | gap=0.1388 | alpha_std=0.02551

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0272 | S_p=-0.0496 | S_m=0.0518 | S_family=0.0011 | gap=0.1014 | alpha_std=0.02474

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0294 | S_p=-0.0589 | S_m=0.0579 | S_family=-0.0005 | gap=0.1168 | alpha_std=0.02475

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2716 | S_p=0.1521 | S_m=0.0669 | S_family=0.1095 | gap=0.0852 | alpha_std=0.02584

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2725 | S_p=0.1642 | S_m=0.0665 | S_family=0.1153 | gap=0.0977 | alpha_std=0.02585

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2437 | S_p=0.0836 | S_m=0.0428 | S_family=0.0632 | gap=0.0409 | alpha_std=0.02585

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2243 | S_p=0.0689 | S_m=0.0195 | S_family=0.0442 | gap=0.0494 | alpha_std=0.02600

Triada 13/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0664 | S_p=0.0230 | S_m=0.0166 | S_family=0.0198 | gap=0.0064 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0836 | S_p=0.0240 | S_m=0.0297 | S_family=0.0269 | gap=0.0057 | alpha_std=0.02609

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2243 | S_p=-0.0034 | S_m=-0.0204 | S_family=-0.0119 | gap=0.0170 | alpha_std=0.02737

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2304 | S_p=0.0126 | S_m=-0.0007 | S_family=0.0060 | gap=0.0132 | alpha_std=0.02740

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3497 | S_p=0.0426 | S_m=-0.0406 | S_family=0.0010 | gap=0.0832 | alpha_std=0.02685

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3609 | S_p=0.0504 | S_m=-0.0287 | S_family=0.0108 | gap=0.0792 | alpha_std=0.02686

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2151 | S_p=0.0859 | S_m=-0.0199 | S_family=0.0330 | gap=0.1058 | alpha_std=0.02728

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2060 | S_p=0.0837 | S_m=-0.0066 | S_family=0.0385 | gap=0.0903 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1997 | S_p=0.0570 | S_m=0.0392 | S_family=0.0481 | gap=0.0178 | alpha_std=0.02773

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2201 | S_p=0.0677 | S_m=0.0287 | S_family=0.0482 | gap=0.0390 | alpha_std=0.02776

Triada 14/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4225 | S_p=-0.0063 | S_m=0.0222 | S_family=0.0080 | gap=0.0285 | alpha_std=0.02846

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4397 | S_p=-0.0031 | S_m=0.0409 | S_family=0.0189 | gap=0.0440 | alpha_std=0.02845

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.5398 | S_p=-0.0102 | S_m=0.0473 | S_family=0.0186 | gap=0.0575 | alpha_std=0.02877

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.5389 | S_p=-0.0150 | S_m=0.0504 | S_family=0.0177 | gap=0.0654 | alpha_std=0.02877

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2016 | S_p=-0.0319 | S_m=0.0574 | S_family=0.0127 | gap=0.0893 | alpha_std=0.02832

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1671 | S_p=-0.0165 | S_m=0.0628 | S_family=0.0232 | gap=0.0793 | alpha_std=0.02833

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3989 | S_p=0.0027 | S_m=0.0863 | S_family=0.0445 | gap=0.0836 | alpha_std=0.02931

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.4074 | S_p=-0.0015 | S_m=0.0891 | S_family=0.0438 | gap=0.0906 | alpha_std=0.02934

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3448 | S_p=0.0170 | S_m=0.0920 | S_family=0.0545 | gap=0.0750 | alpha_std=0.02871

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3482 | S_p=0.0157 | S_m=0.1085 | S_family=0.0621 | gap=0.0927 | alpha_std=0.02873

Triada 15/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.5047 | S_p=-0.0196 | S_m=0.0148 | S_family=-0.0024 | gap=0.0344 | alpha_std=0.02848

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4985 | S_p=-0.0155 | S_m=0.0246 | S_family=0.0045 | gap=0.0401 | alpha_std=0.02848

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3128 | S_p=0.0063 | S_m=-0.0024 | S_family=0.0019 | gap=0.0088 | alpha_std=0.02802

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2973 | S_p=-0.0028 | S_m=0.0037 | S_family=0.0004 | gap=0.0066 | alpha_std=0.02798

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4139 | S_p=-0.0534 | S_m=-0.0106 | S_family=-0.0320 | gap=0.0428 | alpha_std=0.02869

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4093 | S_p=-0.0581 | S_m=-0.0083 | S_family=-0.0332 | gap=0.0499 | alpha_std=0.02868

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1936 | S_p=-0.0520 | S_m=0.0005 | S_family=-0.0257 | gap=0.0525 | alpha_std=0.02896

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1618 | S_p=-0.0573 | S_m=0.0218 | S_family=-0.0178 | gap=0.0791 | alpha_std=0.02880

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2017 | S_p=-0.0133 | S_m=0.0436 | S_family=0.0151 | gap=0.0569 | alpha_std=0.02877

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2035 | S_p=-0.0084 | S_m=0.0522 | S_family=0.0219 | gap=0.0606 | alpha_std=0.02878

Triada 16/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2464 | S_p=-0.0072 | S_m=0.0453 | S_family=0.0190 | gap=0.0526 | alpha_std=0.02824

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2552 | S_p=-0.0016 | S_m=0.0360 | S_family=0.0172 | gap=0.0375 | alpha_std=0.02827

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0084 | S_p=0.0377 | S_m=0.0485 | S_family=0.0431 | gap=0.0108 | alpha_std=0.02703

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0121 | S_p=0.0208 | S_m=0.0342 | S_family=0.0275 | gap=0.0135 | alpha_std=0.02704

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0425 | S_p=0.0082 | S_m=0.0465 | S_family=0.0273 | gap=0.0382 | alpha_std=0.02780

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0499 | S_p=0.0028 | S_m=0.0463 | S_family=0.0246 | gap=0.0435 | alpha_std=0.02781

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=-0.0302 | S_p=0.0339 | S_m=0.0640 | S_family=0.0489 | gap=0.0302 | alpha_std=0.02798

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0311 | S_p=0.0394 | S_m=0.0609 | S_family=0.0502 | gap=0.0215 | alpha_std=0.02801

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3500 | S_p=0.0901 | S_m=0.0327 | S_family=0.0614 | gap=0.0573 | alpha_std=0.02924

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3370 | S_p=0.0888 | S_m=0.0499 | S_family=0.0693 | gap=0.0389 | alpha_std=0.02921

Triada 17/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0237 | S_p=0.0430 | S_m=-0.0096 | S_family=0.0167 | gap=0.0526 | alpha_std=0.02590

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0339 | S_p=0.0440 | S_m=-0.0086 | S_family=0.0177 | gap=0.0526 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1975 | S_p=0.0779 | S_m=0.0144 | S_family=0.0462 | gap=0.0635 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2048 | S_p=0.0741 | S_m=0.0191 | S_family=0.0466 | gap=0.0550 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4121 | S_p=0.0727 | S_m=-0.0229 | S_family=0.0249 | gap=0.0956 | alpha_std=0.02648

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4140 | S_p=0.0897 | S_m=-0.0171 | S_family=0.0363 | gap=0.1068 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0758 | S_p=0.0600 | S_m=0.0037 | S_family=0.0318 | gap=0.0563 | alpha_std=0.02621

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0596 | S_p=0.0591 | S_m=0.0114 | S_family=0.0353 | gap=0.0477 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1459 | S_p=0.1614 | S_m=-0.0052 | S_family=0.0781 | gap=0.1666 | alpha_std=0.02740

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1574 | S_p=0.1729 | S_m=0.0026 | S_family=0.0878 | gap=0.1704 | alpha_std=0.02739

Triada 18/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4963 | S_p=0.1163 | S_m=0.0142 | S_family=0.0652 | gap=0.1021 | alpha_std=0.02495

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4958 | S_p=0.1202 | S_m=0.0339 | S_family=0.0770 | gap=0.0862 | alpha_std=0.02495

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1724 | S_p=0.0045 | S_m=-0.0196 | S_family=-0.0076 | gap=0.0240 | alpha_std=0.02402

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1663 | S_p=0.0012 | S_m=-0.0092 | S_family=-0.0040 | gap=0.0104 | alpha_std=0.02405

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2919 | S_p=0.0420 | S_m=-0.0298 | S_family=0.0061 | gap=0.0718 | alpha_std=0.02498

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2989 | S_p=0.0470 | S_m=-0.0190 | S_family=0.0140 | gap=0.0660 | alpha_std=0.02496

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1010 | S_p=-0.0107 | S_m=-0.0190 | S_family=-0.0148 | gap=0.0083 | alpha_std=0.02401

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0987 | S_p=-0.0132 | S_m=-0.0176 | S_family=-0.0154 | gap=0.0044 | alpha_std=0.02401

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1494 | S_p=-0.0562 | S_m=0.0606 | S_family=0.0022 | gap=0.1168 | alpha_std=0.02486

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1670 | S_p=-0.0359 | S_m=0.0934 | S_family=0.0288 | gap=0.1293 | alpha_std=0.02482

Triada 19/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2306 | S_p=-0.0027 | S_m=0.1606 | S_family=0.0790 | gap=0.1633 | alpha_std=0.02657

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2319 | S_p=-0.0024 | S_m=0.1684 | S_family=0.0830 | gap=0.1708 | alpha_std=0.02658

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0282 | S_p=0.0287 | S_m=0.0073 | S_family=0.0180 | gap=0.0214 | alpha_std=0.02501

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0311 | S_p=0.0306 | S_m=0.0127 | S_family=0.0217 | gap=0.0180 | alpha_std=0.02504

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0562 | S_p=-0.0557 | S_m=0.0051 | S_family=-0.0253 | gap=0.0607 | alpha_std=0.02478

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0728 | S_p=-0.0381 | S_m=0.0118 | S_family=-0.0132 | gap=0.0499 | alpha_std=0.02472

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1360 | S_p=-0.0185 | S_m=0.0789 | S_family=0.0302 | gap=0.0975 | alpha_std=0.02570

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1344 | S_p=0.0127 | S_m=0.0879 | S_family=0.0503 | gap=0.0752 | alpha_std=0.02554

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0216 | S_p=-0.0035 | S_m=-0.0618 | S_family=-0.0327 | gap=0.0583 | alpha_std=0.02519

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0228 | S_p=-0.0116 | S_m=-0.0712 | S_family=-0.0414 | gap=0.0597 | alpha_std=0.02519

Triada 20/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0122 | S_p=-0.0407 | S_m=-0.0379 | S_family=-0.0393 | gap=0.0029 | alpha_std=0.02528

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0056 | S_p=-0.0320 | S_m=-0.0396 | S_family=-0.0358 | gap=0.0076 | alpha_std=0.02529

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1602 | S_p=-0.0185 | S_m=0.0195 | S_family=0.0005 | gap=0.0381 | alpha_std=0.02546

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1632 | S_p=0.0020 | S_m=0.0241 | S_family=0.0131 | gap=0.0222 | alpha_std=0.02545

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1729 | S_p=-0.0385 | S_m=-0.0699 | S_family=-0.0542 | gap=0.0314 | alpha_std=0.02511

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1728 | S_p=-0.0351 | S_m=-0.0833 | S_family=-0.0592 | gap=0.0482 | alpha_std=0.02514

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3406 | S_p=0.1377 | S_m=-0.0583 | S_family=0.0397 | gap=0.1960 | alpha_std=0.02689

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3423 | S_p=0.1379 | S_m=-0.0521 | S_family=0.0429 | gap=0.1900 | alpha_std=0.02688

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1194 | S_p=0.0661 | S_m=0.0314 | S_family=0.0488 | gap=0.0347 | alpha_std=0.02621

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1348 | S_p=0.0753 | S_m=0.0462 | S_family=0.0608 | gap=0.0290 | alpha_std=0.02621

Triada 21/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0138 | S_p=0.0164 | S_m=-0.0210 | S_family=-0.0023 | gap=0.0375 | alpha_std=0.02496

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0157 | S_p=0.0144 | S_m=-0.0150 | S_family=-0.0003 | gap=0.0295 | alpha_std=0.02496

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0123 | S_p=0.0486 | S_m=0.0109 | S_family=0.0298 | gap=0.0378 | alpha_std=0.02500

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0074 | S_p=0.0449 | S_m=0.0058 | S_family=0.0254 | gap=0.0391 | alpha_std=0.02508

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0129 | S_p=0.0124 | S_m=-0.0989 | S_family=-0.0432 | gap=0.1112 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0251 | S_p=0.0203 | S_m=-0.0888 | S_family=-0.0343 | gap=0.1091 | alpha_std=0.02570

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0288 | S_p=0.0180 | S_m=0.0017 | S_family=0.0099 | gap=0.0164 | alpha_std=0.02567

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0375 | S_p=0.0163 | S_m=-0.0055 | S_family=0.0054 | gap=0.0218 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0879 | S_p=-0.0303 | S_m=-0.0223 | S_family=-0.0263 | gap=0.0080 | alpha_std=0.02591

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0878 | S_p=-0.0233 | S_m=-0.0153 | S_family=-0.0193 | gap=0.0080 | alpha_std=0.02592

Triada 22/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4070 | S_p=0.0200 | S_m=-0.0926 | S_family=-0.0363 | gap=0.1126 | alpha_std=0.02911

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2965 | S_p=0.0905 | S_m=-0.0855 | S_family=0.0025 | gap=0.1760 | alpha_std=0.02907

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0252 | S_p=-0.0678 | S_m=-0.0399 | S_family=-0.0539 | gap=0.0279 | alpha_std=0.02821

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0228 | S_p=-0.0281 | S_m=0.0091 | S_family=-0.0095 | gap=0.0372 | alpha_std=0.02825

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1067 | S_p=-0.0021 | S_m=-0.0032 | S_family=-0.0026 | gap=0.0011 | alpha_std=0.02981

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1107 | S_p=-0.0004 | S_m=0.0038 | S_family=0.0017 | gap=0.0041 | alpha_std=0.02982

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2566 | S_p=0.0343 | S_m=-0.0613 | S_family=-0.0135 | gap=0.0956 | alpha_std=0.02953

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2278 | S_p=0.0357 | S_m=-0.0268 | S_family=0.0044 | gap=0.0626 | alpha_std=0.02954

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0138 | S_p=0.1303 | S_m=-0.0014 | S_family=0.0644 | gap=0.1318 | alpha_std=0.02930

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0370 | S_p=0.1152 | S_m=-0.0075 | S_family=0.0539 | gap=0.1227 | alpha_std=0.02932

Triada 23/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2632 | S_p=0.0385 | S_m=0.0575 | S_family=0.0480 | gap=0.0189 | alpha_std=0.02923

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2705 | S_p=0.0341 | S_m=0.0564 | S_family=0.0452 | gap=0.0224 | alpha_std=0.02928

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3347 | S_p=0.0543 | S_m=0.0282 | S_family=0.0413 | gap=0.0261 | alpha_std=0.02907

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3372 | S_p=0.0600 | S_m=0.0292 | S_family=0.0446 | gap=0.0308 | alpha_std=0.02896

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2639 | S_p=0.1080 | S_m=-0.0104 | S_family=0.0488 | gap=0.1184 | alpha_std=0.02907

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2398 | S_p=0.0675 | S_m=-0.0221 | S_family=0.0227 | gap=0.0896 | alpha_std=0.02954

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1789 | S_p=0.0660 | S_m=0.0101 | S_family=0.0380 | gap=0.0560 | alpha_std=0.02985

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1833 | S_p=0.0759 | S_m=0.0095 | S_family=0.0427 | gap=0.0664 | alpha_std=0.02983

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1719 | S_p=0.1316 | S_m=-0.0088 | S_family=0.0614 | gap=0.1404 | alpha_std=0.02976

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1807 | S_p=0.1619 | S_m=-0.0182 | S_family=0.0719 | gap=0.1801 | alpha_std=0.02994

Triada 24/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4446 | S_p=0.0644 | S_m=0.1488 | S_family=0.1066 | gap=0.0844 | alpha_std=0.03052

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4299 | S_p=0.0694 | S_m=0.1557 | S_family=0.1125 | gap=0.0863 | alpha_std=0.03050

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3765 | S_p=0.0441 | S_m=0.0468 | S_family=0.0454 | gap=0.0027 | alpha_std=0.03009

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3748 | S_p=0.0472 | S_m=0.0511 | S_family=0.0491 | gap=0.0039 | alpha_std=0.03007

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2631 | S_p=0.0762 | S_m=0.0129 | S_family=0.0445 | gap=0.0633 | alpha_std=0.03009

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2484 | S_p=0.0837 | S_m=0.0383 | S_family=0.0610 | gap=0.0454 | alpha_std=0.03015

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2752 | S_p=-0.0050 | S_m=0.0105 | S_family=0.0027 | gap=0.0156 | alpha_std=0.03054

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2411 | S_p=-0.0142 | S_m=-0.0004 | S_family=-0.0073 | gap=0.0138 | alpha_std=0.03057

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2573 | S_p=0.0374 | S_m=0.0627 | S_family=0.0501 | gap=0.0253 | alpha_std=0.03049

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2570 | S_p=0.0358 | S_m=0.0486 | S_family=0.0422 | gap=0.0129 | alpha_std=0.03054

Triada 25/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0480 | S_p=0.0219 | S_m=-0.0557 | S_family=-0.0169 | gap=0.0776 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0391 | S_p=0.0005 | S_m=-0.0480 | S_family=-0.0237 | gap=0.0486 | alpha_std=0.02572

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0383 | S_p=-0.0766 | S_m=0.0025 | S_family=-0.0371 | gap=0.0791 | alpha_std=0.02564

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0516 | S_p=-0.0955 | S_m=0.0268 | S_family=-0.0344 | gap=0.1223 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3226 | S_p=-0.0451 | S_m=0.0013 | S_family=-0.0219 | gap=0.0464 | alpha_std=0.02669

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3567 | S_p=-0.0469 | S_m=0.0129 | S_family=-0.0170 | gap=0.0598 | alpha_std=0.02654

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1582 | S_p=-0.0851 | S_m=0.0397 | S_family=-0.0227 | gap=0.1247 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1584 | S_p=-0.0853 | S_m=0.0292 | S_family=-0.0280 | gap=0.1145 | alpha_std=0.02625

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2830 | S_p=-0.0272 | S_m=0.0140 | S_family=-0.0066 | gap=0.0413 | alpha_std=0.02634

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2865 | S_p=-0.0475 | S_m=0.0470 | S_family=-0.0002 | gap=0.0945 | alpha_std=0.02606

Triada 26/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0113 | S_p=-0.0417 | S_m=-0.0078 | S_family=-0.0248 | gap=0.0340 | alpha_std=0.02530

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0143 | S_p=-0.0399 | S_m=-0.0052 | S_family=-0.0226 | gap=0.0347 | alpha_std=0.02516

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0661 | S_p=-0.0424 | S_m=-0.0028 | S_family=-0.0226 | gap=0.0397 | alpha_std=0.02535

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0818 | S_p=-0.0458 | S_m=-0.0264 | S_family=-0.0361 | gap=0.0194 | alpha_std=0.02551

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0083 | S_p=-0.0485 | S_m=0.0020 | S_family=-0.0232 | gap=0.0505 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0091 | S_p=-0.0450 | S_m=0.0041 | S_family=-0.0205 | gap=0.0491 | alpha_std=0.02542

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2522 | S_p=-0.0697 | S_m=-0.1126 | S_family=-0.0912 | gap=0.0429 | alpha_std=0.02562

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2583 | S_p=-0.0670 | S_m=-0.1176 | S_family=-0.0923 | gap=0.0506 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2243 | S_p=0.0012 | S_m=0.0980 | S_family=0.0496 | gap=0.0968 | alpha_std=0.02592

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2236 | S_p=-0.0096 | S_m=0.0818 | S_family=0.0361 | gap=0.0914 | alpha_std=0.02620

Triada 27/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4513 | S_p=-0.0385 | S_m=0.1208 | S_family=0.0412 | gap=0.1593 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4533 | S_p=-0.0327 | S_m=0.1342 | S_family=0.0507 | gap=0.1669 | alpha_std=0.02652

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0154 | S_p=0.0787 | S_m=0.0009 | S_family=0.0398 | gap=0.0779 | alpha_std=0.02532

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0164 | S_p=0.0813 | S_m=-0.0057 | S_family=0.0378 | gap=0.0870 | alpha_std=0.02528

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4667 | S_p=-0.0403 | S_m=0.1029 | S_family=0.0313 | gap=0.1433 | alpha_std=0.02609

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4589 | S_p=-0.0443 | S_m=0.1108 | S_family=0.0332 | gap=0.1551 | alpha_std=0.02608

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3097 | S_p=0.0126 | S_m=0.0513 | S_family=0.0319 | gap=0.0387 | alpha_std=0.02597

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3122 | S_p=0.0064 | S_m=0.0469 | S_family=0.0266 | gap=0.0405 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2114 | S_p=-0.0104 | S_m=-0.0415 | S_family=-0.0260 | gap=0.0311 | alpha_std=0.02630

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2202 | S_p=0.0132 | S_m=-0.0352 | S_family=-0.0110 | gap=0.0484 | alpha_std=0.02631

Triada 28/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0284 | S_p=0.0621 | S_m=0.0397 | S_family=0.0509 | gap=0.0224 | alpha_std=0.02561

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0671 | S_p=0.0135 | S_m=-0.0379 | S_family=-0.0122 | gap=0.0514 | alpha_std=0.02558

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4772 | S_p=0.0137 | S_m=0.0704 | S_family=0.0420 | gap=0.0567 | alpha_std=0.02663

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4807 | S_p=0.0539 | S_m=0.1232 | S_family=0.0885 | gap=0.0694 | alpha_std=0.02669

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.5345 | S_p=0.0149 | S_m=0.0784 | S_family=0.0467 | gap=0.0635 | alpha_std=0.02713

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.5264 | S_p=0.0327 | S_m=0.0968 | S_family=0.0648 | gap=0.0641 | alpha_std=0.02712

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.4606 | S_p=0.0152 | S_m=0.1346 | S_family=0.0749 | gap=0.1194 | alpha_std=0.02681

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.4646 | S_p=0.0251 | S_m=0.1378 | S_family=0.0815 | gap=0.1127 | alpha_std=0.02689

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1282 | S_p=-0.0085 | S_m=0.1342 | S_family=0.0629 | gap=0.1427 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1335 | S_p=0.0047 | S_m=0.1354 | S_family=0.0701 | gap=0.1307 | alpha_std=0.02603

Triada 29/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4822 | S_p=0.0919 | S_m=0.0177 | S_family=0.0548 | gap=0.0742 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4786 | S_p=0.0947 | S_m=0.0341 | S_family=0.0644 | gap=0.0606 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1275 | S_p=-0.0078 | S_m=-0.0265 | S_family=-0.0171 | gap=0.0187 | alpha_std=0.02509

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1236 | S_p=-0.0087 | S_m=-0.0656 | S_family=-0.0371 | gap=0.0569 | alpha_std=0.02523

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2356 | S_p=-0.0070 | S_m=0.0626 | S_family=0.0278 | gap=0.0695 | alpha_std=0.02592

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2359 | S_p=-0.0043 | S_m=0.0586 | S_family=0.0272 | gap=0.0629 | alpha_std=0.02593

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.4352 | S_p=-0.0366 | S_m=-0.0238 | S_family=-0.0302 | gap=0.0128 | alpha_std=0.02632

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.4329 | S_p=-0.0298 | S_m=-0.0224 | S_family=-0.0261 | gap=0.0074 | alpha_std=0.02631

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3771 | S_p=0.0288 | S_m=0.0244 | S_family=0.0266 | gap=0.0043 | alpha_std=0.02674

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3706 | S_p=0.0365 | S_m=0.0410 | S_family=0.0388 | gap=0.0045 | alpha_std=0.02679

Triada 30/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0386 | S_p=-0.0060 | S_m=-0.0487 | S_family=-0.0273 | gap=0.0427 | alpha_std=0.02675

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0491 | S_p=0.0038 | S_m=-0.0416 | S_family=-0.0189 | gap=0.0454 | alpha_std=0.02674

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2031 | S_p=0.0148 | S_m=0.0102 | S_family=0.0125 | gap=0.0046 | alpha_std=0.02695

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1870 | S_p=0.0144 | S_m=0.0204 | S_family=0.0174 | gap=0.0059 | alpha_std=0.02690

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1719 | S_p=0.0048 | S_m=0.0407 | S_family=0.0227 | gap=0.0359 | alpha_std=0.02749

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1506 | S_p=0.0194 | S_m=0.0430 | S_family=0.0312 | gap=0.0237 | alpha_std=0.02745

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=-0.0053 | S_p=-0.1137 | S_m=0.0128 | S_family=-0.0505 | gap=0.1265 | alpha_std=0.02717

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0206 | S_p=-0.1111 | S_m=0.0046 | S_family=-0.0533 | gap=0.1157 | alpha_std=0.02715

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1867 | S_p=0.0758 | S_m=0.0963 | S_family=0.0860 | gap=0.0205 | alpha_std=0.02796

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1800 | S_p=0.0831 | S_m=0.1057 | S_family=0.0944 | gap=0.0226 | alpha_std=0.02800

Triada 31/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0531 | S_p=-0.0704 | S_m=0.0244 | S_family=-0.0230 | gap=0.0948 | alpha_std=0.02682

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0580 | S_p=-0.0681 | S_m=0.0280 | S_family=-0.0201 | gap=0.0961 | alpha_std=0.02686

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0985 | S_p=-0.0881 | S_m=0.0302 | S_family=-0.0290 | gap=0.1183 | alpha_std=0.02633

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1517 | S_p=-0.0544 | S_m=-0.0057 | S_family=-0.0301 | gap=0.0488 | alpha_std=0.02641

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1265 | S_p=-0.1135 | S_m=-0.0100 | S_family=-0.0618 | gap=0.1035 | alpha_std=0.02693

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0635 | S_p=-0.1387 | S_m=-0.0124 | S_family=-0.0755 | gap=0.1263 | alpha_std=0.02691

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1085 | S_p=-0.0327 | S_m=-0.0620 | S_family=-0.0473 | gap=0.0293 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0907 | S_p=-0.0165 | S_m=-0.0431 | S_family=-0.0298 | gap=0.0266 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1445 | S_p=-0.0732 | S_m=0.0092 | S_family=-0.0320 | gap=0.0824 | alpha_std=0.02771

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1426 | S_p=-0.0535 | S_m=0.0255 | S_family=-0.0140 | gap=0.0790 | alpha_std=0.02769

Triada 32/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4415 | S_p=0.1351 | S_m=0.0258 | S_family=0.0804 | gap=0.1093 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4355 | S_p=0.1361 | S_m=0.0384 | S_family=0.0873 | gap=0.0977 | alpha_std=0.02747

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3883 | S_p=0.1186 | S_m=0.0417 | S_family=0.0802 | gap=0.0769 | alpha_std=0.02769

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3703 | S_p=0.1240 | S_m=0.0399 | S_family=0.0820 | gap=0.0842 | alpha_std=0.02772

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3300 | S_p=0.1376 | S_m=0.0322 | S_family=0.0849 | gap=0.1054 | alpha_std=0.02739

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3692 | S_p=0.1613 | S_m=0.0210 | S_family=0.0911 | gap=0.1403 | alpha_std=0.02742

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1193 | S_p=0.0511 | S_m=-0.0028 | S_family=0.0242 | gap=0.0539 | alpha_std=0.02677

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1315 | S_p=0.0499 | S_m=-0.0106 | S_family=0.0196 | gap=0.0605 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2458 | S_p=0.1758 | S_m=-0.0476 | S_family=0.0641 | gap=0.2234 | alpha_std=0.02785

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2419 | S_p=0.1921 | S_m=-0.0374 | S_family=0.0773 | gap=0.2295 | alpha_std=0.02786

Triada 33/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3423 | S_p=0.0116 | S_m=0.0016 | S_family=0.0066 | gap=0.0100 | alpha_std=0.02759

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4004 | S_p=0.0250 | S_m=-0.0077 | S_family=0.0087 | gap=0.0327 | alpha_std=0.02761

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3750 | S_p=0.0140 | S_m=-0.0023 | S_family=0.0059 | gap=0.0162 | alpha_std=0.02695

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3577 | S_p=0.0262 | S_m=0.0038 | S_family=0.0150 | gap=0.0223 | alpha_std=0.02693

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2997 | S_p=-0.0293 | S_m=-0.0692 | S_family=-0.0492 | gap=0.0399 | alpha_std=0.02697

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2988 | S_p=-0.0178 | S_m=-0.0719 | S_family=-0.0448 | gap=0.0542 | alpha_std=0.02695

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3145 | S_p=0.0754 | S_m=0.0171 | S_family=0.0462 | gap=0.0582 | alpha_std=0.02839

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3136 | S_p=0.0818 | S_m=0.0242 | S_family=0.0530 | gap=0.0576 | alpha_std=0.02837

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1337 | S_p=0.0568 | S_m=-0.0770 | S_family=-0.0101 | gap=0.1338 | alpha_std=0.02703

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1306 | S_p=0.0668 | S_m=-0.0664 | S_family=0.0002 | gap=0.1332 | alpha_std=0.02699

Triada 34/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1478 | S_p=-0.0579 | S_m=-0.0673 | S_family=-0.0626 | gap=0.0094 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1569 | S_p=-0.0415 | S_m=-0.0685 | S_family=-0.0550 | gap=0.0271 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1602 | S_p=0.0853 | S_m=-0.0200 | S_family=0.0326 | gap=0.1053 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1615 | S_p=0.0930 | S_m=0.0093 | S_family=0.0511 | gap=0.0836 | alpha_std=0.02677

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0730 | S_p=0.0457 | S_m=0.0000 | S_family=0.0229 | gap=0.0457 | alpha_std=0.02654

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0478 | S_p=0.0390 | S_m=0.0157 | S_family=0.0273 | gap=0.0233 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0154 | S_p=-0.0031 | S_m=0.0094 | S_family=0.0032 | gap=0.0126 | alpha_std=0.02618

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0148 | S_p=0.0098 | S_m=0.0149 | S_family=0.0123 | gap=0.0051 | alpha_std=0.02620

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1125 | S_p=0.0285 | S_m=-0.0182 | S_family=0.0052 | gap=0.0467 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1054 | S_p=0.0514 | S_m=0.0356 | S_family=0.0435 | gap=0.0158 | alpha_std=0.02621

Triada 35/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2323 | S_p=0.0502 | S_m=-0.0596 | S_family=-0.0047 | gap=0.1098 | alpha_std=0.02662

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2350 | S_p=0.0539 | S_m=-0.0469 | S_family=0.0035 | gap=0.1008 | alpha_std=0.02671

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0255 | S_p=-0.0523 | S_m=-0.0232 | S_family=-0.0377 | gap=0.0291 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0289 | S_p=-0.0611 | S_m=-0.0231 | S_family=-0.0421 | gap=0.0379 | alpha_std=0.02611

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0509 | S_p=-0.0857 | S_m=0.0318 | S_family=-0.0270 | gap=0.1175 | alpha_std=0.02617

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0509 | S_p=-0.0888 | S_m=0.0327 | S_family=-0.0281 | gap=0.1215 | alpha_std=0.02618

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1789 | S_p=-0.0401 | S_m=-0.0226 | S_family=-0.0313 | gap=0.0175 | alpha_std=0.02677

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1920 | S_p=-0.0294 | S_m=-0.0205 | S_family=-0.0250 | gap=0.0089 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0174 | S_p=-0.0658 | S_m=0.0356 | S_family=-0.0151 | gap=0.1014 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0130 | S_p=-0.0705 | S_m=0.0380 | S_family=-0.0162 | gap=0.1086 | alpha_std=0.02604

Triada 36/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1558 | S_p=0.0661 | S_m=-0.0326 | S_family=0.0168 | gap=0.0988 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1681 | S_p=0.0843 | S_m=-0.0317 | S_family=0.0263 | gap=0.1160 | alpha_std=0.02653

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0866 | S_p=0.0173 | S_m=0.0311 | S_family=0.0242 | gap=0.0138 | alpha_std=0.02659

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0921 | S_p=0.0168 | S_m=0.0255 | S_family=0.0212 | gap=0.0087 | alpha_std=0.02658

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0264 | S_p=0.0047 | S_m=0.0057 | S_family=0.0052 | gap=0.0010 | alpha_std=0.02633

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0371 | S_p=0.0302 | S_m=-0.0189 | S_family=0.0057 | gap=0.0491 | alpha_std=0.02642

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1796 | S_p=0.0014 | S_m=-0.0133 | S_family=-0.0060 | gap=0.0148 | alpha_std=0.02695

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2077 | S_p=-0.0141 | S_m=-0.0012 | S_family=-0.0077 | gap=0.0129 | alpha_std=0.02697

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1850 | S_p=0.0070 | S_m=0.0160 | S_family=0.0115 | gap=0.0090 | alpha_std=0.02738

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2117 | S_p=0.0092 | S_m=0.0131 | S_family=0.0111 | gap=0.0039 | alpha_std=0.02738

Triada 37/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2563 | S_p=0.0382 | S_m=0.0177 | S_family=0.0279 | gap=0.0205 | alpha_std=0.02818

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2656 | S_p=0.0404 | S_m=0.0009 | S_family=0.0207 | gap=0.0395 | alpha_std=0.02822

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2877 | S_p=0.0384 | S_m=-0.0730 | S_family=-0.0173 | gap=0.1114 | alpha_std=0.02701

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2856 | S_p=0.0455 | S_m=-0.0626 | S_family=-0.0086 | gap=0.1081 | alpha_std=0.02701

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2748 | S_p=0.0342 | S_m=-0.0723 | S_family=-0.0191 | gap=0.1064 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3203 | S_p=0.0267 | S_m=-0.0327 | S_family=-0.0030 | gap=0.0593 | alpha_std=0.02744

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3247 | S_p=0.1286 | S_m=-0.0111 | S_family=0.0587 | gap=0.1397 | alpha_std=0.02829

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3408 | S_p=0.1247 | S_m=-0.0055 | S_family=0.0596 | gap=0.1302 | alpha_std=0.02838

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3823 | S_p=0.0703 | S_m=0.0212 | S_family=0.0457 | gap=0.0491 | alpha_std=0.02831

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3824 | S_p=0.0809 | S_m=0.0352 | S_family=0.0581 | gap=0.0457 | alpha_std=0.02827

Triada 38/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4535 | S_p=-0.0096 | S_m=-0.0058 | S_family=-0.0077 | gap=0.0038 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4655 | S_p=0.0039 | S_m=0.0267 | S_family=0.0153 | gap=0.0229 | alpha_std=0.02759

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4554 | S_p=-0.0281 | S_m=0.0017 | S_family=-0.0132 | gap=0.0298 | alpha_std=0.02720

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4572 | S_p=-0.0149 | S_m=0.0103 | S_family=-0.0023 | gap=0.0252 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3951 | S_p=-0.0182 | S_m=-0.1039 | S_family=-0.0610 | gap=0.0857 | alpha_std=0.02704

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3796 | S_p=-0.0297 | S_m=-0.1018 | S_family=-0.0657 | gap=0.0721 | alpha_std=0.02711

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0881 | S_p=0.0535 | S_m=-0.0710 | S_family=-0.0088 | gap=0.1245 | alpha_std=0.02679

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0938 | S_p=0.0531 | S_m=-0.0766 | S_family=-0.0118 | gap=0.1298 | alpha_std=0.02680

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0660 | S_p=-0.0078 | S_m=0.0476 | S_family=0.0199 | gap=0.0555 | alpha_std=0.02834

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0784 | S_p=0.0304 | S_m=-0.0025 | S_family=0.0139 | gap=0.0328 | alpha_std=0.02816

Triada 39/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0975 | S_p=0.0752 | S_m=-0.0337 | S_family=0.0207 | gap=0.1089 | alpha_std=0.02827

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0797 | S_p=0.0289 | S_m=0.0071 | S_family=0.0180 | gap=0.0218 | alpha_std=0.02829

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0825 | S_p=0.0088 | S_m=0.0730 | S_family=0.0409 | gap=0.0643 | alpha_std=0.02831

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0707 | S_p=0.0107 | S_m=0.0661 | S_family=0.0384 | gap=0.0555 | alpha_std=0.02834

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1318 | S_p=0.0807 | S_m=-0.0001 | S_family=0.0403 | gap=0.0808 | alpha_std=0.02858

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1367 | S_p=0.0897 | S_m=0.0081 | S_family=0.0489 | gap=0.0816 | alpha_std=0.02857

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0154 | S_p=0.0790 | S_m=-0.0053 | S_family=0.0369 | gap=0.0843 | alpha_std=0.02827

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0256 | S_p=0.0697 | S_m=-0.0004 | S_family=0.0346 | gap=0.0702 | alpha_std=0.02825

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0902 | S_p=0.0159 | S_m=-0.0281 | S_family=-0.0061 | gap=0.0440 | alpha_std=0.02827

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0865 | S_p=0.0187 | S_m=-0.0200 | S_family=-0.0006 | gap=0.0387 | alpha_std=0.02827

Triada 40/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0376 | S_p=0.0220 | S_m=0.0470 | S_family=0.0345 | gap=0.0251 | alpha_std=0.02781

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0397 | S_p=0.0210 | S_m=0.0470 | S_family=0.0340 | gap=0.0260 | alpha_std=0.02779

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1953 | S_p=0.0194 | S_m=0.0510 | S_family=0.0352 | gap=0.0316 | alpha_std=0.02811

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2006 | S_p=0.0208 | S_m=0.0540 | S_family=0.0374 | gap=0.0332 | alpha_std=0.02815

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4087 | S_p=0.0030 | S_m=0.0267 | S_family=0.0148 | gap=0.0238 | alpha_std=0.02960

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4056 | S_p=0.0161 | S_m=0.0374 | S_family=0.0268 | gap=0.0214 | alpha_std=0.02958

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2248 | S_p=0.0383 | S_m=0.1383 | S_family=0.0883 | gap=0.0999 | alpha_std=0.02838

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2258 | S_p=0.0469 | S_m=0.1325 | S_family=0.0897 | gap=0.0857 | alpha_std=0.02838

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3477 | S_p=-0.0399 | S_m=0.0531 | S_family=0.0066 | gap=0.0930 | alpha_std=0.02948

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3575 | S_p=-0.0399 | S_m=0.0604 | S_family=0.0102 | gap=0.1003 | alpha_std=0.02944

Triada 41/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1664 | S_p=0.0395 | S_m=-0.0195 | S_family=0.0100 | gap=0.0590 | alpha_std=0.02830

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1679 | S_p=0.0489 | S_m=-0.0289 | S_family=0.0100 | gap=0.0779 | alpha_std=0.02831

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0562 | S_p=-0.0013 | S_m=0.0111 | S_family=0.0049 | gap=0.0124 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0638 | S_p=-0.0046 | S_m=0.0122 | S_family=0.0038 | gap=0.0168 | alpha_std=0.02724

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3797 | S_p=0.0046 | S_m=0.0639 | S_family=0.0343 | gap=0.0593 | alpha_std=0.02838

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3899 | S_p=0.0110 | S_m=0.0695 | S_family=0.0402 | gap=0.0585 | alpha_std=0.02852

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1813 | S_p=0.0186 | S_m=0.1003 | S_family=0.0594 | gap=0.0817 | alpha_std=0.02882

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1790 | S_p=0.0151 | S_m=0.1121 | S_family=0.0636 | gap=0.0970 | alpha_std=0.02879

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3385 | S_p=0.0463 | S_m=0.1013 | S_family=0.0738 | gap=0.0550 | alpha_std=0.02926

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3445 | S_p=0.0550 | S_m=0.1082 | S_family=0.0816 | gap=0.0532 | alpha_std=0.02926

Triada 42/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0065 | S_p=-0.0624 | S_m=-0.0541 | S_family=-0.0583 | gap=0.0084 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0299 | S_p=-0.0440 | S_m=-0.0739 | S_family=-0.0590 | gap=0.0300 | alpha_std=0.02553

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1363 | S_p=-0.0367 | S_m=0.0178 | S_family=-0.0094 | gap=0.0546 | alpha_std=0.02666

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1455 | S_p=0.0061 | S_m=-0.0168 | S_family=-0.0053 | gap=0.0230 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0356 | S_p=-0.0013 | S_m=-0.0888 | S_family=-0.0451 | gap=0.0875 | alpha_std=0.02559

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0331 | S_p=-0.0059 | S_m=-0.0909 | S_family=-0.0484 | gap=0.0850 | alpha_std=0.02557

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=-0.0659 | S_p=-0.0702 | S_m=-0.0226 | S_family=-0.0464 | gap=0.0476 | alpha_std=0.02608

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0580 | S_p=-0.0434 | S_m=0.0019 | S_family=-0.0208 | gap=0.0453 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1649 | S_p=0.0859 | S_m=0.0294 | S_family=0.0576 | gap=0.0566 | alpha_std=0.02646

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1493 | S_p=0.0727 | S_m=0.0327 | S_family=0.0527 | gap=0.0400 | alpha_std=0.02643

Triada 43/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1763 | S_p=-0.0739 | S_m=-0.0850 | S_family=-0.0795 | gap=0.0111 | alpha_std=0.02643

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1488 | S_p=-0.0636 | S_m=-0.1106 | S_family=-0.0871 | gap=0.0470 | alpha_std=0.02643

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0667 | S_p=-0.0615 | S_m=-0.0321 | S_family=-0.0468 | gap=0.0294 | alpha_std=0.02573

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0669 | S_p=-0.0732 | S_m=-0.0175 | S_family=-0.0454 | gap=0.0557 | alpha_std=0.02572

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0039 | S_p=0.0096 | S_m=-0.0351 | S_family=-0.0128 | gap=0.0448 | alpha_std=0.02629

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0300 | S_p=-0.0020 | S_m=-0.0868 | S_family=-0.0444 | gap=0.0848 | alpha_std=0.02633

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=-0.0223 | S_p=-0.0142 | S_m=-0.0714 | S_family=-0.0428 | gap=0.0572 | alpha_std=0.02536

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0160 | S_p=-0.0068 | S_m=-0.0741 | S_family=-0.0405 | gap=0.0673 | alpha_std=0.02534

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1191 | S_p=-0.0314 | S_m=-0.1269 | S_family=-0.0791 | gap=0.0955 | alpha_std=0.02734

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1139 | S_p=-0.0463 | S_m=-0.0936 | S_family=-0.0699 | gap=0.0472 | alpha_std=0.02733

Triada 44/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0121 | S_p=0.0032 | S_m=-0.0569 | S_family=-0.0268 | gap=0.0601 | alpha_std=0.02581

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0055 | S_p=0.0044 | S_m=-0.0574 | S_family=-0.0265 | gap=0.0618 | alpha_std=0.02582

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1522 | S_p=-0.0141 | S_m=0.0399 | S_family=0.0129 | gap=0.0540 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1485 | S_p=-0.0198 | S_m=0.0147 | S_family=-0.0025 | gap=0.0345 | alpha_std=0.02620

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0328 | S_p=-0.1340 | S_m=-0.0575 | S_family=-0.0958 | gap=0.0766 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0112 | S_p=-0.1396 | S_m=-0.0468 | S_family=-0.0932 | gap=0.0927 | alpha_std=0.02650

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0735 | S_p=0.0516 | S_m=-0.0652 | S_family=-0.0068 | gap=0.1169 | alpha_std=0.02600

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0701 | S_p=0.0309 | S_m=-0.0769 | S_family=-0.0230 | gap=0.1079 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1389 | S_p=-0.0121 | S_m=0.0036 | S_family=-0.0042 | gap=0.0157 | alpha_std=0.02675

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1439 | S_p=0.0092 | S_m=0.0279 | S_family=0.0186 | gap=0.0187 | alpha_std=0.02670

Triada 45/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0539 | S_p=0.0020 | S_m=-0.0110 | S_family=-0.0045 | gap=0.0130 | alpha_std=0.02624

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0559 | S_p=0.0056 | S_m=-0.0057 | S_family=-0.0000 | gap=0.0113 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2823 | S_p=-0.0406 | S_m=0.0214 | S_family=-0.0096 | gap=0.0620 | alpha_std=0.02835

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2839 | S_p=-0.0303 | S_m=0.0528 | S_family=0.0113 | gap=0.0831 | alpha_std=0.02833

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0006 | S_p=-0.0473 | S_m=0.0845 | S_family=0.0186 | gap=0.1317 | alpha_std=0.02682

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0138 | S_p=-0.0496 | S_m=0.0817 | S_family=0.0161 | gap=0.1313 | alpha_std=0.02675

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1296 | S_p=0.0173 | S_m=-0.0403 | S_family=-0.0115 | gap=0.0576 | alpha_std=0.02742

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1346 | S_p=0.0255 | S_m=-0.0255 | S_family=0.0000 | gap=0.0510 | alpha_std=0.02732

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=-0.0104 | S_p=-0.0110 | S_m=-0.0271 | S_family=-0.0191 | gap=0.0160 | alpha_std=0.02727

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0666 | S_p=0.0277 | S_m=-0.1162 | S_family=-0.0442 | gap=0.1439 | alpha_std=0.02715

Triada 46/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2427 | S_p=-0.0442 | S_m=0.1429 | S_family=0.0493 | gap=0.1871 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1975 | S_p=-0.0455 | S_m=0.1439 | S_family=0.0492 | gap=0.1894 | alpha_std=0.02746

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2429 | S_p=-0.0548 | S_m=0.0291 | S_family=-0.0129 | gap=0.0839 | alpha_std=0.02820

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2347 | S_p=-0.0475 | S_m=0.0428 | S_family=-0.0023 | gap=0.0903 | alpha_std=0.02825

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1259 | S_p=-0.0511 | S_m=0.0949 | S_family=0.0219 | gap=0.1460 | alpha_std=0.02851

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1209 | S_p=-0.0521 | S_m=0.1039 | S_family=0.0259 | gap=0.1560 | alpha_std=0.02844

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1980 | S_p=-0.1007 | S_m=0.0498 | S_family=-0.0254 | gap=0.1505 | alpha_std=0.02887

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1428 | S_p=-0.0829 | S_m=0.0698 | S_family=-0.0065 | gap=0.1526 | alpha_std=0.02884

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1382 | S_p=-0.0860 | S_m=0.0055 | S_family=-0.0403 | gap=0.0915 | alpha_std=0.02830

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1354 | S_p=-0.0752 | S_m=0.0065 | S_family=-0.0344 | gap=0.0816 | alpha_std=0.02829

Triada 47/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3017 | S_p=0.0256 | S_m=-0.0576 | S_family=-0.0160 | gap=0.0832 | alpha_std=0.02827

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3013 | S_p=0.0291 | S_m=-0.0600 | S_family=-0.0155 | gap=0.0891 | alpha_std=0.02831

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4068 | S_p=-0.0942 | S_m=-0.0133 | S_family=-0.0537 | gap=0.0808 | alpha_std=0.02887

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4672 | S_p=-0.0832 | S_m=-0.0084 | S_family=-0.0458 | gap=0.0748 | alpha_std=0.02891

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3728 | S_p=0.0262 | S_m=0.0368 | S_family=0.0315 | gap=0.0107 | alpha_std=0.02927

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3681 | S_p=-0.0002 | S_m=0.0548 | S_family=0.0273 | gap=0.0550 | alpha_std=0.02915

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1928 | S_p=-0.0210 | S_m=-0.0898 | S_family=-0.0554 | gap=0.0688 | alpha_std=0.02946

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2513 | S_p=0.0226 | S_m=-0.0244 | S_family=-0.0009 | gap=0.0470 | alpha_std=0.02946

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0784 | S_p=0.0357 | S_m=-0.0673 | S_family=-0.0158 | gap=0.1029 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0445 | S_p=0.0521 | S_m=-0.0664 | S_family=-0.0072 | gap=0.1185 | alpha_std=0.02763

Triada 48/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2451 | S_p=-0.0147 | S_m=0.0140 | S_family=-0.0004 | gap=0.0287 | alpha_std=0.02815

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3092 | S_p=0.0168 | S_m=-0.0159 | S_family=0.0005 | gap=0.0326 | alpha_std=0.02817

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0812 | S_p=0.0490 | S_m=-0.0386 | S_family=0.0052 | gap=0.0876 | alpha_std=0.02774

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0799 | S_p=0.0560 | S_m=-0.0293 | S_family=0.0133 | gap=0.0853 | alpha_std=0.02771

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3671 | S_p=-0.0589 | S_m=0.0529 | S_family=-0.0030 | gap=0.1119 | alpha_std=0.02859

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3682 | S_p=-0.0450 | S_m=0.0615 | S_family=0.0082 | gap=0.1066 | alpha_std=0.02858

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1448 | S_p=-0.0147 | S_m=0.0551 | S_family=0.0202 | gap=0.0698 | alpha_std=0.02831

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2039 | S_p=-0.0352 | S_m=0.0165 | S_family=-0.0093 | gap=0.0518 | alpha_std=0.02838

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3030 | S_p=0.0140 | S_m=0.0536 | S_family=0.0338 | gap=0.0395 | alpha_std=0.02895

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3083 | S_p=-0.0003 | S_m=0.1104 | S_family=0.0551 | gap=0.1107 | alpha_std=0.02901

Triada 49/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3713 | S_p=-0.0095 | S_m=0.0870 | S_family=0.0388 | gap=0.0966 | alpha_std=0.02763

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3698 | S_p=0.0003 | S_m=0.0714 | S_family=0.0359 | gap=0.0712 | alpha_std=0.02765

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1370 | S_p=-0.0329 | S_m=0.0122 | S_family=-0.0104 | gap=0.0450 | alpha_std=0.02801

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1370 | S_p=-0.0248 | S_m=0.0148 | S_family=-0.0050 | gap=0.0397 | alpha_std=0.02802

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2335 | S_p=-0.0318 | S_m=-0.0223 | S_family=-0.0271 | gap=0.0095 | alpha_std=0.02783

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2250 | S_p=-0.0256 | S_m=-0.0201 | S_family=-0.0229 | gap=0.0055 | alpha_std=0.02781

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1638 | S_p=-0.0579 | S_m=-0.0412 | S_family=-0.0496 | gap=0.0166 | alpha_std=0.02818

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1830 | S_p=-0.0255 | S_m=-0.0354 | S_family=-0.0305 | gap=0.0099 | alpha_std=0.02810

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2740 | S_p=0.0438 | S_m=0.0597 | S_family=0.0517 | gap=0.0159 | alpha_std=0.02883

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2771 | S_p=0.0603 | S_m=0.0754 | S_family=0.0679 | gap=0.0151 | alpha_std=0.02884

Triada 50/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0893 | S_p=-0.0114 | S_m=0.0986 | S_family=0.0436 | gap=0.1100 | alpha_std=0.02654

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1203 | S_p=-0.0102 | S_m=0.0823 | S_family=0.0360 | gap=0.0925 | alpha_std=0.02663

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0742 | S_p=-0.0055 | S_m=0.0937 | S_family=0.0441 | gap=0.0992 | alpha_std=0.02720

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0757 | S_p=-0.0048 | S_m=0.0894 | S_family=0.0423 | gap=0.0942 | alpha_std=0.02719

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4446 | S_p=0.0922 | S_m=0.0456 | S_family=0.0689 | gap=0.0466 | alpha_std=0.02851

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4462 | S_p=0.0892 | S_m=0.0572 | S_family=0.0732 | gap=0.0320 | alpha_std=0.02849

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0871 | S_p=-0.0365 | S_m=0.0442 | S_family=0.0039 | gap=0.0808 | alpha_std=0.02779

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0872 | S_p=-0.0446 | S_m=0.0487 | S_family=0.0021 | gap=0.0933 | alpha_std=0.02777

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1796 | S_p=0.0699 | S_m=0.0162 | S_family=0.0430 | gap=0.0537 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1795 | S_p=0.0664 | S_m=0.0262 | S_family=0.0463 | gap=0.0402 | alpha_std=0.02719

Triada 51/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2748 | S_p=0.0320 | S_m=0.0095 | S_family=0.0207 | gap=0.0225 | alpha_std=0.02738

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2845 | S_p=0.0288 | S_m=0.0201 | S_family=0.0244 | gap=0.0087 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1083 | S_p=0.0006 | S_m=0.0381 | S_family=0.0194 | gap=0.0375 | alpha_std=0.02715

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1026 | S_p=-0.0025 | S_m=0.0385 | S_family=0.0180 | gap=0.0410 | alpha_std=0.02714

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2647 | S_p=0.0171 | S_m=0.0148 | S_family=0.0159 | gap=0.0023 | alpha_std=0.02816

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2609 | S_p=0.0172 | S_m=0.0187 | S_family=0.0179 | gap=0.0014 | alpha_std=0.02817

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3334 | S_p=0.0508 | S_m=-0.0110 | S_family=0.0199 | gap=0.0618 | alpha_std=0.02842

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3314 | S_p=0.0616 | S_m=0.0024 | S_family=0.0320 | gap=0.0592 | alpha_std=0.02842

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0415 | S_p=-0.0402 | S_m=-0.0113 | S_family=-0.0257 | gap=0.0290 | alpha_std=0.02668

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0433 | S_p=-0.0405 | S_m=-0.0028 | S_family=-0.0216 | gap=0.0377 | alpha_std=0.02674

Triada 52/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0230 | S_p=0.0355 | S_m=0.0724 | S_family=0.0539 | gap=0.0369 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0292 | S_p=0.0366 | S_m=0.0812 | S_family=0.0589 | gap=0.0446 | alpha_std=0.02740

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0493 | S_p=0.0407 | S_m=0.0783 | S_family=0.0595 | gap=0.0376 | alpha_std=0.02762

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0892 | S_p=0.0319 | S_m=0.0717 | S_family=0.0518 | gap=0.0398 | alpha_std=0.02747

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0154 | S_p=0.0032 | S_m=-0.0306 | S_family=-0.0137 | gap=0.0339 | alpha_std=0.02730

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0054 | S_p=0.0063 | S_m=-0.0300 | S_family=-0.0119 | gap=0.0362 | alpha_std=0.02729

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0472 | S_p=0.0863 | S_m=-0.0259 | S_family=0.0302 | gap=0.1121 | alpha_std=0.02773

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0461 | S_p=0.0874 | S_m=-0.0216 | S_family=0.0329 | gap=0.1090 | alpha_std=0.02773

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2271 | S_p=0.0898 | S_m=0.0648 | S_family=0.0773 | gap=0.0250 | alpha_std=0.02855

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2271 | S_p=0.1039 | S_m=0.0735 | S_family=0.0887 | gap=0.0303 | alpha_std=0.02855

Triada 53/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3906 | S_p=-0.0262 | S_m=0.0127 | S_family=-0.0068 | gap=0.0389 | alpha_std=0.02669

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3710 | S_p=-0.0101 | S_m=0.0151 | S_family=0.0025 | gap=0.0251 | alpha_std=0.02667

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0434 | S_p=0.0668 | S_m=-0.0222 | S_family=0.0223 | gap=0.0890 | alpha_std=0.02627

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0380 | S_p=0.0714 | S_m=-0.0205 | S_family=0.0255 | gap=0.0919 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2337 | S_p=-0.0118 | S_m=0.0074 | S_family=-0.0022 | gap=0.0192 | alpha_std=0.02639

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2092 | S_p=-0.0462 | S_m=-0.0011 | S_family=-0.0237 | gap=0.0451 | alpha_std=0.02624

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2177 | S_p=-0.0336 | S_m=0.0220 | S_family=-0.0058 | gap=0.0556 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1989 | S_p=-0.0860 | S_m=0.0943 | S_family=0.0042 | gap=0.1802 | alpha_std=0.02750

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1397 | S_p=-0.0311 | S_m=0.0132 | S_family=-0.0090 | gap=0.0443 | alpha_std=0.02781

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1356 | S_p=-0.0327 | S_m=0.0190 | S_family=-0.0069 | gap=0.0517 | alpha_std=0.02780

Triada 54/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4321 | S_p=0.0844 | S_m=0.1246 | S_family=0.1045 | gap=0.0402 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4416 | S_p=0.0624 | S_m=0.1230 | S_family=0.0927 | gap=0.0607 | alpha_std=0.02714

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3862 | S_p=0.0074 | S_m=0.1577 | S_family=0.0825 | gap=0.1503 | alpha_std=0.02855

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3758 | S_p=0.0022 | S_m=0.1621 | S_family=0.0821 | gap=0.1599 | alpha_std=0.02856

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3444 | S_p=0.0479 | S_m=0.1628 | S_family=0.1054 | gap=0.1149 | alpha_std=0.02948

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3295 | S_p=0.0568 | S_m=0.1655 | S_family=0.1111 | gap=0.1087 | alpha_std=0.02949

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2488 | S_p=0.0474 | S_m=0.1292 | S_family=0.0883 | gap=0.0818 | alpha_std=0.02768

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2404 | S_p=0.0565 | S_m=0.1240 | S_family=0.0903 | gap=0.0675 | alpha_std=0.02777

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1855 | S_p=0.0409 | S_m=0.1182 | S_family=0.0795 | gap=0.0773 | alpha_std=0.02831

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2236 | S_p=0.0603 | S_m=0.1125 | S_family=0.0864 | gap=0.0522 | alpha_std=0.02834

Triada 55/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2318 | S_p=0.0560 | S_m=0.0182 | S_family=0.0371 | gap=0.0378 | alpha_std=0.02763

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2216 | S_p=0.0511 | S_m=0.0346 | S_family=0.0429 | gap=0.0165 | alpha_std=0.02760

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1006 | S_p=-0.0361 | S_m=0.0371 | S_family=0.0005 | gap=0.0732 | alpha_std=0.02749

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0798 | S_p=-0.0072 | S_m=0.0585 | S_family=0.0256 | gap=0.0657 | alpha_std=0.02747

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1065 | S_p=0.0289 | S_m=0.0601 | S_family=0.0445 | gap=0.0313 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0775 | S_p=0.0307 | S_m=0.0258 | S_family=0.0282 | gap=0.0048 | alpha_std=0.02724

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1723 | S_p=-0.0561 | S_m=-0.0525 | S_family=-0.0543 | gap=0.0036 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2108 | S_p=0.0054 | S_m=-0.0268 | S_family=-0.0107 | gap=0.0322 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2010 | S_p=0.0009 | S_m=-0.0620 | S_family=-0.0306 | gap=0.0629 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1952 | S_p=0.0185 | S_m=-0.0534 | S_family=-0.0175 | gap=0.0719 | alpha_std=0.02756

Triada 56/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4044 | S_p=0.1230 | S_m=0.0854 | S_family=0.1042 | gap=0.0376 | alpha_std=0.02603

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3963 | S_p=0.1316 | S_m=0.1048 | S_family=0.1182 | gap=0.0268 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3211 | S_p=0.0709 | S_m=0.0342 | S_family=0.0525 | gap=0.0367 | alpha_std=0.02616

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3107 | S_p=0.0831 | S_m=0.0567 | S_family=0.0699 | gap=0.0265 | alpha_std=0.02622

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0577 | S_p=-0.0061 | S_m=0.0000 | S_family=-0.0031 | gap=0.0062 | alpha_std=0.02550

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0713 | S_p=0.0141 | S_m=0.0263 | S_family=0.0202 | gap=0.0122 | alpha_std=0.02543

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1122 | S_p=-0.0633 | S_m=-0.0186 | S_family=-0.0410 | gap=0.0448 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1364 | S_p=-0.0205 | S_m=0.0495 | S_family=0.0145 | gap=0.0700 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0715 | S_p=-0.0567 | S_m=-0.0051 | S_family=-0.0309 | gap=0.0516 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0318 | S_p=-0.0386 | S_m=-0.0020 | S_family=-0.0203 | gap=0.0367 | alpha_std=0.02556

Triada 57/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1277 | S_p=-0.0629 | S_m=-0.0352 | S_family=-0.0490 | gap=0.0277 | alpha_std=0.02512

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1275 | S_p=-0.0136 | S_m=-0.0506 | S_family=-0.0321 | gap=0.0370 | alpha_std=0.02510

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1520 | S_p=0.0581 | S_m=0.0517 | S_family=0.0549 | gap=0.0064 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1765 | S_p=0.0394 | S_m=0.0780 | S_family=0.0587 | gap=0.0386 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2020 | S_p=0.0196 | S_m=0.0241 | S_family=0.0218 | gap=0.0046 | alpha_std=0.02573

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1966 | S_p=0.0295 | S_m=0.0254 | S_family=0.0274 | gap=0.0041 | alpha_std=0.02574

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2167 | S_p=0.0533 | S_m=0.0382 | S_family=0.0457 | gap=0.0151 | alpha_std=0.02620

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2205 | S_p=0.0763 | S_m=0.0680 | S_family=0.0721 | gap=0.0083 | alpha_std=0.02621

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1838 | S_p=-0.0034 | S_m=0.0391 | S_family=0.0179 | gap=0.0425 | alpha_std=0.02561

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1958 | S_p=-0.0082 | S_m=0.0318 | S_family=0.0118 | gap=0.0399 | alpha_std=0.02559

Triada 58/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2657 | S_p=-0.0498 | S_m=-0.0597 | S_family=-0.0548 | gap=0.0099 | alpha_std=0.02770

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2775 | S_p=-0.0441 | S_m=-0.0488 | S_family=-0.0464 | gap=0.0047 | alpha_std=0.02764

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0742 | S_p=-0.0059 | S_m=-0.0323 | S_family=-0.0191 | gap=0.0264 | alpha_std=0.02757

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1668 | S_p=-0.0194 | S_m=0.0105 | S_family=-0.0045 | gap=0.0299 | alpha_std=0.02753

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0712 | S_p=-0.0123 | S_m=0.0058 | S_family=-0.0033 | gap=0.0181 | alpha_std=0.02716

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0530 | S_p=-0.0123 | S_m=-0.0080 | S_family=-0.0101 | gap=0.0042 | alpha_std=0.02711

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.4687 | S_p=-0.0549 | S_m=0.0070 | S_family=-0.0239 | gap=0.0619 | alpha_std=0.02824

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.5195 | S_p=-0.0532 | S_m=-0.0027 | S_family=-0.0280 | gap=0.0505 | alpha_std=0.02823

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0752 | S_p=0.0046 | S_m=0.0098 | S_family=0.0072 | gap=0.0051 | alpha_std=0.02725

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0609 | S_p=0.0219 | S_m=-0.0042 | S_family=0.0088 | gap=0.0262 | alpha_std=0.02722

Triada 59/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4021 | S_p=0.0260 | S_m=0.0232 | S_family=0.0246 | gap=0.0027 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4014 | S_p=0.0291 | S_m=0.0304 | S_family=0.0298 | gap=0.0012 | alpha_std=0.02586

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2991 | S_p=0.0585 | S_m=0.0780 | S_family=0.0683 | gap=0.0195 | alpha_std=0.02607

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2989 | S_p=0.0673 | S_m=0.0901 | S_family=0.0787 | gap=0.0229 | alpha_std=0.02607

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0785 | S_p=-0.0903 | S_m=-0.0008 | S_family=-0.0456 | gap=0.0895 | alpha_std=0.02544

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0821 | S_p=-0.0894 | S_m=0.0031 | S_family=-0.0431 | gap=0.0925 | alpha_std=0.02543

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3051 | S_p=0.0622 | S_m=0.0452 | S_family=0.0537 | gap=0.0170 | alpha_std=0.02694

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3161 | S_p=0.0750 | S_m=0.0609 | S_family=0.0679 | gap=0.0141 | alpha_std=0.02694

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1311 | S_p=0.0454 | S_m=-0.0557 | S_family=-0.0051 | gap=0.1011 | alpha_std=0.02638

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1302 | S_p=0.0598 | S_m=-0.0583 | S_family=0.0008 | gap=0.1182 | alpha_std=0.02638

Triada 60/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1124 | S_p=0.0567 | S_m=-0.0037 | S_family=0.0265 | gap=0.0604 | alpha_std=0.02563

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1081 | S_p=0.0781 | S_m=0.0238 | S_family=0.0510 | gap=0.0543 | alpha_std=0.02568

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3350 | S_p=0.1627 | S_m=0.0603 | S_family=0.1115 | gap=0.1024 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3547 | S_p=0.1627 | S_m=0.0710 | S_family=0.1168 | gap=0.0916 | alpha_std=0.02588

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1117 | S_p=0.0599 | S_m=0.0271 | S_family=0.0435 | gap=0.0329 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1144 | S_p=0.0585 | S_m=0.0335 | S_family=0.0460 | gap=0.0251 | alpha_std=0.02582

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0215 | S_p=0.0421 | S_m=-0.0212 | S_family=0.0105 | gap=0.0633 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0095 | S_p=0.0376 | S_m=-0.0014 | S_family=0.0181 | gap=0.0390 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0347 | S_p=-0.0669 | S_m=0.0153 | S_family=-0.0258 | gap=0.0822 | alpha_std=0.02578

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0316 | S_p=-0.0726 | S_m=0.0205 | S_family=-0.0261 | gap=0.0931 | alpha_std=0.02579

Triada 61/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1640 | S_p=-0.0279 | S_m=-0.0171 | S_family=-0.0225 | gap=0.0108 | alpha_std=0.02574

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1802 | S_p=-0.0184 | S_m=-0.0087 | S_family=-0.0135 | gap=0.0097 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3906 | S_p=-0.0745 | S_m=-0.0167 | S_family=-0.0456 | gap=0.0577 | alpha_std=0.02619

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3594 | S_p=-0.0716 | S_m=-0.0060 | S_family=-0.0388 | gap=0.0655 | alpha_std=0.02620

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4093 | S_p=-0.0115 | S_m=-0.0310 | S_family=-0.0212 | gap=0.0195 | alpha_std=0.02696

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4572 | S_p=0.0072 | S_m=-0.0337 | S_family=-0.0132 | gap=0.0408 | alpha_std=0.02606

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0518 | S_p=-0.0254 | S_m=-0.0657 | S_family=-0.0455 | gap=0.0403 | alpha_std=0.02586

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1102 | S_p=0.0382 | S_m=0.0095 | S_family=0.0238 | gap=0.0287 | alpha_std=0.02586

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0029 | S_p=-0.0214 | S_m=-0.0877 | S_family=-0.0545 | gap=0.0663 | alpha_std=0.02488

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=-0.0064 | S_p=0.0050 | S_m=-0.0891 | S_family=-0.0420 | gap=0.0941 | alpha_std=0.02492

Triada 62/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1765 | S_p=-0.0686 | S_m=0.0428 | S_family=-0.0129 | gap=0.1114 | alpha_std=0.02580

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1809 | S_p=-0.0675 | S_m=0.0471 | S_family=-0.0102 | gap=0.1146 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1101 | S_p=-0.0355 | S_m=0.0450 | S_family=0.0047 | gap=0.0804 | alpha_std=0.02570

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2255 | S_p=-0.0204 | S_m=0.0035 | S_family=-0.0085 | gap=0.0238 | alpha_std=0.02585

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1173 | S_p=0.0001 | S_m=0.0112 | S_family=0.0057 | gap=0.0111 | alpha_std=0.02592

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1103 | S_p=0.0130 | S_m=0.0173 | S_family=0.0152 | gap=0.0043 | alpha_std=0.02591

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0476 | S_p=0.0138 | S_m=0.1072 | S_family=0.0605 | gap=0.0934 | alpha_std=0.02598

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0466 | S_p=0.0259 | S_m=0.1210 | S_family=0.0735 | gap=0.0951 | alpha_std=0.02597

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1096 | S_p=0.0642 | S_m=0.0256 | S_family=0.0449 | gap=0.0385 | alpha_std=0.02657

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1713 | S_p=0.0865 | S_m=0.0656 | S_family=0.0761 | gap=0.0209 | alpha_std=0.02660

Triada 63/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0056 | S_p=0.0494 | S_m=-0.0480 | S_family=0.0007 | gap=0.0973 | alpha_std=0.02683

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1696 | S_p=0.0206 | S_m=-0.0129 | S_family=0.0039 | gap=0.0335 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1304 | S_p=-0.0454 | S_m=0.0414 | S_family=-0.0020 | gap=0.0868 | alpha_std=0.02709

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1582 | S_p=-0.0396 | S_m=0.0583 | S_family=0.0093 | gap=0.0980 | alpha_std=0.02723

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1588 | S_p=0.0516 | S_m=0.0396 | S_family=0.0456 | gap=0.0120 | alpha_std=0.02783

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1593 | S_p=0.0468 | S_m=0.0490 | S_family=0.0479 | gap=0.0022 | alpha_std=0.02777

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2761 | S_p=0.0490 | S_m=0.0297 | S_family=0.0393 | gap=0.0193 | alpha_std=0.02815

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2665 | S_p=0.0551 | S_m=0.0363 | S_family=0.0457 | gap=0.0189 | alpha_std=0.02816

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1756 | S_p=0.0108 | S_m=-0.0407 | S_family=-0.0149 | gap=0.0515 | alpha_std=0.02801

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1980 | S_p=0.0188 | S_m=-0.0082 | S_family=0.0053 | gap=0.0270 | alpha_std=0.02796

Triada 64/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4284 | S_p=0.0206 | S_m=0.0075 | S_family=0.0140 | gap=0.0130 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4435 | S_p=0.0327 | S_m=0.0189 | S_family=0.0258 | gap=0.0138 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3218 | S_p=-0.0312 | S_m=-0.0237 | S_family=-0.0274 | gap=0.0075 | alpha_std=0.02743

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3702 | S_p=0.0207 | S_m=-0.0044 | S_family=0.0082 | gap=0.0252 | alpha_std=0.02745

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2523 | S_p=-0.0538 | S_m=0.0191 | S_family=-0.0173 | gap=0.0729 | alpha_std=0.02742

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2443 | S_p=-0.0538 | S_m=0.0197 | S_family=-0.0170 | gap=0.0735 | alpha_std=0.02752

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0862 | S_p=0.0080 | S_m=0.0200 | S_family=0.0140 | gap=0.0121 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0747 | S_p=0.0071 | S_m=0.0109 | S_family=0.0090 | gap=0.0039 | alpha_std=0.02731

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1562 | S_p=-0.0365 | S_m=0.0275 | S_family=-0.0045 | gap=0.0640 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1206 | S_p=-0.0513 | S_m=0.0333 | S_family=-0.0090 | gap=0.0845 | alpha_std=0.02756

Triada 65/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0311 | S_p=0.0378 | S_m=-0.0862 | S_family=-0.0242 | gap=0.1239 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0312 | S_p=0.0164 | S_m=-0.0906 | S_family=-0.0371 | gap=0.1070 | alpha_std=0.02723

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3367 | S_p=0.0065 | S_m=0.0638 | S_family=0.0352 | gap=0.0573 | alpha_std=0.02771

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3444 | S_p=0.0423 | S_m=0.0726 | S_family=0.0574 | gap=0.0304 | alpha_std=0.02775

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0505 | S_p=-0.0349 | S_m=-0.0509 | S_family=-0.0429 | gap=0.0160 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0473 | S_p=-0.0501 | S_m=-0.0435 | S_family=-0.0468 | gap=0.0066 | alpha_std=0.02727

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1914 | S_p=-0.0263 | S_m=-0.0188 | S_family=-0.0226 | gap=0.0075 | alpha_std=0.02816

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1957 | S_p=-0.0184 | S_m=-0.0540 | S_family=-0.0362 | gap=0.0356 | alpha_std=0.02790

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0718 | S_p=0.0783 | S_m=0.0167 | S_family=0.0475 | gap=0.0616 | alpha_std=0.02771

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0569 | S_p=0.0595 | S_m=0.0290 | S_family=0.0443 | gap=0.0305 | alpha_std=0.02767

Triada 66/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0414 | S_p=-0.0124 | S_m=-0.0379 | S_family=-0.0252 | gap=0.0255 | alpha_std=0.02698

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0899 | S_p=0.0121 | S_m=0.0163 | S_family=0.0142 | gap=0.0042 | alpha_std=0.02706

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1142 | S_p=0.0988 | S_m=-0.0475 | S_family=0.0257 | gap=0.1463 | alpha_std=0.02741

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1126 | S_p=0.1066 | S_m=-0.0386 | S_family=0.0340 | gap=0.1453 | alpha_std=0.02742

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1401 | S_p=0.1818 | S_m=0.0203 | S_family=0.1011 | gap=0.1616 | alpha_std=0.02803

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1569 | S_p=0.1940 | S_m=0.0368 | S_family=0.1154 | gap=0.1572 | alpha_std=0.02803

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1146 | S_p=0.0278 | S_m=0.0067 | S_family=0.0173 | gap=0.0210 | alpha_std=0.02792

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1092 | S_p=0.0323 | S_m=0.0185 | S_family=0.0254 | gap=0.0138 | alpha_std=0.02790

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1807 | S_p=-0.0035 | S_m=-0.0612 | S_family=-0.0323 | gap=0.0576 | alpha_std=0.02798

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1913 | S_p=0.0017 | S_m=-0.0520 | S_family=-0.0251 | gap=0.0537 | alpha_std=0.02796

Triada 67/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0923 | S_p=0.0115 | S_m=-0.0484 | S_family=-0.0184 | gap=0.0600 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0926 | S_p=0.0235 | S_m=-0.0417 | S_family=-0.0091 | gap=0.0652 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0263 | S_p=0.0250 | S_m=-0.0286 | S_family=-0.0018 | gap=0.0536 | alpha_std=0.02646

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0537 | S_p=0.0256 | S_m=0.0159 | S_family=0.0207 | gap=0.0097 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0637 | S_p=-0.0416 | S_m=-0.0140 | S_family=-0.0278 | gap=0.0276 | alpha_std=0.02729

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0757 | S_p=-0.0586 | S_m=0.0012 | S_family=-0.0287 | gap=0.0598 | alpha_std=0.02731

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2273 | S_p=0.0036 | S_m=-0.0220 | S_family=-0.0092 | gap=0.0255 | alpha_std=0.02806

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2248 | S_p=-0.0169 | S_m=-0.0218 | S_family=-0.0194 | gap=0.0049 | alpha_std=0.02801

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1703 | S_p=-0.0268 | S_m=0.0552 | S_family=0.0142 | gap=0.0820 | alpha_std=0.02763

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1820 | S_p=-0.0259 | S_m=0.0543 | S_family=0.0142 | gap=0.0802 | alpha_std=0.02764

Triada 68/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1706 | S_p=-0.0130 | S_m=0.0175 | S_family=0.0023 | gap=0.0305 | alpha_std=0.02643

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1777 | S_p=-0.0005 | S_m=0.0391 | S_family=0.0193 | gap=0.0395 | alpha_std=0.02644

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1035 | S_p=0.0138 | S_m=0.1031 | S_family=0.0585 | gap=0.0894 | alpha_std=0.02591

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0847 | S_p=0.0370 | S_m=0.0966 | S_family=0.0668 | gap=0.0596 | alpha_std=0.02578

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1037 | S_p=0.0197 | S_m=0.0634 | S_family=0.0416 | gap=0.0438 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1072 | S_p=0.0380 | S_m=0.0570 | S_family=0.0475 | gap=0.0191 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0086 | S_p=0.0224 | S_m=0.0508 | S_family=0.0366 | gap=0.0283 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0186 | S_p=0.0386 | S_m=0.0558 | S_family=0.0472 | gap=0.0172 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2485 | S_p=-0.0320 | S_m=-0.0072 | S_family=-0.0196 | gap=0.0248 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2476 | S_p=-0.0309 | S_m=-0.0113 | S_family=-0.0211 | gap=0.0196 | alpha_std=0.02670

Triada 69/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3380 | S_p=0.0393 | S_m=0.0617 | S_family=0.0505 | gap=0.0223 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3398 | S_p=0.0454 | S_m=0.0693 | S_family=0.0574 | gap=0.0239 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0241 | S_p=0.0266 | S_m=0.0619 | S_family=0.0442 | gap=0.0353 | alpha_std=0.02649

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0257 | S_p=0.0236 | S_m=0.0601 | S_family=0.0419 | gap=0.0364 | alpha_std=0.02648

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0125 | S_p=0.0220 | S_m=0.0232 | S_family=0.0226 | gap=0.0011 | alpha_std=0.02628

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0412 | S_p=-0.0177 | S_m=0.0347 | S_family=0.0085 | gap=0.0524 | alpha_std=0.02659

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0561 | S_p=0.0136 | S_m=0.0508 | S_family=0.0322 | gap=0.0372 | alpha_std=0.02663

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1977 | S_p=0.0059 | S_m=0.0133 | S_family=0.0096 | gap=0.0074 | alpha_std=0.02683

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1886 | S_p=0.0677 | S_m=-0.0153 | S_family=0.0262 | gap=0.0830 | alpha_std=0.02717

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1774 | S_p=0.0809 | S_m=0.0086 | S_family=0.0447 | gap=0.0723 | alpha_std=0.02720

Triada 70/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3321 | S_p=0.0292 | S_m=0.0315 | S_family=0.0304 | gap=0.0023 | alpha_std=0.02740

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3252 | S_p=0.0395 | S_m=0.0374 | S_family=0.0384 | gap=0.0021 | alpha_std=0.02738

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2566 | S_p=0.0124 | S_m=0.0031 | S_family=0.0078 | gap=0.0093 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2866 | S_p=0.0281 | S_m=0.0366 | S_family=0.0323 | gap=0.0085 | alpha_std=0.02713

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1895 | S_p=0.0306 | S_m=0.0175 | S_family=0.0240 | gap=0.0131 | alpha_std=0.02762

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1831 | S_p=0.0396 | S_m=0.0390 | S_family=0.0393 | gap=0.0006 | alpha_std=0.02760

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2466 | S_p=0.0103 | S_m=-0.0998 | S_family=-0.0448 | gap=0.1100 | alpha_std=0.02833

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2435 | S_p=0.0154 | S_m=-0.0851 | S_family=-0.0348 | gap=0.1005 | alpha_std=0.02836

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1749 | S_p=-0.0132 | S_m=0.0351 | S_family=0.0109 | gap=0.0483 | alpha_std=0.02740

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1799 | S_p=-0.0187 | S_m=0.0285 | S_family=0.0049 | gap=0.0471 | alpha_std=0.02743

Triada 71/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1159 | S_p=-0.0480 | S_m=0.0464 | S_family=-0.0008 | gap=0.0944 | alpha_std=0.02657

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1295 | S_p=-0.0177 | S_m=0.0613 | S_family=0.0218 | gap=0.0790 | alpha_std=0.02654

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3283 | S_p=0.0015 | S_m=-0.0011 | S_family=0.0002 | gap=0.0026 | alpha_std=0.02619

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3224 | S_p=-0.0036 | S_m=0.0043 | S_family=0.0004 | gap=0.0079 | alpha_std=0.02618

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0781 | S_p=-0.0849 | S_m=0.0528 | S_family=-0.0160 | gap=0.1378 | alpha_std=0.02654

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0646 | S_p=-0.0877 | S_m=0.0587 | S_family=-0.0145 | gap=0.1463 | alpha_std=0.02639

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2442 | S_p=-0.0156 | S_m=0.0568 | S_family=0.0206 | gap=0.0724 | alpha_std=0.02744

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2459 | S_p=-0.0144 | S_m=0.0785 | S_family=0.0321 | gap=0.0929 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2282 | S_p=-0.0115 | S_m=0.0944 | S_family=0.0414 | gap=0.1059 | alpha_std=0.02708

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2403 | S_p=-0.0091 | S_m=0.0814 | S_family=0.0361 | gap=0.0904 | alpha_std=0.02710

Triada 72/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2736 | S_p=0.0212 | S_m=-0.0524 | S_family=-0.0156 | gap=0.0736 | alpha_std=0.02490

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2898 | S_p=0.0248 | S_m=-0.0662 | S_family=-0.0207 | gap=0.0910 | alpha_std=0.02494

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4674 | S_p=0.0594 | S_m=0.0325 | S_family=0.0460 | gap=0.0270 | alpha_std=0.02554

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4528 | S_p=0.0700 | S_m=0.0522 | S_family=0.0611 | gap=0.0178 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0979 | S_p=-0.0047 | S_m=0.0320 | S_family=0.0137 | gap=0.0367 | alpha_std=0.02526

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0281 | S_p=0.0097 | S_m=0.0633 | S_family=0.0365 | gap=0.0536 | alpha_std=0.02525

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0534 | S_p=0.0029 | S_m=0.0400 | S_family=0.0215 | gap=0.0370 | alpha_std=0.02528

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0573 | S_p=-0.0110 | S_m=0.0481 | S_family=0.0186 | gap=0.0591 | alpha_std=0.02528

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0258 | S_p=-0.0229 | S_m=0.0640 | S_family=0.0205 | gap=0.0869 | alpha_std=0.02515

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=-0.0146 | S_p=-0.0549 | S_m=0.0834 | S_family=0.0142 | gap=0.1383 | alpha_std=0.02515

Triada 73/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2983 | S_p=-0.0088 | S_m=0.0031 | S_family=-0.0029 | gap=0.0120 | alpha_std=0.02609

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2914 | S_p=-0.0019 | S_m=0.0136 | S_family=0.0059 | gap=0.0155 | alpha_std=0.02611

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2823 | S_p=0.0425 | S_m=0.0350 | S_family=0.0388 | gap=0.0075 | alpha_std=0.02571

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3115 | S_p=0.0631 | S_m=0.0273 | S_family=0.0452 | gap=0.0358 | alpha_std=0.02573

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0889 | S_p=0.0455 | S_m=-0.0128 | S_family=0.0164 | gap=0.0582 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0962 | S_p=0.0598 | S_m=-0.0018 | S_family=0.0290 | gap=0.0616 | alpha_std=0.02563

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=-0.0185 | S_p=0.0467 | S_m=-0.0083 | S_family=0.0192 | gap=0.0549 | alpha_std=0.02557

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0258 | S_p=0.0553 | S_m=0.0050 | S_family=0.0301 | gap=0.0502 | alpha_std=0.02561

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1453 | S_p=-0.0474 | S_m=0.0310 | S_family=-0.0082 | gap=0.0784 | alpha_std=0.02615

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1484 | S_p=-0.0329 | S_m=0.0383 | S_family=0.0027 | gap=0.0712 | alpha_std=0.02613

Triada 74/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2200 | S_p=0.0432 | S_m=-0.0687 | S_family=-0.0127 | gap=0.1119 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2302 | S_p=0.0471 | S_m=-0.0700 | S_family=-0.0115 | gap=0.1171 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1969 | S_p=-0.0015 | S_m=0.0405 | S_family=0.0195 | gap=0.0420 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2067 | S_p=0.0074 | S_m=0.0292 | S_family=0.0183 | gap=0.0218 | alpha_std=0.02598

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1871 | S_p=0.0065 | S_m=0.0336 | S_family=0.0200 | gap=0.0271 | alpha_std=0.02500

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2146 | S_p=0.0070 | S_m=0.0420 | S_family=0.0245 | gap=0.0350 | alpha_std=0.02503

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1239 | S_p=0.0686 | S_m=0.0576 | S_family=0.0631 | gap=0.0110 | alpha_std=0.02571

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1360 | S_p=0.0712 | S_m=0.0565 | S_family=0.0639 | gap=0.0147 | alpha_std=0.02570

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1078 | S_p=0.0361 | S_m=0.0549 | S_family=0.0455 | gap=0.0188 | alpha_std=0.02466

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1162 | S_p=0.0337 | S_m=0.0551 | S_family=0.0444 | gap=0.0214 | alpha_std=0.02466

Triada 75/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.6054 | S_p=0.0791 | S_m=0.0324 | S_family=0.0558 | gap=0.0467 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.6032 | S_p=0.0844 | S_m=0.0362 | S_family=0.0603 | gap=0.0482 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3105 | S_p=0.0968 | S_m=-0.0325 | S_family=0.0322 | gap=0.1292 | alpha_std=0.02570

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2802 | S_p=0.0966 | S_m=-0.0296 | S_family=0.0335 | gap=0.1262 | alpha_std=0.02569

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1781 | S_p=0.0437 | S_m=-0.0721 | S_family=-0.0142 | gap=0.1157 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1007 | S_p=-0.0438 | S_m=-0.0749 | S_family=-0.0594 | gap=0.0311 | alpha_std=0.02567

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3394 | S_p=0.0203 | S_m=0.0006 | S_family=0.0105 | gap=0.0197 | alpha_std=0.02706

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3392 | S_p=0.0381 | S_m=0.0136 | S_family=0.0259 | gap=0.0245 | alpha_std=0.02708

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3518 | S_p=0.1049 | S_m=0.0334 | S_family=0.0692 | gap=0.0715 | alpha_std=0.02684

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3775 | S_p=0.1273 | S_m=0.0207 | S_family=0.0740 | gap=0.1066 | alpha_std=0.02684

Triada 76/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0616 | S_p=0.0058 | S_m=-0.0573 | S_family=-0.0257 | gap=0.0631 | alpha_std=0.02616

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0706 | S_p=0.0058 | S_m=-0.0441 | S_family=-0.0191 | gap=0.0499 | alpha_std=0.02603

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3225 | S_p=-0.0051 | S_m=-0.0363 | S_family=-0.0207 | gap=0.0312 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3310 | S_p=0.0104 | S_m=-0.0271 | S_family=-0.0084 | gap=0.0375 | alpha_std=0.02671

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3962 | S_p=-0.0176 | S_m=-0.0636 | S_family=-0.0406 | gap=0.0460 | alpha_std=0.02628

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3774 | S_p=-0.0142 | S_m=-0.0437 | S_family=-0.0290 | gap=0.0295 | alpha_std=0.02630

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0342 | S_p=-0.0332 | S_m=-0.0429 | S_family=-0.0380 | gap=0.0097 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0144 | S_p=-0.0289 | S_m=-0.0140 | S_family=-0.0214 | gap=0.0149 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1976 | S_p=0.0319 | S_m=0.0571 | S_family=0.0445 | gap=0.0253 | alpha_std=0.02688

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2192 | S_p=0.0515 | S_m=0.0639 | S_family=0.0577 | gap=0.0123 | alpha_std=0.02681

Triada 77/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4686 | S_p=-0.0209 | S_m=0.0702 | S_family=0.0247 | gap=0.0911 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4129 | S_p=-0.0388 | S_m=0.0756 | S_family=0.0184 | gap=0.1145 | alpha_std=0.02728

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2051 | S_p=-0.0057 | S_m=-0.0130 | S_family=-0.0093 | gap=0.0073 | alpha_std=0.02578

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2229 | S_p=0.0168 | S_m=-0.0057 | S_family=0.0056 | gap=0.0225 | alpha_std=0.02573

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2318 | S_p=0.0440 | S_m=-0.0072 | S_family=0.0184 | gap=0.0512 | alpha_std=0.02698

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2208 | S_p=0.0604 | S_m=0.0092 | S_family=0.0348 | gap=0.0512 | alpha_std=0.02696

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1974 | S_p=0.0623 | S_m=0.0358 | S_family=0.0491 | gap=0.0265 | alpha_std=0.02760

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2004 | S_p=0.0705 | S_m=0.0360 | S_family=0.0533 | gap=0.0345 | alpha_std=0.02761

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1794 | S_p=0.0440 | S_m=0.0179 | S_family=0.0309 | gap=0.0261 | alpha_std=0.02768

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1602 | S_p=0.0425 | S_m=0.0073 | S_family=0.0249 | gap=0.0352 | alpha_std=0.02771

Triada 78/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0832 | S_p=-0.0025 | S_m=0.0418 | S_family=0.0196 | gap=0.0443 | alpha_std=0.02852

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0848 | S_p=0.0106 | S_m=0.0534 | S_family=0.0320 | gap=0.0429 | alpha_std=0.02857

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1318 | S_p=-0.0620 | S_m=0.0011 | S_family=-0.0304 | gap=0.0631 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1238 | S_p=-0.0473 | S_m=0.0053 | S_family=-0.0210 | gap=0.0525 | alpha_std=0.02678

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1271 | S_p=0.0614 | S_m=0.0097 | S_family=0.0355 | gap=0.0517 | alpha_std=0.02695

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1494 | S_p=0.0854 | S_m=-0.0107 | S_family=0.0374 | gap=0.0961 | alpha_std=0.02697

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0102 | S_p=-0.0123 | S_m=-0.0437 | S_family=-0.0280 | gap=0.0313 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0113 | S_p=-0.0371 | S_m=-0.0410 | S_family=-0.0391 | gap=0.0039 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1803 | S_p=0.1184 | S_m=0.0499 | S_family=0.0842 | gap=0.0685 | alpha_std=0.02742

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1669 | S_p=0.1179 | S_m=0.0663 | S_family=0.0921 | gap=0.0516 | alpha_std=0.02741

Triada 79/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1175 | S_p=-0.0576 | S_m=0.0092 | S_family=-0.0242 | gap=0.0669 | alpha_std=0.02514

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1169 | S_p=-0.0770 | S_m=0.0403 | S_family=-0.0184 | gap=0.1173 | alpha_std=0.02521

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2006 | S_p=-0.0319 | S_m=-0.0013 | S_family=-0.0166 | gap=0.0306 | alpha_std=0.02568

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2017 | S_p=-0.0480 | S_m=0.0048 | S_family=-0.0216 | gap=0.0528 | alpha_std=0.02571

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0534 | S_p=-0.0549 | S_m=0.0296 | S_family=-0.0127 | gap=0.0845 | alpha_std=0.02486

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0822 | S_p=-0.0528 | S_m=0.0222 | S_family=-0.0153 | gap=0.0750 | alpha_std=0.02489

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3150 | S_p=0.0816 | S_m=0.0738 | S_family=0.0777 | gap=0.0077 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3073 | S_p=0.0889 | S_m=0.0792 | S_family=0.0841 | gap=0.0098 | alpha_std=0.02594

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1938 | S_p=-0.0343 | S_m=0.0561 | S_family=0.0109 | gap=0.0904 | alpha_std=0.02542

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1858 | S_p=-0.0407 | S_m=0.0624 | S_family=0.0108 | gap=0.1031 | alpha_std=0.02540

Triada 80/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0493 | S_p=-0.0590 | S_m=0.0144 | S_family=-0.0223 | gap=0.0734 | alpha_std=0.02475

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0459 | S_p=-0.0578 | S_m=0.0055 | S_family=-0.0261 | gap=0.0633 | alpha_std=0.02482

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0981 | S_p=0.0116 | S_m=0.0362 | S_family=0.0239 | gap=0.0246 | alpha_std=0.02459

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0665 | S_p=0.0175 | S_m=0.0007 | S_family=0.0091 | gap=0.0168 | alpha_std=0.02461

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1446 | S_p=-0.0406 | S_m=0.0376 | S_family=-0.0015 | gap=0.0782 | alpha_std=0.02525

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1398 | S_p=-0.0363 | S_m=0.0435 | S_family=0.0036 | gap=0.0798 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0284 | S_p=-0.0045 | S_m=-0.0055 | S_family=-0.0050 | gap=0.0011 | alpha_std=0.02512

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0698 | S_p=0.0405 | S_m=0.0674 | S_family=0.0540 | gap=0.0268 | alpha_std=0.02495

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0511 | S_p=0.0038 | S_m=0.0785 | S_family=0.0412 | gap=0.0747 | alpha_std=0.02531

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0780 | S_p=0.0238 | S_m=0.0779 | S_family=0.0508 | gap=0.0541 | alpha_std=0.02544

Triada 81/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.5628 | S_p=0.0708 | S_m=0.0936 | S_family=0.0822 | gap=0.0228 | alpha_std=0.03038

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.5714 | S_p=0.0775 | S_m=0.1062 | S_family=0.0918 | gap=0.0287 | alpha_std=0.03039

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1959 | S_p=0.0389 | S_m=-0.0462 | S_family=-0.0036 | gap=0.0851 | alpha_std=0.02903

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1812 | S_p=0.0373 | S_m=-0.0403 | S_family=-0.0015 | gap=0.0776 | alpha_std=0.02899

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1437 | S_p=-0.0247 | S_m=-0.0463 | S_family=-0.0355 | gap=0.0216 | alpha_std=0.02841

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1438 | S_p=-0.0199 | S_m=-0.0613 | S_family=-0.0406 | gap=0.0414 | alpha_std=0.02844

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2269 | S_p=-0.0171 | S_m=0.0008 | S_family=-0.0081 | gap=0.0178 | alpha_std=0.02905

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2238 | S_p=-0.0086 | S_m=0.0180 | S_family=0.0047 | gap=0.0267 | alpha_std=0.02910

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2559 | S_p=-0.0574 | S_m=0.0783 | S_family=0.0104 | gap=0.1357 | alpha_std=0.02967

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2574 | S_p=-0.0478 | S_m=0.0832 | S_family=0.0177 | gap=0.1310 | alpha_std=0.02970

Triada 82/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0894 | S_p=0.0126 | S_m=0.0071 | S_family=0.0099 | gap=0.0055 | alpha_std=0.02865

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0519 | S_p=0.0506 | S_m=-0.0403 | S_family=0.0051 | gap=0.0908 | alpha_std=0.02848

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2344 | S_p=0.0489 | S_m=0.0045 | S_family=0.0267 | gap=0.0443 | alpha_std=0.02893

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2454 | S_p=0.0538 | S_m=0.0154 | S_family=0.0346 | gap=0.0385 | alpha_std=0.02889

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0304 | S_p=-0.0338 | S_m=0.0353 | S_family=0.0008 | gap=0.0691 | alpha_std=0.02844

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0452 | S_p=-0.0221 | S_m=0.0376 | S_family=0.0077 | gap=0.0598 | alpha_std=0.02855

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0533 | S_p=0.0391 | S_m=0.0545 | S_family=0.0468 | gap=0.0154 | alpha_std=0.02864

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0647 | S_p=0.0493 | S_m=0.0142 | S_family=0.0317 | gap=0.0351 | alpha_std=0.02866

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2033 | S_p=-0.0452 | S_m=0.0075 | S_family=-0.0188 | gap=0.0528 | alpha_std=0.02965

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2021 | S_p=-0.0285 | S_m=0.0355 | S_family=0.0035 | gap=0.0640 | alpha_std=0.02967

Triada 83/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4417 | S_p=0.0028 | S_m=0.0398 | S_family=0.0213 | gap=0.0369 | alpha_std=0.02933

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4982 | S_p=0.0133 | S_m=0.0469 | S_family=0.0301 | gap=0.0335 | alpha_std=0.02940

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0801 | S_p=0.0894 | S_m=0.0929 | S_family=0.0912 | gap=0.0034 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0949 | S_p=0.1002 | S_m=0.0962 | S_family=0.0982 | gap=0.0040 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0661 | S_p=-0.0689 | S_m=0.0077 | S_family=-0.0306 | gap=0.0766 | alpha_std=0.02991

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0906 | S_p=-0.0590 | S_m=0.0310 | S_family=-0.0140 | gap=0.0900 | alpha_std=0.03002

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2618 | S_p=-0.0013 | S_m=0.0010 | S_family=-0.0002 | gap=0.0023 | alpha_std=0.02997

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2385 | S_p=-0.0070 | S_m=0.0425 | S_family=0.0177 | gap=0.0494 | alpha_std=0.02975

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0897 | S_p=-0.0434 | S_m=0.0416 | S_family=-0.0009 | gap=0.0850 | alpha_std=0.02942

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0918 | S_p=-0.0409 | S_m=0.0619 | S_family=0.0105 | gap=0.1028 | alpha_std=0.02937

Triada 84/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1375 | S_p=-0.0071 | S_m=0.0040 | S_family=-0.0015 | gap=0.0111 | alpha_std=0.02503

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1294 | S_p=0.0324 | S_m=-0.0049 | S_family=0.0137 | gap=0.0372 | alpha_std=0.02498

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1709 | S_p=-0.0552 | S_m=-0.0187 | S_family=-0.0370 | gap=0.0365 | alpha_std=0.02611

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1737 | S_p=-0.0526 | S_m=-0.0100 | S_family=-0.0313 | gap=0.0426 | alpha_std=0.02611

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2750 | S_p=-0.0496 | S_m=-0.0009 | S_family=-0.0253 | gap=0.0487 | alpha_std=0.02652

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2579 | S_p=-0.0455 | S_m=0.0236 | S_family=-0.0109 | gap=0.0691 | alpha_std=0.02660

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0590 | S_p=-0.0595 | S_m=0.0057 | S_family=-0.0269 | gap=0.0652 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0061 | S_p=-0.1156 | S_m=-0.0113 | S_family=-0.0635 | gap=0.1043 | alpha_std=0.02622

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0067 | S_p=0.0384 | S_m=-0.0291 | S_family=0.0046 | gap=0.0675 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=-0.0018 | S_p=0.0649 | S_m=-0.0218 | S_family=0.0216 | gap=0.0867 | alpha_std=0.02604

Triada 85/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4267 | S_p=0.0164 | S_m=0.0238 | S_family=0.0201 | gap=0.0073 | alpha_std=0.02637

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4297 | S_p=0.0205 | S_m=0.0477 | S_family=0.0341 | gap=0.0272 | alpha_std=0.02639

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2878 | S_p=-0.0131 | S_m=0.0442 | S_family=0.0155 | gap=0.0572 | alpha_std=0.02631

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2754 | S_p=0.0114 | S_m=0.0539 | S_family=0.0326 | gap=0.0426 | alpha_std=0.02631

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1824 | S_p=0.0174 | S_m=0.0439 | S_family=0.0306 | gap=0.0265 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1769 | S_p=0.0244 | S_m=0.0547 | S_family=0.0396 | gap=0.0303 | alpha_std=0.02598

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1618 | S_p=-0.0942 | S_m=-0.0094 | S_family=-0.0518 | gap=0.0848 | alpha_std=0.02636

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1666 | S_p=-0.0904 | S_m=0.0010 | S_family=-0.0447 | gap=0.0914 | alpha_std=0.02633

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1257 | S_p=0.0731 | S_m=0.0415 | S_family=0.0573 | gap=0.0316 | alpha_std=0.02597

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1279 | S_p=0.0991 | S_m=0.0625 | S_family=0.0808 | gap=0.0366 | alpha_std=0.02596

Triada 86/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1689 | S_p=-0.0035 | S_m=0.0812 | S_family=0.0388 | gap=0.0847 | alpha_std=0.02561

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1273 | S_p=-0.0003 | S_m=0.0715 | S_family=0.0356 | gap=0.0718 | alpha_std=0.02569

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0238 | S_p=0.0182 | S_m=0.0753 | S_family=0.0468 | gap=0.0571 | alpha_std=0.02600

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0388 | S_p=0.0224 | S_m=0.0775 | S_family=0.0500 | gap=0.0551 | alpha_std=0.02593

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0245 | S_p=0.0292 | S_m=0.1084 | S_family=0.0688 | gap=0.0792 | alpha_std=0.02571

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0669 | S_p=0.0367 | S_m=0.0960 | S_family=0.0663 | gap=0.0593 | alpha_std=0.02571

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2153 | S_p=0.0965 | S_m=0.0761 | S_family=0.0863 | gap=0.0204 | alpha_std=0.02661

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2083 | S_p=0.1290 | S_m=0.0881 | S_family=0.1086 | gap=0.0409 | alpha_std=0.02660

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2774 | S_p=0.0352 | S_m=0.0814 | S_family=0.0583 | gap=0.0461 | alpha_std=0.02666

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3328 | S_p=0.0348 | S_m=0.0580 | S_family=0.0464 | gap=0.0232 | alpha_std=0.02666

Triada 87/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1990 | S_p=0.0096 | S_m=0.0236 | S_family=0.0166 | gap=0.0140 | alpha_std=0.02567

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1946 | S_p=0.0143 | S_m=0.0295 | S_family=0.0219 | gap=0.0151 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0363 | S_p=0.0816 | S_m=0.0499 | S_family=0.0657 | gap=0.0317 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0385 | S_p=0.0751 | S_m=0.0351 | S_family=0.0551 | gap=0.0400 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2847 | S_p=0.0151 | S_m=0.0434 | S_family=0.0292 | gap=0.0283 | alpha_std=0.02671

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2939 | S_p=0.0296 | S_m=0.0757 | S_family=0.0527 | gap=0.0461 | alpha_std=0.02674

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2348 | S_p=-0.0444 | S_m=0.0088 | S_family=-0.0178 | gap=0.0532 | alpha_std=0.02699

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2556 | S_p=-0.0121 | S_m=0.0377 | S_family=0.0128 | gap=0.0498 | alpha_std=0.02716

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1988 | S_p=-0.0388 | S_m=0.0768 | S_family=0.0190 | gap=0.1155 | alpha_std=0.02597

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1907 | S_p=-0.0425 | S_m=0.1035 | S_family=0.0305 | gap=0.1460 | alpha_std=0.02597

Triada 88/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2320 | S_p=-0.0091 | S_m=0.0572 | S_family=0.0241 | gap=0.0663 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2104 | S_p=0.0061 | S_m=0.0561 | S_family=0.0311 | gap=0.0499 | alpha_std=0.02575

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0298 | S_p=-0.0334 | S_m=-0.0239 | S_family=-0.0287 | gap=0.0095 | alpha_std=0.02503

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0230 | S_p=-0.0324 | S_m=-0.0210 | S_family=-0.0267 | gap=0.0114 | alpha_std=0.02505

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0377 | S_p=-0.0174 | S_m=0.0134 | S_family=-0.0020 | gap=0.0308 | alpha_std=0.02519

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0471 | S_p=-0.0051 | S_m=0.0007 | S_family=-0.0022 | gap=0.0057 | alpha_std=0.02521

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0402 | S_p=-0.0459 | S_m=-0.0316 | S_family=-0.0387 | gap=0.0143 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0383 | S_p=-0.0432 | S_m=-0.0324 | S_family=-0.0378 | gap=0.0109 | alpha_std=0.02568

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2741 | S_p=0.0479 | S_m=0.0866 | S_family=0.0673 | gap=0.0387 | alpha_std=0.02563

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2683 | S_p=0.0489 | S_m=0.0946 | S_family=0.0718 | gap=0.0457 | alpha_std=0.02563

Triada 89/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2826 | S_p=0.0408 | S_m=0.0498 | S_family=0.0453 | gap=0.0091 | alpha_std=0.02664

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2874 | S_p=0.0472 | S_m=0.0595 | S_family=0.0534 | gap=0.0123 | alpha_std=0.02662

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2247 | S_p=0.1262 | S_m=0.0068 | S_family=0.0665 | gap=0.1194 | alpha_std=0.02699

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2273 | S_p=0.1274 | S_m=0.0134 | S_family=0.0704 | gap=0.1140 | alpha_std=0.02697

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2215 | S_p=0.0154 | S_m=0.0210 | S_family=0.0182 | gap=0.0056 | alpha_std=0.02703

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2296 | S_p=0.0228 | S_m=0.0280 | S_family=0.0254 | gap=0.0051 | alpha_std=0.02698

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0814 | S_p=-0.0044 | S_m=0.0507 | S_family=0.0231 | gap=0.0551 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0806 | S_p=0.0005 | S_m=0.0535 | S_family=0.0270 | gap=0.0529 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3389 | S_p=0.0579 | S_m=0.1182 | S_family=0.0880 | gap=0.0603 | alpha_std=0.02674

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3353 | S_p=0.0839 | S_m=0.1066 | S_family=0.0953 | gap=0.0227 | alpha_std=0.02672

Triada 90/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3300 | S_p=0.0865 | S_m=-0.0187 | S_family=0.0339 | gap=0.1052 | alpha_std=0.02791

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3292 | S_p=0.0874 | S_m=-0.0068 | S_family=0.0403 | gap=0.0942 | alpha_std=0.02784

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3829 | S_p=0.0711 | S_m=-0.0737 | S_family=-0.0013 | gap=0.1448 | alpha_std=0.02794

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3592 | S_p=0.0768 | S_m=-0.0455 | S_family=0.0156 | gap=0.1223 | alpha_std=0.02799

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4360 | S_p=0.1362 | S_m=-0.0942 | S_family=0.0210 | gap=0.2304 | alpha_std=0.02727

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4323 | S_p=0.1307 | S_m=-0.0791 | S_family=0.0258 | gap=0.2098 | alpha_std=0.02724

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3285 | S_p=0.0749 | S_m=0.0327 | S_family=0.0538 | gap=0.0422 | alpha_std=0.02677

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3414 | S_p=0.0611 | S_m=0.0131 | S_family=0.0371 | gap=0.0480 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=-0.0683 | S_p=-0.0524 | S_m=0.0314 | S_family=-0.0105 | gap=0.0838 | alpha_std=0.02570

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=-0.0663 | S_p=-0.0502 | S_m=0.0247 | S_family=-0.0128 | gap=0.0750 | alpha_std=0.02569

Triada 91/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3970 | S_p=0.0736 | S_m=-0.0114 | S_family=0.0311 | gap=0.0851 | alpha_std=0.02737

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4088 | S_p=0.0808 | S_m=0.0051 | S_family=0.0429 | gap=0.0757 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4985 | S_p=0.0563 | S_m=0.0120 | S_family=0.0341 | gap=0.0443 | alpha_std=0.02762

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4765 | S_p=0.0281 | S_m=0.0208 | S_family=0.0245 | gap=0.0074 | alpha_std=0.02747

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0504 | S_p=-0.0335 | S_m=-0.0371 | S_family=-0.0353 | gap=0.0036 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0487 | S_p=-0.0059 | S_m=-0.0389 | S_family=-0.0224 | gap=0.0330 | alpha_std=0.02601

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.4341 | S_p=0.0770 | S_m=0.0209 | S_family=0.0489 | gap=0.0561 | alpha_std=0.02769

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.4282 | S_p=0.0834 | S_m=0.0379 | S_family=0.0607 | gap=0.0454 | alpha_std=0.02770

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3539 | S_p=0.0493 | S_m=0.0864 | S_family=0.0678 | gap=0.0371 | alpha_std=0.02824

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3646 | S_p=0.0480 | S_m=0.0980 | S_family=0.0730 | gap=0.0500 | alpha_std=0.02826

Triada 92/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3631 | S_p=0.0579 | S_m=-0.0422 | S_family=0.0078 | gap=0.1002 | alpha_std=0.02717

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3732 | S_p=0.0809 | S_m=-0.0336 | S_family=0.0237 | gap=0.1145 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0878 | S_p=0.0005 | S_m=-0.0319 | S_family=-0.0157 | gap=0.0323 | alpha_std=0.02697

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0734 | S_p=0.0245 | S_m=-0.0488 | S_family=-0.0121 | gap=0.0733 | alpha_std=0.02671

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2466 | S_p=0.1268 | S_m=-0.0574 | S_family=0.0347 | gap=0.1841 | alpha_std=0.02694

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2284 | S_p=0.1312 | S_m=-0.0625 | S_family=0.0343 | gap=0.1938 | alpha_std=0.02683

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1581 | S_p=0.0838 | S_m=-0.0276 | S_family=0.0281 | gap=0.1114 | alpha_std=0.02602

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1516 | S_p=0.0956 | S_m=-0.0124 | S_family=0.0416 | gap=0.1080 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0528 | S_p=-0.0512 | S_m=-0.0232 | S_family=-0.0372 | gap=0.0280 | alpha_std=0.02632

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0327 | S_p=-0.0423 | S_m=-0.0417 | S_family=-0.0420 | gap=0.0006 | alpha_std=0.02627

Triada 93/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2794 | S_p=0.0425 | S_m=-0.0701 | S_family=-0.0138 | gap=0.1126 | alpha_std=0.02745

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2964 | S_p=0.0480 | S_m=-0.0587 | S_family=-0.0053 | gap=0.1067 | alpha_std=0.02731

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1948 | S_p=0.0124 | S_m=0.0259 | S_family=0.0192 | gap=0.0135 | alpha_std=0.02585

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2150 | S_p=0.0156 | S_m=0.0375 | S_family=0.0265 | gap=0.0220 | alpha_std=0.02584

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3742 | S_p=-0.0374 | S_m=-0.0798 | S_family=-0.0586 | gap=0.0424 | alpha_std=0.02714

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3902 | S_p=-0.0140 | S_m=-0.0713 | S_family=-0.0427 | gap=0.0573 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2427 | S_p=0.0456 | S_m=-0.1350 | S_family=-0.0447 | gap=0.1806 | alpha_std=0.02735

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2425 | S_p=0.0457 | S_m=-0.1188 | S_family=-0.0365 | gap=0.1644 | alpha_std=0.02737

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3083 | S_p=0.0785 | S_m=0.0307 | S_family=0.0546 | gap=0.0478 | alpha_std=0.02790

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3212 | S_p=0.0911 | S_m=0.0487 | S_family=0.0699 | gap=0.0424 | alpha_std=0.02791

Triada 94/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2946 | S_p=0.0007 | S_m=-0.0267 | S_family=-0.0130 | gap=0.0273 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2714 | S_p=-0.0110 | S_m=-0.0138 | S_family=-0.0124 | gap=0.0028 | alpha_std=0.02681

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1306 | S_p=0.0672 | S_m=-0.0674 | S_family=-0.0001 | gap=0.1347 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1344 | S_p=0.0631 | S_m=0.0342 | S_family=0.0487 | gap=0.0289 | alpha_std=0.02654

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1088 | S_p=0.0619 | S_m=-0.0276 | S_family=0.0172 | gap=0.0895 | alpha_std=0.02661

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1041 | S_p=0.0739 | S_m=-0.0233 | S_family=0.0253 | gap=0.0972 | alpha_std=0.02657

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1456 | S_p=0.0938 | S_m=-0.0014 | S_family=0.0462 | gap=0.0952 | alpha_std=0.02680

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1913 | S_p=0.1373 | S_m=0.0198 | S_family=0.0785 | gap=0.1175 | alpha_std=0.02694

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0594 | S_p=0.0418 | S_m=0.0523 | S_family=0.0471 | gap=0.0106 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0606 | S_p=0.0663 | S_m=0.0520 | S_family=0.0591 | gap=0.0143 | alpha_std=0.02754

Triada 95/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2239 | S_p=0.1052 | S_m=0.0176 | S_family=0.0614 | gap=0.0876 | alpha_std=0.02883

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2205 | S_p=0.1133 | S_m=0.0202 | S_family=0.0667 | gap=0.0932 | alpha_std=0.02882

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3067 | S_p=0.0671 | S_m=-0.0288 | S_family=0.0191 | gap=0.0959 | alpha_std=0.02911

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3233 | S_p=0.0969 | S_m=0.0032 | S_family=0.0500 | gap=0.0937 | alpha_std=0.02915

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0705 | S_p=-0.0164 | S_m=0.0026 | S_family=-0.0069 | gap=0.0190 | alpha_std=0.02822

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0699 | S_p=-0.0249 | S_m=0.0153 | S_family=-0.0048 | gap=0.0402 | alpha_std=0.02829

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0884 | S_p=0.0052 | S_m=-0.0626 | S_family=-0.0287 | gap=0.0679 | alpha_std=0.02867

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1006 | S_p=0.0121 | S_m=-0.0386 | S_family=-0.0133 | gap=0.0507 | alpha_std=0.02858

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3058 | S_p=0.0565 | S_m=-0.0535 | S_family=0.0015 | gap=0.1100 | alpha_std=0.03001

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3071 | S_p=0.0567 | S_m=-0.0510 | S_family=0.0028 | gap=0.1077 | alpha_std=0.03012

Triada 96/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1789 | S_p=0.0891 | S_m=0.1086 | S_family=0.0989 | gap=0.0195 | alpha_std=0.02873

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1688 | S_p=0.0921 | S_m=0.1194 | S_family=0.1057 | gap=0.0273 | alpha_std=0.02875

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2171 | S_p=0.0321 | S_m=0.0164 | S_family=0.0242 | gap=0.0156 | alpha_std=0.02843

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1986 | S_p=0.0434 | S_m=0.0187 | S_family=0.0311 | gap=0.0247 | alpha_std=0.02833

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1499 | S_p=0.0443 | S_m=0.0610 | S_family=0.0526 | gap=0.0166 | alpha_std=0.02788

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1261 | S_p=0.0096 | S_m=0.0418 | S_family=0.0257 | gap=0.0322 | alpha_std=0.02807

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0761 | S_p=-0.0394 | S_m=0.0688 | S_family=0.0147 | gap=0.1082 | alpha_std=0.02787

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0832 | S_p=-0.0382 | S_m=0.0715 | S_family=0.0167 | gap=0.1097 | alpha_std=0.02783

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1386 | S_p=-0.0278 | S_m=0.1009 | S_family=0.0365 | gap=0.1288 | alpha_std=0.02846

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1481 | S_p=-0.0460 | S_m=0.0554 | S_family=0.0047 | gap=0.1015 | alpha_std=0.02832

Triada 97/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0192 | S_p=-0.0345 | S_m=-0.0534 | S_family=-0.0440 | gap=0.0188 | alpha_std=0.02461

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0382 | S_p=-0.0310 | S_m=-0.0547 | S_family=-0.0428 | gap=0.0237 | alpha_std=0.02470

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0623 | S_p=0.0295 | S_m=-0.1254 | S_family=-0.0479 | gap=0.1549 | alpha_std=0.02527

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0776 | S_p=0.0061 | S_m=-0.1152 | S_family=-0.0545 | gap=0.1213 | alpha_std=0.02532

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2508 | S_p=0.0498 | S_m=0.0260 | S_family=0.0379 | gap=0.0238 | alpha_std=0.02590

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2567 | S_p=0.0537 | S_m=0.0434 | S_family=0.0485 | gap=0.0102 | alpha_std=0.02588

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2655 | S_p=0.0812 | S_m=0.0514 | S_family=0.0663 | gap=0.0298 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2602 | S_p=0.0877 | S_m=0.0634 | S_family=0.0755 | gap=0.0243 | alpha_std=0.02601

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1815 | S_p=0.0734 | S_m=0.0914 | S_family=0.0824 | gap=0.0181 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1854 | S_p=0.0797 | S_m=0.1018 | S_family=0.0908 | gap=0.0221 | alpha_std=0.02584

Triada 98/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0170 | S_p=0.0108 | S_m=0.0052 | S_family=0.0080 | gap=0.0056 | alpha_std=0.02345

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0378 | S_p=0.0126 | S_m=0.0207 | S_family=0.0167 | gap=0.0081 | alpha_std=0.02347

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1449 | S_p=0.0829 | S_m=0.0593 | S_family=0.0711 | gap=0.0237 | alpha_std=0.02407

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1317 | S_p=0.0931 | S_m=0.0370 | S_family=0.0650 | gap=0.0561 | alpha_std=0.02408

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0343 | S_p=-0.0014 | S_m=-0.0326 | S_family=-0.0170 | gap=0.0312 | alpha_std=0.02413

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0369 | S_p=0.0082 | S_m=-0.0325 | S_family=-0.0121 | gap=0.0407 | alpha_std=0.02413

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0387 | S_p=0.0181 | S_m=-0.0023 | S_family=0.0079 | gap=0.0203 | alpha_std=0.02370

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0315 | S_p=0.0090 | S_m=0.0015 | S_family=0.0052 | gap=0.0074 | alpha_std=0.02374

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0471 | S_p=-0.0128 | S_m=0.0131 | S_family=0.0001 | gap=0.0259 | alpha_std=0.02417

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0364 | S_p=-0.0083 | S_m=0.0350 | S_family=0.0134 | gap=0.0433 | alpha_std=0.02414

Triada 99/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1582 | S_p=-0.0566 | S_m=0.1111 | S_family=0.0273 | gap=0.1678 | alpha_std=0.02563

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1679 | S_p=-0.0412 | S_m=0.1185 | S_family=0.0386 | gap=0.1597 | alpha_std=0.02563

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1286 | S_p=-0.0570 | S_m=0.0431 | S_family=-0.0070 | gap=0.1000 | alpha_std=0.02497

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1066 | S_p=-0.0508 | S_m=0.0316 | S_family=-0.0096 | gap=0.0824 | alpha_std=0.02508

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1140 | S_p=-0.0178 | S_m=-0.0048 | S_family=-0.0113 | gap=0.0130 | alpha_std=0.02530

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1185 | S_p=-0.0159 | S_m=-0.0139 | S_family=-0.0149 | gap=0.0020 | alpha_std=0.02529

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1968 | S_p=-0.0475 | S_m=0.0522 | S_family=0.0023 | gap=0.0997 | alpha_std=0.02636

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2294 | S_p=-0.0117 | S_m=0.0598 | S_family=0.0241 | gap=0.0714 | alpha_std=0.02638

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=-0.0380 | S_p=0.0193 | S_m=-0.0361 | S_family=-0.0084 | gap=0.0554 | alpha_std=0.02492

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=-0.0380 | S_p=0.0192 | S_m=-0.0454 | S_family=-0.0131 | gap=0.0646 | alpha_std=0.02489

Triada 100/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2577 | S_p=-0.0328 | S_m=-0.0496 | S_family=-0.0412 | gap=0.0168 | alpha_std=0.02598

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2631 | S_p=-0.0223 | S_m=-0.0445 | S_family=-0.0334 | gap=0.0221 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1585 | S_p=-0.0242 | S_m=-0.1173 | S_family=-0.0708 | gap=0.0931 | alpha_std=0.02690

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1583 | S_p=-0.0026 | S_m=-0.0938 | S_family=-0.0482 | gap=0.0912 | alpha_std=0.02690

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2160 | S_p=-0.0487 | S_m=-0.0240 | S_family=-0.0364 | gap=0.0247 | alpha_std=0.02725

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2170 | S_p=-0.0433 | S_m=-0.0043 | S_family=-0.0238 | gap=0.0390 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1629 | S_p=-0.0623 | S_m=0.0440 | S_family=-0.0091 | gap=0.1064 | alpha_std=0.02743

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1799 | S_p=-0.0343 | S_m=0.0512 | S_family=0.0084 | gap=0.0855 | alpha_std=0.02737

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1657 | S_p=-0.0325 | S_m=0.0840 | S_family=0.0257 | gap=0.1166 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1671 | S_p=-0.0277 | S_m=0.1007 | S_family=0.0365 | gap=0.1284 | alpha_std=0.02671

Triada 101/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1808 | S_p=0.0200 | S_m=-0.0590 | S_family=-0.0195 | gap=0.0790 | alpha_std=0.02503

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1988 | S_p=0.0042 | S_m=-0.0580 | S_family=-0.0269 | gap=0.0622 | alpha_std=0.02508

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0115 | S_p=-0.0629 | S_m=-0.0267 | S_family=-0.0448 | gap=0.0363 | alpha_std=0.02527

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0444 | S_p=0.0004 | S_m=-0.0282 | S_family=-0.0139 | gap=0.0286 | alpha_std=0.02536

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1630 | S_p=-0.0510 | S_m=-0.0046 | S_family=-0.0278 | gap=0.0464 | alpha_std=0.02556

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1566 | S_p=-0.0489 | S_m=0.0137 | S_family=-0.0176 | gap=0.0626 | alpha_std=0.02550

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1822 | S_p=-0.0270 | S_m=-0.0002 | S_family=-0.0136 | gap=0.0268 | alpha_std=0.02644

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1755 | S_p=-0.0263 | S_m=0.0004 | S_family=-0.0130 | gap=0.0267 | alpha_std=0.02648

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2347 | S_p=-0.0225 | S_m=0.0361 | S_family=0.0068 | gap=0.0585 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2369 | S_p=-0.0083 | S_m=0.0695 | S_family=0.0306 | gap=0.0778 | alpha_std=0.02601

Triada 102/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1602 | S_p=-0.0078 | S_m=0.1755 | S_family=0.0838 | gap=0.1833 | alpha_std=0.02584

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1633 | S_p=-0.0148 | S_m=0.1748 | S_family=0.0800 | gap=0.1896 | alpha_std=0.02587

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2482 | S_p=0.1647 | S_m=0.1221 | S_family=0.1434 | gap=0.0426 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2639 | S_p=0.1852 | S_m=0.1368 | S_family=0.1610 | gap=0.0484 | alpha_std=0.02622

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1529 | S_p=0.0029 | S_m=0.0334 | S_family=0.0182 | gap=0.0306 | alpha_std=0.02602

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1558 | S_p=-0.0056 | S_m=0.0247 | S_family=0.0096 | gap=0.0304 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1563 | S_p=0.1016 | S_m=0.1705 | S_family=0.1360 | gap=0.0689 | alpha_std=0.02529

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1559 | S_p=0.1103 | S_m=0.1803 | S_family=0.1453 | gap=0.0701 | alpha_std=0.02529

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1787 | S_p=-0.0037 | S_m=0.0988 | S_family=0.0475 | gap=0.1026 | alpha_std=0.02646

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1966 | S_p=0.0118 | S_m=0.1163 | S_family=0.0641 | gap=0.1045 | alpha_std=0.02646

Triada 103/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2511 | S_p=0.0704 | S_m=0.0671 | S_family=0.0688 | gap=0.0034 | alpha_std=0.02680

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2632 | S_p=0.0784 | S_m=0.0790 | S_family=0.0787 | gap=0.0006 | alpha_std=0.02681

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2830 | S_p=0.0920 | S_m=0.0828 | S_family=0.0874 | gap=0.0092 | alpha_std=0.02640

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2760 | S_p=0.0939 | S_m=0.0883 | S_family=0.0911 | gap=0.0055 | alpha_std=0.02639

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0107 | S_p=0.0231 | S_m=0.0380 | S_family=0.0305 | gap=0.0149 | alpha_std=0.02576

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0107 | S_p=0.0253 | S_m=0.0426 | S_family=0.0339 | gap=0.0173 | alpha_std=0.02578

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1129 | S_p=0.1132 | S_m=0.1292 | S_family=0.1212 | gap=0.0160 | alpha_std=0.02551

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1297 | S_p=0.1135 | S_m=0.1367 | S_family=0.1251 | gap=0.0231 | alpha_std=0.02546

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2192 | S_p=0.1190 | S_m=0.0709 | S_family=0.0949 | gap=0.0481 | alpha_std=0.02652

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2557 | S_p=0.1216 | S_m=0.1091 | S_family=0.1153 | gap=0.0125 | alpha_std=0.02653

Triada 104/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3188 | S_p=-0.0687 | S_m=0.0765 | S_family=0.0039 | gap=0.1452 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3154 | S_p=-0.0668 | S_m=0.0746 | S_family=0.0039 | gap=0.1414 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1239 | S_p=0.0486 | S_m=-0.0710 | S_family=-0.0112 | gap=0.1196 | alpha_std=0.02689

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1297 | S_p=0.0532 | S_m=-0.0636 | S_family=-0.0052 | gap=0.1168 | alpha_std=0.02686

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2117 | S_p=-0.0468 | S_m=0.1013 | S_family=0.0273 | gap=0.1481 | alpha_std=0.02745

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2006 | S_p=-0.0321 | S_m=0.1109 | S_family=0.0394 | gap=0.1431 | alpha_std=0.02741

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2602 | S_p=0.0179 | S_m=-0.0042 | S_family=0.0068 | gap=0.0221 | alpha_std=0.02745

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2113 | S_p=0.0615 | S_m=-0.0001 | S_family=0.0307 | gap=0.0616 | alpha_std=0.02740

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2028 | S_p=-0.0114 | S_m=0.0027 | S_family=-0.0044 | gap=0.0141 | alpha_std=0.02721

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1818 | S_p=-0.0081 | S_m=-0.0079 | S_family=-0.0080 | gap=0.0002 | alpha_std=0.02718

Triada 105/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3660 | S_p=0.0743 | S_m=0.0702 | S_family=0.0723 | gap=0.0041 | alpha_std=0.02723

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3502 | S_p=0.0687 | S_m=0.0765 | S_family=0.0726 | gap=0.0078 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2173 | S_p=-0.0337 | S_m=0.1383 | S_family=0.0523 | gap=0.1720 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2388 | S_p=-0.0095 | S_m=0.0887 | S_family=0.0396 | gap=0.0981 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3518 | S_p=0.1142 | S_m=0.0789 | S_family=0.0965 | gap=0.0353 | alpha_std=0.02793

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3479 | S_p=0.1194 | S_m=0.0874 | S_family=0.1034 | gap=0.0320 | alpha_std=0.02793

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2824 | S_p=0.1005 | S_m=0.0781 | S_family=0.0893 | gap=0.0225 | alpha_std=0.02799

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3005 | S_p=0.0277 | S_m=0.1056 | S_family=0.0666 | gap=0.0779 | alpha_std=0.02793

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2802 | S_p=0.0155 | S_m=0.1318 | S_family=0.0737 | gap=0.1163 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2523 | S_p=0.0275 | S_m=0.1022 | S_family=0.0648 | gap=0.0747 | alpha_std=0.02759

Triada 106/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2309 | S_p=0.0388 | S_m=-0.1760 | S_family=-0.0686 | gap=0.2148 | alpha_std=0.02615

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2468 | S_p=0.0391 | S_m=-0.1592 | S_family=-0.0601 | gap=0.1983 | alpha_std=0.02616

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0850 | S_p=0.0229 | S_m=-0.0943 | S_family=-0.0357 | gap=0.1172 | alpha_std=0.02569

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0785 | S_p=0.0301 | S_m=-0.0667 | S_family=-0.0183 | gap=0.0968 | alpha_std=0.02565

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3913 | S_p=0.1608 | S_m=-0.0108 | S_family=0.0750 | gap=0.1716 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3836 | S_p=0.1603 | S_m=-0.0049 | S_family=0.0777 | gap=0.1652 | alpha_std=0.02678

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1835 | S_p=0.1363 | S_m=-0.0113 | S_family=0.0625 | gap=0.1476 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2027 | S_p=0.1511 | S_m=0.0036 | S_family=0.0774 | gap=0.1475 | alpha_std=0.02674

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1074 | S_p=0.1159 | S_m=-0.0290 | S_family=0.0435 | gap=0.1449 | alpha_std=0.02642

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1070 | S_p=0.1274 | S_m=-0.0246 | S_family=0.0514 | gap=0.1519 | alpha_std=0.02641

Triada 107/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4376 | S_p=0.0172 | S_m=-0.0115 | S_family=0.0028 | gap=0.0288 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4327 | S_p=0.0228 | S_m=0.0147 | S_family=0.0188 | gap=0.0081 | alpha_std=0.02644

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0679 | S_p=0.0199 | S_m=0.0441 | S_family=0.0320 | gap=0.0242 | alpha_std=0.02513

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0478 | S_p=-0.0150 | S_m=0.0389 | S_family=0.0120 | gap=0.0539 | alpha_std=0.02486

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1820 | S_p=-0.0106 | S_m=-0.0037 | S_family=-0.0072 | gap=0.0069 | alpha_std=0.02634

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1806 | S_p=-0.0229 | S_m=0.0007 | S_family=-0.0111 | gap=0.0235 | alpha_std=0.02632

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3575 | S_p=-0.0504 | S_m=0.0433 | S_family=-0.0035 | gap=0.0937 | alpha_std=0.02641

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3535 | S_p=-0.0559 | S_m=0.0478 | S_family=-0.0041 | gap=0.1037 | alpha_std=0.02640

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3674 | S_p=0.0166 | S_m=0.1028 | S_family=0.0597 | gap=0.0862 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3670 | S_p=0.0190 | S_m=0.1114 | S_family=0.0652 | gap=0.0923 | alpha_std=0.02676

Triada 108/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3599 | S_p=0.0234 | S_m=-0.0876 | S_family=-0.0321 | gap=0.1110 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3733 | S_p=-0.0033 | S_m=-0.0703 | S_family=-0.0368 | gap=0.0671 | alpha_std=0.02587

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2910 | S_p=0.0557 | S_m=-0.0383 | S_family=0.0087 | gap=0.0940 | alpha_std=0.02617

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2866 | S_p=0.1070 | S_m=-0.0205 | S_family=0.0432 | gap=0.1274 | alpha_std=0.02619

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0418 | S_p=-0.0382 | S_m=-0.0176 | S_family=-0.0279 | gap=0.0206 | alpha_std=0.02567

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0414 | S_p=-0.0410 | S_m=-0.0171 | S_family=-0.0291 | gap=0.0238 | alpha_std=0.02565

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1580 | S_p=0.0417 | S_m=-0.0090 | S_family=0.0163 | gap=0.0507 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1379 | S_p=0.0373 | S_m=0.0060 | S_family=0.0217 | gap=0.0314 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2408 | S_p=0.1050 | S_m=0.0045 | S_family=0.0547 | gap=0.1005 | alpha_std=0.02666

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2302 | S_p=0.1396 | S_m=0.0196 | S_family=0.0796 | gap=0.1200 | alpha_std=0.02666

Triada 109/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4158 | S_p=-0.0572 | S_m=-0.0515 | S_family=-0.0543 | gap=0.0057 | alpha_std=0.02630

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3984 | S_p=-0.0363 | S_m=-0.0407 | S_family=-0.0385 | gap=0.0044 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1068 | S_p=-0.0004 | S_m=-0.0306 | S_family=-0.0155 | gap=0.0302 | alpha_std=0.02576

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1106 | S_p=0.0071 | S_m=-0.0261 | S_family=-0.0095 | gap=0.0333 | alpha_std=0.02574

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3169 | S_p=0.0746 | S_m=-0.0140 | S_family=0.0303 | gap=0.0886 | alpha_std=0.02679

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3130 | S_p=0.0840 | S_m=0.0060 | S_family=0.0450 | gap=0.0780 | alpha_std=0.02679

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1224 | S_p=0.0246 | S_m=0.0009 | S_family=0.0127 | gap=0.0237 | alpha_std=0.02540

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1234 | S_p=0.0425 | S_m=0.0138 | S_family=0.0282 | gap=0.0287 | alpha_std=0.02541

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0715 | S_p=0.0239 | S_m=0.0383 | S_family=0.0311 | gap=0.0144 | alpha_std=0.02568

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0686 | S_p=0.0244 | S_m=0.0139 | S_family=0.0192 | gap=0.0105 | alpha_std=0.02593

Triada 110/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4271 | S_p=-0.0248 | S_m=0.0967 | S_family=0.0359 | gap=0.1216 | alpha_std=0.02681

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4348 | S_p=-0.0117 | S_m=0.1037 | S_family=0.0460 | gap=0.1154 | alpha_std=0.02675

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1786 | S_p=0.0307 | S_m=0.0220 | S_family=0.0263 | gap=0.0087 | alpha_std=0.02662

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1386 | S_p=0.0292 | S_m=0.0127 | S_family=0.0209 | gap=0.0165 | alpha_std=0.02664

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2568 | S_p=-0.0525 | S_m=0.0337 | S_family=-0.0094 | gap=0.0862 | alpha_std=0.02761

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2628 | S_p=-0.0414 | S_m=0.0656 | S_family=0.0121 | gap=0.1070 | alpha_std=0.02759

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0820 | S_p=-0.0958 | S_m=-0.0195 | S_family=-0.0577 | gap=0.0763 | alpha_std=0.02694

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0883 | S_p=-0.0927 | S_m=-0.0016 | S_family=-0.0471 | gap=0.0911 | alpha_std=0.02697

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1375 | S_p=0.0282 | S_m=0.0638 | S_family=0.0460 | gap=0.0355 | alpha_std=0.02689

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1393 | S_p=-0.0232 | S_m=0.0526 | S_family=0.0147 | gap=0.0758 | alpha_std=0.02712

Triada 111/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2843 | S_p=-0.0778 | S_m=-0.0636 | S_family=-0.0707 | gap=0.0142 | alpha_std=0.02556

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2900 | S_p=-0.0806 | S_m=-0.0457 | S_family=-0.0632 | gap=0.0349 | alpha_std=0.02554

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3664 | S_p=-0.0856 | S_m=0.0159 | S_family=-0.0348 | gap=0.1015 | alpha_std=0.02556

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2450 | S_p=-0.0253 | S_m=-0.0586 | S_family=-0.0420 | gap=0.0333 | alpha_std=0.02496

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2405 | S_p=0.0504 | S_m=-0.0132 | S_family=0.0186 | gap=0.0636 | alpha_std=0.02513

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2521 | S_p=0.0434 | S_m=-0.0099 | S_family=0.0167 | gap=0.0533 | alpha_std=0.02517

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0720 | S_p=0.0292 | S_m=-0.0401 | S_family=-0.0055 | gap=0.0693 | alpha_std=0.02481

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0673 | S_p=0.0248 | S_m=-0.0526 | S_family=-0.0139 | gap=0.0773 | alpha_std=0.02481

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2194 | S_p=-0.0041 | S_m=0.0473 | S_family=0.0216 | gap=0.0514 | alpha_std=0.02530

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2107 | S_p=0.0246 | S_m=0.0506 | S_family=0.0376 | gap=0.0260 | alpha_std=0.02530

Triada 112/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1687 | S_p=0.0191 | S_m=-0.0955 | S_family=-0.0382 | gap=0.1146 | alpha_std=0.02477

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1746 | S_p=0.0352 | S_m=-0.0857 | S_family=-0.0252 | gap=0.1209 | alpha_std=0.02478

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4431 | S_p=0.0022 | S_m=0.0275 | S_family=0.0148 | gap=0.0254 | alpha_std=0.02515

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4502 | S_p=-0.0283 | S_m=0.0040 | S_family=-0.0121 | gap=0.0323 | alpha_std=0.02522

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2679 | S_p=0.0210 | S_m=0.0267 | S_family=0.0238 | gap=0.0058 | alpha_std=0.02562

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2680 | S_p=-0.0063 | S_m=0.0527 | S_family=0.0232 | gap=0.0590 | alpha_std=0.02559

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0963 | S_p=-0.0087 | S_m=0.0619 | S_family=0.0266 | gap=0.0706 | alpha_std=0.02470

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1048 | S_p=0.0167 | S_m=0.0674 | S_family=0.0420 | gap=0.0506 | alpha_std=0.02471

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2424 | S_p=-0.0177 | S_m=0.0702 | S_family=0.0262 | gap=0.0879 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2752 | S_p=-0.0081 | S_m=0.0940 | S_family=0.0430 | gap=0.1021 | alpha_std=0.02546

Triada 113/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4275 | S_p=0.1300 | S_m=0.0298 | S_family=0.0799 | gap=0.1002 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4326 | S_p=0.1369 | S_m=0.0523 | S_family=0.0946 | gap=0.0846 | alpha_std=0.02715

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1119 | S_p=0.0347 | S_m=0.0180 | S_family=0.0264 | gap=0.0167 | alpha_std=0.02711

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0911 | S_p=0.0305 | S_m=0.0023 | S_family=0.0164 | gap=0.0282 | alpha_std=0.02713

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0864 | S_p=0.0081 | S_m=0.0453 | S_family=0.0267 | gap=0.0371 | alpha_std=0.02659

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0840 | S_p=0.0178 | S_m=0.0610 | S_family=0.0394 | gap=0.0432 | alpha_std=0.02659

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1169 | S_p=-0.0026 | S_m=0.1096 | S_family=0.0535 | gap=0.1123 | alpha_std=0.02617

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1661 | S_p=0.0276 | S_m=0.1169 | S_family=0.0722 | gap=0.0893 | alpha_std=0.02617

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1896 | S_p=0.0955 | S_m=-0.0168 | S_family=0.0393 | gap=0.1122 | alpha_std=0.02735

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2001 | S_p=0.1075 | S_m=0.0125 | S_family=0.0600 | gap=0.0950 | alpha_std=0.02734

Triada 114/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1163 | S_p=-0.0058 | S_m=0.0504 | S_family=0.0223 | gap=0.0561 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0923 | S_p=0.0120 | S_m=0.0647 | S_family=0.0383 | gap=0.0527 | alpha_std=0.02578

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1097 | S_p=-0.0362 | S_m=0.0686 | S_family=0.0162 | gap=0.1048 | alpha_std=0.02483

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1294 | S_p=-0.0018 | S_m=0.0355 | S_family=0.0169 | gap=0.0372 | alpha_std=0.02481

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0662 | S_p=0.0122 | S_m=0.0538 | S_family=0.0330 | gap=0.0415 | alpha_std=0.02587

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1075 | S_p=-0.0001 | S_m=0.0424 | S_family=0.0212 | gap=0.0425 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2575 | S_p=0.0765 | S_m=0.0123 | S_family=0.0444 | gap=0.0642 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2593 | S_p=0.0677 | S_m=0.0242 | S_family=0.0459 | gap=0.0435 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0409 | S_p=0.1018 | S_m=-0.0252 | S_family=0.0383 | gap=0.1270 | alpha_std=0.02534

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0437 | S_p=0.1066 | S_m=-0.0272 | S_family=0.0397 | gap=0.1338 | alpha_std=0.02533

Triada 115/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0404 | S_p=0.0084 | S_m=-0.0235 | S_family=-0.0076 | gap=0.0319 | alpha_std=0.02507

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0327 | S_p=0.0111 | S_m=-0.0184 | S_family=-0.0036 | gap=0.0295 | alpha_std=0.02510

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0694 | S_p=-0.0279 | S_m=-0.0379 | S_family=-0.0329 | gap=0.0100 | alpha_std=0.02451

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0692 | S_p=-0.0380 | S_m=-0.0377 | S_family=-0.0379 | gap=0.0003 | alpha_std=0.02452

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0722 | S_p=-0.0183 | S_m=-0.0150 | S_family=-0.0167 | gap=0.0033 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0523 | S_p=-0.0059 | S_m=-0.0012 | S_family=-0.0035 | gap=0.0047 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=-0.0623 | S_p=-0.0304 | S_m=-0.0936 | S_family=-0.0620 | gap=0.0631 | alpha_std=0.02509

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0541 | S_p=-0.0351 | S_m=-0.0863 | S_family=-0.0607 | gap=0.0512 | alpha_std=0.02509

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=-0.0488 | S_p=0.0290 | S_m=-0.0524 | S_family=-0.0117 | gap=0.0814 | alpha_std=0.02526

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=-0.0587 | S_p=0.0174 | S_m=-0.0594 | S_family=-0.0210 | gap=0.0769 | alpha_std=0.02525

Triada 116/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3731 | S_p=0.0982 | S_m=-0.0422 | S_family=0.0280 | gap=0.1404 | alpha_std=0.02582

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3220 | S_p=0.1256 | S_m=-0.0581 | S_family=0.0337 | gap=0.1836 | alpha_std=0.02585

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0321 | S_p=-0.0276 | S_m=-0.0505 | S_family=-0.0390 | gap=0.0229 | alpha_std=0.02485

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0250 | S_p=-0.0426 | S_m=-0.0500 | S_family=-0.0463 | gap=0.0074 | alpha_std=0.02484

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0656 | S_p=0.0170 | S_m=0.0294 | S_family=0.0232 | gap=0.0124 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0615 | S_p=0.0085 | S_m=0.0399 | S_family=0.0242 | gap=0.0314 | alpha_std=0.02532

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1910 | S_p=-0.0525 | S_m=0.0327 | S_family=-0.0099 | gap=0.0852 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1925 | S_p=-0.0382 | S_m=0.0500 | S_family=0.0059 | gap=0.0881 | alpha_std=0.02649

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0693 | S_p=0.0187 | S_m=0.0680 | S_family=0.0433 | gap=0.0493 | alpha_std=0.02564

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0679 | S_p=0.0457 | S_m=0.0868 | S_family=0.0662 | gap=0.0411 | alpha_std=0.02553

Triada 117/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2583 | S_p=0.0197 | S_m=0.1910 | S_family=0.1053 | gap=0.1713 | alpha_std=0.02863

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2727 | S_p=0.0243 | S_m=0.1559 | S_family=0.0901 | gap=0.1316 | alpha_std=0.02861

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0335 | S_p=-0.0130 | S_m=0.0037 | S_family=-0.0046 | gap=0.0167 | alpha_std=0.02804

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0374 | S_p=-0.0394 | S_m=0.0260 | S_family=-0.0067 | gap=0.0653 | alpha_std=0.02800

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4053 | S_p=0.0796 | S_m=0.0431 | S_family=0.0614 | gap=0.0364 | alpha_std=0.02868

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4220 | S_p=0.0948 | S_m=0.0662 | S_family=0.0805 | gap=0.0286 | alpha_std=0.02864

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2460 | S_p=0.0771 | S_m=0.0291 | S_family=0.0531 | gap=0.0480 | alpha_std=0.02794

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2380 | S_p=0.0591 | S_m=0.0450 | S_family=0.0521 | gap=0.0141 | alpha_std=0.02776

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0373 | S_p=-0.0434 | S_m=0.1202 | S_family=0.0384 | gap=0.1637 | alpha_std=0.02761

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0292 | S_p=-0.0327 | S_m=0.1126 | S_family=0.0400 | gap=0.1453 | alpha_std=0.02760

Triada 118/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3253 | S_p=0.0407 | S_m=-0.0151 | S_family=0.0128 | gap=0.0558 | alpha_std=0.02771

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3603 | S_p=0.0804 | S_m=0.0033 | S_family=0.0418 | gap=0.0771 | alpha_std=0.02798

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0442 | S_p=0.0226 | S_m=-0.0161 | S_family=0.0033 | gap=0.0387 | alpha_std=0.02706

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0201 | S_p=0.0449 | S_m=-0.0130 | S_family=0.0160 | gap=0.0579 | alpha_std=0.02702

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2744 | S_p=0.0644 | S_m=-0.1072 | S_family=-0.0214 | gap=0.1717 | alpha_std=0.02835

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2666 | S_p=0.0522 | S_m=-0.0756 | S_family=-0.0117 | gap=0.1278 | alpha_std=0.02853

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.4013 | S_p=-0.0219 | S_m=-0.0713 | S_family=-0.0466 | gap=0.0494 | alpha_std=0.02912

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.4053 | S_p=0.0001 | S_m=-0.0703 | S_family=-0.0351 | gap=0.0703 | alpha_std=0.02912

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2064 | S_p=0.0634 | S_m=-0.0149 | S_family=0.0242 | gap=0.0783 | alpha_std=0.02910

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1889 | S_p=0.0894 | S_m=-0.0100 | S_family=0.0397 | gap=0.0994 | alpha_std=0.02901

Triada 119/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2281 | S_p=0.0559 | S_m=0.0330 | S_family=0.0444 | gap=0.0229 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2208 | S_p=0.0039 | S_m=-0.0038 | S_family=0.0000 | gap=0.0077 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1985 | S_p=0.0639 | S_m=0.0127 | S_family=0.0383 | gap=0.0512 | alpha_std=0.02517

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1742 | S_p=0.0671 | S_m=0.0354 | S_family=0.0512 | gap=0.0317 | alpha_std=0.02518

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2340 | S_p=0.0340 | S_m=-0.0491 | S_family=-0.0076 | gap=0.0831 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2043 | S_p=0.0243 | S_m=0.0072 | S_family=0.0158 | gap=0.0170 | alpha_std=0.02675

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2431 | S_p=0.0246 | S_m=-0.0324 | S_family=-0.0039 | gap=0.0570 | alpha_std=0.02622

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2395 | S_p=0.0393 | S_m=-0.0148 | S_family=0.0123 | gap=0.0541 | alpha_std=0.02620

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1566 | S_p=0.0000 | S_m=0.0205 | S_family=0.0103 | gap=0.0205 | alpha_std=0.02643

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1537 | S_p=0.0104 | S_m=0.0240 | S_family=0.0172 | gap=0.0136 | alpha_std=0.02640

Triada 120/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2758 | S_p=0.0695 | S_m=0.0488 | S_family=0.0592 | gap=0.0207 | alpha_std=0.02601

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2721 | S_p=0.0729 | S_m=0.0619 | S_family=0.0674 | gap=0.0110 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0224 | S_p=0.0419 | S_m=0.0321 | S_family=0.0370 | gap=0.0097 | alpha_std=0.02471

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0352 | S_p=0.0390 | S_m=0.0221 | S_family=0.0306 | gap=0.0169 | alpha_std=0.02467

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3706 | S_p=0.0729 | S_m=0.0182 | S_family=0.0456 | gap=0.0547 | alpha_std=0.02620

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3708 | S_p=0.0820 | S_m=0.0337 | S_family=0.0578 | gap=0.0483 | alpha_std=0.02618

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.4238 | S_p=-0.0121 | S_m=0.0878 | S_family=0.0379 | gap=0.1000 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.4359 | S_p=0.0002 | S_m=0.0907 | S_family=0.0454 | gap=0.0904 | alpha_std=0.02622

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1225 | S_p=0.0454 | S_m=-0.0266 | S_family=0.0094 | gap=0.0720 | alpha_std=0.02537

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1668 | S_p=0.0664 | S_m=-0.0366 | S_family=0.0149 | gap=0.1030 | alpha_std=0.02535

Triada 121/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0696 | S_p=0.0044 | S_m=0.0134 | S_family=0.0089 | gap=0.0090 | alpha_std=0.02619

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0613 | S_p=0.0029 | S_m=0.0015 | S_family=0.0022 | gap=0.0013 | alpha_std=0.02621

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1953 | S_p=0.0434 | S_m=0.1148 | S_family=0.0791 | gap=0.0714 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2002 | S_p=0.0559 | S_m=0.1008 | S_family=0.0783 | gap=0.0449 | alpha_std=0.02734

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3717 | S_p=-0.0229 | S_m=-0.0030 | S_family=-0.0129 | gap=0.0199 | alpha_std=0.02658

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3639 | S_p=-0.0134 | S_m=0.0149 | S_family=0.0008 | gap=0.0283 | alpha_std=0.02653

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3854 | S_p=-0.0603 | S_m=0.2145 | S_family=0.0771 | gap=0.2748 | alpha_std=0.02792

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3884 | S_p=-0.0355 | S_m=0.2075 | S_family=0.0860 | gap=0.2430 | alpha_std=0.02789

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2111 | S_p=0.0454 | S_m=0.0749 | S_family=0.0602 | gap=0.0295 | alpha_std=0.02797

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2268 | S_p=0.0599 | S_m=0.0912 | S_family=0.0755 | gap=0.0313 | alpha_std=0.02798

Triada 122/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2789 | S_p=0.0740 | S_m=0.0647 | S_family=0.0693 | gap=0.0093 | alpha_std=0.02685

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2905 | S_p=0.0843 | S_m=0.0707 | S_family=0.0775 | gap=0.0136 | alpha_std=0.02687

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2743 | S_p=0.0352 | S_m=0.1161 | S_family=0.0756 | gap=0.0809 | alpha_std=0.02641

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2649 | S_p=0.0464 | S_m=0.1137 | S_family=0.0801 | gap=0.0673 | alpha_std=0.02642

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0299 | S_p=-0.0279 | S_m=0.0195 | S_family=-0.0042 | gap=0.0475 | alpha_std=0.02581

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0387 | S_p=-0.0358 | S_m=0.0208 | S_family=-0.0075 | gap=0.0566 | alpha_std=0.02573

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2978 | S_p=0.0080 | S_m=0.0272 | S_family=0.0176 | gap=0.0192 | alpha_std=0.02784

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3034 | S_p=0.0173 | S_m=0.0349 | S_family=0.0261 | gap=0.0176 | alpha_std=0.02782

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1927 | S_p=-0.0031 | S_m=0.1058 | S_family=0.0514 | gap=0.1090 | alpha_std=0.02757

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2080 | S_p=0.0178 | S_m=0.1075 | S_family=0.0627 | gap=0.0897 | alpha_std=0.02760

Triada 123/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1657 | S_p=0.0080 | S_m=0.1008 | S_family=0.0544 | gap=0.0929 | alpha_std=0.02586

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1340 | S_p=0.0031 | S_m=0.0936 | S_family=0.0483 | gap=0.0905 | alpha_std=0.02586

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1556 | S_p=0.0538 | S_m=-0.0140 | S_family=0.0199 | gap=0.0677 | alpha_std=0.02730

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1907 | S_p=0.0830 | S_m=0.0029 | S_family=0.0430 | gap=0.0801 | alpha_std=0.02727

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1461 | S_p=0.0750 | S_m=0.1125 | S_family=0.0938 | gap=0.0375 | alpha_std=0.02678

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1425 | S_p=0.0719 | S_m=0.1386 | S_family=0.1052 | gap=0.0667 | alpha_std=0.02679

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0220 | S_p=0.0108 | S_m=-0.0517 | S_family=-0.0204 | gap=0.0625 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0024 | S_p=0.0190 | S_m=-0.0604 | S_family=-0.0207 | gap=0.0795 | alpha_std=0.02622

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2486 | S_p=0.0206 | S_m=-0.0429 | S_family=-0.0111 | gap=0.0635 | alpha_std=0.02788

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1006 | S_p=-0.0295 | S_m=0.0382 | S_family=0.0044 | gap=0.0677 | alpha_std=0.02678

Triada 124/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3385 | S_p=0.0188 | S_m=0.0420 | S_family=0.0304 | gap=0.0232 | alpha_std=0.02664

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4335 | S_p=-0.0012 | S_m=0.0357 | S_family=0.0172 | gap=0.0369 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3822 | S_p=0.0502 | S_m=0.0562 | S_family=0.0532 | gap=0.0060 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3802 | S_p=0.0491 | S_m=0.0483 | S_family=0.0487 | gap=0.0008 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3587 | S_p=0.0128 | S_m=0.0072 | S_family=0.0100 | gap=0.0055 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3573 | S_p=0.0271 | S_m=0.0108 | S_family=0.0189 | gap=0.0163 | alpha_std=0.02756

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2289 | S_p=-0.0038 | S_m=0.1277 | S_family=0.0619 | gap=0.1315 | alpha_std=0.02769

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2372 | S_p=-0.0114 | S_m=0.1385 | S_family=0.0636 | gap=0.1499 | alpha_std=0.02769

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1557 | S_p=0.1435 | S_m=0.0295 | S_family=0.0865 | gap=0.1140 | alpha_std=0.02709

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1473 | S_p=0.1352 | S_m=0.0055 | S_family=0.0704 | gap=0.1297 | alpha_std=0.02709

Triada 125/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3260 | S_p=-0.0297 | S_m=-0.0167 | S_family=-0.0232 | gap=0.0130 | alpha_std=0.02716

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3654 | S_p=-0.0511 | S_m=-0.0884 | S_family=-0.0698 | gap=0.0372 | alpha_std=0.02715

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0006 | S_p=-0.0195 | S_m=0.0502 | S_family=0.0154 | gap=0.0697 | alpha_std=0.02607

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0142 | S_p=-0.0340 | S_m=0.0298 | S_family=-0.0021 | gap=0.0638 | alpha_std=0.02609

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1096 | S_p=0.0078 | S_m=-0.0311 | S_family=-0.0116 | gap=0.0390 | alpha_std=0.02704

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1237 | S_p=0.0163 | S_m=-0.0060 | S_family=0.0052 | gap=0.0224 | alpha_std=0.02705

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2525 | S_p=-0.0639 | S_m=-0.0343 | S_family=-0.0491 | gap=0.0296 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3246 | S_p=-0.0532 | S_m=-0.0041 | S_family=-0.0286 | gap=0.0490 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1196 | S_p=-0.0346 | S_m=-0.0244 | S_family=-0.0295 | gap=0.0102 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1306 | S_p=-0.0296 | S_m=-0.0182 | S_family=-0.0239 | gap=0.0114 | alpha_std=0.02715

Triada 126/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1981 | S_p=0.0078 | S_m=0.1322 | S_family=0.0700 | gap=0.1244 | alpha_std=0.02498

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1952 | S_p=0.0207 | S_m=0.1421 | S_family=0.0814 | gap=0.1214 | alpha_std=0.02499

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2313 | S_p=0.0408 | S_m=0.1195 | S_family=0.0802 | gap=0.0787 | alpha_std=0.02524

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2410 | S_p=0.0519 | S_m=0.1376 | S_family=0.0948 | gap=0.0857 | alpha_std=0.02526

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2084 | S_p=0.0263 | S_m=0.0879 | S_family=0.0571 | gap=0.0616 | alpha_std=0.02628

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1930 | S_p=0.0657 | S_m=0.0941 | S_family=0.0799 | gap=0.0284 | alpha_std=0.02614

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0832 | S_p=0.0640 | S_m=0.1178 | S_family=0.0909 | gap=0.0538 | alpha_std=0.02564

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0798 | S_p=0.0755 | S_m=0.1274 | S_family=0.1015 | gap=0.0519 | alpha_std=0.02564

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1917 | S_p=0.0622 | S_m=0.0117 | S_family=0.0370 | gap=0.0505 | alpha_std=0.02579

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2031 | S_p=0.0708 | S_m=0.0339 | S_family=0.0524 | gap=0.0369 | alpha_std=0.02577

Triada 127/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3571 | S_p=0.0009 | S_m=0.1385 | S_family=0.0697 | gap=0.1376 | alpha_std=0.02815

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3545 | S_p=0.0117 | S_m=0.1509 | S_family=0.0813 | gap=0.1393 | alpha_std=0.02815

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4520 | S_p=-0.0342 | S_m=0.1000 | S_family=0.0329 | gap=0.1342 | alpha_std=0.02914

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4580 | S_p=-0.0164 | S_m=0.1123 | S_family=0.0480 | gap=0.1287 | alpha_std=0.02911

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3701 | S_p=-0.0657 | S_m=0.0695 | S_family=0.0019 | gap=0.1352 | alpha_std=0.02874

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3756 | S_p=-0.0495 | S_m=0.0842 | S_family=0.0173 | gap=0.1337 | alpha_std=0.02872

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0728 | S_p=-0.0124 | S_m=0.0742 | S_family=0.0309 | gap=0.0866 | alpha_std=0.02709

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1018 | S_p=-0.0140 | S_m=0.0660 | S_family=0.0260 | gap=0.0800 | alpha_std=0.02717

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2750 | S_p=-0.0466 | S_m=0.0635 | S_family=0.0084 | gap=0.1101 | alpha_std=0.02750

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3069 | S_p=-0.0189 | S_m=0.0766 | S_family=0.0288 | gap=0.0955 | alpha_std=0.02747

Triada 128/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3785 | S_p=-0.0224 | S_m=0.0831 | S_family=0.0303 | gap=0.1056 | alpha_std=0.02798

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3943 | S_p=-0.0138 | S_m=0.0944 | S_family=0.0403 | gap=0.1082 | alpha_std=0.02797

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0992 | S_p=-0.0681 | S_m=0.0924 | S_family=0.0121 | gap=0.1605 | alpha_std=0.02743

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1068 | S_p=-0.0194 | S_m=0.1044 | S_family=0.0425 | gap=0.1238 | alpha_std=0.02737

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2187 | S_p=-0.0001 | S_m=-0.0401 | S_family=-0.0201 | gap=0.0400 | alpha_std=0.02885

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2221 | S_p=0.0203 | S_m=-0.0298 | S_family=-0.0048 | gap=0.0501 | alpha_std=0.02885

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1980 | S_p=0.1540 | S_m=-0.0177 | S_family=0.0681 | gap=0.1718 | alpha_std=0.02892

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1906 | S_p=0.1704 | S_m=-0.0057 | S_family=0.0823 | gap=0.1761 | alpha_std=0.02893

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2462 | S_p=0.1776 | S_m=-0.0191 | S_family=0.0793 | gap=0.1966 | alpha_std=0.02857

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2464 | S_p=0.1898 | S_m=-0.0257 | S_family=0.0821 | gap=0.2155 | alpha_std=0.02856

Triada 129/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4423 | S_p=-0.0438 | S_m=0.0974 | S_family=0.0268 | gap=0.1412 | alpha_std=0.02528

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4574 | S_p=-0.0298 | S_m=0.0898 | S_family=0.0300 | gap=0.1195 | alpha_std=0.02536

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1362 | S_p=-0.0017 | S_m=0.0664 | S_family=0.0323 | gap=0.0681 | alpha_std=0.02478

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1303 | S_p=-0.0143 | S_m=0.0738 | S_family=0.0297 | gap=0.0881 | alpha_std=0.02480

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3303 | S_p=0.0220 | S_m=0.1190 | S_family=0.0705 | gap=0.0970 | alpha_std=0.02531

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3310 | S_p=-0.0140 | S_m=0.1489 | S_family=0.0675 | gap=0.1629 | alpha_std=0.02520

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0844 | S_p=-0.0023 | S_m=-0.0204 | S_family=-0.0114 | gap=0.0181 | alpha_std=0.02517

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0724 | S_p=-0.0035 | S_m=-0.0194 | S_family=-0.0115 | gap=0.0159 | alpha_std=0.02515

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2561 | S_p=-0.0130 | S_m=0.1963 | S_family=0.0917 | gap=0.2093 | alpha_std=0.02572

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2343 | S_p=-0.0099 | S_m=0.1910 | S_family=0.0906 | gap=0.2009 | alpha_std=0.02570

Triada 130/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1715 | S_p=0.0190 | S_m=-0.0416 | S_family=-0.0113 | gap=0.0607 | alpha_std=0.02507

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1843 | S_p=0.0341 | S_m=-0.0368 | S_family=-0.0014 | gap=0.0709 | alpha_std=0.02513

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2117 | S_p=-0.0333 | S_m=-0.0097 | S_family=-0.0215 | gap=0.0236 | alpha_std=0.02535

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2191 | S_p=-0.0300 | S_m=-0.0023 | S_family=-0.0162 | gap=0.0278 | alpha_std=0.02530

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4132 | S_p=0.0494 | S_m=-0.0345 | S_family=0.0074 | gap=0.0839 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3932 | S_p=0.0408 | S_m=-0.0500 | S_family=-0.0046 | gap=0.0908 | alpha_std=0.02584

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2389 | S_p=0.0366 | S_m=0.0412 | S_family=0.0389 | gap=0.0046 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2362 | S_p=0.0477 | S_m=0.0539 | S_family=0.0508 | gap=0.0062 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3373 | S_p=0.0772 | S_m=0.0460 | S_family=0.0616 | gap=0.0312 | alpha_std=0.02629

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2926 | S_p=0.0675 | S_m=0.0669 | S_family=0.0672 | gap=0.0006 | alpha_std=0.02609

Triada 131/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3674 | S_p=-0.0083 | S_m=-0.0268 | S_family=-0.0176 | gap=0.0185 | alpha_std=0.02555

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3676 | S_p=0.0028 | S_m=-0.0171 | S_family=-0.0071 | gap=0.0199 | alpha_std=0.02556

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3516 | S_p=0.0286 | S_m=0.0480 | S_family=0.0383 | gap=0.0194 | alpha_std=0.02580

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3546 | S_p=0.0421 | S_m=0.0614 | S_family=0.0518 | gap=0.0194 | alpha_std=0.02581

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1536 | S_p=-0.0481 | S_m=-0.0237 | S_family=-0.0359 | gap=0.0245 | alpha_std=0.02473

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1746 | S_p=-0.0279 | S_m=-0.0250 | S_family=-0.0264 | gap=0.0029 | alpha_std=0.02472

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2715 | S_p=0.0756 | S_m=0.0411 | S_family=0.0583 | gap=0.0345 | alpha_std=0.02613

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2679 | S_p=0.0862 | S_m=0.0456 | S_family=0.0659 | gap=0.0406 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2731 | S_p=0.0914 | S_m=0.0100 | S_family=0.0507 | gap=0.0814 | alpha_std=0.02638

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2682 | S_p=0.1031 | S_m=0.0133 | S_family=0.0582 | gap=0.0898 | alpha_std=0.02640

Triada 132/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0874 | S_p=0.0118 | S_m=0.0637 | S_family=0.0377 | gap=0.0519 | alpha_std=0.02633

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1028 | S_p=0.0051 | S_m=0.0431 | S_family=0.0241 | gap=0.0381 | alpha_std=0.02637

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1099 | S_p=-0.0420 | S_m=-0.0240 | S_family=-0.0330 | gap=0.0180 | alpha_std=0.02650

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1081 | S_p=-0.0343 | S_m=-0.0203 | S_family=-0.0273 | gap=0.0140 | alpha_std=0.02649

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1396 | S_p=0.0114 | S_m=0.0893 | S_family=0.0504 | gap=0.0779 | alpha_std=0.02710

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1199 | S_p=0.0103 | S_m=0.1112 | S_family=0.0608 | gap=0.1009 | alpha_std=0.02703

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0390 | S_p=-0.0399 | S_m=0.1139 | S_family=0.0370 | gap=0.1538 | alpha_std=0.02696

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0367 | S_p=-0.0437 | S_m=0.1249 | S_family=0.0406 | gap=0.1686 | alpha_std=0.02697

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1975 | S_p=0.0003 | S_m=0.0548 | S_family=0.0276 | gap=0.0545 | alpha_std=0.02701

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1890 | S_p=0.0109 | S_m=0.0638 | S_family=0.0373 | gap=0.0530 | alpha_std=0.02702

Triada 133/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1192 | S_p=-0.0995 | S_m=0.0309 | S_family=-0.0343 | gap=0.1304 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1394 | S_p=-0.0815 | S_m=0.0213 | S_family=-0.0301 | gap=0.1028 | alpha_std=0.02735

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0870 | S_p=-0.0572 | S_m=0.0144 | S_family=-0.0214 | gap=0.0715 | alpha_std=0.02714

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0963 | S_p=-0.0435 | S_m=0.0120 | S_family=-0.0158 | gap=0.0556 | alpha_std=0.02717

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1880 | S_p=-0.0154 | S_m=-0.0328 | S_family=-0.0241 | gap=0.0174 | alpha_std=0.02668

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1857 | S_p=-0.0063 | S_m=-0.0247 | S_family=-0.0155 | gap=0.0184 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2089 | S_p=-0.0380 | S_m=0.0794 | S_family=0.0207 | gap=0.1174 | alpha_std=0.02811

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2060 | S_p=-0.0342 | S_m=0.0993 | S_family=0.0326 | gap=0.1335 | alpha_std=0.02814

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0392 | S_p=-0.0699 | S_m=0.1006 | S_family=0.0154 | gap=0.1706 | alpha_std=0.02662

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0601 | S_p=-0.0431 | S_m=0.1111 | S_family=0.0340 | gap=0.1542 | alpha_std=0.02662

Triada 134/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2929 | S_p=-0.1143 | S_m=0.0707 | S_family=-0.0218 | gap=0.1850 | alpha_std=0.02729

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2839 | S_p=-0.1019 | S_m=0.0574 | S_family=-0.0223 | gap=0.1593 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2468 | S_p=-0.0547 | S_m=0.1204 | S_family=0.0329 | gap=0.1751 | alpha_std=0.02775

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2446 | S_p=-0.0672 | S_m=0.1178 | S_family=0.0253 | gap=0.1850 | alpha_std=0.02773

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2169 | S_p=-0.0849 | S_m=-0.0059 | S_family=-0.0454 | gap=0.0790 | alpha_std=0.02833

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1709 | S_p=-0.0539 | S_m=0.0055 | S_family=-0.0242 | gap=0.0594 | alpha_std=0.02849

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0724 | S_p=-0.0996 | S_m=0.1143 | S_family=0.0073 | gap=0.2138 | alpha_std=0.02705

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0651 | S_p=-0.0953 | S_m=0.1076 | S_family=0.0062 | gap=0.2029 | alpha_std=0.02706

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2088 | S_p=-0.1214 | S_m=0.1805 | S_family=0.0295 | gap=0.3019 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2310 | S_p=-0.0942 | S_m=0.1931 | S_family=0.0495 | gap=0.2873 | alpha_std=0.02764

Triada 135/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3119 | S_p=-0.0250 | S_m=-0.0558 | S_family=-0.0404 | gap=0.0308 | alpha_std=0.02559

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3293 | S_p=-0.0219 | S_m=-0.0501 | S_family=-0.0360 | gap=0.0282 | alpha_std=0.02567

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3012 | S_p=-0.0101 | S_m=-0.0452 | S_family=-0.0276 | gap=0.0351 | alpha_std=0.02531

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2894 | S_p=-0.0019 | S_m=-0.0431 | S_family=-0.0225 | gap=0.0412 | alpha_std=0.02532

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2526 | S_p=-0.0342 | S_m=-0.0464 | S_family=-0.0403 | gap=0.0122 | alpha_std=0.02518

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2540 | S_p=-0.0245 | S_m=-0.0375 | S_family=-0.0310 | gap=0.0130 | alpha_std=0.02517

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3645 | S_p=-0.0405 | S_m=-0.0934 | S_family=-0.0670 | gap=0.0529 | alpha_std=0.02543

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3622 | S_p=-0.0135 | S_m=-0.0923 | S_family=-0.0529 | gap=0.0788 | alpha_std=0.02543

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2072 | S_p=0.0060 | S_m=0.0120 | S_family=0.0090 | gap=0.0061 | alpha_std=0.02535

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1920 | S_p=0.0120 | S_m=0.0280 | S_family=0.0200 | gap=0.0160 | alpha_std=0.02535

Triada 136/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3455 | S_p=-0.0019 | S_m=0.0971 | S_family=0.0476 | gap=0.0990 | alpha_std=0.02580

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3293 | S_p=0.0158 | S_m=0.0932 | S_family=0.0545 | gap=0.0775 | alpha_std=0.02575

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3705 | S_p=0.0255 | S_m=0.0646 | S_family=0.0451 | gap=0.0391 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3602 | S_p=0.0499 | S_m=0.0625 | S_family=0.0562 | gap=0.0127 | alpha_std=0.02622

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3685 | S_p=0.0179 | S_m=0.0729 | S_family=0.0454 | gap=0.0550 | alpha_std=0.02568

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3959 | S_p=0.0377 | S_m=0.1172 | S_family=0.0774 | gap=0.0795 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1770 | S_p=0.0069 | S_m=0.0032 | S_family=0.0050 | gap=0.0037 | alpha_std=0.02585

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1843 | S_p=0.0034 | S_m=0.0037 | S_family=0.0035 | gap=0.0003 | alpha_std=0.02584

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2127 | S_p=0.0157 | S_m=0.0426 | S_family=0.0291 | gap=0.0268 | alpha_std=0.02584

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2067 | S_p=0.0054 | S_m=0.0608 | S_family=0.0331 | gap=0.0553 | alpha_std=0.02583

Triada 137/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1446 | S_p=-0.0303 | S_m=0.0406 | S_family=0.0052 | gap=0.0709 | alpha_std=0.02600

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0830 | S_p=-0.0299 | S_m=0.0345 | S_family=0.0023 | gap=0.0644 | alpha_std=0.02597

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4629 | S_p=0.0419 | S_m=0.0004 | S_family=0.0212 | gap=0.0414 | alpha_std=0.02773

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4625 | S_p=0.0498 | S_m=0.0133 | S_family=0.0315 | gap=0.0364 | alpha_std=0.02769

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0776 | S_p=0.0357 | S_m=0.0742 | S_family=0.0549 | gap=0.0385 | alpha_std=0.02567

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0818 | S_p=0.0335 | S_m=0.0694 | S_family=0.0514 | gap=0.0359 | alpha_std=0.02569

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0851 | S_p=0.0310 | S_m=0.0249 | S_family=0.0280 | gap=0.0061 | alpha_std=0.02586

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0786 | S_p=0.0365 | S_m=0.0248 | S_family=0.0306 | gap=0.0117 | alpha_std=0.02589

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0293 | S_p=-0.0094 | S_m=0.0068 | S_family=-0.0013 | gap=0.0162 | alpha_std=0.02619

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0354 | S_p=-0.0072 | S_m=0.0078 | S_family=0.0003 | gap=0.0150 | alpha_std=0.02617

Triada 138/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3634 | S_p=0.0164 | S_m=0.0151 | S_family=0.0158 | gap=0.0013 | alpha_std=0.02797

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3673 | S_p=0.0243 | S_m=0.0266 | S_family=0.0254 | gap=0.0024 | alpha_std=0.02799

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2177 | S_p=0.0097 | S_m=0.0386 | S_family=0.0242 | gap=0.0289 | alpha_std=0.02798

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2561 | S_p=0.0039 | S_m=0.0179 | S_family=0.0109 | gap=0.0140 | alpha_std=0.02798

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0085 | S_p=-0.0381 | S_m=0.0148 | S_family=-0.0117 | gap=0.0529 | alpha_std=0.02752

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0005 | S_p=-0.0279 | S_m=0.0091 | S_family=-0.0094 | gap=0.0370 | alpha_std=0.02752

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3244 | S_p=-0.0182 | S_m=0.1485 | S_family=0.0651 | gap=0.1667 | alpha_std=0.02774

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3329 | S_p=-0.0048 | S_m=0.1420 | S_family=0.0686 | gap=0.1468 | alpha_std=0.02770

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3693 | S_p=0.0815 | S_m=0.1592 | S_family=0.1203 | gap=0.0777 | alpha_std=0.02815

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3681 | S_p=0.0900 | S_m=0.1680 | S_family=0.1290 | gap=0.0780 | alpha_std=0.02815

Triada 139/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1845 | S_p=0.0845 | S_m=0.0616 | S_family=0.0730 | gap=0.0229 | alpha_std=0.02747

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1610 | S_p=0.0878 | S_m=0.0305 | S_family=0.0592 | gap=0.0573 | alpha_std=0.02746

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2356 | S_p=-0.0041 | S_m=-0.0109 | S_family=-0.0075 | gap=0.0068 | alpha_std=0.02769

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2551 | S_p=0.0038 | S_m=-0.0182 | S_family=-0.0072 | gap=0.0220 | alpha_std=0.02771

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0266 | S_p=0.0556 | S_m=0.0591 | S_family=0.0573 | gap=0.0035 | alpha_std=0.02684

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0316 | S_p=0.0571 | S_m=0.0685 | S_family=0.0628 | gap=0.0114 | alpha_std=0.02688

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.4934 | S_p=-0.0440 | S_m=-0.0540 | S_family=-0.0490 | gap=0.0100 | alpha_std=0.02870

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.4823 | S_p=-0.0272 | S_m=-0.0444 | S_family=-0.0358 | gap=0.0172 | alpha_std=0.02864

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3538 | S_p=-0.0607 | S_m=-0.0403 | S_family=-0.0505 | gap=0.0204 | alpha_std=0.02924

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3859 | S_p=0.0152 | S_m=-0.0146 | S_family=0.0003 | gap=0.0298 | alpha_std=0.02957

Triada 140/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1791 | S_p=0.0576 | S_m=0.0633 | S_family=0.0604 | gap=0.0057 | alpha_std=0.02773

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1768 | S_p=0.0651 | S_m=0.0653 | S_family=0.0652 | gap=0.0001 | alpha_std=0.02773

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1324 | S_p=-0.0158 | S_m=0.0476 | S_family=0.0159 | gap=0.0635 | alpha_std=0.02739

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1155 | S_p=-0.0107 | S_m=0.0532 | S_family=0.0213 | gap=0.0640 | alpha_std=0.02740

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4673 | S_p=0.0309 | S_m=-0.0432 | S_family=-0.0061 | gap=0.0741 | alpha_std=0.02898

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4500 | S_p=0.0389 | S_m=-0.0335 | S_family=0.0027 | gap=0.0725 | alpha_std=0.02900

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0623 | S_p=0.0223 | S_m=0.0124 | S_family=0.0173 | gap=0.0100 | alpha_std=0.02767

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1387 | S_p=0.0930 | S_m=0.0157 | S_family=0.0543 | gap=0.0773 | alpha_std=0.02783

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1680 | S_p=0.1459 | S_m=0.0251 | S_family=0.0855 | gap=0.1208 | alpha_std=0.02836

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1671 | S_p=0.1480 | S_m=0.0309 | S_family=0.0895 | gap=0.1170 | alpha_std=0.02836

Triada 141/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2206 | S_p=-0.0154 | S_m=-0.0184 | S_family=-0.0169 | gap=0.0029 | alpha_std=0.02789

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2136 | S_p=-0.0089 | S_m=-0.0209 | S_family=-0.0149 | gap=0.0119 | alpha_std=0.02789

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2442 | S_p=0.0088 | S_m=0.0439 | S_family=0.0264 | gap=0.0351 | alpha_std=0.02834

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2524 | S_p=0.0092 | S_m=0.0562 | S_family=0.0327 | gap=0.0470 | alpha_std=0.02828

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1066 | S_p=-0.0340 | S_m=0.0285 | S_family=-0.0027 | gap=0.0625 | alpha_std=0.02816

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0843 | S_p=-0.0391 | S_m=0.0219 | S_family=-0.0086 | gap=0.0610 | alpha_std=0.02812

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2232 | S_p=0.0717 | S_m=0.0519 | S_family=0.0618 | gap=0.0198 | alpha_std=0.02800

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2215 | S_p=0.0756 | S_m=0.0533 | S_family=0.0644 | gap=0.0223 | alpha_std=0.02798

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0851 | S_p=-0.0541 | S_m=0.0224 | S_family=-0.0158 | gap=0.0765 | alpha_std=0.02826

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0634 | S_p=-0.0529 | S_m=0.0353 | S_family=-0.0088 | gap=0.0882 | alpha_std=0.02825

Triada 142/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0817 | S_p=-0.0161 | S_m=-0.0995 | S_family=-0.0578 | gap=0.0834 | alpha_std=0.02821

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0951 | S_p=0.0578 | S_m=-0.0364 | S_family=0.0107 | gap=0.0941 | alpha_std=0.02829

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0804 | S_p=-0.0166 | S_m=0.0277 | S_family=0.0055 | gap=0.0443 | alpha_std=0.02702

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0881 | S_p=-0.0135 | S_m=0.0200 | S_family=0.0033 | gap=0.0336 | alpha_std=0.02698

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2167 | S_p=0.0437 | S_m=0.0248 | S_family=0.0342 | gap=0.0189 | alpha_std=0.02692

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2866 | S_p=0.1135 | S_m=0.0542 | S_family=0.0839 | gap=0.0592 | alpha_std=0.02682

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0780 | S_p=0.0100 | S_m=-0.0591 | S_family=-0.0245 | gap=0.0691 | alpha_std=0.02748

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1447 | S_p=0.0129 | S_m=-0.0034 | S_family=0.0047 | gap=0.0162 | alpha_std=0.02754

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2228 | S_p=-0.0209 | S_m=-0.0071 | S_family=-0.0140 | gap=0.0138 | alpha_std=0.02788

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2258 | S_p=-0.0103 | S_m=0.0180 | S_family=0.0039 | gap=0.0283 | alpha_std=0.02785

Triada 143/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1459 | S_p=0.0148 | S_m=-0.0246 | S_family=-0.0049 | gap=0.0394 | alpha_std=0.02532

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1450 | S_p=0.0033 | S_m=-0.0077 | S_family=-0.0022 | gap=0.0110 | alpha_std=0.02530

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1547 | S_p=-0.0795 | S_m=-0.0309 | S_family=-0.0552 | gap=0.0486 | alpha_std=0.02524

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1454 | S_p=-0.0727 | S_m=-0.0335 | S_family=-0.0531 | gap=0.0393 | alpha_std=0.02520

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1856 | S_p=-0.0316 | S_m=-0.0201 | S_family=-0.0258 | gap=0.0115 | alpha_std=0.02578

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1959 | S_p=-0.0323 | S_m=-0.0207 | S_family=-0.0265 | gap=0.0116 | alpha_std=0.02574

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0616 | S_p=-0.0218 | S_m=0.0745 | S_family=0.0264 | gap=0.0962 | alpha_std=0.02511

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0562 | S_p=0.0041 | S_m=0.0361 | S_family=0.0201 | gap=0.0320 | alpha_std=0.02511

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3548 | S_p=-0.0081 | S_m=-0.0641 | S_family=-0.0361 | gap=0.0560 | alpha_std=0.02584

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3506 | S_p=-0.0051 | S_m=-0.0578 | S_family=-0.0315 | gap=0.0528 | alpha_std=0.02583

Triada 144/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0028 | S_p=0.0224 | S_m=-0.0380 | S_family=-0.0078 | gap=0.0603 | alpha_std=0.02537

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0099 | S_p=0.0108 | S_m=-0.0433 | S_family=-0.0162 | gap=0.0542 | alpha_std=0.02539

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0623 | S_p=-0.0387 | S_m=-0.0166 | S_family=-0.0277 | gap=0.0221 | alpha_std=0.02540

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0625 | S_p=-0.0380 | S_m=-0.0188 | S_family=-0.0284 | gap=0.0192 | alpha_std=0.02538

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0262 | S_p=-0.0509 | S_m=-0.0594 | S_family=-0.0551 | gap=0.0085 | alpha_std=0.02560

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0499 | S_p=-0.0414 | S_m=-0.0530 | S_family=-0.0472 | gap=0.0116 | alpha_std=0.02561

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0124 | S_p=-0.0512 | S_m=-0.0360 | S_family=-0.0436 | gap=0.0152 | alpha_std=0.02550

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0142 | S_p=-0.0496 | S_m=-0.0346 | S_family=-0.0421 | gap=0.0150 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2034 | S_p=-0.0530 | S_m=0.0705 | S_family=0.0087 | gap=0.1235 | alpha_std=0.02648

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1666 | S_p=-0.0174 | S_m=0.0697 | S_family=0.0261 | gap=0.0871 | alpha_std=0.02635

Triada 145/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1623 | S_p=-0.0279 | S_m=-0.0211 | S_family=-0.0245 | gap=0.0068 | alpha_std=0.02588

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1602 | S_p=-0.0360 | S_m=-0.0147 | S_family=-0.0253 | gap=0.0214 | alpha_std=0.02587

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1572 | S_p=-0.0141 | S_m=-0.0358 | S_family=-0.0250 | gap=0.0217 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1582 | S_p=-0.0086 | S_m=-0.0229 | S_family=-0.0157 | gap=0.0143 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4086 | S_p=-0.0187 | S_m=-0.0144 | S_family=-0.0166 | gap=0.0044 | alpha_std=0.02556

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3432 | S_p=-0.0247 | S_m=-0.0497 | S_family=-0.0372 | gap=0.0250 | alpha_std=0.02545

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3722 | S_p=0.0312 | S_m=-0.0815 | S_family=-0.0251 | gap=0.1128 | alpha_std=0.02627

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3568 | S_p=0.0331 | S_m=-0.0900 | S_family=-0.0284 | gap=0.1231 | alpha_std=0.02616

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0073 | S_p=-0.0346 | S_m=-0.0123 | S_family=-0.0234 | gap=0.0224 | alpha_std=0.02516

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0111 | S_p=-0.0324 | S_m=-0.0189 | S_family=-0.0257 | gap=0.0135 | alpha_std=0.02516

Triada 146/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0988 | S_p=0.0404 | S_m=0.0132 | S_family=0.0268 | gap=0.0272 | alpha_std=0.02608

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1273 | S_p=0.0563 | S_m=0.0487 | S_family=0.0525 | gap=0.0076 | alpha_std=0.02610

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1442 | S_p=0.0322 | S_m=0.1103 | S_family=0.0712 | gap=0.0781 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1510 | S_p=0.0041 | S_m=0.1153 | S_family=0.0597 | gap=0.1113 | alpha_std=0.02754

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1765 | S_p=0.0456 | S_m=0.0479 | S_family=0.0468 | gap=0.0023 | alpha_std=0.02730

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1939 | S_p=0.0498 | S_m=0.0606 | S_family=0.0552 | gap=0.0108 | alpha_std=0.02729

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1576 | S_p=0.0025 | S_m=0.1315 | S_family=0.0670 | gap=0.1291 | alpha_std=0.02668

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1410 | S_p=0.0246 | S_m=0.1288 | S_family=0.0767 | gap=0.1042 | alpha_std=0.02663

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3272 | S_p=-0.0209 | S_m=0.1144 | S_family=0.0468 | gap=0.1353 | alpha_std=0.02639

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3462 | S_p=-0.0285 | S_m=0.1265 | S_family=0.0490 | gap=0.1550 | alpha_std=0.02631

Triada 147/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2002 | S_p=0.0966 | S_m=0.0999 | S_family=0.0982 | gap=0.0033 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1934 | S_p=0.0922 | S_m=0.0987 | S_family=0.0955 | gap=0.0064 | alpha_std=0.02606

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1261 | S_p=0.0123 | S_m=0.0329 | S_family=0.0226 | gap=0.0206 | alpha_std=0.02561

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0886 | S_p=0.0191 | S_m=0.0638 | S_family=0.0414 | gap=0.0447 | alpha_std=0.02555

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1820 | S_p=0.0474 | S_m=0.0135 | S_family=0.0305 | gap=0.0340 | alpha_std=0.02608

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1402 | S_p=0.0454 | S_m=-0.0392 | S_family=0.0031 | gap=0.0845 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0287 | S_p=-0.0346 | S_m=0.0140 | S_family=-0.0103 | gap=0.0486 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0310 | S_p=-0.0350 | S_m=0.0276 | S_family=-0.0037 | gap=0.0627 | alpha_std=0.02547

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0966 | S_p=-0.0370 | S_m=-0.0002 | S_family=-0.0186 | gap=0.0368 | alpha_std=0.02587

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1238 | S_p=-0.0505 | S_m=0.0041 | S_family=-0.0232 | gap=0.0546 | alpha_std=0.02586

Triada 148/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3312 | S_p=0.0002 | S_m=0.1040 | S_family=0.0521 | gap=0.1038 | alpha_std=0.02667

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3294 | S_p=0.0032 | S_m=0.0999 | S_family=0.0515 | gap=0.0967 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2262 | S_p=0.0585 | S_m=-0.0186 | S_family=0.0199 | gap=0.0771 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2098 | S_p=0.0529 | S_m=-0.0042 | S_family=0.0243 | gap=0.0571 | alpha_std=0.02565

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3183 | S_p=-0.0331 | S_m=0.0882 | S_family=0.0276 | gap=0.1213 | alpha_std=0.02756

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3210 | S_p=-0.0361 | S_m=0.1018 | S_family=0.0328 | gap=0.1378 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3367 | S_p=-0.0881 | S_m=0.0819 | S_family=-0.0031 | gap=0.1701 | alpha_std=0.02698

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3161 | S_p=-0.0386 | S_m=0.1081 | S_family=0.0347 | gap=0.1468 | alpha_std=0.02694

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2342 | S_p=-0.0833 | S_m=0.0430 | S_family=-0.0202 | gap=0.1263 | alpha_std=0.02691

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2525 | S_p=-0.0712 | S_m=0.0618 | S_family=-0.0047 | gap=0.1331 | alpha_std=0.02693

Triada 149/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0952 | S_p=0.0829 | S_m=0.0211 | S_family=0.0520 | gap=0.0618 | alpha_std=0.02650

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1146 | S_p=0.1316 | S_m=0.0394 | S_family=0.0855 | gap=0.0923 | alpha_std=0.02646

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2200 | S_p=0.1263 | S_m=0.1266 | S_family=0.1265 | gap=0.0004 | alpha_std=0.02685

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2048 | S_p=0.1395 | S_m=0.1200 | S_family=0.1298 | gap=0.0195 | alpha_std=0.02687

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2697 | S_p=0.0961 | S_m=0.0975 | S_family=0.0968 | gap=0.0014 | alpha_std=0.02733

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2727 | S_p=0.1043 | S_m=0.1104 | S_family=0.1074 | gap=0.0060 | alpha_std=0.02732

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0475 | S_p=0.0846 | S_m=-0.0211 | S_family=0.0318 | gap=0.1058 | alpha_std=0.02737

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0525 | S_p=0.0943 | S_m=-0.0168 | S_family=0.0387 | gap=0.1111 | alpha_std=0.02738

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1748 | S_p=-0.0170 | S_m=0.0785 | S_family=0.0308 | gap=0.0955 | alpha_std=0.02744

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1860 | S_p=-0.0054 | S_m=0.0965 | S_family=0.0456 | gap=0.1019 | alpha_std=0.02741

Triada 150/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3230 | S_p=0.0462 | S_m=0.0711 | S_family=0.0586 | gap=0.0249 | alpha_std=0.02629

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3158 | S_p=0.0562 | S_m=0.0772 | S_family=0.0667 | gap=0.0210 | alpha_std=0.02628

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0345 | S_p=-0.0224 | S_m=0.0284 | S_family=0.0030 | gap=0.0508 | alpha_std=0.02543

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0326 | S_p=-0.0287 | S_m=0.0401 | S_family=0.0057 | gap=0.0689 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2693 | S_p=0.0984 | S_m=0.0666 | S_family=0.0825 | gap=0.0318 | alpha_std=0.02634

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2796 | S_p=0.0792 | S_m=0.0565 | S_family=0.0679 | gap=0.0227 | alpha_std=0.02631

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2434 | S_p=0.0031 | S_m=0.0306 | S_family=0.0169 | gap=0.0276 | alpha_std=0.02682

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2549 | S_p=0.0297 | S_m=0.0415 | S_family=0.0356 | gap=0.0118 | alpha_std=0.02677

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3260 | S_p=-0.0164 | S_m=-0.0142 | S_family=-0.0153 | gap=0.0022 | alpha_std=0.02638

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3275 | S_p=-0.0043 | S_m=-0.0051 | S_family=-0.0047 | gap=0.0008 | alpha_std=0.02635

Triada 151/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4579 | S_p=0.0350 | S_m=0.0419 | S_family=0.0385 | gap=0.0068 | alpha_std=0.02580

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4432 | S_p=0.0419 | S_m=0.0331 | S_family=0.0375 | gap=0.0088 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1300 | S_p=0.0461 | S_m=0.0225 | S_family=0.0343 | gap=0.0236 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1026 | S_p=-0.0274 | S_m=-0.0097 | S_family=-0.0185 | gap=0.0176 | alpha_std=0.02526

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2437 | S_p=0.0475 | S_m=0.0482 | S_family=0.0479 | gap=0.0007 | alpha_std=0.02567

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2225 | S_p=0.0491 | S_m=0.0573 | S_family=0.0532 | gap=0.0082 | alpha_std=0.02580

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0517 | S_p=0.0190 | S_m=0.0233 | S_family=0.0212 | gap=0.0042 | alpha_std=0.02549

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0492 | S_p=0.0228 | S_m=0.0264 | S_family=0.0246 | gap=0.0036 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0127 | S_p=0.0840 | S_m=-0.0347 | S_family=0.0246 | gap=0.1187 | alpha_std=0.02538

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0137 | S_p=0.0790 | S_m=-0.0371 | S_family=0.0209 | gap=0.1160 | alpha_std=0.02539

Triada 152/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1527 | S_p=0.0803 | S_m=-0.0091 | S_family=0.0356 | gap=0.0895 | alpha_std=0.02843

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1485 | S_p=0.0788 | S_m=-0.0077 | S_family=0.0356 | gap=0.0865 | alpha_std=0.02845

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0510 | S_p=0.0609 | S_m=0.1419 | S_family=0.1014 | gap=0.0811 | alpha_std=0.02661

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0689 | S_p=0.0521 | S_m=0.1295 | S_family=0.0908 | gap=0.0774 | alpha_std=0.02666

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0595 | S_p=-0.0034 | S_m=0.0874 | S_family=0.0420 | gap=0.0908 | alpha_std=0.02696

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0702 | S_p=0.0170 | S_m=0.0542 | S_family=0.0356 | gap=0.0371 | alpha_std=0.02691

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0793 | S_p=0.0259 | S_m=0.0359 | S_family=0.0309 | gap=0.0100 | alpha_std=0.02721

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0776 | S_p=0.0275 | S_m=0.0661 | S_family=0.0468 | gap=0.0386 | alpha_std=0.02724

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1855 | S_p=-0.0091 | S_m=-0.0220 | S_family=-0.0156 | gap=0.0129 | alpha_std=0.02730

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2178 | S_p=-0.0099 | S_m=0.0458 | S_family=0.0179 | gap=0.0558 | alpha_std=0.02759

Triada 153/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1374 | S_p=0.0029 | S_m=0.0483 | S_family=0.0256 | gap=0.0454 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1920 | S_p=0.0372 | S_m=0.0424 | S_family=0.0398 | gap=0.0052 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0497 | S_p=0.0242 | S_m=-0.0183 | S_family=0.0029 | gap=0.0426 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0502 | S_p=0.0256 | S_m=-0.0145 | S_family=0.0055 | gap=0.0401 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1776 | S_p=0.0210 | S_m=0.1150 | S_family=0.0680 | gap=0.0939 | alpha_std=0.02719

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3816 | S_p=0.0882 | S_m=0.0484 | S_family=0.0683 | gap=0.0398 | alpha_std=0.02719

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0530 | S_p=0.0230 | S_m=-0.0062 | S_family=0.0084 | gap=0.0292 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0529 | S_p=0.0178 | S_m=-0.0020 | S_family=0.0079 | gap=0.0198 | alpha_std=0.02674

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0685 | S_p=0.0127 | S_m=0.0209 | S_family=0.0168 | gap=0.0082 | alpha_std=0.02761

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0437 | S_p=0.0155 | S_m=0.0418 | S_family=0.0286 | gap=0.0264 | alpha_std=0.02755

Triada 154/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1539 | S_p=0.0258 | S_m=0.0893 | S_family=0.0576 | gap=0.0635 | alpha_std=0.02707

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1399 | S_p=0.0400 | S_m=0.1135 | S_family=0.0767 | gap=0.0735 | alpha_std=0.02708

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0289 | S_p=0.0600 | S_m=0.0635 | S_family=0.0617 | gap=0.0035 | alpha_std=0.02696

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0163 | S_p=0.0590 | S_m=0.0695 | S_family=0.0642 | gap=0.0106 | alpha_std=0.02695

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1094 | S_p=0.0846 | S_m=0.0366 | S_family=0.0606 | gap=0.0481 | alpha_std=0.02734

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1062 | S_p=0.0895 | S_m=0.0517 | S_family=0.0706 | gap=0.0379 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0868 | S_p=0.0226 | S_m=0.0621 | S_family=0.0424 | gap=0.0395 | alpha_std=0.02687

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1000 | S_p=0.0400 | S_m=0.0773 | S_family=0.0587 | gap=0.0373 | alpha_std=0.02699

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0512 | S_p=0.0555 | S_m=0.0085 | S_family=0.0320 | gap=0.0470 | alpha_std=0.02754

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0613 | S_p=0.0453 | S_m=0.0046 | S_family=0.0250 | gap=0.0407 | alpha_std=0.02755

Triada 155/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1516 | S_p=-0.0760 | S_m=-0.0594 | S_family=-0.0677 | gap=0.0166 | alpha_std=0.02478

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1410 | S_p=-0.0229 | S_m=0.0264 | S_family=0.0017 | gap=0.0493 | alpha_std=0.02480

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4599 | S_p=0.0010 | S_m=-0.0404 | S_family=-0.0197 | gap=0.0414 | alpha_std=0.02500

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.4360 | S_p=0.0024 | S_m=-0.0110 | S_family=-0.0043 | gap=0.0134 | alpha_std=0.02504

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3571 | S_p=-0.1029 | S_m=-0.1673 | S_family=-0.1351 | gap=0.0644 | alpha_std=0.02457

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3561 | S_p=-0.0840 | S_m=-0.1195 | S_family=-0.1018 | gap=0.0355 | alpha_std=0.02458

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2359 | S_p=-0.0521 | S_m=-0.0603 | S_family=-0.0562 | gap=0.0082 | alpha_std=0.02488

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2387 | S_p=-0.0535 | S_m=-0.0382 | S_family=-0.0459 | gap=0.0153 | alpha_std=0.02485

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2731 | S_p=0.0875 | S_m=-0.0375 | S_family=0.0250 | gap=0.1249 | alpha_std=0.02591

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2724 | S_p=0.0769 | S_m=-0.0242 | S_family=0.0264 | gap=0.1011 | alpha_std=0.02595

Triada 156/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0502 | S_p=0.0081 | S_m=-0.0466 | S_family=-0.0193 | gap=0.0547 | alpha_std=0.02666

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0629 | S_p=-0.0028 | S_m=-0.0287 | S_family=-0.0157 | gap=0.0260 | alpha_std=0.02664

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3714 | S_p=-0.0158 | S_m=-0.0317 | S_family=-0.0237 | gap=0.0158 | alpha_std=0.02735

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3776 | S_p=-0.0284 | S_m=-0.0130 | S_family=-0.0207 | gap=0.0154 | alpha_std=0.02734

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0022 | S_p=0.0217 | S_m=-0.0302 | S_family=-0.0042 | gap=0.0519 | alpha_std=0.02634

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0047 | S_p=0.0032 | S_m=-0.0253 | S_family=-0.0110 | gap=0.0285 | alpha_std=0.02637

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1655 | S_p=-0.0025 | S_m=0.1224 | S_family=0.0600 | gap=0.1249 | alpha_std=0.02780

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1564 | S_p=0.0039 | S_m=0.1032 | S_family=0.0535 | gap=0.0993 | alpha_std=0.02778

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1852 | S_p=0.0247 | S_m=0.1123 | S_family=0.0685 | gap=0.0876 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1891 | S_p=0.0375 | S_m=0.1081 | S_family=0.0728 | gap=0.0706 | alpha_std=0.02758

Triada 157/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1765 | S_p=-0.0283 | S_m=-0.0813 | S_family=-0.0548 | gap=0.0530 | alpha_std=0.02878

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1640 | S_p=-0.0087 | S_m=-0.0543 | S_family=-0.0315 | gap=0.0456 | alpha_std=0.02885

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0833 | S_p=-0.0125 | S_m=0.0212 | S_family=0.0044 | gap=0.0337 | alpha_std=0.02687

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0804 | S_p=0.0195 | S_m=0.0303 | S_family=0.0249 | gap=0.0109 | alpha_std=0.02691

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0902 | S_p=-0.0015 | S_m=-0.0162 | S_family=-0.0089 | gap=0.0148 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0301 | S_p=0.0267 | S_m=-0.0304 | S_family=-0.0018 | gap=0.0571 | alpha_std=0.02706

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2377 | S_p=-0.0772 | S_m=-0.0300 | S_family=-0.0536 | gap=0.0471 | alpha_std=0.02803

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2146 | S_p=-0.0693 | S_m=-0.0348 | S_family=-0.0521 | gap=0.0345 | alpha_std=0.02793

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=-0.0019 | S_p=0.1093 | S_m=-0.0141 | S_family=0.0476 | gap=0.1234 | alpha_std=0.02697

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=-0.0158 | S_p=0.0857 | S_m=-0.0183 | S_family=0.0337 | gap=0.1040 | alpha_std=0.02702

Triada 158/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3872 | S_p=-0.0591 | S_m=-0.0589 | S_family=-0.0590 | gap=0.0002 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3884 | S_p=-0.0619 | S_m=-0.0512 | S_family=-0.0566 | gap=0.0107 | alpha_std=0.02746

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2371 | S_p=0.0205 | S_m=-0.0279 | S_family=-0.0037 | gap=0.0485 | alpha_std=0.02725

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2459 | S_p=0.0342 | S_m=-0.0183 | S_family=0.0079 | gap=0.0525 | alpha_std=0.02724

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1040 | S_p=-0.0232 | S_m=-0.1025 | S_family=-0.0629 | gap=0.0793 | alpha_std=0.02644

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0846 | S_p=0.0266 | S_m=-0.0640 | S_family=-0.0187 | gap=0.0906 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1818 | S_p=-0.0085 | S_m=-0.0405 | S_family=-0.0245 | gap=0.0320 | alpha_std=0.02802

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1833 | S_p=0.0118 | S_m=-0.0255 | S_family=-0.0069 | gap=0.0373 | alpha_std=0.02803

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1715 | S_p=0.0167 | S_m=0.0595 | S_family=0.0381 | gap=0.0428 | alpha_std=0.02787

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1643 | S_p=0.0167 | S_m=0.0777 | S_family=0.0472 | gap=0.0611 | alpha_std=0.02791

Triada 159/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1115 | S_p=0.0333 | S_m=0.0094 | S_family=0.0214 | gap=0.0239 | alpha_std=0.02607

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0893 | S_p=0.0375 | S_m=0.0331 | S_family=0.0353 | gap=0.0044 | alpha_std=0.02611

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0502 | S_p=-0.0815 | S_m=-0.0410 | S_family=-0.0613 | gap=0.0405 | alpha_std=0.02520

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0373 | S_p=-0.0747 | S_m=-0.0638 | S_family=-0.0692 | gap=0.0109 | alpha_std=0.02514

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2338 | S_p=-0.0370 | S_m=-0.0186 | S_family=-0.0278 | gap=0.0184 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2188 | S_p=0.0073 | S_m=0.0024 | S_family=0.0048 | gap=0.0049 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1757 | S_p=-0.0508 | S_m=0.0767 | S_family=0.0130 | gap=0.1275 | alpha_std=0.02577

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1771 | S_p=-0.0331 | S_m=0.0665 | S_family=0.0167 | gap=0.0996 | alpha_std=0.02581

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0507 | S_p=0.0080 | S_m=-0.0582 | S_family=-0.0251 | gap=0.0662 | alpha_std=0.02498

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0347 | S_p=0.0270 | S_m=-0.0498 | S_family=-0.0114 | gap=0.0768 | alpha_std=0.02491

Triada 160/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0159 | S_p=0.0193 | S_m=-0.0711 | S_family=-0.0259 | gap=0.0905 | alpha_std=0.02525

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0144 | S_p=0.0517 | S_m=-0.0713 | S_family=-0.0098 | gap=0.1230 | alpha_std=0.02521

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0770 | S_p=-0.0399 | S_m=-0.0182 | S_family=-0.0290 | gap=0.0217 | alpha_std=0.02511

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0196 | S_p=-0.0030 | S_m=-0.0207 | S_family=-0.0119 | gap=0.0177 | alpha_std=0.02515

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0464 | S_p=-0.0699 | S_m=-0.0515 | S_family=-0.0607 | gap=0.0184 | alpha_std=0.02527

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0529 | S_p=-0.0644 | S_m=-0.0412 | S_family=-0.0528 | gap=0.0232 | alpha_std=0.02516

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1284 | S_p=-0.0054 | S_m=-0.0403 | S_family=-0.0228 | gap=0.0348 | alpha_std=0.02512

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1594 | S_p=0.0027 | S_m=0.0044 | S_family=0.0035 | gap=0.0016 | alpha_std=0.02513

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3280 | S_p=0.0267 | S_m=-0.0211 | S_family=0.0028 | gap=0.0478 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3181 | S_p=0.0305 | S_m=-0.0064 | S_family=0.0120 | gap=0.0369 | alpha_std=0.02605

Triada 161/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2872 | S_p=0.0853 | S_m=0.0140 | S_family=0.0497 | gap=0.0713 | alpha_std=0.02675

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2926 | S_p=0.0944 | S_m=0.0170 | S_family=0.0557 | gap=0.0774 | alpha_std=0.02678

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1156 | S_p=-0.0406 | S_m=0.1335 | S_family=0.0464 | gap=0.1740 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1123 | S_p=-0.0341 | S_m=0.1475 | S_family=0.0567 | gap=0.1816 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0123 | S_p=-0.0560 | S_m=0.0084 | S_family=-0.0238 | gap=0.0644 | alpha_std=0.02573

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0558 | S_p=-0.0145 | S_m=0.0395 | S_family=0.0125 | gap=0.0540 | alpha_std=0.02559

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0234 | S_p=-0.0624 | S_m=0.1009 | S_family=0.0193 | gap=0.1632 | alpha_std=0.02654

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0434 | S_p=-0.0056 | S_m=0.1192 | S_family=0.0568 | gap=0.1247 | alpha_std=0.02637

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1805 | S_p=-0.1058 | S_m=0.1079 | S_family=0.0011 | gap=0.2137 | alpha_std=0.02666

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1629 | S_p=-0.0911 | S_m=0.1127 | S_family=0.0108 | gap=0.2038 | alpha_std=0.02664

Triada 162/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3606 | S_p=-0.0200 | S_m=0.0458 | S_family=0.0129 | gap=0.0658 | alpha_std=0.02701

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3629 | S_p=-0.0182 | S_m=0.0523 | S_family=0.0170 | gap=0.0705 | alpha_std=0.02702

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4301 | S_p=0.0180 | S_m=0.0250 | S_family=0.0215 | gap=0.0070 | alpha_std=0.02661

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3205 | S_p=-0.0324 | S_m=-0.0272 | S_family=-0.0298 | gap=0.0052 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4697 | S_p=-0.0145 | S_m=0.0611 | S_family=0.0233 | gap=0.0756 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.5021 | S_p=-0.0123 | S_m=0.0751 | S_family=0.0314 | gap=0.0875 | alpha_std=0.02678

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=-0.0325 | S_p=0.0453 | S_m=-0.0431 | S_family=0.0011 | gap=0.0884 | alpha_std=0.02617

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0301 | S_p=0.0320 | S_m=-0.0166 | S_family=0.0077 | gap=0.0485 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1739 | S_p=0.0305 | S_m=-0.0507 | S_family=-0.0101 | gap=0.0811 | alpha_std=0.02657

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1759 | S_p=0.0467 | S_m=-0.0270 | S_family=0.0099 | gap=0.0737 | alpha_std=0.02661

Triada 163/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1143 | S_p=-0.0400 | S_m=0.0618 | S_family=0.0109 | gap=0.1019 | alpha_std=0.02463

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0187 | S_p=0.0768 | S_m=-0.0249 | S_family=0.0260 | gap=0.1017 | alpha_std=0.02424

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2914 | S_p=0.0325 | S_m=0.1498 | S_family=0.0911 | gap=0.1173 | alpha_std=0.02444

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2625 | S_p=0.0040 | S_m=0.1541 | S_family=0.0791 | gap=0.1501 | alpha_std=0.02441

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0196 | S_p=-0.0097 | S_m=-0.0280 | S_family=-0.0188 | gap=0.0183 | alpha_std=0.02438

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0160 | S_p=0.0001 | S_m=-0.0299 | S_family=-0.0149 | gap=0.0300 | alpha_std=0.02440

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0105 | S_p=-0.0281 | S_m=-0.1197 | S_family=-0.0739 | gap=0.0916 | alpha_std=0.02414

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0040 | S_p=0.0161 | S_m=-0.1157 | S_family=-0.0498 | gap=0.1318 | alpha_std=0.02408

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0631 | S_p=0.0331 | S_m=-0.0484 | S_family=-0.0077 | gap=0.0815 | alpha_std=0.02519

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0535 | S_p=0.0300 | S_m=-0.0387 | S_family=-0.0043 | gap=0.0688 | alpha_std=0.02519

Triada 164/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2064 | S_p=0.0373 | S_m=0.0387 | S_family=0.0380 | gap=0.0015 | alpha_std=0.02528

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2326 | S_p=0.0498 | S_m=0.0716 | S_family=0.0607 | gap=0.0218 | alpha_std=0.02531

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0869 | S_p=-0.0206 | S_m=-0.0749 | S_family=-0.0478 | gap=0.0543 | alpha_std=0.02434

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0575 | S_p=0.0047 | S_m=-0.0407 | S_family=-0.0180 | gap=0.0455 | alpha_std=0.02426

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0967 | S_p=-0.0155 | S_m=-0.0859 | S_family=-0.0507 | gap=0.0704 | alpha_std=0.02434

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0976 | S_p=-0.0146 | S_m=-0.0747 | S_family=-0.0446 | gap=0.0601 | alpha_std=0.02438

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1536 | S_p=0.0668 | S_m=0.0444 | S_family=0.0556 | gap=0.0224 | alpha_std=0.02501

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1702 | S_p=0.0595 | S_m=0.0368 | S_family=0.0481 | gap=0.0227 | alpha_std=0.02493

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1154 | S_p=0.0167 | S_m=0.0273 | S_family=0.0220 | gap=0.0106 | alpha_std=0.02483

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0598 | S_p=0.0106 | S_m=0.0158 | S_family=0.0132 | gap=0.0052 | alpha_std=0.02470

Triada 165/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4692 | S_p=-0.0218 | S_m=0.0015 | S_family=-0.0102 | gap=0.0233 | alpha_std=0.02632

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4842 | S_p=-0.0109 | S_m=0.0118 | S_family=0.0005 | gap=0.0227 | alpha_std=0.02631

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0648 | S_p=-0.0051 | S_m=0.0001 | S_family=-0.0025 | gap=0.0052 | alpha_std=0.02661

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0605 | S_p=0.0048 | S_m=0.0136 | S_family=0.0092 | gap=0.0088 | alpha_std=0.02657

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2538 | S_p=0.0134 | S_m=-0.0078 | S_family=0.0028 | gap=0.0212 | alpha_std=0.02743

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2575 | S_p=0.0157 | S_m=-0.0060 | S_family=0.0048 | gap=0.0217 | alpha_std=0.02741

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2363 | S_p=0.0250 | S_m=0.0117 | S_family=0.0184 | gap=0.0133 | alpha_std=0.02695

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2248 | S_p=0.0629 | S_m=0.0517 | S_family=0.0573 | gap=0.0112 | alpha_std=0.02695

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2855 | S_p=0.0542 | S_m=0.0521 | S_family=0.0531 | gap=0.0021 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2395 | S_p=0.0810 | S_m=0.0058 | S_family=0.0434 | gap=0.0753 | alpha_std=0.02674

Triada 166/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2540 | S_p=0.1170 | S_m=0.1339 | S_family=0.1254 | gap=0.0169 | alpha_std=0.02744

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2738 | S_p=0.1234 | S_m=0.1299 | S_family=0.1267 | gap=0.0065 | alpha_std=0.02749

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1258 | S_p=-0.0023 | S_m=0.0102 | S_family=0.0040 | gap=0.0125 | alpha_std=0.02752

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0998 | S_p=0.0226 | S_m=-0.0264 | S_family=-0.0019 | gap=0.0490 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1238 | S_p=0.0023 | S_m=-0.0126 | S_family=-0.0052 | gap=0.0149 | alpha_std=0.02652

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0528 | S_p=0.0216 | S_m=0.0048 | S_family=0.0132 | gap=0.0168 | alpha_std=0.02645

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1391 | S_p=-0.0291 | S_m=0.0385 | S_family=0.0047 | gap=0.0676 | alpha_std=0.02772

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1447 | S_p=-0.0226 | S_m=0.0502 | S_family=0.0138 | gap=0.0728 | alpha_std=0.02770

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0872 | S_p=0.0166 | S_m=0.0278 | S_family=0.0222 | gap=0.0112 | alpha_std=0.02737

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0918 | S_p=0.0383 | S_m=0.0354 | S_family=0.0369 | gap=0.0029 | alpha_std=0.02740

Triada 167/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4439 | S_p=0.0201 | S_m=0.0559 | S_family=0.0380 | gap=0.0358 | alpha_std=0.02734

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4431 | S_p=0.0286 | S_m=0.0561 | S_family=0.0424 | gap=0.0275 | alpha_std=0.02733

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1176 | S_p=0.0183 | S_m=0.0239 | S_family=0.0211 | gap=0.0056 | alpha_std=0.02627

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1253 | S_p=0.0125 | S_m=0.0226 | S_family=0.0175 | gap=0.0101 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1344 | S_p=0.0221 | S_m=0.0002 | S_family=0.0111 | gap=0.0219 | alpha_std=0.02675

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1304 | S_p=0.0256 | S_m=0.0029 | S_family=0.0142 | gap=0.0227 | alpha_std=0.02671

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0921 | S_p=-0.0320 | S_m=-0.0063 | S_family=-0.0192 | gap=0.0257 | alpha_std=0.02720

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0909 | S_p=-0.0323 | S_m=-0.0025 | S_family=-0.0174 | gap=0.0298 | alpha_std=0.02720

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0801 | S_p=0.0151 | S_m=-0.0763 | S_family=-0.0306 | gap=0.0914 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0887 | S_p=0.0023 | S_m=-0.0545 | S_family=-0.0261 | gap=0.0569 | alpha_std=0.02620

Triada 168/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4452 | S_p=0.0923 | S_m=-0.0219 | S_family=0.0352 | gap=0.1142 | alpha_std=0.02769

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4520 | S_p=0.1072 | S_m=-0.0239 | S_family=0.0416 | gap=0.1311 | alpha_std=0.02770

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0430 | S_p=-0.0063 | S_m=0.0016 | S_family=-0.0024 | gap=0.0079 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0420 | S_p=-0.0042 | S_m=0.0002 | S_family=-0.0020 | gap=0.0045 | alpha_std=0.02636

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0934 | S_p=0.0129 | S_m=-0.0352 | S_family=-0.0111 | gap=0.0481 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0930 | S_p=0.0060 | S_m=-0.0415 | S_family=-0.0177 | gap=0.0475 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0462 | S_p=-0.0130 | S_m=-0.0055 | S_family=-0.0092 | gap=0.0075 | alpha_std=0.02716

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0518 | S_p=-0.0161 | S_m=-0.0036 | S_family=-0.0099 | gap=0.0124 | alpha_std=0.02713

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=-0.0133 | S_p=-0.1128 | S_m=-0.0261 | S_family=-0.0694 | gap=0.0868 | alpha_std=0.02735

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=-0.0341 | S_p=-0.1141 | S_m=-0.0344 | S_family=-0.0742 | gap=0.0796 | alpha_std=0.02734

Triada 169/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2362 | S_p=0.0928 | S_m=0.0103 | S_family=0.0515 | gap=0.0826 | alpha_std=0.02563

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2341 | S_p=0.1073 | S_m=0.0253 | S_family=0.0663 | gap=0.0820 | alpha_std=0.02562

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2839 | S_p=0.0852 | S_m=-0.0025 | S_family=0.0414 | gap=0.0876 | alpha_std=0.02632

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2924 | S_p=0.1072 | S_m=0.0091 | S_family=0.0581 | gap=0.0981 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3646 | S_p=0.1496 | S_m=0.0532 | S_family=0.1014 | gap=0.0964 | alpha_std=0.02641

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3580 | S_p=0.1687 | S_m=0.0715 | S_family=0.1201 | gap=0.0972 | alpha_std=0.02641

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2376 | S_p=0.1069 | S_m=-0.0040 | S_family=0.0514 | gap=0.1109 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1928 | S_p=0.0894 | S_m=0.0021 | S_family=0.0457 | gap=0.0873 | alpha_std=0.02585

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2054 | S_p=0.1637 | S_m=0.1308 | S_family=0.1473 | gap=0.0329 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2082 | S_p=0.1790 | S_m=0.1349 | S_family=0.1569 | gap=0.0441 | alpha_std=0.02603

Triada 170/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1651 | S_p=0.0089 | S_m=0.0352 | S_family=0.0221 | gap=0.0263 | alpha_std=0.02634

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1482 | S_p=0.0002 | S_m=0.0392 | S_family=0.0197 | gap=0.0390 | alpha_std=0.02633

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1743 | S_p=-0.1224 | S_m=0.0358 | S_family=-0.0433 | gap=0.1583 | alpha_std=0.02677

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1993 | S_p=-0.1130 | S_m=0.0329 | S_family=-0.0401 | gap=0.1459 | alpha_std=0.02675

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2220 | S_p=-0.0392 | S_m=-0.0279 | S_family=-0.0335 | gap=0.0113 | alpha_std=0.02613

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2098 | S_p=-0.0246 | S_m=-0.0098 | S_family=-0.0172 | gap=0.0148 | alpha_std=0.02611

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2089 | S_p=-0.1310 | S_m=0.0366 | S_family=-0.0472 | gap=0.1675 | alpha_std=0.02594

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2106 | S_p=-0.1240 | S_m=0.0627 | S_family=-0.0307 | gap=0.1867 | alpha_std=0.02592

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2418 | S_p=-0.0229 | S_m=0.0821 | S_family=0.0296 | gap=0.1050 | alpha_std=0.02601

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2253 | S_p=-0.0076 | S_m=0.0957 | S_family=0.0440 | gap=0.1032 | alpha_std=0.02600

Triada 171/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2419 | S_p=0.0260 | S_m=0.0626 | S_family=0.0443 | gap=0.0366 | alpha_std=0.02647

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2217 | S_p=0.0371 | S_m=0.1027 | S_family=0.0699 | gap=0.0656 | alpha_std=0.02630

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0717 | S_p=0.1023 | S_m=0.1022 | S_family=0.1023 | gap=0.0002 | alpha_std=0.02553

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0824 | S_p=0.1273 | S_m=0.1187 | S_family=0.1230 | gap=0.0086 | alpha_std=0.02554

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1334 | S_p=0.1030 | S_m=0.0842 | S_family=0.0936 | gap=0.0188 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1246 | S_p=0.0948 | S_m=0.0845 | S_family=0.0897 | gap=0.0103 | alpha_std=0.02589

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3513 | S_p=0.1165 | S_m=0.1188 | S_family=0.1177 | gap=0.0023 | alpha_std=0.02667

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3518 | S_p=0.1174 | S_m=0.1192 | S_family=0.1183 | gap=0.0018 | alpha_std=0.02668

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1941 | S_p=0.0941 | S_m=0.0582 | S_family=0.0761 | gap=0.0360 | alpha_std=0.02571

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1865 | S_p=0.1011 | S_m=0.0675 | S_family=0.0843 | gap=0.0336 | alpha_std=0.02574

Triada 172/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0295 | S_p=-0.0062 | S_m=0.0400 | S_family=0.0169 | gap=0.0462 | alpha_std=0.02628

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0450 | S_p=0.0030 | S_m=0.0184 | S_family=0.0107 | gap=0.0153 | alpha_std=0.02629

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0126 | S_p=-0.0014 | S_m=0.0410 | S_family=0.0198 | gap=0.0424 | alpha_std=0.02663

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0132 | S_p=-0.0119 | S_m=0.0378 | S_family=0.0130 | gap=0.0497 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0331 | S_p=-0.0295 | S_m=-0.0020 | S_family=-0.0157 | gap=0.0275 | alpha_std=0.02664

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0514 | S_p=-0.0391 | S_m=0.0197 | S_family=-0.0097 | gap=0.0588 | alpha_std=0.02671

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0538 | S_p=-0.0121 | S_m=-0.0721 | S_family=-0.0421 | gap=0.0599 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0540 | S_p=-0.0147 | S_m=-0.0651 | S_family=-0.0399 | gap=0.0504 | alpha_std=0.02724

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2643 | S_p=0.0197 | S_m=0.0194 | S_family=0.0195 | gap=0.0003 | alpha_std=0.02761

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2662 | S_p=0.0241 | S_m=0.0201 | S_family=0.0221 | gap=0.0040 | alpha_std=0.02761

Triada 173/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3067 | S_p=0.0577 | S_m=0.0991 | S_family=0.0784 | gap=0.0414 | alpha_std=0.02682

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3037 | S_p=0.0586 | S_m=0.0952 | S_family=0.0769 | gap=0.0365 | alpha_std=0.02683

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0461 | S_p=-0.0269 | S_m=0.0434 | S_family=0.0083 | gap=0.0702 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0403 | S_p=-0.0243 | S_m=0.0565 | S_family=0.0161 | gap=0.0809 | alpha_std=0.02629

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0189 | S_p=-0.0426 | S_m=-0.0074 | S_family=-0.0250 | gap=0.0352 | alpha_std=0.02610

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0146 | S_p=-0.0323 | S_m=-0.0097 | S_family=-0.0210 | gap=0.0226 | alpha_std=0.02615

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3859 | S_p=0.0699 | S_m=-0.0225 | S_family=0.0237 | gap=0.0923 | alpha_std=0.02734

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3437 | S_p=0.0712 | S_m=-0.0290 | S_family=0.0211 | gap=0.1002 | alpha_std=0.02727

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.4215 | S_p=0.1187 | S_m=0.0931 | S_family=0.1059 | gap=0.0256 | alpha_std=0.02787

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.4259 | S_p=0.1351 | S_m=0.1004 | S_family=0.1178 | gap=0.0347 | alpha_std=0.02786

Triada 174/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3370 | S_p=-0.1113 | S_m=0.0456 | S_family=-0.0328 | gap=0.1569 | alpha_std=0.02631

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3072 | S_p=-0.1100 | S_m=0.0667 | S_family=-0.0217 | gap=0.1767 | alpha_std=0.02628

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0271 | S_p=-0.0500 | S_m=-0.0107 | S_family=-0.0303 | gap=0.0393 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0241 | S_p=-0.0521 | S_m=-0.0308 | S_family=-0.0415 | gap=0.0213 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0234 | S_p=-0.0465 | S_m=0.0094 | S_family=-0.0185 | gap=0.0558 | alpha_std=0.02626

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0339 | S_p=-0.0559 | S_m=0.0060 | S_family=-0.0249 | gap=0.0619 | alpha_std=0.02631

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=-0.0401 | S_p=-0.0275 | S_m=-0.0299 | S_family=-0.0287 | gap=0.0024 | alpha_std=0.02648

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0310 | S_p=-0.0093 | S_m=-0.0375 | S_family=-0.0234 | gap=0.0282 | alpha_std=0.02648

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=-0.0047 | S_p=-0.0104 | S_m=-0.0283 | S_family=-0.0193 | gap=0.0179 | alpha_std=0.02670

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0218 | S_p=-0.0486 | S_m=-0.0072 | S_family=-0.0279 | gap=0.0413 | alpha_std=0.02628

Triada 175/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2340 | S_p=0.0246 | S_m=0.0613 | S_family=0.0429 | gap=0.0368 | alpha_std=0.02681

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2100 | S_p=0.0335 | S_m=0.0531 | S_family=0.0433 | gap=0.0196 | alpha_std=0.02681

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2306 | S_p=-0.0380 | S_m=0.0423 | S_family=0.0021 | gap=0.0803 | alpha_std=0.02693

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2323 | S_p=-0.0238 | S_m=0.0602 | S_family=0.0182 | gap=0.0840 | alpha_std=0.02694

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1123 | S_p=0.0633 | S_m=0.0153 | S_family=0.0393 | gap=0.0480 | alpha_std=0.02666

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1111 | S_p=0.0955 | S_m=0.0261 | S_family=0.0608 | gap=0.0694 | alpha_std=0.02646

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1731 | S_p=-0.0171 | S_m=-0.0092 | S_family=-0.0131 | gap=0.0079 | alpha_std=0.02709

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1720 | S_p=0.0016 | S_m=0.0039 | S_family=0.0027 | gap=0.0023 | alpha_std=0.02705

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1427 | S_p=0.0190 | S_m=0.0160 | S_family=0.0175 | gap=0.0030 | alpha_std=0.02690

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1399 | S_p=0.0233 | S_m=0.0424 | S_family=0.0329 | gap=0.0191 | alpha_std=0.02690

Triada 176/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0333 | S_p=-0.0036 | S_m=-0.0153 | S_family=-0.0095 | gap=0.0117 | alpha_std=0.02733

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0260 | S_p=-0.0089 | S_m=-0.0029 | S_family=-0.0059 | gap=0.0060 | alpha_std=0.02731

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0110 | S_p=0.0198 | S_m=-0.0057 | S_family=0.0070 | gap=0.0255 | alpha_std=0.02699

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0074 | S_p=0.0214 | S_m=0.0055 | S_family=0.0135 | gap=0.0160 | alpha_std=0.02699

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0860 | S_p=-0.0462 | S_m=-0.0381 | S_family=-0.0421 | gap=0.0081 | alpha_std=0.02766

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0859 | S_p=-0.0129 | S_m=-0.0024 | S_family=-0.0076 | gap=0.0105 | alpha_std=0.02760

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3430 | S_p=-0.0567 | S_m=0.0060 | S_family=-0.0254 | gap=0.0627 | alpha_std=0.02795

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3395 | S_p=-0.0432 | S_m=-0.0162 | S_family=-0.0297 | gap=0.0270 | alpha_std=0.02799

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2894 | S_p=0.0748 | S_m=-0.0046 | S_family=0.0351 | gap=0.0793 | alpha_std=0.02883

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2964 | S_p=0.1022 | S_m=0.0153 | S_family=0.0587 | gap=0.0869 | alpha_std=0.02886

Triada 177/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2257 | S_p=-0.0654 | S_m=-0.0547 | S_family=-0.0601 | gap=0.0107 | alpha_std=0.02667

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2070 | S_p=-0.0554 | S_m=-0.0603 | S_family=-0.0578 | gap=0.0049 | alpha_std=0.02668

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1901 | S_p=-0.0160 | S_m=0.0240 | S_family=0.0040 | gap=0.0400 | alpha_std=0.02623

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2015 | S_p=-0.0117 | S_m=0.0310 | S_family=0.0096 | gap=0.0427 | alpha_std=0.02622

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1933 | S_p=-0.0527 | S_m=-0.0209 | S_family=-0.0368 | gap=0.0318 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2573 | S_p=-0.0434 | S_m=-0.0118 | S_family=-0.0276 | gap=0.0317 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3848 | S_p=-0.0035 | S_m=-0.0444 | S_family=-0.0239 | gap=0.0409 | alpha_std=0.02759

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3883 | S_p=0.0148 | S_m=-0.0232 | S_family=-0.0042 | gap=0.0380 | alpha_std=0.02769

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.4214 | S_p=-0.0465 | S_m=-0.0260 | S_family=-0.0362 | gap=0.0205 | alpha_std=0.02704

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.4385 | S_p=-0.0397 | S_m=-0.0150 | S_family=-0.0274 | gap=0.0247 | alpha_std=0.02705

Triada 178/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3884 | S_p=0.0066 | S_m=0.0206 | S_family=0.0136 | gap=0.0140 | alpha_std=0.02785

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4039 | S_p=0.0249 | S_m=0.0403 | S_family=0.0326 | gap=0.0154 | alpha_std=0.02785

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0776 | S_p=0.0116 | S_m=-0.0283 | S_family=-0.0084 | gap=0.0399 | alpha_std=0.02672

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0725 | S_p=-0.0055 | S_m=-0.0532 | S_family=-0.0293 | gap=0.0477 | alpha_std=0.02679

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0201 | S_p=0.0474 | S_m=0.0145 | S_family=0.0309 | gap=0.0329 | alpha_std=0.02688

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0071 | S_p=0.0580 | S_m=0.0252 | S_family=0.0416 | gap=0.0328 | alpha_std=0.02686

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2829 | S_p=-0.0146 | S_m=0.0676 | S_family=0.0265 | gap=0.0822 | alpha_std=0.02823

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2924 | S_p=0.0025 | S_m=0.0723 | S_family=0.0374 | gap=0.0698 | alpha_std=0.02822

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3006 | S_p=-0.0039 | S_m=0.0018 | S_family=-0.0011 | gap=0.0057 | alpha_std=0.02748

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2829 | S_p=-0.0297 | S_m=0.0215 | S_family=-0.0041 | gap=0.0512 | alpha_std=0.02754

Triada 179/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2223 | S_p=-0.0223 | S_m=0.1027 | S_family=0.0402 | gap=0.1250 | alpha_std=0.02632

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2085 | S_p=-0.0142 | S_m=0.1223 | S_family=0.0540 | gap=0.1365 | alpha_std=0.02629

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1881 | S_p=0.0311 | S_m=0.1027 | S_family=0.0669 | gap=0.0716 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2017 | S_p=0.0408 | S_m=0.1067 | S_family=0.0737 | gap=0.0659 | alpha_std=0.02635

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2468 | S_p=-0.0129 | S_m=0.0525 | S_family=0.0198 | gap=0.0655 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2544 | S_p=-0.0145 | S_m=0.0518 | S_family=0.0186 | gap=0.0663 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2675 | S_p=0.0838 | S_m=0.0112 | S_family=0.0475 | gap=0.0726 | alpha_std=0.02677

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2883 | S_p=0.1088 | S_m=0.0407 | S_family=0.0748 | gap=0.0681 | alpha_std=0.02687

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1976 | S_p=0.0082 | S_m=0.0594 | S_family=0.0338 | gap=0.0512 | alpha_std=0.02660

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1615 | S_p=0.0032 | S_m=0.0568 | S_family=0.0300 | gap=0.0536 | alpha_std=0.02657

Triada 180/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1500 | S_p=0.0057 | S_m=0.0307 | S_family=0.0182 | gap=0.0250 | alpha_std=0.02570

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1726 | S_p=0.0053 | S_m=0.0429 | S_family=0.0241 | gap=0.0376 | alpha_std=0.02559

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1087 | S_p=-0.0960 | S_m=0.0231 | S_family=-0.0365 | gap=0.1191 | alpha_std=0.02707

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0351 | S_p=-0.1194 | S_m=0.0325 | S_family=-0.0434 | gap=0.1520 | alpha_std=0.02710

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1356 | S_p=0.0033 | S_m=0.0287 | S_family=0.0160 | gap=0.0254 | alpha_std=0.02618

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1325 | S_p=-0.0147 | S_m=0.0609 | S_family=0.0231 | gap=0.0756 | alpha_std=0.02628

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1649 | S_p=-0.0451 | S_m=0.0807 | S_family=0.0178 | gap=0.1258 | alpha_std=0.02546

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1949 | S_p=-0.0197 | S_m=0.0696 | S_family=0.0249 | gap=0.0893 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1576 | S_p=0.0430 | S_m=-0.0030 | S_family=0.0200 | gap=0.0461 | alpha_std=0.02674

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1313 | S_p=0.0528 | S_m=0.0065 | S_family=0.0297 | gap=0.0463 | alpha_std=0.02666

Triada 181/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0411 | S_p=0.0536 | S_m=0.0163 | S_family=0.0349 | gap=0.0373 | alpha_std=0.02492

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0390 | S_p=0.0612 | S_m=0.0165 | S_family=0.0389 | gap=0.0446 | alpha_std=0.02489

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2447 | S_p=0.0255 | S_m=0.0244 | S_family=0.0249 | gap=0.0011 | alpha_std=0.02649

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3352 | S_p=-0.0062 | S_m=0.0634 | S_family=0.0286 | gap=0.0696 | alpha_std=0.02661

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0535 | S_p=0.0611 | S_m=-0.0175 | S_family=0.0218 | gap=0.0786 | alpha_std=0.02574

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0389 | S_p=0.0621 | S_m=0.0081 | S_family=0.0351 | gap=0.0540 | alpha_std=0.02565

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0286 | S_p=0.0358 | S_m=0.0416 | S_family=0.0387 | gap=0.0058 | alpha_std=0.02588

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0253 | S_p=0.0394 | S_m=0.0370 | S_family=0.0382 | gap=0.0024 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0724 | S_p=0.0494 | S_m=0.0586 | S_family=0.0540 | gap=0.0092 | alpha_std=0.02568

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0544 | S_p=0.0203 | S_m=0.0744 | S_family=0.0474 | gap=0.0541 | alpha_std=0.02573

Triada 182/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2026 | S_p=-0.0120 | S_m=0.1485 | S_family=0.0683 | gap=0.1604 | alpha_std=0.02751

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1796 | S_p=0.0577 | S_m=0.1082 | S_family=0.0829 | gap=0.0505 | alpha_std=0.02744

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2777 | S_p=-0.0183 | S_m=0.0342 | S_family=0.0080 | gap=0.0525 | alpha_std=0.02760

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2794 | S_p=-0.0464 | S_m=0.0473 | S_family=0.0005 | gap=0.0936 | alpha_std=0.02763

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2722 | S_p=-0.0618 | S_m=0.0702 | S_family=0.0042 | gap=0.1320 | alpha_std=0.02787

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3033 | S_p=-0.0430 | S_m=0.1001 | S_family=0.0285 | gap=0.1431 | alpha_std=0.02789

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2723 | S_p=-0.0186 | S_m=0.0060 | S_family=-0.0063 | gap=0.0247 | alpha_std=0.02793

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2657 | S_p=0.0027 | S_m=0.0115 | S_family=0.0071 | gap=0.0088 | alpha_std=0.02790

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2656 | S_p=-0.0186 | S_m=0.0248 | S_family=0.0031 | gap=0.0433 | alpha_std=0.02747

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2645 | S_p=-0.0105 | S_m=0.0686 | S_family=0.0290 | gap=0.0791 | alpha_std=0.02745

Triada 183/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4583 | S_p=-0.0160 | S_m=-0.0497 | S_family=-0.0329 | gap=0.0337 | alpha_std=0.02718

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4739 | S_p=-0.0022 | S_m=-0.0524 | S_family=-0.0273 | gap=0.0502 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1126 | S_p=-0.0273 | S_m=-0.0133 | S_family=-0.0203 | gap=0.0140 | alpha_std=0.02643

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1469 | S_p=-0.0136 | S_m=-0.0258 | S_family=-0.0197 | gap=0.0123 | alpha_std=0.02633

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4719 | S_p=-0.0182 | S_m=0.0048 | S_family=-0.0067 | gap=0.0230 | alpha_std=0.02852

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4454 | S_p=-0.0254 | S_m=0.0109 | S_family=-0.0073 | gap=0.0363 | alpha_std=0.02862

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2279 | S_p=0.0244 | S_m=-0.1470 | S_family=-0.0613 | gap=0.1714 | alpha_std=0.02713

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2404 | S_p=0.0353 | S_m=-0.1437 | S_family=-0.0542 | gap=0.1791 | alpha_std=0.02711

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3456 | S_p=0.0055 | S_m=-0.0244 | S_family=-0.0095 | gap=0.0299 | alpha_std=0.02870

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3435 | S_p=0.0122 | S_m=-0.0087 | S_family=0.0018 | gap=0.0209 | alpha_std=0.02869

Triada 184/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0758 | S_p=0.0779 | S_m=-0.0845 | S_family=-0.0033 | gap=0.1624 | alpha_std=0.02647

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0983 | S_p=0.0728 | S_m=-0.0608 | S_family=0.0060 | gap=0.1336 | alpha_std=0.02642

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1809 | S_p=-0.0232 | S_m=0.0672 | S_family=0.0220 | gap=0.0904 | alpha_std=0.02731

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1639 | S_p=-0.0189 | S_m=0.0703 | S_family=0.0257 | gap=0.0892 | alpha_std=0.02729

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0002 | S_p=-0.0154 | S_m=0.0140 | S_family=-0.0007 | gap=0.0293 | alpha_std=0.02617

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0116 | S_p=-0.0115 | S_m=0.0276 | S_family=0.0081 | gap=0.0392 | alpha_std=0.02613

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2333 | S_p=-0.0756 | S_m=0.0675 | S_family=-0.0041 | gap=0.1431 | alpha_std=0.02687

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2186 | S_p=-0.0576 | S_m=0.0898 | S_family=0.0161 | gap=0.1474 | alpha_std=0.02691

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2792 | S_p=-0.0627 | S_m=-0.0416 | S_family=-0.0521 | gap=0.0212 | alpha_std=0.02850

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2658 | S_p=-0.0615 | S_m=-0.0330 | S_family=-0.0473 | gap=0.0285 | alpha_std=0.02843

Triada 185/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4741 | S_p=0.0605 | S_m=0.0200 | S_family=0.0402 | gap=0.0405 | alpha_std=0.02785

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4640 | S_p=0.0556 | S_m=0.0270 | S_family=0.0413 | gap=0.0286 | alpha_std=0.02785

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3842 | S_p=0.0502 | S_m=0.0149 | S_family=0.0326 | gap=0.0353 | alpha_std=0.02726

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3807 | S_p=0.0603 | S_m=0.0149 | S_family=0.0376 | gap=0.0455 | alpha_std=0.02722

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.4806 | S_p=-0.0202 | S_m=-0.0300 | S_family=-0.0251 | gap=0.0098 | alpha_std=0.02719

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.4871 | S_p=-0.0172 | S_m=-0.0229 | S_family=-0.0200 | gap=0.0057 | alpha_std=0.02720

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.4007 | S_p=0.0281 | S_m=0.0336 | S_family=0.0308 | gap=0.0055 | alpha_std=0.02786

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.4008 | S_p=0.0385 | S_m=0.0373 | S_family=0.0379 | gap=0.0012 | alpha_std=0.02777

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3340 | S_p=0.0001 | S_m=0.0918 | S_family=0.0459 | gap=0.0917 | alpha_std=0.02781

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2685 | S_p=0.0218 | S_m=0.0857 | S_family=0.0538 | gap=0.0639 | alpha_std=0.02770

Triada 186/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3539 | S_p=0.0520 | S_m=0.0405 | S_family=0.0462 | gap=0.0115 | alpha_std=0.02741

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3461 | S_p=0.0473 | S_m=0.0441 | S_family=0.0457 | gap=0.0033 | alpha_std=0.02741

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3229 | S_p=-0.0075 | S_m=0.0515 | S_family=0.0220 | gap=0.0591 | alpha_std=0.02792

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3370 | S_p=-0.0063 | S_m=0.0780 | S_family=0.0358 | gap=0.0843 | alpha_std=0.02793

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1470 | S_p=-0.0547 | S_m=0.0883 | S_family=0.0168 | gap=0.1431 | alpha_std=0.02704

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1505 | S_p=-0.0670 | S_m=0.0783 | S_family=0.0056 | gap=0.1454 | alpha_std=0.02710

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1109 | S_p=0.0403 | S_m=-0.0255 | S_family=0.0074 | gap=0.0658 | alpha_std=0.02688

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1162 | S_p=0.0333 | S_m=-0.0210 | S_family=0.0062 | gap=0.0544 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2237 | S_p=0.0337 | S_m=0.0272 | S_family=0.0304 | gap=0.0065 | alpha_std=0.02841

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1973 | S_p=0.0407 | S_m=0.0480 | S_family=0.0443 | gap=0.0073 | alpha_std=0.02841

Triada 187/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2879 | S_p=0.0495 | S_m=0.0235 | S_family=0.0365 | gap=0.0261 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2891 | S_p=0.0611 | S_m=0.0307 | S_family=0.0459 | gap=0.0304 | alpha_std=0.02678

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.4288 | S_p=0.0107 | S_m=0.0705 | S_family=0.0406 | gap=0.0598 | alpha_std=0.02755

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3314 | S_p=0.0478 | S_m=0.1064 | S_family=0.0771 | gap=0.0586 | alpha_std=0.02752

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2764 | S_p=0.0865 | S_m=-0.0000 | S_family=0.0432 | gap=0.0865 | alpha_std=0.02691

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2926 | S_p=0.0775 | S_m=-0.0162 | S_family=0.0306 | gap=0.0937 | alpha_std=0.02685

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3154 | S_p=-0.0156 | S_m=0.1074 | S_family=0.0459 | gap=0.1230 | alpha_std=0.02787

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3212 | S_p=0.0088 | S_m=0.0985 | S_family=0.0536 | gap=0.0897 | alpha_std=0.02788

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.3548 | S_p=0.0268 | S_m=0.0420 | S_family=0.0344 | gap=0.0152 | alpha_std=0.02863

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.3499 | S_p=0.0234 | S_m=0.0761 | S_family=0.0498 | gap=0.0527 | alpha_std=0.02862

Triada 188/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0637 | S_p=-0.0783 | S_m=-0.0296 | S_family=-0.0539 | gap=0.0488 | alpha_std=0.02903

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0681 | S_p=-0.0509 | S_m=-0.0206 | S_family=-0.0357 | gap=0.0303 | alpha_std=0.02903

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2225 | S_p=-0.0898 | S_m=0.0439 | S_family=-0.0230 | gap=0.1337 | alpha_std=0.02982

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2522 | S_p=-0.0918 | S_m=0.0722 | S_family=-0.0098 | gap=0.1640 | alpha_std=0.02981

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0088 | S_p=-0.0810 | S_m=-0.0504 | S_family=-0.0657 | gap=0.0307 | alpha_std=0.02882

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0028 | S_p=-0.0553 | S_m=-0.0412 | S_family=-0.0482 | gap=0.0141 | alpha_std=0.02890

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1235 | S_p=-0.0306 | S_m=0.0655 | S_family=0.0175 | gap=0.0961 | alpha_std=0.02982

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1114 | S_p=-0.0169 | S_m=0.0729 | S_family=0.0280 | gap=0.0898 | alpha_std=0.02994

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2659 | S_p=-0.1052 | S_m=0.0242 | S_family=-0.0405 | gap=0.1294 | alpha_std=0.03030

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2718 | S_p=-0.0995 | S_m=0.0313 | S_family=-0.0341 | gap=0.1307 | alpha_std=0.03030

Triada 189/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2759 | S_p=-0.0859 | S_m=0.0395 | S_family=-0.0232 | gap=0.1254 | alpha_std=0.02939

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2743 | S_p=-0.0831 | S_m=0.0636 | S_family=-0.0098 | gap=0.1466 | alpha_std=0.02935

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0117 | S_p=-0.0287 | S_m=-0.0609 | S_family=-0.0448 | gap=0.0322 | alpha_std=0.02835

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0178 | S_p=-0.0418 | S_m=-0.0580 | S_family=-0.0499 | gap=0.0162 | alpha_std=0.02815

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1745 | S_p=0.0308 | S_m=0.0472 | S_family=0.0390 | gap=0.0164 | alpha_std=0.02903

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1262 | S_p=0.0633 | S_m=0.0681 | S_family=0.0657 | gap=0.0048 | alpha_std=0.02894

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2458 | S_p=-0.0586 | S_m=-0.0029 | S_family=-0.0308 | gap=0.0556 | alpha_std=0.03054

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2390 | S_p=-0.0394 | S_m=0.0132 | S_family=-0.0131 | gap=0.0526 | alpha_std=0.03053

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2904 | S_p=-0.0408 | S_m=-0.0242 | S_family=-0.0325 | gap=0.0166 | alpha_std=0.03027

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2870 | S_p=-0.0306 | S_m=-0.0179 | S_family=-0.0242 | gap=0.0128 | alpha_std=0.03011

Triada 190/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1781 | S_p=-0.0229 | S_m=-0.0716 | S_family=-0.0472 | gap=0.0487 | alpha_std=0.02696

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1601 | S_p=0.0073 | S_m=-0.0786 | S_family=-0.0356 | gap=0.0859 | alpha_std=0.02676

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3409 | S_p=-0.0109 | S_m=0.0217 | S_family=0.0054 | gap=0.0326 | alpha_std=0.02639

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3159 | S_p=0.0134 | S_m=0.0105 | S_family=0.0120 | gap=0.0030 | alpha_std=0.02639

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0221 | S_p=-0.0599 | S_m=0.0325 | S_family=-0.0137 | gap=0.0924 | alpha_std=0.02590

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0271 | S_p=-0.0536 | S_m=0.0212 | S_family=-0.0162 | gap=0.0748 | alpha_std=0.02588

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.3139 | S_p=-0.0578 | S_m=0.0121 | S_family=-0.0228 | gap=0.0698 | alpha_std=0.02713

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.3105 | S_p=-0.0668 | S_m=0.0175 | S_family=-0.0246 | gap=0.0843 | alpha_std=0.02716

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2513 | S_p=-0.0185 | S_m=-0.0036 | S_family=-0.0110 | gap=0.0148 | alpha_std=0.02703

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2600 | S_p=-0.0457 | S_m=0.0261 | S_family=-0.0098 | gap=0.0719 | alpha_std=0.02712

Triada 191/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1619 | S_p=0.0377 | S_m=0.0441 | S_family=0.0409 | gap=0.0064 | alpha_std=0.02603

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1772 | S_p=0.0394 | S_m=0.0420 | S_family=0.0407 | gap=0.0026 | alpha_std=0.02603

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2764 | S_p=0.0145 | S_m=0.0559 | S_family=0.0352 | gap=0.0414 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2679 | S_p=0.0242 | S_m=0.0854 | S_family=0.0548 | gap=0.0611 | alpha_std=0.02654

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2410 | S_p=0.0390 | S_m=0.0799 | S_family=0.0595 | gap=0.0408 | alpha_std=0.02686

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2655 | S_p=0.0378 | S_m=0.0709 | S_family=0.0543 | gap=0.0331 | alpha_std=0.02617

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0643 | S_p=0.0216 | S_m=0.0731 | S_family=0.0473 | gap=0.0515 | alpha_std=0.02583

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0116 | S_p=-0.0299 | S_m=0.0290 | S_family=-0.0005 | gap=0.0590 | alpha_std=0.02576

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2593 | S_p=0.0605 | S_m=-0.0177 | S_family=0.0214 | gap=0.0782 | alpha_std=0.02749

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2661 | S_p=0.0467 | S_m=0.0003 | S_family=0.0235 | gap=0.0464 | alpha_std=0.02755

Triada 192/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2811 | S_p=0.0238 | S_m=0.1200 | S_family=0.0719 | gap=0.0963 | alpha_std=0.02587

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1993 | S_p=-0.0314 | S_m=0.0797 | S_family=0.0241 | gap=0.1111 | alpha_std=0.02573

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0354 | S_p=0.0029 | S_m=0.0434 | S_family=0.0231 | gap=0.0406 | alpha_std=0.02562

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0126 | S_p=-0.0274 | S_m=0.0093 | S_family=-0.0090 | gap=0.0367 | alpha_std=0.02556

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0052 | S_p=-0.0926 | S_m=-0.1020 | S_family=-0.0973 | gap=0.0094 | alpha_std=0.02539

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0151 | S_p=-0.0337 | S_m=-0.0501 | S_family=-0.0419 | gap=0.0164 | alpha_std=0.02531

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2755 | S_p=0.0176 | S_m=0.0815 | S_family=0.0496 | gap=0.0639 | alpha_std=0.02657

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2874 | S_p=0.0814 | S_m=0.0629 | S_family=0.0721 | gap=0.0185 | alpha_std=0.02621

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2105 | S_p=0.0153 | S_m=0.0917 | S_family=0.0535 | gap=0.0763 | alpha_std=0.02641

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2026 | S_p=0.0282 | S_m=0.0966 | S_family=0.0624 | gap=0.0684 | alpha_std=0.02646

Triada 193/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0860 | S_p=0.0685 | S_m=0.0226 | S_family=0.0456 | gap=0.0459 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0506 | S_p=0.0822 | S_m=-0.0047 | S_family=0.0387 | gap=0.0869 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0521 | S_p=-0.0416 | S_m=-0.0778 | S_family=-0.0597 | gap=0.0361 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0598 | S_p=-0.0431 | S_m=-0.0903 | S_family=-0.0667 | gap=0.0472 | alpha_std=0.02605

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1016 | S_p=0.0764 | S_m=0.0657 | S_family=0.0710 | gap=0.0107 | alpha_std=0.02587

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0942 | S_p=0.0966 | S_m=0.0873 | S_family=0.0919 | gap=0.0093 | alpha_std=0.02590

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0154 | S_p=-0.0315 | S_m=-0.0527 | S_family=-0.0421 | gap=0.0212 | alpha_std=0.02536

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0010 | S_p=-0.0130 | S_m=-0.0492 | S_family=-0.0311 | gap=0.0362 | alpha_std=0.02548

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1006 | S_p=0.0672 | S_m=0.0433 | S_family=0.0552 | gap=0.0239 | alpha_std=0.02709

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1117 | S_p=0.0548 | S_m=0.0548 | S_family=0.0548 | gap=0.0000 | alpha_std=0.02707

Triada 194/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1432 | S_p=0.0318 | S_m=0.0714 | S_family=0.0516 | gap=0.0396 | alpha_std=0.02592

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1427 | S_p=0.0276 | S_m=0.0658 | S_family=0.0467 | gap=0.0382 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0173 | S_p=-0.0182 | S_m=0.0095 | S_family=-0.0044 | gap=0.0277 | alpha_std=0.02597

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=-0.0250 | S_p=-0.0114 | S_m=-0.0192 | S_family=-0.0153 | gap=0.0079 | alpha_std=0.02591

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2726 | S_p=0.0401 | S_m=0.1177 | S_family=0.0789 | gap=0.0777 | alpha_std=0.02762

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2602 | S_p=0.0593 | S_m=0.1005 | S_family=0.0799 | gap=0.0412 | alpha_std=0.02760

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1207 | S_p=0.0894 | S_m=0.0742 | S_family=0.0818 | gap=0.0152 | alpha_std=0.02687

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0961 | S_p=0.0675 | S_m=0.0657 | S_family=0.0666 | gap=0.0018 | alpha_std=0.02698

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2347 | S_p=0.0380 | S_m=0.0284 | S_family=0.0332 | gap=0.0096 | alpha_std=0.02741

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2302 | S_p=0.0613 | S_m=0.0382 | S_family=0.0498 | gap=0.0231 | alpha_std=0.02740

Triada 195/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.1347 | S_p=0.0248 | S_m=0.0569 | S_family=0.0408 | gap=0.0321 | alpha_std=0.02721

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1599 | S_p=0.0440 | S_m=0.0496 | S_family=0.0468 | gap=0.0056 | alpha_std=0.02723

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1266 | S_p=0.0718 | S_m=0.0930 | S_family=0.0824 | gap=0.0212 | alpha_std=0.02665

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0121 | S_p=0.0898 | S_m=0.0048 | S_family=0.0473 | gap=0.0850 | alpha_std=0.02624

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0085 | S_p=0.0408 | S_m=0.0178 | S_family=0.0293 | gap=0.0230 | alpha_std=0.02576

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0010 | S_p=0.0624 | S_m=0.0259 | S_family=0.0441 | gap=0.0365 | alpha_std=0.02572

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0866 | S_p=0.0929 | S_m=0.0821 | S_family=0.0875 | gap=0.0108 | alpha_std=0.02773

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2046 | S_p=0.0305 | S_m=0.0234 | S_family=0.0270 | gap=0.0071 | alpha_std=0.02730

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2442 | S_p=0.0219 | S_m=0.0008 | S_family=0.0113 | gap=0.0211 | alpha_std=0.02809

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2259 | S_p=0.0223 | S_m=0.0209 | S_family=0.0216 | gap=0.0014 | alpha_std=0.02801

Triada 196/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0317 | S_p=0.0179 | S_m=-0.0277 | S_family=-0.0049 | gap=0.0456 | alpha_std=0.02506

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0158 | S_p=0.0235 | S_m=-0.0039 | S_family=0.0098 | gap=0.0274 | alpha_std=0.02515

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3621 | S_p=0.0682 | S_m=0.0494 | S_family=0.0588 | gap=0.0188 | alpha_std=0.02640

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3675 | S_p=0.0732 | S_m=0.0601 | S_family=0.0666 | gap=0.0130 | alpha_std=0.02642

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2477 | S_p=0.0471 | S_m=0.0582 | S_family=0.0527 | gap=0.0111 | alpha_std=0.02610

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2523 | S_p=0.0777 | S_m=0.1013 | S_family=0.0895 | gap=0.0236 | alpha_std=0.02607

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0483 | S_p=0.0824 | S_m=-0.0118 | S_family=0.0353 | gap=0.0942 | alpha_std=0.02566

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0436 | S_p=0.0831 | S_m=-0.0259 | S_family=0.0286 | gap=0.1090 | alpha_std=0.02568

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1281 | S_p=0.1202 | S_m=0.0116 | S_family=0.0659 | gap=0.1086 | alpha_std=0.02668

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1249 | S_p=0.1317 | S_m=0.0153 | S_family=0.0735 | gap=0.1164 | alpha_std=0.02671

Triada 197/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4524 | S_p=0.0643 | S_m=-0.0248 | S_family=0.0198 | gap=0.0890 | alpha_std=0.02655

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4841 | S_p=0.0634 | S_m=-0.0059 | S_family=0.0288 | gap=0.0694 | alpha_std=0.02651

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3075 | S_p=0.0134 | S_m=0.0057 | S_family=0.0096 | gap=0.0078 | alpha_std=0.02758

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3075 | S_p=0.0236 | S_m=0.0309 | S_family=0.0272 | gap=0.0073 | alpha_std=0.02750

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2314 | S_p=0.1193 | S_m=0.0229 | S_family=0.0711 | gap=0.0964 | alpha_std=0.02634

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0900 | S_p=0.1272 | S_m=0.0140 | S_family=0.0706 | gap=0.1132 | alpha_std=0.02599

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0143 | S_p=-0.0239 | S_m=-0.0028 | S_family=-0.0133 | gap=0.0210 | alpha_std=0.02572

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0080 | S_p=-0.0490 | S_m=-0.0166 | S_family=-0.0328 | gap=0.0324 | alpha_std=0.02575

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2029 | S_p=0.0264 | S_m=-0.0488 | S_family=-0.0112 | gap=0.0752 | alpha_std=0.02696

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1940 | S_p=0.0178 | S_m=-0.0397 | S_family=-0.0110 | gap=0.0575 | alpha_std=0.02689

Triada 198/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2176 | S_p=-0.0173 | S_m=0.0197 | S_family=0.0012 | gap=0.0370 | alpha_std=0.02603

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2236 | S_p=-0.0131 | S_m=0.0024 | S_family=-0.0054 | gap=0.0155 | alpha_std=0.02595

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0986 | S_p=-0.0189 | S_m=0.0731 | S_family=0.0271 | gap=0.0920 | alpha_std=0.02572

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0948 | S_p=-0.0163 | S_m=0.0631 | S_family=0.0234 | gap=0.0794 | alpha_std=0.02574

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0290 | S_p=-0.0327 | S_m=0.0277 | S_family=-0.0025 | gap=0.0604 | alpha_std=0.02551

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0217 | S_p=-0.0254 | S_m=0.0380 | S_family=0.0063 | gap=0.0634 | alpha_std=0.02551

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2266 | S_p=-0.0148 | S_m=0.0015 | S_family=-0.0067 | gap=0.0162 | alpha_std=0.02731

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2254 | S_p=-0.0067 | S_m=0.0171 | S_family=0.0052 | gap=0.0237 | alpha_std=0.02730

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2366 | S_p=-0.0777 | S_m=-0.0179 | S_family=-0.0478 | gap=0.0598 | alpha_std=0.02736

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2290 | S_p=-0.0653 | S_m=-0.0085 | S_family=-0.0369 | gap=0.0568 | alpha_std=0.02736

Triada 199/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.4422 | S_p=0.0179 | S_m=-0.0332 | S_family=-0.0077 | gap=0.0511 | alpha_std=0.02603

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.4551 | S_p=0.0102 | S_m=-0.0392 | S_family=-0.0145 | gap=0.0495 | alpha_std=0.02600

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3861 | S_p=0.0255 | S_m=-0.0458 | S_family=-0.0101 | gap=0.0714 | alpha_std=0.02613

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3851 | S_p=0.0280 | S_m=-0.0427 | S_family=-0.0073 | gap=0.0707 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1518 | S_p=-0.0949 | S_m=-0.0954 | S_family=-0.0951 | gap=0.0005 | alpha_std=0.02603

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1526 | S_p=-0.1054 | S_m=-0.0754 | S_family=-0.0904 | gap=0.0301 | alpha_std=0.02596

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0967 | S_p=0.0014 | S_m=-0.0000 | S_family=0.0007 | gap=0.0014 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=-0.0330 | S_p=-0.0308 | S_m=0.0476 | S_family=0.0084 | gap=0.0784 | alpha_std=0.02563

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1675 | S_p=0.0194 | S_m=-0.0470 | S_family=-0.0138 | gap=0.0663 | alpha_std=0.02642

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1669 | S_p=0.0166 | S_m=-0.0482 | S_family=-0.0158 | gap=0.0648 | alpha_std=0.02641

Triada 200/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0023 | S_p=-0.0069 | S_m=-0.0469 | S_family=-0.0269 | gap=0.0400 | alpha_std=0.02587

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0187 | S_p=0.0033 | S_m=-0.0223 | S_family=-0.0095 | gap=0.0256 | alpha_std=0.02576

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=-0.0046 | S_p=-0.1279 | S_m=-0.0024 | S_family=-0.0652 | gap=0.1255 | alpha_std=0.02544

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0418 | S_p=-0.1008 | S_m=0.0012 | S_family=-0.0498 | gap=0.1020 | alpha_std=0.02551

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3158 | S_p=0.0874 | S_m=-0.0401 | S_family=0.0237 | gap=0.1275 | alpha_std=0.02603

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2859 | S_p=0.0559 | S_m=-0.0305 | S_family=0.0127 | gap=0.0864 | alpha_std=0.02606

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0777 | S_p=0.0038 | S_m=-0.0441 | S_family=-0.0202 | gap=0.0479 | alpha_std=0.02673

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0786 | S_p=0.0262 | S_m=-0.0418 | S_family=-0.0078 | gap=0.0680 | alpha_std=0.02664

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1729 | S_p=-0.0248 | S_m=0.0105 | S_family=-0.0072 | gap=0.0353 | alpha_std=0.02679

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1160 | S_p=-0.0131 | S_m=-0.0501 | S_family=-0.0316 | gap=0.0371 | alpha_std=0.02668

Triada 201/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.0949 | S_p=-0.0541 | S_m=-0.0682 | S_family=-0.0611 | gap=0.0141 | alpha_std=0.02593

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.0888 | S_p=-0.0481 | S_m=-0.0529 | S_family=-0.0505 | gap=0.0047 | alpha_std=0.02593

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1553 | S_p=-0.0213 | S_m=-0.0213 | S_family=-0.0213 | gap=0.0001 | alpha_std=0.02555

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1733 | S_p=0.0178 | S_m=0.0284 | S_family=0.0231 | gap=0.0105 | alpha_std=0.02556

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=-0.0494 | S_p=-0.0349 | S_m=-0.1350 | S_family=-0.0849 | gap=0.1001 | alpha_std=0.02509

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=-0.0536 | S_p=-0.0175 | S_m=-0.1246 | S_family=-0.0711 | gap=0.1071 | alpha_std=0.02507

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2117 | S_p=0.0749 | S_m=0.0819 | S_family=0.0784 | gap=0.0070 | alpha_std=0.02634

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1732 | S_p=-0.0285 | S_m=0.0307 | S_family=0.0011 | gap=0.0592 | alpha_std=0.02604

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1828 | S_p=-0.0935 | S_m=-0.0041 | S_family=-0.0488 | gap=0.0894 | alpha_std=0.02578

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0850 | S_p=-0.1417 | S_m=-0.0595 | S_family=-0.1006 | gap=0.0822 | alpha_std=0.02566

Triada 202/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=-0.0413 | S_p=-0.0739 | S_m=0.0595 | S_family=-0.0072 | gap=0.1334 | alpha_std=0.02497

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=-0.0336 | S_p=-0.1062 | S_m=0.0757 | S_family=-0.0152 | gap=0.1819 | alpha_std=0.02505

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0383 | S_p=-0.0037 | S_m=-0.0261 | S_family=-0.0149 | gap=0.0224 | alpha_std=0.02508

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0368 | S_p=-0.0273 | S_m=-0.0158 | S_family=-0.0215 | gap=0.0116 | alpha_std=0.02506

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0243 | S_p=-0.0919 | S_m=0.0746 | S_family=-0.0086 | gap=0.1666 | alpha_std=0.02534

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0402 | S_p=-0.0878 | S_m=0.1017 | S_family=0.0070 | gap=0.1895 | alpha_std=0.02535

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0528 | S_p=-0.0227 | S_m=0.0333 | S_family=0.0053 | gap=0.0560 | alpha_std=0.02500

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0378 | S_p=-0.0387 | S_m=0.0034 | S_family=-0.0177 | gap=0.0421 | alpha_std=0.02488

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2748 | S_p=0.0501 | S_m=0.0184 | S_family=0.0342 | gap=0.0316 | alpha_std=0.02610

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2838 | S_p=0.0680 | S_m=0.0180 | S_family=0.0430 | gap=0.0499 | alpha_std=0.02610

Triada 203/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2856 | S_p=0.0621 | S_m=-0.0213 | S_family=0.0204 | gap=0.0834 | alpha_std=0.02537

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2591 | S_p=0.0785 | S_m=0.0291 | S_family=0.0538 | gap=0.0494 | alpha_std=0.02532

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2435 | S_p=0.0437 | S_m=-0.0503 | S_family=-0.0033 | gap=0.0940 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2412 | S_p=0.0553 | S_m=-0.0420 | S_family=0.0066 | gap=0.0974 | alpha_std=0.02545

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2761 | S_p=0.0830 | S_m=-0.0336 | S_family=0.0247 | gap=0.1166 | alpha_std=0.02532

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2708 | S_p=0.0811 | S_m=-0.0319 | S_family=0.0246 | gap=0.1130 | alpha_std=0.02532

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2013 | S_p=0.0135 | S_m=-0.0594 | S_family=-0.0229 | gap=0.0730 | alpha_std=0.02570

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2041 | S_p=0.0218 | S_m=-0.0546 | S_family=-0.0164 | gap=0.0764 | alpha_std=0.02569

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2597 | S_p=0.0863 | S_m=-0.0444 | S_family=0.0210 | gap=0.1307 | alpha_std=0.02581

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2603 | S_p=0.1016 | S_m=-0.0389 | S_family=0.0314 | gap=0.1405 | alpha_std=0.02580

Triada 204/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.3840 | S_p=0.0789 | S_m=-0.0245 | S_family=0.0272 | gap=0.1034 | alpha_std=0.02607

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.3710 | S_p=0.1008 | S_m=-0.0601 | S_family=0.0204 | gap=0.1609 | alpha_std=0.02600

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0745 | S_p=0.0219 | S_m=0.0100 | S_family=0.0160 | gap=0.0119 | alpha_std=0.02533

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0608 | S_p=0.0281 | S_m=0.0119 | S_family=0.0200 | gap=0.0163 | alpha_std=0.02529

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.3362 | S_p=0.0155 | S_m=0.0437 | S_family=0.0296 | gap=0.0282 | alpha_std=0.02659

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.3311 | S_p=0.0423 | S_m=0.0415 | S_family=0.0419 | gap=0.0008 | alpha_std=0.02659

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.2515 | S_p=0.1207 | S_m=0.0795 | S_family=0.1001 | gap=0.0413 | alpha_std=0.02614

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2461 | S_p=0.1231 | S_m=0.0952 | S_family=0.1092 | gap=0.0279 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1778 | S_p=0.0273 | S_m=0.0079 | S_family=0.0176 | gap=0.0194 | alpha_std=0.02615

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1569 | S_p=0.0435 | S_m=0.0183 | S_family=0.0309 | gap=0.0252 | alpha_std=0.02620

Triada 205/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2697 | S_p=0.0636 | S_m=0.0173 | S_family=0.0405 | gap=0.0463 | alpha_std=0.02628

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2426 | S_p=0.0841 | S_m=0.0282 | S_family=0.0561 | gap=0.0559 | alpha_std=0.02629

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.1686 | S_p=0.0485 | S_m=0.0122 | S_family=0.0303 | gap=0.0362 | alpha_std=0.02576

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.1811 | S_p=0.0320 | S_m=-0.0164 | S_family=0.0078 | gap=0.0484 | alpha_std=0.02572

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.2667 | S_p=0.0800 | S_m=0.0404 | S_family=0.0602 | gap=0.0396 | alpha_std=0.02547

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.2509 | S_p=0.0894 | S_m=0.0319 | S_family=0.0607 | gap=0.0575 | alpha_std=0.02540

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1827 | S_p=-0.0292 | S_m=0.1191 | S_family=0.0450 | gap=0.1483 | alpha_std=0.02659

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.2193 | S_p=-0.0559 | S_m=0.1625 | S_family=0.0533 | gap=0.2185 | alpha_std=0.02660

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0950 | S_p=-0.0262 | S_m=0.0344 | S_family=0.0041 | gap=0.0606 | alpha_std=0.02528

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0589 | S_p=-0.0131 | S_m=0.0305 | S_family=0.0087 | gap=0.0436 | alpha_std=0.02529

Triada 206/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2535 | S_p=-0.0934 | S_m=-0.0275 | S_family=-0.0605 | gap=0.0660 | alpha_std=0.02526

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.1974 | S_p=-0.0806 | S_m=-0.0270 | S_family=-0.0538 | gap=0.0536 | alpha_std=0.02524

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.2539 | S_p=0.0207 | S_m=0.0300 | S_family=0.0253 | gap=0.0093 | alpha_std=0.02526

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.2417 | S_p=0.0264 | S_m=0.0408 | S_family=0.0336 | gap=0.0144 | alpha_std=0.02526

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0396 | S_p=-0.0754 | S_m=0.0554 | S_family=-0.0100 | gap=0.1308 | alpha_std=0.02501

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0242 | S_p=-0.0770 | S_m=0.0632 | S_family=-0.0069 | gap=0.1402 | alpha_std=0.02504

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.1319 | S_p=0.0075 | S_m=0.0560 | S_family=0.0318 | gap=0.0485 | alpha_std=0.02639

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.1465 | S_p=0.0572 | S_m=0.0750 | S_family=0.0661 | gap=0.0178 | alpha_std=0.02640

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.1459 | S_p=0.0318 | S_m=-0.0597 | S_family=-0.0139 | gap=0.0915 | alpha_std=0.02602

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.1379 | S_p=0.0072 | S_m=-0.0122 | S_family=-0.0025 | gap=0.0194 | alpha_std=0.02600

Triada 207/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.2085 | S_p=0.0465 | S_m=0.0495 | S_family=0.0480 | gap=0.0030 | alpha_std=0.02575

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.2122 | S_p=-0.0058 | S_m=0.0938 | S_family=0.0440 | gap=0.0996 | alpha_std=0.02573

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.3148 | S_p=0.1100 | S_m=0.0121 | S_family=0.0610 | gap=0.0979 | alpha_std=0.02586

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.3485 | S_p=0.0467 | S_m=0.0432 | S_family=0.0449 | gap=0.0035 | alpha_std=0.02612

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.0475 | S_p=-0.0430 | S_m=0.0087 | S_family=-0.0171 | gap=0.0518 | alpha_std=0.02517

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.0386 | S_p=-0.0228 | S_m=0.0007 | S_family=-0.0111 | gap=0.0234 | alpha_std=0.02517

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0002 | S_p=-0.0631 | S_m=0.0612 | S_family=-0.0010 | gap=0.1243 | alpha_std=0.02551

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0029 | S_p=-0.0677 | S_m=0.0686 | S_family=0.0004 | gap=0.1362 | alpha_std=0.02553

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.0831 | S_p=-0.0354 | S_m=0.0265 | S_family=-0.0045 | gap=0.0619 | alpha_std=0.02558

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.0789 | S_p=-0.0609 | S_m=0.0348 | S_family=-0.0131 | gap=0.0957 | alpha_std=0.02554

Triada 208/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.0 | S_id=0.5036 | S_p=0.0025 | S_m=0.0770 | S_family=0.0397 | gap=0.0745 | alpha_std=0.02690

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | λ=0.1 | S_id=0.5059 | S_p=0.0178 | S_m=0.0829 | S_family=0.0504 | gap=0.0651 | alpha_std=0.02693

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.0 | S_id=0.0668 | S_p=-0.0151 | S_m=0.0160 | S_family=0.0005 | gap=0.0310 | alpha_std=0.02448

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | λ=0.1 | S_id=0.0719 | S_p=0.0211 | S_m=0.0115 | S_family=0.0163 | gap=0.0096 | alpha_std=0.02440

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.0 | S_id=0.1381 | S_p=0.0307 | S_m=0.0826 | S_family=0.0567 | gap=0.0519 | alpha_std=0.02519

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | λ=0.1 | S_id=0.1271 | S_p=0.0259 | S_m=0.1022 | S_family=0.0640 | gap=0.0763 | alpha_std=0.02520

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.0 | S_id=0.0627 | S_p=-0.0842 | S_m=0.0340 | S_family=-0.0251 | gap=0.1182 | alpha_std=0.02581

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | λ=0.1 | S_id=0.0700 | S_p=-0.0665 | S_m=0.0258 | S_family=-0.0203 | gap=0.0923 | alpha_std=0.02580

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.0 | S_id=0.2284 | S_p=0.0006 | S_m=0.0616 | S_family=0.0311 | gap=0.0609 | alpha_std=0.02613

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | λ=0.1 | S_id=0.2375 | S_p=0.0054 | S_m=0.0595 | S_family=0.0325 | gap=0.0542 | alpha_std=0.02613

==============================
Filas finales BAP2
==============================
2080
Esperadas: 2080
✓ Row count is correct.

==============================
Global summary BAP2 step4689
==============================

,parent_scale,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap,alpha_mean,alpha_std,alpha_min,alpha_max
0,0.0,0.186944,0.011409,0.017132,0.014271,0.058377,0.498077,0.026752,0.366957,0.62997
1,0.1,0.186964,0.017099,0.023106,0.020102,0.058842,0.498077,0.026742,0.366942,0.62978

==============================
Summary by age BAP2 step4689
==============================

,age,parent_scale,S_id_child,S_p_father,S_m_mother,S_family,balance_abs_gap,alpha_mean,alpha_std,alpha_min,alpha_max
0,5,0.0,0.228909,0.015005,0.016991,0.015998,0.057917,0.498078,0.026651,0.368219,0.630570
1,5,0.1,0.229202,0.021431,0.021773,0.021602,0.057876,0.498079,0.026645,0.368137,0.630254
2,15,0.0,0.174865,0.009960,0.017790,0.013875,0.052823,0.498081,0.026513,0.368554,0.628452
3,15,0.1,0.174445,0.014473,0.021724,0.018098,0.051596,0.498081,0.026501,0.368595,0.628218
4,25,0.0,0.176835,0.006010,0.009614,0.007812,0.054142,0.498073,0.026682,0.367497,0.629344
5,25,0.1,0.175151,0.011241,0.016735,0.013988,0.055995,0.498075,0.026671,0.367485,0.629258
6,40,0.0,0.172542,0.008963,0.016993,0.012978,0.061187,0.498073,0.026901,0.365745,0.630306
7,40,0.1,0.176098,0.015348,0.024192,0.019770,0.061390,0.498074,0.026891,0.365732,0.630115
8,60,0.0,0.181572,0.017110,0.024274,0.020692,0.065817,0.498079,0.027011,0.364771,0.631180
9,60,0.1,0.179924,0.023001,0.031106,0.027053,0.067352,0.498079,0.027001,0.364758,0.631055

✓ TEST FINAL BAP2 terminado
CSV: /content/drive/MyDrive/Notebook4/results/eval/bap2/bap2.csv
Images: /content/drive/MyDrive/Notebook4/results/eval/bap2/images
Summary: /content/drive/MyDrive/Notebook4/results/eval/bap2

In [11]:
# ============================================================
# Paired statistics BAP2 TEST
# λ=0.1 vs λ=0.0
# CPU only
# ============================================================

import os
import numpy as np
import pandas as pd
from IPython.display import display

try:
    from scipy.stats import wilcoxon
    HAS_SCIPY = True
except Exception as e:
    HAS_SCIPY = False
    print("⚠ scipy not available:", e)

OUT_DIR = f"{DRIVE}/results/eval/bap2"
CSV_PATH = f"{OUT_DIR}/bap2.csv"

df = pd.read_csv(CSV_PATH)

print("Filas:", len(df))
print("Parent scales:", df["parent_scale"].unique())
print("Triads:", df["triad_idx"].nunique())
print("Ages:", sorted(df["age"].unique()))

metrics = [
    "S_id_child",
    "S_p_father",
    "S_m_mother",
    "S_family",
    "balance_abs_gap",
]

df0 = df[df["parent_scale"] == 0.0].copy()
df1 = df[df["parent_scale"] == 0.1].copy()

key_cols = ["triad_idx", "age"]

merged = df0[key_cols + metrics].merge(
    df1[key_cols + metrics],
    on=key_cols,
    suffixes=("_0", "_1")
)

print("Pares:", len(merged))

rows = []

rng = np.random.default_rng(123)
B = 5000

for m in metrics:
    d = merged[f"{m}_1"] - merged[f"{m}_0"]

    boot = []
    arr = d.values

    for _ in range(B):
        sample = rng.choice(arr, size=len(arr), replace=True)
        boot.append(sample.mean())

    boot = np.array(boot)

    row = {
        "metric": m,
        "mean_lambda0": merged[f"{m}_0"].mean(),
        "mean_lambda01": merged[f"{m}_1"].mean(),
        "mean_delta_0.1_minus_0.0": d.mean(),
        "median_delta": d.median(),
        "ci95_low": np.percentile(boot, 2.5),
        "ci95_high": np.percentile(boot, 97.5),
        "win_rate_delta_gt_0": (d > 0).mean(),
        "n_pairs": len(d),
    }

    if HAS_SCIPY:
        try:
            stat, p = wilcoxon(d)
            row["wilcoxon_stat"] = stat
            row["wilcoxon_p"] = p
        except Exception as e:
            row["wilcoxon_stat"] = None
            row["wilcoxon_p"] = None
            row["wilcoxon_error"] = str(e)

    rows.append(row)

df_bap2_stats = pd.DataFrame(rows)

print("\n==============================")
print("Paired statistics BAP2 λ=0.1 vs λ=0.0")
print("==============================")
display(df_bap2_stats)

# By age
age_rows = []

for age in sorted(merged["age"].unique()):
    sub = merged[merged["age"] == age]

    for m in metrics:
        d = sub[f"{m}_1"] - sub[f"{m}_0"]

        age_rows.append({
            "age": age,
            "metric": m,
            "mean_delta_0.1_minus_0.0": d.mean(),
            "median_delta": d.median(),
            "win_rate_delta_gt_0": (d > 0).mean(),
            "n_pairs": len(d),
        })

df_bap2_stats_age = pd.DataFrame(age_rows)

print("\n==============================")
print("Statistics by age")
print("==============================")
display(df_bap2_stats_age)

df_bap2_stats.to_csv(f"{OUT_DIR}/stats_paired_bap2_l01_vs_lambda0.csv", index=False)
df_bap2_stats_age.to_csv(f"{OUT_DIR}/stats_by_age_bap2_l01_vs_lambda0.csv", index=False)

print("\n✓ Saved to:", OUT_DIR)

Filas: 2080
Parent scales: [0.  0.1]
Triads: 208
Edades: [np.int64(5), np.int64(15), np.int64(25), np.int64(40), np.int64(60)]
Pares: 1040

==============================
Paired statistics BAP2 λ=0.1 vs λ=0.0
==============================

,metric,mean_lambda0,mean_lambda01,mean_delta_0.1_minus_0.0,median_delta,ci95_low,ci95_high,win_rate_delta_gt_0,n_pairs,wilcoxon_stat,wilcoxon_p
0,S_id_child,0.186944,0.186964,0.000020,-0.000127,-0.001574,0.001608,0.492308,1040,269627.0,9.150926e-01
1,S_p_father,0.011409,0.017099,0.005689,0.005642,0.004543,0.006843,0.693269,1040,153045.0,6.545863e-34
2,S_m_mother,0.017132,0.023106,0.005974,0.006525,0.004805,0.007138,0.700962,1040,149108.0,4.204924e-36
3,S_family,0.014271,0.020102,0.005831,0.005978,0.004973,0.006686,0.719231,1040,121298.0,1.280611e-53
4,balance_abs_gap,0.058377,0.058842,0.000465,-0.000064,-0.000925,0.001863,0.498077,1040,268390.0,8.147600e-01

==============================
Statistics by age
==============================

,age,metric,mean_delta_0.1_minus_0.0,median_delta,win_rate_delta_gt_0,n_pairs
0,5,S_id_child,0.000293,0.000706,0.514423,208
1,5,S_p_father,0.006426,0.005774,0.764423,208
2,5,S_m_mother,0.004782,0.006381,0.668269,208
3,5,S_family,0.005604,0.005964,0.740385,208
4,5,balance_abs_gap,-0.000042,-0.000063,0.500000,208
5,15,S_id_child,-0.000420,-0.000524,0.480769,208
6,15,S_p_father,0.004513,0.004859,0.653846,208
7,15,S_m_mother,0.003934,0.004793,0.663462,208
8,15,S_family,0.004224,0.003695,0.649038,208
9,15,balance_abs_gap,-0.001226,-0.000766,0.475962,208
10,25,S_id_child,-0.001684,-0.001260,0.451923,208
11,25,S_p_father,0.005231,0.004856,0.663462,208
12,25,S_m_mother,0.007121,0.008107,0.730769,208
13,25,S_family,0.006176,0.005981,0.721154,208
14,25,balance_abs_gap,0.001853,0.001174,0.557692,208
15,40,S_id_child,0.003556,0.000945,0.533654,208
16,40,S_p_father,0.006385,0.006401,0.692308,208
17,40,S_m_mother,0.007200,0.005751,0.730769,208
18,40,S_family,0.006792,0.006942,0.730769,208
19,40,balance_abs_gap,0.000203,-0.001849,0.451923,208
20,60,S_id_child,-0.001647,-0.000354,0.480769,208
21,60,S_p_father,0.005892,0.006755,0.692308,208
22,60,S_m_mother,0.006832,0.007468,0.711538,208
23,60,S_family,0.006362,0.007257,0.754808,208
24,60,balance_abs_gap,0.001535,0.000096,0.504808,208

✓ Saved to: /content/drive/MyDrive/Notebook4/results/eval/bap2

In [12]:
# ============================================================
# Check the NoGate implementation available in src
# Does not modify the pipeline. Only inspects imports and names.
# ============================================================

import os, sys, importlib, inspect

candidate_modules = [
    "src.bap_processor_no_gate",
    "src.attach_bap",
    "src.attach_child_anchor_bap_gate",
    "src.bap_child_anchor_gate",
    "src.bap2",
    "src.att2",
]

for modname in candidate_modules:
    print("\n" + "="*80)
    print("MODULE:", modname)
    try:
        mod = importlib.import_module(modname)
        print("✓ Importa")

        names = [
            n for n in dir(mod)
            if (
                "Gate" in n
                or "gate" in n
                or "BAP" in n
                or "bap" in n
                or "attach" in n
                or "No" in n
                or "no" in n
                or "Child" in n
                or "Anchor" in n
            )
        ]

        print("Nombres candidatos:")
        for n in names:
            obj = getattr(mod, n)
            print(" -", n, "|", type(obj))

        print("\nFunctions/classes with signature:")
        for n in names:
            obj = getattr(mod, n)
            if inspect.isfunction(obj) or inspect.isclass(obj):
                try:
                    print(f"\n{n}:")
                    print(inspect.signature(obj))
                except Exception as e:
                    print(f"{n}: no signature ({e})")

    except Exception as e:
        print("✗ Import failed")
        print(type(e).__name__, e)

================================================================================
MODULE: src.bap_processor_no_gate
✓ Importa
Nombres candidatos:

Functions/classes with signature:

================================================================================
MODULE: src.attach_bap
✗ No importa
ModuleNotFoundError No module named 'src.attach_bap'

================================================================================
MODULE: src.attach_child_anchor_bap_gate
✓ Importa
Nombres candidatos:
 - ChildAnchorBAPGateAttnProcessor | <class 'type'>
 - attach_child_anchor_bap_gate_to_unet | <class 'function'>

Functions/classes with signature:

ChildAnchorBAPGateAttnProcessor:
(hidden_size: int, cross_attention_dim: int, num_tokens: int = 4, scale: float = 1.0, child_scale: float = 1.0, parent_scale: float = 0.1, gate_groups: int = 16)

attach_child_anchor_bap_gate_to_unet:
(unet, num_tokens: int = 4, scale: float = 1.0, child_scale: float = 1.0, parent_scale: float = 0.1, gate_groups: int = 16, device='cuda', dtype=torch.float16, copy_ip_weights: bool = True)

================================================================================
MODULE: src.bap_child_anchor_gate
✓ Importa
Nombres candidatos:
 - ChildAnchorBAPGateAttnProcessor | <class 'type'>

Functions/classes with signature:

ChildAnchorBAPGateAttnProcessor:
(hidden_size: int, cross_attention_dim: int, num_tokens: int = 4, scale: float = 1.0, child_scale: float = 1.0, parent_scale: float = 0.1, gate_groups: int = 16)

================================================================================
MODULE: src.bap2
✓ Importa
Nombres candidatos:
 - BAP2 | <class 'type'>

Functions/classes with signature:

BAP2:
(hidden_size: int, cross_attention_dim: int, num_tokens: int = 4, scale: float = 1.0, child_scale: float = 1.0, parent_scale: float = 0.1, gate_groups: int = 16, gate_hidden: int = 256, temperature: float = 1.0)

================================================================================
MODULE: src.att2
✓ Importa
Nombres candidatos:
 - BAP2 | <class 'type'>
 - attach_bap2 | <class 'function'>

Functions/classes with signature:

BAP2:
(hidden_size: int, cross_attention_dim: int, num_tokens: int = 4, scale: float = 1.0, child_scale: float = 1.0, parent_scale: float = 0.1, gate_groups: int = 16, gate_hidden: int = 256, temperature: float = 1.0)

attach_bap2:
(unet, num_tokens: int = 4, scale: float = 1.0, child_scale: float = 1.0, parent_scale: float = 0.1, gate_groups: int = 16, gate_hidden: int = 256, temperature: float = 1.0, device='cuda', dtype=torch.float16, copy_ip_weights: bool = True)

In [ ]:
# ============================================================
# TEST FINAL — NoGate / FixedGate α=0.5
# 208 triads × 5 ages × λ=0.1 = 1040 images
#
# Baseline:
#   child anchor + father + mother
#   but WITHOUT a learned gate
#   alpha = 0.5 fijo
# ============================================================

import os
import torch
import torch.nn.functional as F
import pandas as pd
from torch.utils.data._utils.collate import default_collate
from IPython.display import display

# ------------------------------------------------------------
# Verificaciones
# ------------------------------------------------------------

required = [
    "test_ds",
    "bap2_modules",
    "generate_bap2_final",
    "arcface_embed_from_pil",
    "ensure_2d",
]

missing = [x for x in required if x not in globals()]
assert len(missing) == 0, f"Missing objects in memory: {missing}"

assert len(bap2_modules) == 16, "bap2_modules must have 16 modules."

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

AGES = [5, 15, 25, 40, 60]
PARENT_SCALE = 0.1

BASE_SEED = 42

OUT_DIR = f"{DRIVE}/results/eval/nogate"
IMG_DIR = f"{OUT_DIR}/images"
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(IMG_DIR, exist_ok=True)

OUT_CSV = f"{OUT_DIR}/nogate.csv"

print("Test triads:", len(test_ds))
print("Ages:", AGES)
print("Parent scale:", PARENT_SCALE)
print("Total images:", len(test_ds) * len(AGES))
print("OUT_DIR:", OUT_DIR)

# ------------------------------------------------------------
# Forzar NoGate: alpha = sigmoid(0) = 0.5
# ------------------------------------------------------------

for name, proc in bap2_modules.items():
    proc.gate.float()
    with torch.no_grad():
        proc.gate.weight.zero_()
        proc.gate.bias.zero_()
    proc.gate.to(DEVICE)

print("✓ Gates reseteados a cero: alpha fijo = 0.5")

# Sanity check alpha
with torch.no_grad():
    first_name, first_proc = next(iter(bap2_modules.items()))
    dummy = torch.randn(
        1,
        first_proc.gate.in_features,
        device=DEVICE,
        dtype=torch.float32,
    )
    alpha = torch.sigmoid(first_proc.gate(dummy))

print("Alpha sanity:")
print("mean:", alpha.mean().item())
print("std :", alpha.std().item())
print("min :", alpha.min().item())
print("max :", alpha.max().item())

assert abs(alpha.mean().item() - 0.5) < 1e-6
assert alpha.std().item() < 1e-6

# ------------------------------------------------------------
# Saving NoGate images
# ------------------------------------------------------------

def save_nogate_image(img, triad_idx, age):
    subdir = f"{IMG_DIR}/age_{age}"
    os.makedirs(subdir, exist_ok=True)

    path = f"{subdir}/t{triad_idx:04d}_a{int(age):02d}.jpg"
    img.save(path, quality=95)
    return path

# ------------------------------------------------------------
# Automatic resume
# ------------------------------------------------------------

rows = []
done = set()

if os.path.exists(OUT_CSV):
    old = pd.read_csv(OUT_CSV)
    rows = old.to_dict("records")
    done = set(zip(old["triad_idx"], old["age"]))
    print(f"✓ Resume detected: {len(old)} existing rows")

# ------------------------------------------------------------
# Loop principal
# ------------------------------------------------------------

for triad_idx in range(len(test_ds)):

    sample = test_ds[triad_idx]

    batch = default_collate([sample])
    batch = {
        k: v.to(DEVICE) if isinstance(v, torch.Tensor) else v
        for k, v in batch.items()
    }

    h_c = ensure_2d(batch["h_c"])
    h_p = ensure_2d(batch["h_p"])
    h_m = ensure_2d(batch["h_m"])

    h_c_eval = F.normalize(h_c.float(), p=2, dim=1)
    h_p_eval = F.normalize(h_p.float(), p=2, dim=1)
    h_m_eval = F.normalize(h_m.float(), p=2, dim=1)

    gender = sample.get("gender", "person")
    if gender not in ["man", "woman", "person"]:
        gender = "person"

    print(f"\nNoGate | Triada {triad_idx + 1}/{len(test_ds)} | gender={gender}")

    for age in AGES:

        if (triad_idx, age) in done:
            print(f"skip triad={triad_idx} age={age}")
            continue

        paired_seed = BASE_SEED + triad_idx * 1000 + age

        img, alpha_stats, prompt = generate_bap2_final(
            h_c=h_c,
            h_p=h_p,
            h_m=h_m,
            gender=gender,
            age=age,
            parent_scale=PARENT_SCALE,
            seed=paired_seed,
        )

        img_path = save_nogate_image(
            img=img,
            triad_idx=triad_idx,
            age=age,
        )

        h_gen = arcface_embed_from_pil(img)

        S_id = F.cosine_similarity(h_gen, h_c_eval).item()
        S_p  = F.cosine_similarity(h_gen, h_p_eval).item()
        S_m  = F.cosine_similarity(h_gen, h_m_eval).item()

        row = {
            "variant": "NoGate_fixed_alpha05",
            "checkpoint_step": "fixed_alpha_0.5",
            "triad_idx": triad_idx,
            "age": age,
            "parent_scale": PARENT_SCALE,
            "gender": gender,
            "S_id_child": S_id,
            "S_p_father": S_p,
            "S_m_mother": S_m,
            "S_family": 0.5 * (S_p + S_m),
            "balance_abs_gap": abs(S_p - S_m),
            "alpha_mean": alpha_stats["alpha_mean"],
            "alpha_std": alpha_stats["alpha_std"],
            "alpha_min": alpha_stats["alpha_min"],
            "alpha_max": alpha_stats["alpha_max"],
            "key_p": sample.get("key_p", ""),
            "key_m": sample.get("key_m", ""),
            "key_c": sample.get("key_c", ""),
            "seed": paired_seed,
            "prompt": prompt,
            "image_path": img_path,
        }

        rows.append(row)

        # Incremental saving
        pd.DataFrame(rows).to_csv(OUT_CSV, index=False)

        print(
            f"age={age} | "
            f"S_id={S_id:.4f} | "
            f"S_p={S_p:.4f} | "
            f"S_m={S_m:.4f} | "
            f"S_family={row['S_family']:.4f} | "
            f"gap={row['balance_abs_gap']:.4f} | "
            f"alpha_mean={alpha_stats['alpha_mean']:.4f}"
        )

# ------------------------------------------------------------
# Final summary NoGate
# ------------------------------------------------------------

df_final_nogate = pd.DataFrame(rows)

print("\n==============================")
print("Filas finales NoGate")
print("==============================")
print(len(df_final_nogate))

expected_rows = len(test_ds) * len(AGES)
print("Esperadas:", expected_rows)

if len(df_final_nogate) != expected_rows:
    print("⚠ Warning: unexpected number of rows. Check whether there was an interruption.")
else:
    print("✓ Row count is correct.")

summary_nogate_global = (
    df_final_nogate
    .groupby("variant")
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
        "alpha_min",
        "alpha_max",
    ]]
    .mean()
    .reset_index()
)

summary_nogate_age = (
    df_final_nogate
    .groupby(["age"])
    [[
        "S_id_child",
        "S_p_father",
        "S_m_mother",
        "S_family",
        "balance_abs_gap",
        "alpha_mean",
        "alpha_std",
        "alpha_min",
        "alpha_max",
    ]]
    .mean()
    .reset_index()
)

print("\n==============================")
print("Global summary NoGate")
print("==============================")
display(summary_nogate_global)

print("\n==============================")
print("Summary by age NoGate")
print("==============================")
display(summary_nogate_age)

summary_nogate_global.to_csv(f"{OUT_DIR}/summary_global_nogate.csv", index=False)
summary_nogate_age.to_csv(f"{OUT_DIR}/summary_age_nogate.csv", index=False)

print("\n✓ TEST FINAL NoGate terminado")
print("CSV:", OUT_CSV)
print("Images:", IMG_DIR)
print("Summary:", OUT_DIR)

Test triads: 208
Edades: [5, 15, 25, 40, 60]
Parent scale: 0.1
Total images: 1040
OUT_DIR: /content/drive/MyDrive/Notebook4/results/eval/nogate
✓ Gates reseteados a cero: alpha fijo = 0.5
Alpha sanity:
mean: 0.5
std : 0.0
min : 0.5
max : 0.5

NoGate | Triada 1/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0631 | S_p=-0.0072 | S_m=0.0150 | S_family=0.0039 | gap=0.0222 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0610 | S_p=-0.0061 | S_m=-0.0389 | S_family=-0.0225 | gap=0.0329 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0306 | S_p=-0.0050 | S_m=-0.0149 | S_family=-0.0100 | gap=0.0099 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2674 | S_p=0.0168 | S_m=0.0046 | S_family=0.0107 | gap=0.0123 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1851 | S_p=-0.1013 | S_m=-0.0248 | S_family=-0.0630 | gap=0.0764 | alpha_mean=0.5000

NoGate | Triada 2/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1423 | S_p=0.0369 | S_m=-0.0172 | S_family=0.0099 | gap=0.0541 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0943 | S_p=0.0110 | S_m=-0.0736 | S_family=-0.0313 | gap=0.0845 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0096 | S_p=-0.0508 | S_m=-0.0284 | S_family=-0.0396 | gap=0.0224 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3462 | S_p=0.0119 | S_m=0.0773 | S_family=0.0446 | gap=0.0654 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1792 | S_p=-0.0043 | S_m=0.1038 | S_family=0.0498 | gap=0.1080 | alpha_mean=0.5000

NoGate | Triada 3/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3411 | S_p=0.0675 | S_m=0.1340 | S_family=0.1008 | gap=0.0665 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3363 | S_p=0.0439 | S_m=0.0405 | S_family=0.0422 | gap=0.0034 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4507 | S_p=0.0542 | S_m=0.0707 | S_family=0.0625 | gap=0.0164 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3750 | S_p=0.0276 | S_m=0.1002 | S_family=0.0639 | gap=0.0726 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2675 | S_p=0.0647 | S_m=-0.0100 | S_family=0.0274 | gap=0.0748 | alpha_mean=0.5000

NoGate | Triada 4/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3846 | S_p=0.0148 | S_m=0.0798 | S_family=0.0473 | gap=0.0650 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1383 | S_p=0.0437 | S_m=-0.0096 | S_family=0.0171 | gap=0.0533 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0045 | S_p=-0.0030 | S_m=-0.0388 | S_family=-0.0209 | gap=0.0358 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1970 | S_p=0.0856 | S_m=0.0703 | S_family=0.0780 | gap=0.0153 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2402 | S_p=0.0741 | S_m=0.0929 | S_family=0.0835 | gap=0.0188 | alpha_mean=0.5000

NoGate | Triada 5/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3351 | S_p=0.0323 | S_m=-0.0197 | S_family=0.0063 | gap=0.0520 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3260 | S_p=0.0459 | S_m=0.0010 | S_family=0.0235 | gap=0.0449 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2602 | S_p=0.0467 | S_m=0.1185 | S_family=0.0826 | gap=0.0718 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1891 | S_p=0.0079 | S_m=0.0355 | S_family=0.0217 | gap=0.0277 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1525 | S_p=-0.0334 | S_m=0.0753 | S_family=0.0210 | gap=0.1088 | alpha_mean=0.5000

NoGate | Triada 6/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3796 | S_p=-0.0096 | S_m=-0.0280 | S_family=-0.0188 | gap=0.0183 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0550 | S_p=-0.0263 | S_m=0.0211 | S_family=-0.0026 | gap=0.0475 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2337 | S_p=0.0596 | S_m=-0.0173 | S_family=0.0211 | gap=0.0769 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1983 | S_p=0.0456 | S_m=0.0244 | S_family=0.0350 | gap=0.0212 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2047 | S_p=0.0152 | S_m=0.0284 | S_family=0.0218 | gap=0.0131 | alpha_mean=0.5000

NoGate | Triada 7/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1425 | S_p=0.0609 | S_m=0.0294 | S_family=0.0452 | gap=0.0314 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1233 | S_p=0.0641 | S_m=-0.0492 | S_family=0.0074 | gap=0.1133 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1516 | S_p=-0.0064 | S_m=0.0391 | S_family=0.0163 | gap=0.0455 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2643 | S_p=0.0070 | S_m=0.0541 | S_family=0.0305 | gap=0.0471 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2278 | S_p=0.0176 | S_m=0.0642 | S_family=0.0409 | gap=0.0465 | alpha_mean=0.5000

NoGate | Triada 8/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1410 | S_p=0.1149 | S_m=0.0763 | S_family=0.0956 | gap=0.0385 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1067 | S_p=0.1375 | S_m=0.0064 | S_family=0.0720 | gap=0.1312 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1685 | S_p=0.1037 | S_m=0.0161 | S_family=0.0599 | gap=0.0876 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2011 | S_p=0.0203 | S_m=-0.0120 | S_family=0.0041 | gap=0.0322 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1926 | S_p=0.1382 | S_m=0.0079 | S_family=0.0730 | gap=0.1303 | alpha_mean=0.5000

NoGate | Triada 9/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2249 | S_p=0.1666 | S_m=-0.0181 | S_family=0.0742 | gap=0.1847 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1205 | S_p=0.0786 | S_m=-0.0312 | S_family=0.0237 | gap=0.1098 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1006 | S_p=0.0347 | S_m=-0.0380 | S_family=-0.0016 | gap=0.0727 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1578 | S_p=-0.0332 | S_m=-0.0126 | S_family=-0.0229 | gap=0.0206 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2402 | S_p=0.0490 | S_m=-0.0722 | S_family=-0.0116 | gap=0.1212 | alpha_mean=0.5000

NoGate | Triada 10/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0341 | S_p=0.0237 | S_m=0.0381 | S_family=0.0309 | gap=0.0144 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1103 | S_p=0.0688 | S_m=0.0498 | S_family=0.0593 | gap=0.0190 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1002 | S_p=0.0723 | S_m=0.0650 | S_family=0.0686 | gap=0.0073 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1462 | S_p=0.1136 | S_m=0.0025 | S_family=0.0580 | gap=0.1111 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1529 | S_p=0.0315 | S_m=0.0596 | S_family=0.0456 | gap=0.0281 | alpha_mean=0.5000

NoGate | Triada 11/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2452 | S_p=0.1220 | S_m=0.0966 | S_family=0.1093 | gap=0.0254 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1849 | S_p=0.0806 | S_m=0.1228 | S_family=0.1017 | gap=0.0423 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0740 | S_p=0.0542 | S_m=-0.0225 | S_family=0.0158 | gap=0.0767 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0349 | S_p=0.0902 | S_m=0.0007 | S_family=0.0454 | gap=0.0895 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0725 | S_p=0.0254 | S_m=-0.0134 | S_family=0.0060 | gap=0.0388 | alpha_mean=0.5000

NoGate | Triada 12/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0070 | S_p=0.0074 | S_m=0.0812 | S_family=0.0443 | gap=0.0738 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0269 | S_p=-0.0652 | S_m=0.0680 | S_family=0.0014 | gap=0.1333 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0292 | S_p=-0.0596 | S_m=0.0590 | S_family=-0.0003 | gap=0.1187 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2745 | S_p=0.1637 | S_m=0.0667 | S_family=0.1152 | gap=0.0970 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2272 | S_p=0.0672 | S_m=0.0213 | S_family=0.0442 | gap=0.0459 | alpha_mean=0.5000

NoGate | Triada 13/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0815 | S_p=0.0241 | S_m=0.0288 | S_family=0.0264 | gap=0.0048 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2284 | S_p=0.0119 | S_m=-0.0014 | S_family=0.0053 | gap=0.0134 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3614 | S_p=0.0511 | S_m=-0.0284 | S_family=0.0114 | gap=0.0795 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2033 | S_p=0.0814 | S_m=-0.0102 | S_family=0.0356 | gap=0.0915 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2199 | S_p=0.0680 | S_m=0.0294 | S_family=0.0487 | gap=0.0386 | alpha_mean=0.5000

NoGate | Triada 14/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4385 | S_p=-0.0054 | S_m=0.0394 | S_family=0.0170 | gap=0.0447 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.5391 | S_p=-0.0157 | S_m=0.0490 | S_family=0.0166 | gap=0.0647 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1687 | S_p=-0.0154 | S_m=0.0643 | S_family=0.0245 | gap=0.0798 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.4075 | S_p=-0.0046 | S_m=0.0869 | S_family=0.0411 | gap=0.0915 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3506 | S_p=0.0173 | S_m=0.1089 | S_family=0.0631 | gap=0.0917 | alpha_mean=0.5000

NoGate | Triada 15/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4980 | S_p=-0.0166 | S_m=0.0241 | S_family=0.0037 | gap=0.0407 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2970 | S_p=-0.0040 | S_m=0.0044 | S_family=0.0002 | gap=0.0083 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4087 | S_p=-0.0583 | S_m=-0.0086 | S_family=-0.0335 | gap=0.0497 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1610 | S_p=-0.0561 | S_m=0.0211 | S_family=-0.0175 | gap=0.0772 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2042 | S_p=-0.0082 | S_m=0.0527 | S_family=0.0223 | gap=0.0609 | alpha_mean=0.5000

NoGate | Triada 16/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2557 | S_p=-0.0025 | S_m=0.0350 | S_family=0.0162 | gap=0.0375 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0077 | S_p=0.0447 | S_m=0.0132 | S_family=0.0289 | gap=0.0315 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0482 | S_p=0.0041 | S_m=0.0463 | S_family=0.0252 | gap=0.0422 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0306 | S_p=0.0368 | S_m=0.0633 | S_family=0.0501 | gap=0.0265 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3372 | S_p=0.0912 | S_m=0.0500 | S_family=0.0706 | gap=0.0412 | alpha_mean=0.5000

NoGate | Triada 17/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0343 | S_p=0.0452 | S_m=-0.0095 | S_family=0.0179 | gap=0.0548 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2088 | S_p=0.0724 | S_m=0.0199 | S_family=0.0462 | gap=0.0525 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4124 | S_p=0.0896 | S_m=-0.0176 | S_family=0.0360 | gap=0.1072 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0714 | S_p=0.0485 | S_m=0.0176 | S_family=0.0331 | gap=0.0310 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1577 | S_p=0.1727 | S_m=0.0028 | S_family=0.0878 | gap=0.1699 | alpha_mean=0.5000

NoGate | Triada 18/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4932 | S_p=0.1196 | S_m=0.0345 | S_family=0.0771 | gap=0.0851 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1682 | S_p=0.0049 | S_m=-0.0123 | S_family=-0.0037 | gap=0.0173 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3000 | S_p=0.0498 | S_m=-0.0228 | S_family=0.0135 | gap=0.0726 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0924 | S_p=-0.0164 | S_m=-0.0183 | S_family=-0.0174 | gap=0.0020 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1652 | S_p=-0.0374 | S_m=0.0937 | S_family=0.0281 | gap=0.1311 | alpha_mean=0.5000

NoGate | Triada 19/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2316 | S_p=-0.0023 | S_m=0.1695 | S_family=0.0836 | gap=0.1719 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0304 | S_p=0.0322 | S_m=0.0121 | S_family=0.0221 | gap=0.0202 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0720 | S_p=-0.0389 | S_m=0.0120 | S_family=-0.0135 | gap=0.0508 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1361 | S_p=0.0112 | S_m=0.0919 | S_family=0.0516 | gap=0.0807 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0243 | S_p=-0.0101 | S_m=-0.0722 | S_family=-0.0411 | gap=0.0621 | alpha_mean=0.5000

NoGate | Triada 20/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0056 | S_p=-0.0321 | S_m=-0.0395 | S_family=-0.0358 | gap=0.0074 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1626 | S_p=0.0023 | S_m=0.0239 | S_family=0.0131 | gap=0.0216 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1700 | S_p=-0.0333 | S_m=-0.0844 | S_family=-0.0588 | gap=0.0511 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3434 | S_p=0.1379 | S_m=-0.0541 | S_family=0.0419 | gap=0.1920 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1352 | S_p=0.0754 | S_m=0.0443 | S_family=0.0599 | gap=0.0311 | alpha_mean=0.5000

NoGate | Triada 21/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0157 | S_p=0.0128 | S_m=-0.0147 | S_family=-0.0010 | gap=0.0275 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0076 | S_p=0.0454 | S_m=0.0064 | S_family=0.0259 | gap=0.0390 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0275 | S_p=0.0238 | S_m=-0.0893 | S_family=-0.0327 | gap=0.1131 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0380 | S_p=0.0182 | S_m=-0.0067 | S_family=0.0057 | gap=0.0248 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0860 | S_p=-0.0248 | S_m=-0.0182 | S_family=-0.0215 | gap=0.0067 | alpha_mean=0.5000

NoGate | Triada 22/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2916 | S_p=0.0939 | S_m=-0.0889 | S_family=0.0025 | gap=0.1828 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0214 | S_p=-0.0394 | S_m=-0.0131 | S_family=-0.0263 | gap=0.0264 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1083 | S_p=0.0007 | S_m=0.0032 | S_family=0.0020 | gap=0.0025 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2285 | S_p=0.0331 | S_m=-0.0266 | S_family=0.0032 | gap=0.0597 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0315 | S_p=0.1141 | S_m=-0.0036 | S_family=0.0553 | gap=0.1177 | alpha_mean=0.5000

NoGate | Triada 23/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2680 | S_p=0.0321 | S_m=0.0579 | S_family=0.0450 | gap=0.0258 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3373 | S_p=0.0603 | S_m=0.0297 | S_family=0.0450 | gap=0.0306 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2376 | S_p=0.0628 | S_m=-0.0216 | S_family=0.0206 | gap=0.0845 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1816 | S_p=0.0757 | S_m=0.0094 | S_family=0.0426 | gap=0.0664 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1785 | S_p=0.1620 | S_m=-0.0200 | S_family=0.0710 | gap=0.1821 | alpha_mean=0.5000

NoGate | Triada 24/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4291 | S_p=0.0696 | S_m=0.1561 | S_family=0.1128 | gap=0.0864 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3741 | S_p=0.0470 | S_m=0.0490 | S_family=0.0480 | gap=0.0020 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2507 | S_p=0.0839 | S_m=0.0371 | S_family=0.0605 | gap=0.0468 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2436 | S_p=-0.0113 | S_m=0.0017 | S_family=-0.0048 | gap=0.0129 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2570 | S_p=0.0348 | S_m=0.0473 | S_family=0.0411 | gap=0.0125 | alpha_mean=0.5000

NoGate | Triada 25/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0406 | S_p=0.0021 | S_m=-0.0470 | S_family=-0.0224 | gap=0.0491 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0508 | S_p=-0.0957 | S_m=0.0258 | S_family=-0.0349 | gap=0.1214 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3545 | S_p=-0.0464 | S_m=0.0139 | S_family=-0.0163 | gap=0.0603 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1590 | S_p=-0.0866 | S_m=0.0303 | S_family=-0.0282 | gap=0.1170 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2780 | S_p=-0.0413 | S_m=0.0496 | S_family=0.0042 | gap=0.0910 | alpha_mean=0.5000

NoGate | Triada 26/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0139 | S_p=-0.0407 | S_m=-0.0056 | S_family=-0.0232 | gap=0.0351 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0793 | S_p=-0.0445 | S_m=-0.0304 | S_family=-0.0375 | gap=0.0141 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0119 | S_p=-0.0458 | S_m=0.0032 | S_family=-0.0213 | gap=0.0490 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2564 | S_p=-0.0662 | S_m=-0.1157 | S_family=-0.0910 | gap=0.0495 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2233 | S_p=-0.0097 | S_m=0.0829 | S_family=0.0366 | gap=0.0926 | alpha_mean=0.5000

NoGate | Triada 27/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4527 | S_p=-0.0335 | S_m=0.1342 | S_family=0.0503 | gap=0.1677 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0163 | S_p=0.0804 | S_m=-0.0073 | S_family=0.0366 | gap=0.0877 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4599 | S_p=-0.0439 | S_m=0.1122 | S_family=0.0341 | gap=0.1561 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3162 | S_p=0.0050 | S_m=0.0489 | S_family=0.0270 | gap=0.0439 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2276 | S_p=0.0176 | S_m=-0.0343 | S_family=-0.0083 | gap=0.0519 | alpha_mean=0.5000

NoGate | Triada 28/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0678 | S_p=0.0109 | S_m=-0.0393 | S_family=-0.0142 | gap=0.0502 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4792 | S_p=0.0561 | S_m=0.1238 | S_family=0.0900 | gap=0.0677 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.5258 | S_p=0.0323 | S_m=0.0980 | S_family=0.0651 | gap=0.0658 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.4647 | S_p=0.0262 | S_m=0.1388 | S_family=0.0825 | gap=0.1126 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1347 | S_p=0.0056 | S_m=0.1363 | S_family=0.0710 | gap=0.1308 | alpha_mean=0.5000

NoGate | Triada 29/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4783 | S_p=0.0935 | S_m=0.0341 | S_family=0.0638 | gap=0.0594 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1278 | S_p=-0.0052 | S_m=-0.0599 | S_family=-0.0326 | gap=0.0547 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2339 | S_p=-0.0032 | S_m=0.0581 | S_family=0.0275 | gap=0.0613 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.4333 | S_p=-0.0291 | S_m=-0.0226 | S_family=-0.0258 | gap=0.0065 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3738 | S_p=0.0387 | S_m=0.0438 | S_family=0.0412 | gap=0.0050 | alpha_mean=0.5000

NoGate | Triada 30/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0494 | S_p=0.0030 | S_m=-0.0435 | S_family=-0.0202 | gap=0.0465 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1895 | S_p=0.0147 | S_m=0.0198 | S_family=0.0172 | gap=0.0051 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1422 | S_p=0.0191 | S_m=0.0451 | S_family=0.0321 | gap=0.0260 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0188 | S_p=-0.1192 | S_m=0.0051 | S_family=-0.0570 | gap=0.1243 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1802 | S_p=0.0841 | S_m=0.1068 | S_family=0.0955 | gap=0.0227 | alpha_mean=0.5000

NoGate | Triada 31/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0613 | S_p=-0.0691 | S_m=0.0218 | S_family=-0.0236 | gap=0.0909 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1252 | S_p=-0.0478 | S_m=-0.0046 | S_family=-0.0262 | gap=0.0432 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0626 | S_p=-0.1393 | S_m=-0.0107 | S_family=-0.0750 | gap=0.1286 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0903 | S_p=-0.0184 | S_m=-0.0439 | S_family=-0.0312 | gap=0.0254 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1448 | S_p=-0.0553 | S_m=0.0265 | S_family=-0.0144 | gap=0.0817 | alpha_mean=0.5000

NoGate | Triada 32/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4357 | S_p=0.1343 | S_m=0.0399 | S_family=0.0871 | gap=0.0944 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3702 | S_p=0.1235 | S_m=0.0403 | S_family=0.0819 | gap=0.0832 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3706 | S_p=0.1609 | S_m=0.0204 | S_family=0.0907 | gap=0.1406 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1318 | S_p=0.0481 | S_m=-0.0104 | S_family=0.0189 | gap=0.0585 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2418 | S_p=0.1933 | S_m=-0.0377 | S_family=0.0778 | gap=0.2310 | alpha_mean=0.5000

NoGate | Triada 33/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3999 | S_p=0.0238 | S_m=-0.0054 | S_family=0.0092 | gap=0.0292 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3576 | S_p=0.0254 | S_m=0.0022 | S_family=0.0138 | gap=0.0232 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2998 | S_p=-0.0180 | S_m=-0.0705 | S_family=-0.0442 | gap=0.0525 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3125 | S_p=0.0803 | S_m=0.0243 | S_family=0.0523 | gap=0.0560 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1297 | S_p=0.0672 | S_m=-0.0674 | S_family=-0.0001 | gap=0.1347 | alpha_mean=0.5000

NoGate | Triada 34/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1569 | S_p=-0.0417 | S_m=-0.0694 | S_family=-0.0556 | gap=0.0277 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1629 | S_p=0.0923 | S_m=0.0090 | S_family=0.0507 | gap=0.0833 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0398 | S_p=0.0367 | S_m=0.0158 | S_family=0.0262 | gap=0.0209 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0143 | S_p=0.0127 | S_m=0.0146 | S_family=0.0136 | gap=0.0019 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1035 | S_p=0.0533 | S_m=0.0346 | S_family=0.0440 | gap=0.0188 | alpha_mean=0.5000

NoGate | Triada 35/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2364 | S_p=0.0537 | S_m=-0.0465 | S_family=0.0036 | gap=0.1002 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0278 | S_p=-0.0614 | S_m=-0.0213 | S_family=-0.0413 | gap=0.0401 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0493 | S_p=-0.0878 | S_m=0.0312 | S_family=-0.0283 | gap=0.1190 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1921 | S_p=-0.0299 | S_m=-0.0218 | S_family=-0.0258 | gap=0.0081 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0120 | S_p=-0.0707 | S_m=0.0368 | S_family=-0.0170 | gap=0.1075 | alpha_mean=0.5000

NoGate | Triada 36/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1655 | S_p=0.0839 | S_m=-0.0310 | S_family=0.0264 | gap=0.1149 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0923 | S_p=0.0151 | S_m=0.0249 | S_family=0.0200 | gap=0.0098 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0331 | S_p=0.0268 | S_m=-0.0170 | S_family=0.0049 | gap=0.0439 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2147 | S_p=-0.0207 | S_m=-0.0086 | S_family=-0.0147 | gap=0.0121 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2114 | S_p=0.0073 | S_m=0.0135 | S_family=0.0104 | gap=0.0062 | alpha_mean=0.5000

NoGate | Triada 37/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2635 | S_p=0.0409 | S_m=0.0053 | S_family=0.0231 | gap=0.0355 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2861 | S_p=0.0440 | S_m=-0.0623 | S_family=-0.0091 | gap=0.1063 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3219 | S_p=0.0257 | S_m=-0.0342 | S_family=-0.0043 | gap=0.0599 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3491 | S_p=0.0869 | S_m=-0.0374 | S_family=0.0248 | gap=0.1243 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3838 | S_p=0.0817 | S_m=0.0348 | S_family=0.0583 | gap=0.0469 | alpha_mean=0.5000

NoGate | Triada 38/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4636 | S_p=0.0096 | S_m=0.0247 | S_family=0.0172 | gap=0.0150 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4586 | S_p=-0.0160 | S_m=0.0100 | S_family=-0.0030 | gap=0.0260 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3828 | S_p=-0.0290 | S_m=-0.1019 | S_family=-0.0655 | gap=0.0729 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0934 | S_p=0.0498 | S_m=-0.0766 | S_family=-0.0134 | gap=0.1264 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0674 | S_p=-0.0008 | S_m=-0.0200 | S_family=-0.0104 | gap=0.0193 | alpha_mean=0.5000

NoGate | Triada 39/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0789 | S_p=0.0281 | S_m=0.0066 | S_family=0.0174 | gap=0.0215 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0696 | S_p=0.0093 | S_m=0.0661 | S_family=0.0377 | gap=0.0568 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1374 | S_p=0.0900 | S_m=0.0101 | S_family=0.0500 | gap=0.0800 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0265 | S_p=0.0690 | S_m=-0.0006 | S_family=0.0342 | gap=0.0696 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0854 | S_p=0.0188 | S_m=-0.0198 | S_family=-0.0005 | gap=0.0386 | alpha_mean=0.5000

NoGate | Triada 40/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0405 | S_p=0.0219 | S_m=0.0478 | S_family=0.0348 | gap=0.0259 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2014 | S_p=0.0198 | S_m=0.0536 | S_family=0.0367 | gap=0.0338 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4064 | S_p=0.0145 | S_m=0.0388 | S_family=0.0267 | gap=0.0243 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2262 | S_p=0.0461 | S_m=0.1320 | S_family=0.0890 | gap=0.0859 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3594 | S_p=-0.0379 | S_m=0.0621 | S_family=0.0121 | gap=0.1000 | alpha_mean=0.5000

NoGate | Triada 41/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1673 | S_p=0.0485 | S_m=-0.0293 | S_family=0.0096 | gap=0.0778 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0645 | S_p=-0.0054 | S_m=0.0125 | S_family=0.0036 | gap=0.0179 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3893 | S_p=0.0117 | S_m=0.0696 | S_family=0.0406 | gap=0.0579 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1789 | S_p=0.0158 | S_m=0.1089 | S_family=0.0623 | gap=0.0931 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3445 | S_p=0.0547 | S_m=0.1094 | S_family=0.0821 | gap=0.0547 | alpha_mean=0.5000

NoGate | Triada 42/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0249 | S_p=-0.0389 | S_m=-0.0866 | S_family=-0.0627 | gap=0.0477 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1477 | S_p=0.0075 | S_m=-0.0163 | S_family=-0.0044 | gap=0.0238 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0339 | S_p=-0.0072 | S_m=-0.0886 | S_family=-0.0479 | gap=0.0814 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0583 | S_p=-0.0468 | S_m=0.0043 | S_family=-0.0212 | gap=0.0511 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1588 | S_p=0.0840 | S_m=0.0383 | S_family=0.0612 | gap=0.0457 | alpha_mean=0.5000

NoGate | Triada 43/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1548 | S_p=-0.0632 | S_m=-0.1063 | S_family=-0.0848 | gap=0.0430 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0623 | S_p=-0.0736 | S_m=-0.0172 | S_family=-0.0454 | gap=0.0564 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0226 | S_p=0.0026 | S_m=-0.0810 | S_family=-0.0392 | gap=0.0836 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0190 | S_p=-0.0034 | S_m=-0.0744 | S_family=-0.0389 | gap=0.0710 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1144 | S_p=-0.0468 | S_m=-0.0970 | S_family=-0.0719 | gap=0.0501 | alpha_mean=0.5000

NoGate | Triada 44/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0059 | S_p=0.0053 | S_m=-0.0610 | S_family=-0.0278 | gap=0.0663 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1459 | S_p=-0.0217 | S_m=0.0189 | S_family=-0.0014 | gap=0.0405 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0118 | S_p=-0.1375 | S_m=-0.0438 | S_family=-0.0906 | gap=0.0937 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0698 | S_p=0.0313 | S_m=-0.0780 | S_family=-0.0234 | gap=0.1093 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1443 | S_p=0.0077 | S_m=0.0265 | S_family=0.0171 | gap=0.0188 | alpha_mean=0.5000

NoGate | Triada 45/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0602 | S_p=0.0068 | S_m=-0.0079 | S_family=-0.0005 | gap=0.0146 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2811 | S_p=-0.0308 | S_m=0.0486 | S_family=0.0089 | gap=0.0794 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0144 | S_p=-0.0490 | S_m=0.0814 | S_family=0.0162 | gap=0.1304 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1364 | S_p=0.0254 | S_m=-0.0263 | S_family=-0.0004 | gap=0.0517 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0649 | S_p=0.0274 | S_m=-0.1156 | S_family=-0.0441 | gap=0.1430 | alpha_mean=0.5000

NoGate | Triada 46/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1982 | S_p=-0.0460 | S_m=0.1426 | S_family=0.0483 | gap=0.1887 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2351 | S_p=-0.0479 | S_m=0.0441 | S_family=-0.0019 | gap=0.0920 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1216 | S_p=-0.0515 | S_m=0.1036 | S_family=0.0261 | gap=0.1551 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1431 | S_p=-0.0837 | S_m=0.0702 | S_family=-0.0068 | gap=0.1539 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1350 | S_p=-0.0762 | S_m=0.0064 | S_family=-0.0349 | gap=0.0825 | alpha_mean=0.5000

NoGate | Triada 47/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2996 | S_p=0.0296 | S_m=-0.0582 | S_family=-0.0143 | gap=0.0878 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4663 | S_p=-0.0824 | S_m=-0.0089 | S_family=-0.0456 | gap=0.0736 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3770 | S_p=0.0056 | S_m=0.0556 | S_family=0.0306 | gap=0.0501 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2528 | S_p=0.0255 | S_m=-0.0228 | S_family=0.0013 | gap=0.0483 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0463 | S_p=0.0532 | S_m=-0.0665 | S_family=-0.0066 | gap=0.1197 | alpha_mean=0.5000

NoGate | Triada 48/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3048 | S_p=0.0207 | S_m=-0.0236 | S_family=-0.0014 | gap=0.0444 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0815 | S_p=0.0545 | S_m=-0.0279 | S_family=0.0133 | gap=0.0823 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3669 | S_p=-0.0438 | S_m=0.0609 | S_family=0.0085 | gap=0.1047 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2034 | S_p=-0.0351 | S_m=0.0160 | S_family=-0.0095 | gap=0.0512 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3130 | S_p=-0.0024 | S_m=0.1087 | S_family=0.0531 | gap=0.1111 | alpha_mean=0.5000

NoGate | Triada 49/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3692 | S_p=0.0007 | S_m=0.0712 | S_family=0.0360 | gap=0.0706 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1357 | S_p=-0.0258 | S_m=0.0142 | S_family=-0.0058 | gap=0.0400 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2252 | S_p=-0.0252 | S_m=-0.0188 | S_family=-0.0220 | gap=0.0064 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1796 | S_p=-0.0251 | S_m=-0.0362 | S_family=-0.0306 | gap=0.0111 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2761 | S_p=0.0554 | S_m=0.0751 | S_family=0.0653 | gap=0.0197 | alpha_mean=0.5000

NoGate | Triada 50/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1224 | S_p=-0.0133 | S_m=0.0797 | S_family=0.0332 | gap=0.0930 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0764 | S_p=-0.0049 | S_m=0.0889 | S_family=0.0420 | gap=0.0939 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.4467 | S_p=0.0895 | S_m=0.0564 | S_family=0.0729 | gap=0.0331 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0867 | S_p=-0.0440 | S_m=0.0500 | S_family=0.0030 | gap=0.0940 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1784 | S_p=0.0670 | S_m=0.0251 | S_family=0.0460 | gap=0.0419 | alpha_mean=0.5000

NoGate | Triada 51/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2853 | S_p=0.0266 | S_m=0.0190 | S_family=0.0228 | gap=0.0076 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1035 | S_p=-0.0017 | S_m=0.0385 | S_family=0.0184 | gap=0.0402 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2607 | S_p=0.0186 | S_m=0.0185 | S_family=0.0186 | gap=0.0000 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3343 | S_p=0.0617 | S_m=0.0013 | S_family=0.0315 | gap=0.0604 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0488 | S_p=-0.0434 | S_m=-0.0036 | S_family=-0.0235 | gap=0.0398 | alpha_mean=0.5000

NoGate | Triada 52/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0316 | S_p=0.0352 | S_m=0.0820 | S_family=0.0586 | gap=0.0468 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0854 | S_p=0.0364 | S_m=0.0690 | S_family=0.0527 | gap=0.0326 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0029 | S_p=0.0069 | S_m=-0.0341 | S_family=-0.0136 | gap=0.0410 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0472 | S_p=0.0879 | S_m=-0.0213 | S_family=0.0333 | gap=0.1092 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2283 | S_p=0.1040 | S_m=0.0736 | S_family=0.0888 | gap=0.0305 | alpha_mean=0.5000

NoGate | Triada 53/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3708 | S_p=-0.0097 | S_m=0.0153 | S_family=0.0028 | gap=0.0250 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0379 | S_p=0.0720 | S_m=-0.0205 | S_family=0.0257 | gap=0.0925 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2087 | S_p=-0.0452 | S_m=-0.0004 | S_family=-0.0228 | gap=0.0448 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2253 | S_p=-0.0851 | S_m=0.0968 | S_family=0.0058 | gap=0.1819 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1369 | S_p=-0.0327 | S_m=0.0205 | S_family=-0.0061 | gap=0.0532 | alpha_mean=0.5000

NoGate | Triada 54/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4399 | S_p=0.0627 | S_m=0.1234 | S_family=0.0931 | gap=0.0607 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3732 | S_p=0.0050 | S_m=0.1619 | S_family=0.0835 | gap=0.1569 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3311 | S_p=0.0581 | S_m=0.1645 | S_family=0.1113 | gap=0.1064 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2384 | S_p=0.0537 | S_m=0.1232 | S_family=0.0885 | gap=0.0694 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2139 | S_p=0.0449 | S_m=0.1160 | S_family=0.0804 | gap=0.0710 | alpha_mean=0.5000

NoGate | Triada 55/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2221 | S_p=0.0517 | S_m=0.0352 | S_family=0.0434 | gap=0.0165 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0795 | S_p=-0.0050 | S_m=0.0601 | S_family=0.0276 | gap=0.0651 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0759 | S_p=0.0298 | S_m=0.0252 | S_family=0.0275 | gap=0.0046 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1991 | S_p=-0.0010 | S_m=-0.0315 | S_family=-0.0163 | gap=0.0305 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1975 | S_p=0.0084 | S_m=-0.0502 | S_family=-0.0209 | gap=0.0587 | alpha_mean=0.5000

NoGate | Triada 56/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3948 | S_p=0.1311 | S_m=0.1060 | S_family=0.1185 | gap=0.0251 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3115 | S_p=0.0835 | S_m=0.0578 | S_family=0.0706 | gap=0.0257 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0723 | S_p=0.0132 | S_m=0.0255 | S_family=0.0193 | gap=0.0123 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1350 | S_p=-0.0179 | S_m=0.0484 | S_family=0.0153 | gap=0.0663 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0319 | S_p=-0.0372 | S_m=-0.0008 | S_family=-0.0190 | gap=0.0364 | alpha_mean=0.5000

NoGate | Triada 57/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1291 | S_p=-0.0153 | S_m=-0.0518 | S_family=-0.0336 | gap=0.0365 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1810 | S_p=0.0336 | S_m=0.0770 | S_family=0.0553 | gap=0.0434 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1973 | S_p=0.0276 | S_m=0.0259 | S_family=0.0267 | gap=0.0017 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2198 | S_p=0.0767 | S_m=0.0677 | S_family=0.0722 | gap=0.0090 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1969 | S_p=-0.0119 | S_m=0.0363 | S_family=0.0122 | gap=0.0482 | alpha_mean=0.5000

NoGate | Triada 58/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2813 | S_p=-0.0448 | S_m=-0.0481 | S_family=-0.0464 | gap=0.0033 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1613 | S_p=-0.0174 | S_m=0.0129 | S_family=-0.0023 | gap=0.0303 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0519 | S_p=-0.0129 | S_m=-0.0055 | S_family=-0.0092 | gap=0.0074 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.5160 | S_p=-0.0565 | S_m=-0.0050 | S_family=-0.0307 | gap=0.0515 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0626 | S_p=0.0195 | S_m=-0.0037 | S_family=0.0079 | gap=0.0232 | alpha_mean=0.5000

NoGate | Triada 59/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3993 | S_p=0.0287 | S_m=0.0285 | S_family=0.0286 | gap=0.0002 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2974 | S_p=0.0635 | S_m=0.1012 | S_family=0.0823 | gap=0.0377 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=-0.0812 | S_p=-0.0924 | S_m=0.0088 | S_family=-0.0418 | gap=0.1012 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3155 | S_p=0.0747 | S_m=0.0594 | S_family=0.0670 | gap=0.0153 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1314 | S_p=0.0590 | S_m=-0.0561 | S_family=0.0014 | gap=0.1152 | alpha_mean=0.5000

NoGate | Triada 60/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1071 | S_p=0.0781 | S_m=0.0219 | S_family=0.0500 | gap=0.0562 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3560 | S_p=0.1591 | S_m=0.0707 | S_family=0.1149 | gap=0.0884 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1141 | S_p=0.0598 | S_m=0.0325 | S_family=0.0461 | gap=0.0273 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0084 | S_p=0.0378 | S_m=-0.0023 | S_family=0.0177 | gap=0.0401 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0340 | S_p=-0.0719 | S_m=0.0215 | S_family=-0.0252 | gap=0.0935 | alpha_mean=0.5000

NoGate | Triada 61/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1802 | S_p=-0.0129 | S_m=-0.0078 | S_family=-0.0103 | gap=0.0052 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3593 | S_p=-0.0713 | S_m=-0.0057 | S_family=-0.0385 | gap=0.0656 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3598 | S_p=0.0095 | S_m=-0.0078 | S_family=0.0009 | gap=0.0173 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1023 | S_p=0.0440 | S_m=0.0161 | S_family=0.0301 | gap=0.0278 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=-0.0066 | S_p=0.0044 | S_m=-0.0893 | S_family=-0.0424 | gap=0.0937 | alpha_mean=0.5000

NoGate | Triada 62/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1804 | S_p=-0.0671 | S_m=0.0475 | S_family=-0.0098 | gap=0.1146 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2243 | S_p=-0.0206 | S_m=0.0026 | S_family=-0.0090 | gap=0.0232 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1086 | S_p=0.0126 | S_m=0.0174 | S_family=0.0150 | gap=0.0048 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0480 | S_p=0.0241 | S_m=0.1193 | S_family=0.0717 | gap=0.0952 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1699 | S_p=0.0874 | S_m=0.0656 | S_family=0.0765 | gap=0.0219 | alpha_mean=0.5000

NoGate | Triada 63/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1703 | S_p=0.0208 | S_m=-0.0136 | S_family=0.0036 | gap=0.0344 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1588 | S_p=-0.0394 | S_m=0.0587 | S_family=0.0096 | gap=0.0982 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1599 | S_p=0.0484 | S_m=0.0494 | S_family=0.0489 | gap=0.0009 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2661 | S_p=0.0550 | S_m=0.0356 | S_family=0.0453 | gap=0.0194 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1981 | S_p=0.0196 | S_m=-0.0069 | S_family=0.0064 | gap=0.0265 | alpha_mean=0.5000

NoGate | Triada 64/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4447 | S_p=0.0334 | S_m=0.0201 | S_family=0.0268 | gap=0.0133 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3690 | S_p=0.0211 | S_m=-0.0043 | S_family=0.0084 | gap=0.0253 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2431 | S_p=-0.0542 | S_m=0.0209 | S_family=-0.0167 | gap=0.0752 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0761 | S_p=0.0089 | S_m=0.0095 | S_family=0.0092 | gap=0.0005 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1186 | S_p=-0.0520 | S_m=0.0322 | S_family=-0.0099 | gap=0.0842 | alpha_mean=0.5000

NoGate | Triada 65/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=-0.0318 | S_p=0.0179 | S_m=-0.0922 | S_family=-0.0372 | gap=0.1101 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3412 | S_p=0.0396 | S_m=0.0731 | S_family=0.0563 | gap=0.0335 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0454 | S_p=-0.0505 | S_m=-0.0431 | S_family=-0.0468 | gap=0.0074 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1963 | S_p=-0.0164 | S_m=-0.0558 | S_family=-0.0361 | gap=0.0394 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0599 | S_p=0.0608 | S_m=0.0304 | S_family=0.0456 | gap=0.0304 | alpha_mean=0.5000

NoGate | Triada 66/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0825 | S_p=0.0033 | S_m=0.0121 | S_family=0.0077 | gap=0.0087 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1127 | S_p=0.1059 | S_m=-0.0402 | S_family=0.0329 | gap=0.1461 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1580 | S_p=0.1944 | S_m=0.0370 | S_family=0.1157 | gap=0.1574 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1076 | S_p=0.0373 | S_m=0.0189 | S_family=0.0281 | gap=0.0184 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1924 | S_p=0.0024 | S_m=-0.0510 | S_family=-0.0243 | gap=0.0534 | alpha_mean=0.5000

NoGate | Triada 67/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0935 | S_p=0.0225 | S_m=-0.0406 | S_family=-0.0090 | gap=0.0631 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0532 | S_p=0.0272 | S_m=0.0146 | S_family=0.0209 | gap=0.0126 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0760 | S_p=-0.0613 | S_m=-0.0004 | S_family=-0.0308 | gap=0.0609 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2245 | S_p=-0.0177 | S_m=-0.0201 | S_family=-0.0189 | gap=0.0025 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1796 | S_p=-0.0275 | S_m=0.0524 | S_family=0.0125 | gap=0.0799 | alpha_mean=0.5000

NoGate | Triada 68/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1785 | S_p=0.0007 | S_m=0.0387 | S_family=0.0197 | gap=0.0380 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0851 | S_p=0.0362 | S_m=0.0965 | S_family=0.0663 | gap=0.0603 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1075 | S_p=0.0381 | S_m=0.0570 | S_family=0.0475 | gap=0.0189 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0194 | S_p=0.0391 | S_m=0.0547 | S_family=0.0469 | gap=0.0156 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2477 | S_p=-0.0276 | S_m=-0.0100 | S_family=-0.0188 | gap=0.0176 | alpha_mean=0.5000

NoGate | Triada 69/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3394 | S_p=0.0443 | S_m=0.0697 | S_family=0.0570 | gap=0.0253 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=-0.0289 | S_p=0.0240 | S_m=0.0575 | S_family=0.0408 | gap=0.0335 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0409 | S_p=-0.0141 | S_m=0.0361 | S_family=0.0110 | gap=0.0502 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2003 | S_p=0.0051 | S_m=0.0150 | S_family=0.0101 | gap=0.0099 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1763 | S_p=0.0807 | S_m=0.0081 | S_family=0.0444 | gap=0.0726 | alpha_mean=0.5000

NoGate | Triada 70/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.3260 | S_p=0.0402 | S_m=0.0365 | S_family=0.0384 | gap=0.0037 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2874 | S_p=0.0278 | S_m=0.0370 | S_family=0.0324 | gap=0.0092 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1842 | S_p=0.0400 | S_m=0.0371 | S_family=0.0385 | gap=0.0029 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2450 | S_p=0.0151 | S_m=-0.0851 | S_family=-0.0350 | gap=0.1002 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1793 | S_p=-0.0165 | S_m=0.0273 | S_family=0.0054 | gap=0.0438 | alpha_mean=0.5000

NoGate | Triada 71/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1238 | S_p=-0.0202 | S_m=0.0624 | S_family=0.0211 | gap=0.0826 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3421 | S_p=0.0011 | S_m=0.0066 | S_family=0.0038 | gap=0.0056 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0632 | S_p=-0.0898 | S_m=0.0609 | S_family=-0.0144 | gap=0.1507 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3007 | S_p=0.0800 | S_m=0.1254 | S_family=0.1027 | gap=0.0453 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2356 | S_p=-0.0107 | S_m=0.0820 | S_family=0.0356 | gap=0.0927 | alpha_mean=0.5000

NoGate | Triada 72/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2887 | S_p=0.0259 | S_m=-0.0613 | S_family=-0.0177 | gap=0.0873 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.4518 | S_p=0.0693 | S_m=0.0538 | S_family=0.0615 | gap=0.0155 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0215 | S_p=0.0065 | S_m=0.0717 | S_family=0.0391 | gap=0.0652 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0546 | S_p=-0.0097 | S_m=0.0508 | S_family=0.0205 | gap=0.0605 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=-0.0116 | S_p=-0.0542 | S_m=0.0823 | S_family=0.0140 | gap=0.1366 | alpha_mean=0.5000

NoGate | Triada 73/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2915 | S_p=-0.0013 | S_m=0.0124 | S_family=0.0056 | gap=0.0137 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3091 | S_p=0.0638 | S_m=0.0280 | S_family=0.0459 | gap=0.0358 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0953 | S_p=0.0582 | S_m=-0.0008 | S_family=0.0287 | gap=0.0590 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0247 | S_p=0.0557 | S_m=0.0020 | S_family=0.0288 | gap=0.0536 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1467 | S_p=-0.0344 | S_m=0.0375 | S_family=0.0015 | gap=0.0719 | alpha_mean=0.5000

NoGate | Triada 74/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2304 | S_p=0.0477 | S_m=-0.0705 | S_family=-0.0114 | gap=0.1182 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2065 | S_p=0.0058 | S_m=0.0303 | S_family=0.0181 | gap=0.0245 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2137 | S_p=0.0098 | S_m=0.0405 | S_family=0.0252 | gap=0.0307 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1352 | S_p=0.0708 | S_m=0.0541 | S_family=0.0624 | gap=0.0168 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1155 | S_p=0.0337 | S_m=0.0551 | S_family=0.0444 | gap=0.0214 | alpha_mean=0.5000

NoGate | Triada 75/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.6047 | S_p=0.0809 | S_m=0.0345 | S_family=0.0577 | gap=0.0465 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2788 | S_p=0.0957 | S_m=-0.0308 | S_family=0.0324 | gap=0.1264 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1039 | S_p=-0.0434 | S_m=-0.0718 | S_family=-0.0576 | gap=0.0284 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3392 | S_p=0.0389 | S_m=0.0124 | S_family=0.0256 | gap=0.0265 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3770 | S_p=0.1269 | S_m=0.0205 | S_family=0.0737 | gap=0.1064 | alpha_mean=0.5000

NoGate | Triada 76/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0702 | S_p=0.0071 | S_m=-0.0447 | S_family=-0.0188 | gap=0.0518 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.3284 | S_p=0.0107 | S_m=-0.0242 | S_family=-0.0068 | gap=0.0349 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3782 | S_p=-0.0148 | S_m=-0.0439 | S_family=-0.0293 | gap=0.0291 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0122 | S_p=-0.0286 | S_m=-0.0120 | S_family=-0.0203 | gap=0.0166 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2206 | S_p=0.0472 | S_m=0.0647 | S_family=0.0560 | gap=0.0176 | alpha_mean=0.5000

NoGate | Triada 77/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4126 | S_p=-0.0390 | S_m=0.0756 | S_family=0.0183 | gap=0.1146 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2227 | S_p=0.0167 | S_m=-0.0046 | S_family=0.0061 | gap=0.0212 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2204 | S_p=0.0617 | S_m=0.0097 | S_family=0.0357 | gap=0.0520 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1991 | S_p=0.0704 | S_m=0.0363 | S_family=0.0534 | gap=0.0341 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1612 | S_p=0.0415 | S_m=0.0061 | S_family=0.0238 | gap=0.0354 | alpha_mean=0.5000

NoGate | Triada 78/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0850 | S_p=0.0091 | S_m=0.0542 | S_family=0.0316 | gap=0.0451 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1230 | S_p=-0.0474 | S_m=0.0039 | S_family=-0.0217 | gap=0.0512 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1471 | S_p=0.0867 | S_m=-0.0098 | S_family=0.0385 | gap=0.0965 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0081 | S_p=-0.0403 | S_m=-0.0392 | S_family=-0.0397 | gap=0.0011 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1670 | S_p=0.1154 | S_m=0.0668 | S_family=0.0911 | gap=0.0486 | alpha_mean=0.5000

NoGate | Triada 79/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1274 | S_p=-0.0814 | S_m=0.0308 | S_family=-0.0253 | gap=0.1122 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2010 | S_p=-0.0476 | S_m=0.0064 | S_family=-0.0206 | gap=0.0540 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0812 | S_p=-0.0522 | S_m=0.0215 | S_family=-0.0153 | gap=0.0736 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.3063 | S_p=0.0901 | S_m=0.0788 | S_family=0.0844 | gap=0.0113 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1874 | S_p=-0.0402 | S_m=0.0625 | S_family=0.0112 | gap=0.1027 | alpha_mean=0.5000

NoGate | Triada 80/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0504 | S_p=-0.0634 | S_m=0.0072 | S_family=-0.0281 | gap=0.0706 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0783 | S_p=0.0128 | S_m=0.0137 | S_family=0.0133 | gap=0.0009 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1373 | S_p=-0.0358 | S_m=0.0420 | S_family=0.0031 | gap=0.0778 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0713 | S_p=0.0430 | S_m=0.0761 | S_family=0.0596 | gap=0.0331 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0790 | S_p=0.0208 | S_m=0.0771 | S_family=0.0489 | gap=0.0563 | alpha_mean=0.5000

NoGate | Triada 81/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.5712 | S_p=0.0789 | S_m=0.1066 | S_family=0.0927 | gap=0.0278 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1811 | S_p=0.0379 | S_m=-0.0405 | S_family=-0.0013 | gap=0.0784 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1458 | S_p=-0.0125 | S_m=-0.0553 | S_family=-0.0339 | gap=0.0427 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2230 | S_p=-0.0081 | S_m=0.0170 | S_family=0.0045 | gap=0.0251 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2571 | S_p=-0.0449 | S_m=0.0819 | S_family=0.0185 | gap=0.1268 | alpha_mean=0.5000

NoGate | Triada 82/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.0574 | S_p=0.0452 | S_m=-0.0473 | S_family=-0.0011 | gap=0.0925 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2402 | S_p=0.0580 | S_m=0.0174 | S_family=0.0377 | gap=0.0406 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0437 | S_p=-0.0245 | S_m=0.0362 | S_family=0.0058 | gap=0.0607 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0549 | S_p=0.0304 | S_m=0.0255 | S_family=0.0279 | gap=0.0050 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2046 | S_p=-0.0284 | S_m=0.0371 | S_family=0.0043 | gap=0.0655 | alpha_mean=0.5000

NoGate | Triada 83/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4982 | S_p=0.0144 | S_m=0.0470 | S_family=0.0307 | gap=0.0326 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0921 | S_p=0.1015 | S_m=0.0963 | S_family=0.0989 | gap=0.0052 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0865 | S_p=-0.0705 | S_m=0.0192 | S_family=-0.0257 | gap=0.0897 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2398 | S_p=-0.0086 | S_m=0.0434 | S_family=0.0174 | gap=0.0520 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.0921 | S_p=-0.0411 | S_m=0.0606 | S_family=0.0098 | gap=0.1017 | alpha_mean=0.5000

NoGate | Triada 84/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1268 | S_p=0.0344 | S_m=-0.0022 | S_family=0.0161 | gap=0.0366 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.1743 | S_p=-0.0515 | S_m=-0.0098 | S_family=-0.0307 | gap=0.0416 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.2552 | S_p=-0.0463 | S_m=0.0224 | S_family=-0.0120 | gap=0.0687 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=-0.0051 | S_p=-0.1157 | S_m=-0.0101 | S_family=-0.0629 | gap=0.1056 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=-0.0019 | S_p=0.0629 | S_m=-0.0228 | S_family=0.0201 | gap=0.0857 | alpha_mean=0.5000

NoGate | Triada 85/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.4307 | S_p=0.0203 | S_m=0.0492 | S_family=0.0348 | gap=0.0289 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2727 | S_p=0.0104 | S_m=0.0540 | S_family=0.0322 | gap=0.0436 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.1768 | S_p=0.0247 | S_m=0.0491 | S_family=0.0369 | gap=0.0244 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.1661 | S_p=-0.0915 | S_m=0.0003 | S_family=-0.0456 | gap=0.0918 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1298 | S_p=0.1000 | S_m=0.0640 | S_family=0.0820 | gap=0.0360 | alpha_mean=0.5000

NoGate | Triada 86/208 | gender=man

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1271 | S_p=0.0017 | S_m=0.0737 | S_family=0.0377 | gap=0.0720 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0347 | S_p=0.0258 | S_m=0.0808 | S_family=0.0533 | gap=0.0550 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0690 | S_p=0.0325 | S_m=0.0953 | S_family=0.0639 | gap=0.0628 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2087 | S_p=0.1287 | S_m=0.0884 | S_family=0.1085 | gap=0.0403 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.3314 | S_p=0.0337 | S_m=0.0557 | S_family=0.0447 | gap=0.0219 | alpha_mean=0.5000

NoGate | Triada 87/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.1930 | S_p=0.0158 | S_m=0.0294 | S_family=0.0226 | gap=0.0136 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0364 | S_p=0.0756 | S_m=0.0333 | S_family=0.0544 | gap=0.0423 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.3125 | S_p=0.0068 | S_m=0.0649 | S_family=0.0358 | gap=0.0581 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.2517 | S_p=-0.0167 | S_m=0.0370 | S_family=0.0101 | gap=0.0537 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.1911 | S_p=-0.0388 | S_m=0.1025 | S_family=0.0318 | gap=0.1413 | alpha_mean=0.5000

NoGate | Triada 88/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2103 | S_p=0.0072 | S_m=0.0567 | S_family=0.0320 | gap=0.0495 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.0236 | S_p=-0.0312 | S_m=-0.0211 | S_family=-0.0261 | gap=0.0101 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=25 | S_id=0.0474 | S_p=-0.0063 | S_m=-0.0003 | S_family=-0.0033 | gap=0.0061 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=40 | S_id=0.0375 | S_p=-0.0437 | S_m=-0.0313 | S_family=-0.0375 | gap=0.0124 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=60 | S_id=0.2667 | S_p=0.0464 | S_m=0.0948 | S_family=0.0706 | gap=0.0485 | alpha_mean=0.5000

NoGate | Triada 89/208 | gender=woman

  0%|          | 0/30 [00:00<?, ?it/s]

age=5 | S_id=0.2870 | S_p=0.0452 | S_m=0.0598 | S_family=0.0525 | gap=0.0146 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

age=15 | S_id=0.2272 | S_p=0.1279 | S_m=0.0133 | S_family=0.0706 | gap=0.1147 | alpha_mean=0.5000

  0%|          | 0/30 [00:00<?, ?it/s]

In [ ]:
sd = ckpt["bap2_gate_state"]

first_key = list(sd.keys())[0]
print("Primera capa:", first_key)
print(type(sd[first_key]))

if isinstance(sd[first_key], dict):
    print("Keys inside one layer:")
    for k, v in sd[first_key].items():
        if hasattr(v, "shape"):
            print(k, v.shape, v.dtype)
        else:
            print(k, type(v), v)
else:
    print(sd[first_key])

Primera capa: down_blocks_0_attentions_0_transformer_blocks_0_attn2
<class 'collections.OrderedDict'>
Keys inside one layer:
weight torch.Size([16, 2176]) torch.float32
bias torch.Size([16]) torch.float32